// Generated by tools/jdeob.py from x/bb.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bb`.
// String constants: <clinit> | <init> | Code | java/lang/Exception | java/lang/Object | StackMap
public class AssetManager {
    public static TileList a;
    public static MidList a_ae;
    public static HighList a_ap;
    public static Textures a_cf;
    public static MeshCache a_b;
    public static Meshes a_de;
    static {
        AssetManager.a = null;
        AssetManager.a_ae = null;
        AssetManager.a_ap = null;
        AssetManager.a_cf = null;
        AssetManager.a_b = null;
        AssetManager.a_de = null;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public AssetManager() {
        super();
        return;
    }
    // bytecode 79 bytes, max_stack 3, max_locals 0
    public static void a() {
        if (AssetManager.a_cf != null) goto L29;
        new Textures(); /* constructor */
        AssetManager.a_cf = new Textures();
        new Meshes(AssetManager.a_cf); /* constructor */
        AssetManager.a_de = new Meshes(AssetManager.a_cf);
        L29:
        new TileList(AssetManager.a_cf); /* constructor */
        AssetManager.a = new TileList(AssetManager.a_cf);
        new MidList(AssetManager.a_cf); /* constructor */
        AssetManager.a_ae = new MidList(AssetManager.a_cf);
        new HighList(); /* constructor */
        AssetManager.a_ap = new HighList();
        new MeshCache(AssetManager.a_cf); /* constructor */
        AssetManager.a_b = new MeshCache(AssetManager.a_cf);
        return;
    }
    // bytecode 91 bytes, max_stack 1, max_locals 0
    public static void b() {
        /* try L0-L72 catch java.lang.Exception -> L73 */
        if (AssetManager.a_cf == null) goto L32;
        if (Settings.c() != 0) goto L32;
        AssetManager.a_de.a();
        AssetManager.a_cf.a();
        AssetManager.a_de = null;
        AssetManager.a_cf = null;
        L32:
        AssetManager.a.a();
        AssetManager.a_ae.a();
        AssetManager.a_ap.a();
        AssetManager.a_b.a();
        AssetManager.a = null;
        AssetManager.a_ae = null;
        AssetManager.a_ap = null;
        AssetManager.a_b = null;
        return;
        /* pop: ex_73; */
        AssetManager.a = null;
        AssetManager.a_ae = null;
        AssetManager.a_ap = null;
        AssetManager.a_b = null;
        return;
    }
}

