// Generated by tools/jdeob.py from x/ba.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ba`.
// String constants: /cars/ | /models/ | /tex/ | <clinit> | <init> | Code | [Lat; | [Ljava/lang/String; | append | bonus.car | close | cool.car
// API references: java/io javax/microedition
public class CarSpec {
    public static String[] a;
    private ObfAt[] a_arrLat;
    private String[] b;
    private int[] a_arrI;
    private int[] b_arrI;
    private int[] c;
    private int[] d;
    private static Transform a_Transf;
    static {
        new java.lang.String[8]#1[0] = "rally.car";
        new java.lang.String[8]#1[1] = "fashion.car";
        new java.lang.String[8]#1[2] = "vintage.car";
        new java.lang.String[8]#1[3] = "sport.car";
        new java.lang.String[8]#1[4] = "bonus.car";
        new java.lang.String[8]#1[5] = "suv.car";
        new java.lang.String[8]#1[6] = "cx.car";
        new java.lang.String[8]#1[7] = "cool.car";
        CarSpec.a = new java.lang.String[8]#1;
        CarSpec.a_Transf = null;
        return;
    }
    // bytecode 262 bytes, max_stack 5, max_locals 1
    public CarSpec() {
        super();
        new ObfAt[8]#1[0] = null;
        new ObfAt[8]#1[1] = null;
        new ObfAt[8]#1[2] = null;
        new ObfAt[8]#1[3] = null;
        new ObfAt[8]#1[4] = null;
        new ObfAt[8]#1[5] = null;
        new ObfAt[8]#1[6] = null;
        new ObfAt[8]#1[7] = null;
        this.a_arrLat = new ObfAt[8]#1;
        new java.lang.String[8]#2[0] = null;
        new java.lang.String[8]#2[1] = null;
        new java.lang.String[8]#2[2] = null;
        new java.lang.String[8]#2[3] = null;
        new java.lang.String[8]#2[4] = null;
        new java.lang.String[8]#2[5] = null;
        new java.lang.String[8]#2[6] = null;
        new java.lang.String[8]#2[7] = null;
        this.b = new java.lang.String[8]#2;
        new int[8]#3[0] = 0;
        new int[8]#3[1] = 0;
        new int[8]#3[2] = 0;
        new int[8]#3[3] = 0;
        new int[8]#3[4] = 0;
        new int[8]#3[5] = 0;
        new int[8]#3[6] = 0;
        new int[8]#3[7] = 0;
        this.a_arrI = new int[8]#3;
        new int[8]#4[0] = 0;
        new int[8]#4[1] = 0;
        new int[8]#4[2] = 0;
        new int[8]#4[3] = 0;
        new int[8]#4[4] = 0;
        new int[8]#4[5] = 0;
        new int[8]#4[6] = 0;
        new int[8]#4[7] = 0;
        this.b_arrI = new int[8]#4;
        new int[8]#5[0] = 0;
        new int[8]#5[1] = 0;
        new int[8]#5[2] = 0;
        new int[8]#5[3] = 0;
        new int[8]#5[4] = 0;
        new int[8]#5[5] = 0;
        new int[8]#5[6] = 0;
        new int[8]#5[7] = 0;
        this.c = new int[8]#5;
        new int[8]#6[0] = 0;
        new int[8]#6[1] = 0;
        new int[8]#6[2] = 0;
        new int[8]#6[3] = 0;
        new int[8]#6[4] = 0;
        new int[8]#6[5] = 0;
        new int[8]#6[6] = 0;
        new int[8]#6[7] = 0;
        this.d = new int[8]#6;
        ObfBb.a();
        return;
    }
    // bytecode 65 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a_arrLat.length) goto L31;
        this.a_arrLat[v1] = null;
        this.b[v1] = null;
        v1 += 1;
        goto L2;
        L31:
        this.a_arrLat = null;
        this.b = null;
        this.a_arrI = null;
        this.b_arrI = null;
        this.c = null;
        this.d = null;
        ObfBb.b();
        return;
    }
    // bytecode 214 bytes, max_stack 8, max_locals 5
    public void a(int v1) {
        /* try L0-L186 catch java.lang.Exception -> L187 */
        new java.lang.StringBuffer(); /* constructor */
        String v2 = new java.lang.StringBuffer().append("/cars/").append(CarSpec.a[v1]).toString();
        v2 = ((String) Resources.a(new java.lang.StringBuffer().append("/cars/").append(CarSpec.a[v1]).toString()));
        String v3 = StreamReader.a(Resources.a(new java.lang.StringBuffer().append("/cars/").append(CarSpec.a[v1]).toString()));
        /* pop: StreamReader.a(v2); */
        String v4 = StreamReader.a(v2);
        this.b[v1] = StreamReader.a(v2);
        this.a_arrI[v1] = StreamReader.a(v2);
        this.b_arrI[v1] = StreamReader.a(v2);
        this.c[v1] = StreamReader.a(v2);
        this.d[v1] = StreamReader.a(v2);
        v2.close();
        ObfAt.a_Z = true;
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        new ObfAt(ObfBb.a_cf, new java.lang.StringBuffer().append("/models/").append(v3).toString(), new java.lang.StringBuffer().append("/tex/").append(v4).toString()); /* constructor */
        this.a_arrLat[v1] = new ObfAt(ObfBb.a_cf, new java.lang.StringBuffer().append("/models/").append(v3).toString(), new java.lang.StringBuffer().append("/tex/").append(v4).toString());
        if (CarSpec.a_Transf != null) goto L186;
        if (this.a_arrLat[v1].a == null) goto L186;
        new javax.microedition.m3g.Transform(); /* constructor */
        CarSpec.a_Transf = new javax.microedition.m3g.Transform();
        L186:
        return;
        v2 = ((String) ex_187);
        new java.lang.StringBuffer(); /* constructor */
        java.lang.System.out.println(new java.lang.StringBuffer().append("!!!!").append(v2).toString());
        return;
    }
    // bytecode 69 bytes, max_stack 4, max_locals 3
    public ObfAt a(int v1, float v2) {
        if (this.a_arrLat[v1] != null) goto L14;
        this.a(v1);
        L14:
        if (this.a_arrLat[v1].a == null) goto L62;
        CarSpec.a_Transf.setIdentity();
        CarSpec.a_Transf.postTranslate((((-v2) / 360.0f) * 2.0f), 0.0f, 0.0f);
        this.a_arrLat[v1].a.setTransform(CarSpec.a_Transf);
        L62:
        return this.a_arrLat[v1];
    }
    // bytecode 21 bytes, max_stack 2, max_locals 2
    public String a(int v1) {
        if (this.b[v1] != null) goto L14;
        this.a(v1);
        L14:
        return this.b[v1];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public int a(int v1) {
        return this.a_arrI[v1];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public int b(int v1) {
        return this.b_arrI[v1];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public int c(int v1) {
        return this.c[v1];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public int d(int v1) {
        return this.d[v1];
    }
    // bytecode 65 bytes, max_stack 2, max_locals 3
    public int a(int v1, int v2) {
        if (v2 != 0) goto L15;
        v2 = v1;
        v1 = ((int) this);
        return this.a_arrI[v2];
        L15:
        if (v2 != 1) goto L31;
        v2 = v1;
        v1 = ((int) this);
        return this.b_arrI[v2];
        L31:
        if (v2 != 2) goto L47;
        v2 = v1;
        v1 = ((int) this);
        return this.c[v2];
        L47:
        if (v2 != 3) goto L63;
        v2 = v1;
        v1 = ((int) this);
        return this.d[v2];
        L63:
        return 0;
    }
}

