// Generated by tools/jdeob.py from x/as.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `as`.
// String constants: /sounds/acc2_8k.amr | /sounds/acc3_8k.amr | /sounds/acc_8k.amr | /sounds/dec_8k.amr | /sounds/fade_8k.amr | /sounds/l0_8k.amr | /sounds/l1_8k.amr | /sounds/slide_8k.amr | /sounds/theme.mid | <clinit> | <init> | Code
// API references: java/util javax/microedition
public class EngineSounds implements java.lang.Runnable {
    private static Thread a;
    private static EngineSounds a_as;
    private static boolean a_Z;
    private static volatile boolean b;
    private static boolean c;
    private static boolean d;
    private static boolean e;
    private static float a_F;
    private static int a_I;
    private static volatile int b_I;
    private static volatile boolean f;
    private static volatile long a_J;
    private static String[] a_String;
    private static String a_String_2;
    private static int[] a_arrI;
    private static int c_I;
    private static volatile boolean g;
    private static AudioPlayer a_cy;
    private static int d_I;
    private static long b_J;
    static {
        EngineSounds.a = null;
        EngineSounds.a_as = null;
        EngineSounds.a_Z = false;
        EngineSounds.b = false;
        EngineSounds.c = false;
        EngineSounds.d = false;
        EngineSounds.e = false;
        EngineSounds.a_F = 0.0f;
        EngineSounds.a_I = 0;
        EngineSounds.b_I = 0;
        EngineSounds.f = false;
        EngineSounds.a_J = 0L;
        new java.lang.String[8][0] = "/sounds/acc_8k.amr";
        new java.lang.String[8][1] = "/sounds/acc2_8k.amr";
        new java.lang.String[8][2] = "/sounds/dec_8k.amr";
        new java.lang.String[8][3] = "/sounds/fade_8k.amr";
        new java.lang.String[8][4] = "/sounds/slide_8k.amr";
        new java.lang.String[8][5] = "/sounds/l0_8k.amr";
        new java.lang.String[8][6] = "/sounds/l1_8k.amr";
        new java.lang.String[8][7] = "/sounds/acc3_8k.amr";
        EngineSounds.a_String = new java.lang.String[8];
        EngineSounds.a_String_2 = "/sounds/theme.mid";
        new int[8][0] = 11272;
        new int[8][1] = 5314;
        new int[8][2] = 2350;
        new int[8][3] = 4005;
        new int[8][4] = 2709;
        new int[8][5] = 3502;
        new int[8][6] = 7721;
        new int[8][7] = 5072;
        EngineSounds.a_arrI = new int[8];
        EngineSounds.c_I = m1;
        EngineSounds.g = false;
        EngineSounds.a_cy = null;
        EngineSounds.d_I = m1;
        EngineSounds.b_J = 0L;
        return;
    }
    // bytecode 33 bytes, max_stack 3, max_locals 2
    public EngineSounds() {
        super();
        EngineSounds v1 = this;
        new java.lang.Thread(v1); /* constructor */
        EngineSounds.a = new java.lang.Thread(v1);
        new java.lang.Thread(v1).setPriority(1);
        EngineSounds.a.start();
        EngineSounds.b = false;
        return;
    }
    // bytecode 18 bytes, max_stack 2, max_locals 0
    public static void a() {
        if (EngineSounds.a_as == null) goto L7;
        return;
        L7:
        new EngineSounds(); /* constructor */
        EngineSounds.a_as = new EngineSounds();
        return;
    }
    // bytecode 74 bytes, max_stack 2, max_locals 0
    public static void g() {
        if (EngineSounds.a_cy == null) goto L7;
        return;
        L7:
        if (Settings.u() != 0) goto L26;
        new AudioPlayer(); /* constructor */
        EngineSounds.a_cy = new AudioPlayer();
        goto L63;
        L26:
        if (Settings.u() != 1) goto L46;
        new SoundBank(); /* constructor */
        EngineSounds.a_cy = new SoundBank();
        goto L63;
        L46:
        if (Settings.u() != 2) goto L63;
        new SoundTrigger(); /* constructor */
        EngineSounds.a_cy = new SoundTrigger();
        L63:
        if (Settings.s() != 0) goto L70;
        return;
        L70:
        EngineSounds.h();
        return;
    }
    // bytecode 118 bytes, max_stack 3, max_locals 1
    public static void h() {
        /* try L0-L111 catch java.lang.Exception -> L112 */
        if (Settings.b() != 0) goto L70;
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[0]); */
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[1]); */
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[2]); */
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[5]); */
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[6]); */
        goto L105;
        L70:
        if (Settings.b() != 1) goto L105;
        int v0 = 0;
        L79:
        if (v0 >= EngineSounds.a_String.length) goto L105;
        /* pop: EngineSounds.a_cy.a(EngineSounds.a_String[v0]); */
        v0 += 1;
        goto L79;
        L105:
        EngineSounds.d_I = Settings.b();
        return;
        v0 = ((int) ex_112);
        ex_112.printStackTrace();
        return;
    }
    // bytecode 94 bytes, max_stack 4, max_locals 2
    public static void i() {
        if (EngineSounds.c_I >= 0) goto L7;
        return;
        L7:
        int v0 = EngineSounds.c_I;
        if (EngineSounds.c_I != 100) goto L24;
        String v1 = EngineSounds.a_String_2;
        goto L30;
        L24:
        v1 = ((String) EngineSounds.a_String[v0]);
        L30:
        if (EngineSounds.a_cy.a(v1, v0) == 0) goto L93;
        EngineSounds.b_J = java.lang.System.currentTimeMillis();
        if (v0 != 100) goto L66;
        EngineSounds.a_J = (EngineSounds.b_J + 10000000L);
        goto L83;
        L66:
        EngineSounds.a_J = ((EngineSounds.b_J + ((long) EngineSounds.a_arrI[v0])) - 100L);
        L83:
        EngineSounds.c_I = m1;
        EngineSounds.a_cy.e();
        L93:
        return;
    }
    // bytecode 515 bytes, max_stack 4, max_locals 2
    public void run() {
        /* try L498-L504 catch java.lang.Exception -> L507 */
        /* try L0-L15 catch java.lang.Exception -> L511 */
        /* try L18-L508 catch java.lang.Exception -> L511 */
        L0:
        if (java.lang.Thread.currentThread() != EngineSounds.a) goto L15;
        if (EngineSounds.a_Z == 0) goto L18;
        L15:
        goto L0;
        L18:
        if (EngineSounds.b_I <= 0) goto L38;
        /* pop: KORa.m_pDisplay.vibrate(EngineSounds.b_I); */
        EngineSounds.b_I = 0;
        L38:
        if (EngineSounds.f != 0) goto L477;
        if (Settings.s() <= 0) goto L477;
        if (EngineSounds.a_cy != null) goto L59;
        EngineSounds.g();
        L59:
        if (EngineSounds.d_I == Settings.b()) goto L71;
        EngineSounds.h();
        L71:
        EngineSounds.a_Z = true;
        if (EngineSounds.g == 0) goto L90;
        EngineSounds.a_cy.c();
        goto L108;
        L90:
        if (EngineSounds.a_cy.a() == Settings.s()) goto L108;
        EngineSounds.a_cy.e();
        L108:
        if (EngineSounds.g != 0) goto L470;
        if (Settings.b() != 2) goto L137;
        if (AudioPlayer.b() == 100) goto L470;
        EngineSounds.c_I = 100;
        goto L467;
        L137:
        if (Settings.s() <= 0) goto L470;
        int v1 = 0;
        if (EngineSounds.a_I == 0) goto L467;
        if (EngineSounds.a_I != 1) goto L164;
        EngineSounds.c_I = 5;
        v1 = 1;
        L164:
        if (EngineSounds.a_I != 50) goto L178;
        EngineSounds.c_I = 0;
        v1 = 1;
        L178:
        if (v1 != 0) goto L209;
        if (EngineSounds.a_I <= 2) goto L209;
        if (AudioPlayer.b() == 2) goto L207;
        if (AudioPlayer.b() == 5) goto L207;
        EngineSounds.c_I = 2;
        L207:
        v1 = 1;
        L209:
        if (v1 != 0) goto L225;
        if (EngineSounds.c == 0) goto L225;
        EngineSounds.c_I = 4;
        v1 = 1;
        L225:
        if (v1 != 0) goto L255;
        if (EngineSounds.e == 0) goto L255;
        if (AudioPlayer.b() == 2) goto L253;
        if (AudioPlayer.b() == 5) goto L253;
        EngineSounds.c_I = 2;
        L253:
        v1 = 1;
        L255:
        if (v1 != 0) goto L405;
        if (EngineSounds.d == 0) goto L356;
        if (fcmpl(EngineSounds.a_F, 2.0f) > 0) goto L280;
        EngineSounds.c_I = 0;
        goto L345;
        L280:
        if (AudioPlayer.b() == 0) goto L347;
        if (AudioPlayer.b() == 1) goto L347;
        if (AudioPlayer.b() == 7) goto L347;
        if (AudioPlayer.b() == 6) goto L347;
        if (AudioPlayer.b() != 4) goto L341;
        if (KORa.rand.nextInt(2) != 0) goto L334;
        EngineSounds.c_I = 7;
        goto L345;
        L334:
        EngineSounds.c_I = 1;
        goto L345;
        L341:
        EngineSounds.c_I = 1;
        L345:
        v1 = 1;
        L347:
        EngineSounds.b_J = java.lang.System.currentTimeMillis();
        goto L405;
        L356:
        if (AudioPlayer.b() == 0) goto L385;
        if (AudioPlayer.b() == 1) goto L385;
        if (AudioPlayer.b() == 7) goto L385;
        if (AudioPlayer.b() != 6) goto L405;
        L385:
        if (lcmp((java.lang.System.currentTimeMillis() - EngineSounds.b_J), 1000L) <= 0) goto L405;
        EngineSounds.c_I = 2;
        v1 = 1;
        L405:
        if (v1 != 0) goto L426;
        if (EngineSounds.c != 0) goto L426;
        if (AudioPlayer.b() != 4) goto L426;
        EngineSounds.c_I = 2;
        L426:
        if (EngineSounds.c_I != m1) goto L467;
        if (Settings.u() != 0) goto L467;
        if (Settings.b() >= 2) goto L467;
        if (lcmp(EngineSounds.a_J, 0L) <= 0) goto L467;
        if (lcmp(java.lang.System.currentTimeMillis(), EngineSounds.a_J) < 0) goto L467;
        EngineSounds.j();
        L467:
        EngineSounds.i();
        L470:
        EngineSounds.a_Z = false;
        goto L498;
        L477:
        if (EngineSounds.a_cy == null) goto L498;
        if (EngineSounds.a_cy.a() == 0) goto L498;
        EngineSounds.a_cy.a();
        L498:
        java.lang.Thread.sleep(50L);
        goto L0;
        /* pop: ex_507; */
        goto L0;
        /* pop: ex_511; */
        goto L0;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 0
    public static void b() {
        EngineSounds.f = false;
        return;
    }
    // bytecode 123 bytes, max_stack 2, max_locals 0
    public static void j() {
        if (AudioPlayer.b() != 100) goto L13;
        EngineSounds.c_I = 100;
        L13:
        if (AudioPlayer.b() != 4) goto L38;
        if (EngineSounds.c == 0) goto L33;
        EngineSounds.c_I = 4;
        goto L38;
        L33:
        EngineSounds.c_I = 7;
        L38:
        if (AudioPlayer.b() != 0) goto L62;
        if (EngineSounds.d == 0) goto L57;
        EngineSounds.c_I = 1;
        goto L62;
        L57:
        EngineSounds.c_I = 6;
        L62:
        if (AudioPlayer.b() != 1) goto L74;
        EngineSounds.c_I = 6;
        L74:
        if (AudioPlayer.b() != 7) goto L87;
        EngineSounds.c_I = 6;
        L87:
        if (AudioPlayer.b() != 6) goto L100;
        EngineSounds.c_I = 6;
        L100:
        if (AudioPlayer.b() != 2) goto L111;
        EngineSounds.c_I = 5;
        L111:
        if (AudioPlayer.b() != 5) goto L122;
        EngineSounds.c_I = 5;
        L122:
        return;
    }
    // bytecode 7 bytes, max_stack 0, max_locals 0
    public static void c() {
        EngineSounds.j();
        EngineSounds.i();
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 0
    public static void d() {
        EngineSounds.g = true;
        return;
    }
    // bytecode 17 bytes, max_stack 1, max_locals 0
    public static void e() {
        EngineSounds.g = false;
        if (EngineSounds.a_cy == null) goto L16;
        EngineSounds.a_cy.b();
        L16:
        return;
    }
    // bytecode 17 bytes, max_stack 1, max_locals 0
    public static void f() {
        EngineSounds.f = true;
        if (EngineSounds.a_cy == null) goto L16;
        EngineSounds.a_cy.a();
        L16:
        return;
    }
    // bytecode 14 bytes, max_stack 1, max_locals 1
    public static void a(int v0) {
        if (EngineSounds.a_as != null) goto L9;
        EngineSounds.g();
        L9:
        EngineSounds.b_I = v0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void a(boolean v0) {
        EngineSounds.c = v0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void b(boolean v0) {
        EngineSounds.e = v0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void c(boolean v0) {
        EngineSounds.d = v0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void a(float v0) {
        EngineSounds.a_F = v0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void b(int v0) {
        EngineSounds.a_I = v0;
        return;
    }
}

