// Generated by tools/jdeob.py from x/p.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `p`.
// String constants: .png | <clinit> | <init> | Code | append | charAt | close | createImage | createRGBImage | drawImage | getClipHeight | getClipWidth
// API references: java/io javax/microedition
public class Font {
    private byte[] a;
    private FontCodec a_g;
    protected byte a_B;
    protected Image a_Image;
    public int a_I;
    private byte[] b;
    private byte[] c;
    private static byte[] d;
    private static int c_I;
    private static int d_I;
    private static int e;
    private static int f;
    private static int g;
    private static int h;
    private static int i;
    private static int j;
    private static int k;
    private static byte b_B;
    private static int l;
    private static int m;
    private static int n;
    private static int o;
    private static int p;
    protected int b_I;
    private int q;
    private int r;
    private boolean a_Z;
    private int s;
    static {
        Font.d = new byte[255];
        Font.c_I = 0;
        Font.d_I = 0;
        Font.e = 0;
        Font.f = 0;
        Font.g = 0;
        Font.h = 0;
        Font.i = 0;
        Font.j = 0;
        Font.k = 0;
        Font.b_B = 0;
        Font.l = 0;
        return;
    }
    // bytecode 67 bytes, max_stack 2, max_locals 1
    public Font() {
        super();
        this.a = null;
        this.a_g = null;
        this.a_B = 0;
        this.a_Image = null;
        this.a_I = 0;
        this.b = null;
        this.c = null;
        this.b_I = 0;
        this.q = 0;
        this.r = 0;
        this.a_Z = false;
        this.s = -1000;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.a_Z = true;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void b() {
        this.a_Z = false;
        return;
    }
    // bytecode 149 bytes, max_stack 3, max_locals 4
    public Font(Font v1) {
        this();
        this.a = null;
        this.a_g = null;
        this.a_B = 0;
        this.a_Image = null;
        this.a_I = 0;
        this.b = null;
        this.c = null;
        this.b_I = 0;
        this.q = 0;
        this.r = 0;
        this.a_Z = false;
        this.s = -1000;
        Font v2 = v1;
        v1 = this;
        Font v3 = v2;
        this.a_g = v2.a_g;
        v1.a_B = v2.a_B;
        v1.a = v2.a;
        v1.b = v2.b;
        v1.c = v2.c;
        v1.a_Image = v2.a_Image;
        v1.q = v2.q;
        v1.a_I = v2.a_I;
        v1.b_I = v2.b_I;
        v1.c();
        return;
    }
    // bytecode 37 bytes, max_stack 4, max_locals 1
    public void c() {
        /* try L0-L34 catch java.lang.Exception -> L35 */
        this.a_Image = SysUtil.a(this.a_Image, (((Settings.n() - this.b_I) + 360) % 360));
        this.b_I = Settings.n();
        return;
        /* pop: ex_35; */
        return;
    }
    // bytecode 195 bytes, max_stack 4, max_locals 6
    public void a(String v1, FontCodec v2, int v3) {
        InputStream v4 = Resources.a(v1);
        int v5 = Resources.a(v1).read();
        this.a = new byte[v5];
        this.a_g = v2;
        v2 = ((FontCodec) 0);
        L27:
        if (v2 >= v5) goto L51;
        this.a[v2] = ((byte) v4.read());
        v2 += 1;
        goto L27;
        L51:
        this.a_B = ((byte) v4.read());
        this.a_I = v3;
        new java.lang.StringBuffer(); /* constructor */
        this.a_Image = javax.microedition.lcdui.Image.createImage(Resources.a(new java.lang.StringBuffer().append(v1).append(".png").toString()));
        this.b = new byte[v5];
        this.c = new byte[v5];
        v2 = ((FontCodec) 0);
        v1 = ((String) 0);
        v3 = 0;
        L117:
        if (v3 >= v5) goto L185;
        if ((v2 + this.a[v3]) <= this.a_Image.getWidth()) goto L148;
        v2 = ((FontCodec) 0);
        v1 = ((String) ((short) (v1 + 1)));
        L148:
        this.b[v3] = ((byte) v2);
        this.c[v3] = ((byte) (v1 * this.a_B));
        v2 = ((FontCodec) ((short) (v2 + this.a[v3])));
        v3 += 1;
        goto L117;
        L185:
        v4.close();
        this.c();
        return;
    }
    // bytecode 25 bytes, max_stack 4, max_locals 1
    public void d() {
        this.s = this.a(32);
        this.a[this.s] = ((byte) (this.a[this.s] + 3));
        return;
    }
    // bytecode 74 bytes, max_stack 4, max_locals 4
    public Font(String v1, FontCodec v2, int v3) {
        this();
        this.a = null;
        this.a_g = null;
        this.a_B = 0;
        this.a_Image = null;
        this.a_I = 0;
        this.b = null;
        this.c = null;
        this.b_I = 0;
        this.q = 0;
        this.r = 0;
        this.a_Z = false;
        this.s = -1000;
        this.a(v1, v2, v3);
        return;
    }
    // bytecode 80 bytes, max_stack 4, max_locals 5
    public Font(String v1, FontCodec v2, int v3, int v4) {
        this();
        this.a = null;
        this.a_g = null;
        this.a_B = 0;
        this.a_Image = null;
        this.a_I = 0;
        this.b = null;
        this.c = null;
        this.b_I = 0;
        this.q = 0;
        this.r = 0;
        this.a_Z = false;
        this.s = -1000;
        this.a(v1, v2, v3);
        this.r = v4;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        this.q = 2;
        return;
    }
    // bytecode 22 bytes, max_stack 2, max_locals 2
    public int a(byte v1) {
        if ((v1 & 255) < this.a.length) goto L15;
        return 0;
        L15:
        return this.a[v1];
    }
    // bytecode 11 bytes, max_stack 2, max_locals 2
    public int b(byte v1) {
        return (this.a(v1) - this.q);
    }
    // bytecode 22 bytes, max_stack 2, max_locals 2
    public int c(byte v1) {
        if ((v1 & 255) < this.b.length) goto L15;
        return 0;
        L15:
        return this.b[v1];
    }
    // bytecode 22 bytes, max_stack 2, max_locals 2
    public int d(byte v1) {
        if ((v1 & 255) < this.c.length) goto L15;
        return 0;
        L15:
        return this.c[v1];
    }
    // bytecode 59 bytes, max_stack 5, max_locals 4
    public int a(String v1) {
        if (v1 == null) goto L11;
        if (v1.length() != 0) goto L13;
        L11:
        return 0;
        L13:
        int v2 = 0;
        int v3 = 0;
        L17:
        if (v3 >= v1.length()) goto L52;
        v2 = (v2 + (this.b(this.a(v1.charAt(v3))) + this.a_I));
        v3 += 1;
        goto L17;
        L52:
        return (v2 - this.a_I);
    }
    // bytecode 60 bytes, max_stack 5, max_locals 3
    public int a(int v1) {
        if (v1 > 0) goto L15;
        return this.b(this.a(48));
        L15:
        int v2 = 0;
        L17:
        if (v1 <= 0) goto L53;
        v2 = (v2 + (this.b(this.a(((char) ((v1 % 10) + 48)))) + this.a_I));
        v1 = (v1 / 10);
        goto L17;
        L53:
        return (v2 - this.a_I);
    }
    // bytecode 9 bytes, max_stack 4, max_locals 2
    public int a(byte[] v1) {
        return this.a(v1, 0, v1.length);
    }
    // bytecode 104 bytes, max_stack 4, max_locals 7
    public int a(byte[] v1, int v2, int v3) {
        if (v1 == null) goto L9;
        if (v1.length != 0) goto L11;
        L9:
        return 0;
        L11:
        int v4 = 0;
        int v6 = 0;
        L17:
        if (v6 >= v3) goto L96;
        int v5 = (v6 + v2);
        if ((v6 + v2) >= v1.length) goto L96;
        if ((v1[v5] & 255) <= SysUtil.b_I) goto L72;
        v4 = (v4 + (this.b(this.a(32)) + this.a_I));
        goto L90;
        L72:
        v4 = (v4 + (this.b(v1[v5]) + this.a_I));
        L90:
        v6 += 1;
        goto L17;
        L96:
        return (v4 - this.a_I);
    }
    // bytecode 10 bytes, max_stack 3, max_locals 2
    public int a(char v1) {
        return this.b(this.a(v1));
    }
    // bytecode 11 bytes, max_stack 2, max_locals 2
    public int e(byte v1) {
        return (this.a(v1) + this.a_I);
    }
    // bytecode 106 bytes, max_stack 4, max_locals 7
    public String a(byte[] v1) {
        int v3 = v1.length;
        v1 = ((byte[]) 0);
        byte[] v2 = v1;
        v1 = ((byte[]) this);
        String v4 = "";
        int v6 = 0;
        L16:
        if (v6 >= v3) goto L103;
        int v5 = (v6 + 0);
        if ((v6 + 0) >= v2.length) goto L103;
        if ((v2[v5] & 255) <= 0) goto L97;
        if ((v2[v5] & 255) > SysUtil.b_I) goto L97;
        new java.lang.StringBuffer(); /* constructor */
        v5 = v2[v5];
        v4 = ((String) v1);
        v4 = new java.lang.StringBuffer().append(v4).append(v1.a_g.a(v5)).toString();
        L97:
        v6 += 1;
        goto L16;
        L103:
        return v4;
    }
    // bytecode 16 bytes, max_stack 3, max_locals 3
    public byte[] a(String v1) {
        byte v2 = new byte[v1.length()];
        /* pop: this.a(v1, v2); */
        return v2;
    }
    // bytecode 45 bytes, max_stack 5, max_locals 4
    public int a(String v1, byte[] v2) {
        if (v1 != null) goto L6;
        return 0;
        L6:
        int v3 = 0;
        L8:
        if (v3 >= v1.length()) goto L40;
        if (v3 >= v2.length) goto L40;
        v2[v3] = this.a(v1.charAt(v3));
        v3 += 1;
        goto L8;
        L40:
        return v1.length();
    }
    // bytecode 78 bytes, max_stack 5, max_locals 3
    public int a(int v1, int v2) {
        if (v1 > 0) goto L23;
        Font.e = 1;
        Font.d[v2] = this.a(48);
        return Font.e;
        L23:
        Font.e = 0;
        L27:
        if (v1 <= 0) goto L74;
        Font.f = (v1 % 10);
        v1 = (v1 / 10);
        Font.d[(v2 - Font.e)] = this.a(((char) (48 + Font.f)));
        Font.e = (Font.e + 1);
        goto L27;
        L74:
        return Font.e;
    }
    // bytecode 29 bytes, max_stack 8, max_locals 5
    public void a(Graphics v1, int v2, int v3, int v4) {
        v2 = this.a(v2, 32);
        this.a(v1, Font.d, ((32 - v2) + 1), v2, v3, v4, 10);
        return;
    }
    // bytecode 27 bytes, max_stack 8, max_locals 5
    public void a(Graphics v1, String v2, int v3, int v4) {
        v1 = ((Graphics) this);
        this.a(v1, Font.d, 0, this.a(v2, Font.d), v3, v4, 10);
        return;
    }
    // bytecode 20 bytes, max_stack 8, max_locals 5
    public void a(Graphics v1, byte[] v2, int v3, int v4) {
        if (v2 != null) goto L5;
        return;
        L5:
        this.a(v1, v2, 0, v2.length, v3, v4, 10);
        return;
    }
    // bytecode 247 bytes, max_stack 11, max_locals 8
    public void a(Graphics v1, byte[] v2, int v3, int v4, int v5, int v6, int v7) {
        /* pop: v1.getClipX(); */
        /* pop: v1.getClipWidth(); */
        /* pop: v1.getClipY(); */
        /* pop: v1.getClipHeight(); */
        v7 = v6;
        v6 = v5;
        v5 = v4;
        v4 = v3;
        v3 = ((int) v2);
        v2 = ((byte[]) v1);
        v1 = ((Graphics) this);
        if (v3 != null) goto L49;
        goto L245;
        L49:
        Font.g = v2.getClipX();
        Font.h = v2.getClipY();
        Font.i = v2.getClipWidth();
        Font.j = v2.getClipHeight();
        Font.k = 0;
        Font.c_I = 0;
        Font.b_B = 0;
        Font.l = 0;
        L93:
        if (Font.l >= v5) goto L228;
        Font.c_I = (v4 + Font.l);
        Font.b_B = v3[Font.c_I];
        if ((v3[Font.c_I] & 255) <= SysUtil.b_I) goto L169;
        Font.k = (Font.k + v1.a(v1.a(32), v6, v7, v2, Font.g, Font.h, Font.i, Font.j, Font.k));
        goto L217;
        L169:
        if (Font.c_I >= v3.length) goto L217;
        if (Font.b_B < 0) goto L217;
        Font.k = (Font.k + v1.a(Font.b_B, v6, v7, v2, Font.g, Font.h, Font.i, Font.j, Font.k));
        L217:
        Font.l = (Font.l + 1);
        goto L93;
        L228:
        v2.setClip(Font.g, Font.h, Font.i, Font.j);
        L245:
        return;
    }
    // bytecode 604 bytes, max_stack 7, max_locals 10
    public int a(byte v1, int v2, int v3, Graphics v4, int v5, int v6, int v7, int v8, int v9) {
        v2 += 1;
        if (v1 >= 86) goto L12;
        v3 += 1;
        L12:
        if (this.a_Z == 0) goto L28;
        v3 = (v3 + (this.r / 2));
        L28:
        if (this.b_I == Settings.n()) goto L42;
        this.c();
        L42:
        Font.m = (v2 + v9);
        Font.o = this.a(v1);
        Font.n = v3;
        Font.p = this.a_B;
        if ((Settings.l() % 2) != 1) goto L245;
        if (Settings.l() != 1) goto L102;
        Font.n = (v2 - Font.p);
        Font.m = (v3 + v9);
        goto L117;
        L102:
        Font.n = v2;
        Font.m = ((v3 + v9) - Font.o);
        L117:
        if (Font.m >= v6) goto L153;
        Font.o = (Font.o - (v6 - Font.m));
        Font.m = v6;
        if (Font.o >= 0) goto L153;
        Font.o = 0;
        L153:
        if (Font.n >= v5) goto L189;
        Font.p = (Font.p - (v5 - Font.n));
        Font.n = v5;
        if (Font.p >= 0) goto L189;
        Font.p = 0;
        L189:
        if ((Font.n + Font.p) <= (v5 + v7)) goto L217;
        Font.p = (((-Font.n) + v5) + v7);
        L217:
        if ((Font.m + Font.o) <= (v6 + v8)) goto L245;
        Font.o = (((-Font.m) + v6) + v8);
        L245:
        if (Settings.l() != 1) goto L324;
        v4.setClip(Font.n, Font.m, Font.p, Font.o);
        if (v1 == this.s) goto L313;
        v4.drawImage(this.a_Image, (v2 + this.d(v1)), ((v3 - ((256 + this.c(v1)) % 256)) + v9), 24);
        L313:
        return (this.b(v1) + this.a_I);
        L324:
        if (Settings.l() != 3) goto L404;
        v4.setClip(Font.n, Font.m, Font.p, Font.o);
        if (v1 == this.s) goto L392;
        v4.drawImage(this.a_Image, (v2 - this.d(v1)), ((v3 + ((256 + this.c(v1)) % 256)) + v9), 36);
        L392:
        return (-(this.b(v1) + this.a_I));
        L404:
        if (Font.m >= v5) goto L440;
        Font.o = (Font.o - (v5 - Font.m));
        Font.m = v5;
        if (Font.o >= 0) goto L440;
        Font.o = 0;
        L440:
        if (Font.n >= v6) goto L476;
        Font.p = (Font.p - (v6 - Font.n));
        Font.n = v6;
        if (Font.p >= 0) goto L476;
        Font.p = 0;
        L476:
        if ((Font.m + Font.o) <= (v5 + v7)) goto L504;
        Font.o = (((-Font.m) + v5) + v7);
        L504:
        if ((Font.n + Font.p) <= (v6 + v8)) goto L532;
        Font.p = (((-Font.n) + v6) + v8);
        L532:
        v4.setClip(Font.m, Font.n, Font.o, Font.p);
        if (v1 == this.s) goto L593;
        v4.drawImage(this.a_Image, ((v2 - ((256 + this.c(v1)) % 256)) + v9), (v3 - this.d(v1)), 20);
        L593:
        return (this.b(v1) + this.a_I);
    }
    // bytecode 9 bytes, max_stack 2, max_locals 1
    public byte a() {
        return this.a(this.a_Z);
    }
    // bytecode 19 bytes, max_stack 2, max_locals 2
    public byte a(boolean v1) {
        if (v1 == 0) goto L15;
        jt1 = this.r; /* join L16 from L8 */
        goto L16;
        L15:
        jt1 = 0; /* join L16 from L15 */
        L16:
        return ((byte) (this.a_B + jt1));
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public byte a(char v1) {
        return this.a_g.a(v1);
    }
    // bytecode 123 bytes, max_stack 8, max_locals 4
    public void a(int v1, boolean v2) {
        v2 = ((boolean) new int[(this.a_Image.getWidth() * this.a_Image.getHeight())]);
        this.a_Image.getRGB(v2, 0, this.a_Image.getWidth(), 0, 0, this.a_Image.getWidth(), this.a_Image.getHeight());
        int v3 = 0;
        L52:
        if (v3 >= v2.length) goto L99;
        if ((v2[v3] & -16777216) == 0) goto L89;
        if (v2[v3] != m1) goto L81;
        v2[v3] = v1;
        goto L93;
        L81:
        if (v2[v3] != -16777216) goto L93;
        L89:
        v2[v3] = 0;
        L93:
        v3 += 1;
        goto L52;
        L99:
        this.a_Image = javax.microedition.lcdui.Image.createRGBImage(v2, this.a_Image.getWidth(), this.a_Image.getHeight(), true);
        return;
    }
    // bytecode 383 bytes, max_stack 8, max_locals 8
    public void b(Graphics v1, int v2, int v3, int v4) {
        v2 = (v2 / 60);
        int v5 = ((v2 / 60) % 60);
        v2 = (v2 / 60);
        int v6 = ((v2 / 60) % 24);
        v2 = (v2 / 24);
        byte[] v7 = SysUtil.a(170);
        Font.d_I = 0;
        Font.d[(32 - Font.d_I)] = v7[2];
        Font.d_I = (Font.d_I + 1);
        if (v5 > 0) goto L75;
        if (v6 > 0) goto L75;
        if (v2 <= 0) goto L160;
        L75:
        v5 = this.a(v5, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v5);
        if (v5 >= 2) goto L208;
        if (v5 > 0) goto L133;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L133:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        goto L208;
        L160:
        Font.d[(32 - Font.d_I)] = this.a(49);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = this.a(60);
        Font.d_I = (Font.d_I + 1);
        L208:
        if (v6 > 0) goto L217;
        if (v2 <= 0) goto L286;
        L217:
        Font.d[(32 - Font.d_I)] = this.a(32);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = v7[1];
        Font.d_I = (Font.d_I + 1);
        v5 = this.a(v6, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v5);
        L286:
        if (v2 <= 0) goto L358;
        Font.d[(32 - Font.d_I)] = this.a(32);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = v7[0];
        Font.d_I = (Font.d_I + 1);
        v5 = this.a(v2, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v5);
        L358:
        this.a(v1, Font.d, ((32 - Font.d_I) + 1), Font.d_I, v3, v4, 10);
        return;
    }
    // bytecode 332 bytes, max_stack 8, max_locals 8
    public void a(Graphics v1, long v2, int v4, int v5) {
        int v6 = ((int) ((v2 / 10L) % 100L));
        v2 = (v2 / 1000L);
        int v7 = ((int) ((v2 / 1000L) / 60L));
        v2 = ((long) ((int) (v2 % 60L)));
        Font.d_I = this.a(v6, 32);
        if (this.a(v6, 32) >= 2) goto L103;
        if (Font.d_I > 0) goto L79;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L79:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L103:
        Font.d[(32 - Font.d_I)] = this.a(46);
        Font.d_I = (Font.d_I + 1);
        v2 = ((long) this.a(v2, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v2);
        if (v2 >= 2) goto L204;
        if (v2 > 0) goto L180;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L180:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L204:
        Font.d[(32 - Font.d_I)] = this.a(58);
        Font.d_I = (Font.d_I + 1);
        v2 = ((long) this.a(v7, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v2);
        if (v2 >= 2) goto L306;
        if (v2 > 0) goto L282;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L282:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L306:
        this.a(v1, Font.d, ((32 - Font.d_I) + 1), Font.d_I, v4, v5, 10);
        return;
    }
    // bytecode 362 bytes, max_stack 4, max_locals 5
    public int b(int v1) {
        v1 = (v1 / 60);
        int v2 = ((v1 / 60) % 60);
        v1 = (v1 / 60);
        int v3 = ((v1 / 60) % 24);
        v1 = (v1 / 24);
        byte[] v4 = SysUtil.a(170);
        Font.d_I = 0;
        Font.d[(32 - Font.d_I)] = v4[2];
        Font.d_I = (Font.d_I + 1);
        if (v2 > 0) goto L71;
        if (v3 > 0) goto L71;
        if (v1 <= 0) goto L151;
        L71:
        v2 = this.a(v2, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v2);
        if (v2 >= 2) goto L199;
        if (v2 > 0) goto L124;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L124:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        goto L199;
        L151:
        Font.d[(32 - Font.d_I)] = this.a(49);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = this.a(60);
        Font.d_I = (Font.d_I + 1);
        L199:
        if (v3 > 0) goto L207;
        if (v1 <= 0) goto L273;
        L207:
        Font.d[(32 - Font.d_I)] = this.a(32);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = v4[1];
        Font.d_I = (Font.d_I + 1);
        v2 = this.a(v3, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v2);
        L273:
        if (v1 <= 0) goto L343;
        Font.d[(32 - Font.d_I)] = this.a(32);
        Font.d_I = (Font.d_I + 1);
        Font.d[(32 - Font.d_I)] = v4[0];
        Font.d_I = (Font.d_I + 1);
        v2 = this.a(v1, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v2);
        L343:
        return this.a(Font.d, ((32 - Font.d_I) + 1), Font.d_I);
    }
    // bytecode 323 bytes, max_stack 4, max_locals 5
    public int a(long v1) {
        int v3 = ((int) ((v1 / 10L) % 100L));
        v1 = (v1 / 1000L);
        int v4 = ((int) ((v1 / 1000L) / 60L));
        v1 = ((long) ((int) (v1 % 60L)));
        Font.d_I = this.a(v3, 32);
        if (this.a(v3, 32) >= 2) goto L101;
        if (Font.d_I > 0) goto L77;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L77:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L101:
        Font.d[(32 - Font.d_I)] = this.a(46);
        Font.d_I = (Font.d_I + 1);
        v1 = ((long) this.a(v1, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v1);
        if (v1 >= 2) goto L202;
        if (v1 > 0) goto L178;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L178:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L202:
        Font.d[(32 - Font.d_I)] = this.a(58);
        Font.d_I = (Font.d_I + 1);
        v1 = ((long) this.a(v4, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v1);
        if (v1 >= 2) goto L304;
        if (v1 > 0) goto L280;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L280:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L304:
        return this.a(Font.d, ((32 - Font.d_I) + 1), Font.d_I);
    }
    // bytecode 399 bytes, max_stack 8, max_locals 10
    public void b(Graphics v1, long v2, int v4, int v5) {
        long v6 = v2;
        if (lcmp(v2, 0L) >= 0) goto L13;
        v6 = (-v2);
        L13:
        int v8 = ((int) ((v6 / 10L) % 100L));
        v6 = (v6 / 1000L);
        int v9 = ((int) ((v6 / 1000L) / 60L));
        v6 = ((long) ((int) (v6 % 60L)));
        Font.d_I = 0;
        int v7 = (v8 % 10);
        if ((v8 % 10) <= 0) goto L77;
        Font.d_I = this.a(v7, 32);
        L77:
        v7 = (v8 / 10);
        Font.d_I = (Font.d_I + this.a(v7, (32 - Font.d_I)));
        if ((Font.d_I + this.a(v7, (32 - Font.d_I))) > 0) goto L131;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L131:
        Font.d[(32 - Font.d_I)] = this.a(46);
        Font.d_I = (Font.d_I + 1);
        v6 = ((long) this.a(v6, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v6);
        if (v6 >= 2) goto L242;
        if (v9 <= 0) goto L242;
        if (v6 > 0) goto L218;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L218:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L242:
        if (v9 <= 0) goto L324;
        Font.d[(32 - Font.d_I)] = this.a(58);
        Font.d_I = (Font.d_I + 1);
        v6 = ((long) this.a(v9, (32 - Font.d_I)));
        Font.d_I = (Font.d_I + v6);
        if (v6 >= 2) goto L324;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L324:
        if (lcmp(v2, 0L) < 0) goto L349;
        Font.d[(32 - Font.d_I)] = this.a(43);
        goto L365;
        L349:
        Font.d[(32 - Font.d_I)] = this.a(45);
        L365:
        Font.d_I = (Font.d_I + 1);
        this.a(v1, Font.d, ((32 - Font.d_I) + 1), Font.d_I, v4, v5, 10);
        return;
    }
    // bytecode 365 bytes, max_stack 5, max_locals 7
    public int b(long v1) {
        int v3 = ((int) ((v1 / 10L) % 100L));
        v1 = (v1 / 1000L);
        int v4 = ((int) ((v1 / 1000L) / 60L));
        int v5 = ((int) (v1 % 60L));
        Font.d_I = 0;
        int v6 = (v3 % 10);
        if ((v3 % 10) <= 0) goto L58;
        Font.d_I = this.a(v6, 32);
        L58:
        v6 = (v3 / 10);
        Font.d_I = (Font.d_I + this.a(v6, (32 - Font.d_I)));
        if ((Font.d_I + this.a(v6, (32 - Font.d_I))) > 0) goto L111;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L111:
        Font.d[(32 - Font.d_I)] = this.a(46);
        Font.d_I = (Font.d_I + 1);
        v3 = this.a(v5, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v3);
        if (v3 >= 2) goto L218;
        if (v4 <= 0) goto L218;
        if (v3 > 0) goto L194;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L194:
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L218:
        if (v4 <= 0) goto L297;
        Font.d[(32 - Font.d_I)] = this.a(58);
        Font.d_I = (Font.d_I + 1);
        v3 = this.a(v4, (32 - Font.d_I));
        Font.d_I = (Font.d_I + v3);
        if (v3 >= 2) goto L297;
        Font.d[(32 - Font.d_I)] = this.a(48);
        Font.d_I = (Font.d_I + 1);
        L297:
        if (lcmp(v1, 0L) <= 0) goto L322;
        Font.d[(32 - Font.d_I)] = this.a(43);
        goto L338;
        L322:
        Font.d[(32 - Font.d_I)] = this.a(45);
        L338:
        Font.d_I = (Font.d_I + 1);
        return this.a(Font.d, ((32 - Font.d_I) + 1), Font.d_I);
    }
}

