// Generated by tools/jdeob.py from x/co.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `co`.
// String constants: /images/add.png | /images/bob_full.png | /images/box.png | /images/bt.png | /images/ea.png | /images/full.png | /images/garage.png | /images/pho.png | <clinit> | <init> | Code | KORa
// API references: java/util javax/microedition
public class Garage {
    private static Image[] a;
    private static boolean a_Z;
    private static boolean b;
    private static byte[] a_arrB;
    private static int[] a_arrI;
    private static int a_I;
    private static float[][] a_arrarrF;
    private static int[][] a_arrarrI;
    private static int[][] b_arrarrI;
    private static int b_I;
    private static int c;
    private static float a_F;
    private static float b_F;
    private static float c_F;
    private static float d;
    private static CheckBox a_n;
    private static int d_I;
    private static int e;
    private static float e_F;
    private static float f;
    private static boolean c_Z;
    private static String a_String;
    private static int[] b_arrI;
    private static int f_I;
    private static int g;
    private static boolean d_Z;
    private static boolean e_Z;
    private static boolean f_Z;
    private static boolean g_Z;
    private static Image a_Image;
    private static ObfAm a_am;
    private static ObfCq a_cq;
    private static Transform a_Transf;
    private static Image b_Image;
    private static Image c_Image;
    private static Image d_Image;
    private static Image e_Image;
    private static Image f_Image;
    private static Image g_Image;
    private static int h;
    private static boolean h_Z;
    private static boolean i;
    private static Background a_Backgr;
    private static boolean j;
    static {
        new javax.microedition.lcdui.Image[2]#1[0] = null;
        new javax.microedition.lcdui.Image[2]#1[1] = null;
        Garage.a = new javax.microedition.lcdui.Image[2]#1;
        Garage.a_Z = false;
        Garage.b = false;
        new byte[6]#2[0] = 48;
        new byte[6]#2[1] = 28;
        new byte[6]#2[2] = 38;
        new byte[6]#2[3] = 40;
        new byte[6]#2[4] = 34;
        new byte[6]#2[5] = 34;
        Garage.a_arrB = new byte[6]#2;
        new int[6]#3[0] = 0;
        new int[6]#3[1] = 48;
        new int[6]#3[2] = 76;
        new int[6]#3[3] = 114;
        new int[6]#3[4] = 154;
        new int[6]#3[5] = 188;
        Garage.a_arrI = new int[6]#3;
        Garage.a_I = Garage.a_arrB.length;
        new float[6]#5[0] = 0.15000000596046448f;
        new float[6]#5[1] = 0.15000000596046448f;
        new float[6]#5[2] = 0.15000000596046448f;
        new float[6]#5[3] = 0.15000000596046448f;
        new float[6]#5[4] = 0.15000000596046448f;
        new float[6]#5[5] = 0.15000000596046448f;
        new Obf[F[5]#4[0] = new float[6]#5;
        new float[6]#6[0] = 0.15000000596046448f;
        new float[6]#6[1] = 0.15000000596046448f;
        new float[6]#6[2] = 0.15000000596046448f;
        new float[6]#6[3] = 0.15000000596046448f;
        new float[6]#6[4] = 0.15000000596046448f;
        new float[6]#6[5] = 0.15000000596046448f;
        new Obf[F[5]#4[1] = new float[6]#6;
        new float[3]#7[0] = 2.0f;
        new float[3]#7[1] = 4.0f;
        new float[3]#7[2] = 1.5f;
        new Obf[F[5]#4[2] = new float[3]#7;
        new float[3]#8[0] = 2.0f;
        new float[3]#8[1] = 4.5f;
        new float[3]#8[2] = 1.5f;
        new Obf[F[5]#4[3] = new float[3]#8;
        new float[2]#9[0] = 2.5f;
        new float[2]#9[1] = 2.200000047683716f;
        new Obf[F[5]#4[4] = new float[2]#9;
        Garage.a_arrarrF = new Obf[F[5]#4;
        new int[6]#11[0] = 1;
        new int[6]#11[1] = 2;
        new int[6]#11[2] = 1;
        new int[6]#11[3] = 5;
        new int[6]#11[4] = 3;
        new int[6]#11[5] = 5;
        new Obf[I[5]#10[0] = new int[6]#11;
        new int[6]#12[0] = (Garage.a_I + 1);
        new int[6]#12[1] = (Garage.a_I + 2);
        new int[6]#12[2] = (Garage.a_I + 1);
        new int[6]#12[3] = (Garage.a_I + 5);
        new int[6]#12[4] = (Garage.a_I + 3);
        new int[6]#12[5] = (Garage.a_I + 5);
        new Obf[I[5]#10[1] = new int[6]#12;
        new int[3]#13[0] = 4;
        new int[3]#13[1] = 0;
        new int[3]#13[2] = 4;
        new Obf[I[5]#10[2] = new int[3]#13;
        new int[3]#14[0] = (Garage.a_I + 4);
        new int[3]#14[1] = Garage.a_I;
        new int[3]#14[2] = (Garage.a_I + 4);
        new Obf[I[5]#10[3] = new int[3]#14;
        new int[2]#15[0] = 4;
        new int[2]#15[1] = (Garage.a_I + 4);
        new Obf[I[5]#10[4] = new int[2]#15;
        Garage.a_arrarrI = new Obf[I[5]#10;
        new int[6]#17[0] = 7;
        new int[6]#17[1] = 7;
        new int[6]#17[2] = 7;
        new int[6]#17[3] = 7;
        new int[6]#17[4] = 7;
        new int[6]#17[5] = 7;
        new Obf[I[5]#16[0] = new int[6]#17;
        new int[6]#18[0] = -7;
        new int[6]#18[1] = -7;
        new int[6]#18[2] = -7;
        new int[6]#18[3] = -7;
        new int[6]#18[4] = -7;
        new int[6]#18[5] = -7;
        new Obf[I[5]#16[1] = new int[6]#18;
        new int[3]#19[0] = 0;
        new int[3]#19[1] = 0;
        new int[3]#19[2] = 0;
        new Obf[I[5]#16[2] = new int[3]#19;
        new int[3]#20[0] = 0;
        new int[3]#20[1] = 0;
        new int[3]#20[2] = 0;
        new Obf[I[5]#16[3] = new int[3]#20;
        new int[2]#21[0] = 0;
        new int[2]#21[1] = 0;
        new Obf[I[5]#16[4] = new int[2]#21;
        Garage.b_arrarrI = new Obf[I[5]#16;
        Garage.b_I = 2;
        Garage.c = 0;
        Garage.a_F = 0.0f;
        Garage.b_F = 0.0f;
        Garage.c_F = 140.0f;
        Garage.d = 10.0f;
        Garage.a_n = null;
        Garage.d_I = 200;
        Garage.e = 160;
        Garage.e_F = 0.30000001192092896f;
        Garage.f = 0.30000001192092896f;
        Garage.c_Z = false;
        Garage.a_String = "";
        Garage.b_arrI = new int[15]#22;
        Garage.f_I = 0;
        Garage.g = 0;
        Garage.d_Z = false;
        Garage.e_Z = true;
        Garage.f_Z = false;
        Garage.g_Z = false;
        Garage.a_Image = null;
        Garage.a_am = null;
        Garage.a_cq = null;
        Garage.a_Transf = null;
        Garage.b_Image = null;
        Garage.c_Image = null;
        Garage.d_Image = null;
        Garage.e_Image = null;
        Garage.f_Image = null;
        Garage.g_Image = null;
        Garage.h = 0;
        Garage.h_Z = false;
        Garage.i = false;
        Garage.a_Backgr = null;
        Garage.j = false;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Garage() {
        super();
        return;
    }
    // bytecode 116 bytes, max_stack 4, max_locals 0
    public static void d() {
        /* try L7-L113 catch java.io.IOException -> L114 */
        if (Garage.a_Z == 0) goto L7;
        return;
        L7:
        if (Garage.a[0] != null) goto L28;
        Garage.a[0] = javax.microedition.lcdui.Image.createImage(Resources.a("/images/bob_full.png"));
        L28:
        if (Garage.a[1] != null) goto L49;
        Garage.a[1] = SysUtil.a(Garage.a[0]);
        L49:
        if (Garage.a_Image != null) goto L66;
        Garage.a_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/garage.png"));
        L66:
        Garage.c_F = ((float) ((SysUtil.e / 2) - 8));
        new CheckBox(Garage.d_I, Garage.e); /* constructor */
        Garage.a_n = new CheckBox(Garage.d_I, Garage.e);
        Garage.a_Z = true;
        new javax.microedition.m3g.Background(); /* constructor */
        Garage.a_Backgr = new javax.microedition.m3g.Background();
        new javax.microedition.m3g.Background().setColor(0);
        return;
        /* pop: ex_114; */
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void a(boolean v0) {
        Garage.e_Z = v0;
        return;
    }
    // bytecode 4 bytes, max_stack 1, max_locals 0
    public static boolean a() {
        return Garage.d_Z;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public static void b(boolean v0) {
        Garage.d_Z = v0;
        return;
    }
    // bytecode 4 bytes, max_stack 1, max_locals 0
    public static boolean b() {
        return Garage.e_Z;
    }
    // bytecode 37 bytes, max_stack 3, max_locals 0
    public static void a() {
        if (Garage.a_am == null) goto L36;
        KORa.m_pCanvas.a().a(Garage.a_Backgr);
        KORa.m_pCanvas.a().a(Garage.a_am.a(), Garage.a_Transf);
        L36:
        return;
    }
    // bytecode 1219 bytes, max_stack 6, max_locals 10
    public static void a(Graphics v0) {
        if (Garage.c() != 0) goto L13;
        if (Garage.d_Z != 0) goto L13;
        return;
        L13:
        if (Garage.a_Z != 0) goto L22;
        Garage.d();
        L22:
        if (Garage.e_Z == 0) goto L440;
        Graphics v1 = v0;
        if (Garage.a_am != null) goto L97;
        if (Garage.h != 0) goto L97;
        v1.setColor(0);
        v1.fillRect(0, 0, v1.getClipWidth(), v1.getClipHeight());
        v1.drawImage(Garage.a_Image, ((SysUtil.e - Garage.a_Image.getWidth()) / 2), ((SysUtil.f_I - Garage.a_Image.getHeight()) / 2), 20);
        goto L440;
        L97:
        if (Garage.h <= 0) goto L440;
        v1.setColor(0);
        v1.fillRect(0, 0, v1.getClipWidth(), v1.getClipHeight());
        if (Garage.b_arrI[Garage.g] != 51) goto L173;
        v1.drawImage(Garage.d(), ((SysUtil.e - Garage.d().getWidth()) / 2), (((SysUtil.f_I - Garage.d().getHeight()) / 2) - 20), 20);
        goto L440;
        L173:
        if (Garage.b_arrI[Garage.g] != 53) goto L224;
        v1.drawImage(Garage.f(), ((SysUtil.e - Garage.f().getWidth()) / 2), (((SysUtil.f_I - Garage.f().getHeight()) / 2) + 10), 20);
        goto L440;
        L224:
        if (Garage.b_arrI[Garage.g] != 52) goto L272;
        v1.drawImage(Garage.e(), ((SysUtil.e - Garage.e().getWidth()) / 2), ((SysUtil.f_I - Garage.e().getHeight()) / 2), 20);
        goto L440;
        L272:
        if (Garage.b_arrI[Garage.g] != 65) goto L401;
        v1.drawImage(Garage.c(), (((SysUtil.e - Garage.c().getWidth()) / 2) - 60), (((SysUtil.f_I - Garage.c().getHeight()) / 2) + 20), 20);
        v1.drawImage(Garage.c(), (((SysUtil.e - Garage.c().getWidth()) / 2) + 60), (((SysUtil.f_I - Garage.c().getHeight()) / 2) + 20), 20);
        v1.drawImage(Garage.b(), ((SysUtil.e - Garage.b().getWidth()) / 2), (((SysUtil.f_I - Garage.b().getHeight()) / 2) + 20), 20);
        goto L440;
        L401:
        v1.drawImage(Garage.a(), (((SysUtil.e - Garage.a().getWidth()) / 2) - 30), (((SysUtil.f_I - Garage.a().getHeight()) / 2) + 10), 20);
        L440:
        Garage.d = ((((float) SysUtil.f_I) / 2.0f) - (((float) Garage.a[0].getHeight()) / 4.0f));
        if (fcmpg(((((((float) SysUtil.f_I) / 2.0f) - (((float) Garage.a[0].getHeight()) / 4.0f)) + ((float) Garage.a[0].getHeight())) + 4.0f), ((float) SysUtil.f_I)) <= 0) goto L502;
        Garage.d = ((float) ((SysUtil.f_I - Garage.a[0].getHeight()) - 4));
        L502:
        int v3 = ((int) (Garage.e_F * ((float) Garage.e)));
        int v2 = ((int) (Garage.e_F * ((float) Garage.d_I)));
        v1 = v0;
        float v4 = (Garage.c_F / ((float) SysUtil.e));
        int v5 = ((int) (((float) (SysUtil.e / 2)) - (((float) Garage.d_I) * Garage.f)));
        int v6 = ((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f));
        if (((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f)) >= 5) goto L581;
        v6 = 5;
        L581:
        if (v5 >= 10) goto L592;
        v5 = 10;
        L592:
        if ((v5 + Garage.d_I) <= (SysUtil.e - 10)) goto L619;
        v5 = ((SysUtil.e - Garage.d_I) - 10);
        L619:
        Garage.a_n.b(v2, v3);
        int v7 = v6;
        if (Garage.a_n.d() <= 80) goto L665;
        v6 = (v6 + ((Garage.a_n.d() - Garage.a_n.a()) / 4));
        goto L683;
        L665:
        v6 = (v6 + (Garage.a_n.d() - Garage.a_n.a()));
        L683:
        v3 = Garage.a_n.a();
        int v8 = ((int) (Garage.e_F * 20.0f));
        int v9 = 0;
        L702:
        if (v9 >= v8) goto L784;
        v1.setColor(15921906);
        v1.drawLine((((int) (Garage.c_F + (((1.0f - v4) * 24.0f) * (((float) (v5 + (Garage.d_I / 2))) / ((float) SysUtil.e))))) + 3), (((int) Garage.d) - 7), (((v5 + ((int) (v4 * ((float) v2)))) + v9) - (v8 / 2)), ((v6 + v3) - 1));
        v9 += 1;
        goto L702;
        L784:
        v1.setColor(5000268);
        v1.drawLine((((int) (Garage.c_F + (((1.0f - v4) * 24.0f) * (((float) (v5 + (Garage.d_I / 2))) / ((float) SysUtil.e))))) + 3), (((int) Garage.d) - 7), ((v5 + ((int) (v4 * ((float) v2)))) - (v8 / 2)), ((v6 + v3) - 1));
        v1.drawLine((((int) (Garage.c_F + (((1.0f - v4) * 24.0f) * (((float) (v5 + (Garage.d_I / 2))) / ((float) SysUtil.e))))) + 3), (((int) Garage.d) - 7), ((v5 + ((int) (v4 * ((float) v2)))) + (v8 / 2)), ((v6 + v3) - 1));
        Garage.a_n.a(v1, v5, v7);
        if (((v6 + v3) - 1) >= (((int) Garage.d) - 7)) goto L987;
        v1.setColor(15921906);
        v1.drawLine(((v5 + ((int) (v4 * ((float) v2)))) - (v8 / 2)), ((v6 + v3) - 1), ((v5 + ((int) (v4 * ((float) v2)))) + (v8 / 2)), ((v6 + v3) - 1));
        L987:
        v3 = ((int) Garage.d);
        v2 = ((int) Garage.c_F);
        v1 = v0;
        if (Garage.a_arrarrI[Garage.b_I][Garage.c] >= Garage.a_arrI.length) goto L1090;
        v1.setClip(v2, v3, Garage.a_arrB[Garage.a_arrarrI[Garage.b_I][Garage.c]], Garage.a[0].getHeight());
        v1.drawImage(Garage.a[0], (v2 - Garage.a_arrI[Garage.a_arrarrI[Garage.b_I][Garage.c]]), v3, 20);
        v1.setClip(0, 0, SysUtil.e, SysUtil.f_I);
        goto L1206;
        L1090:
        v1.setClip(((v2 + 16) - Garage.a_arrB[(Garage.a_arrarrI[Garage.b_I][Garage.c] % Garage.a_arrI.length)]), v3, Garage.a_arrB[(Garage.a_arrarrI[Garage.b_I][Garage.c] % Garage.a_arrI.length)], Garage.a[0].getHeight());
        v1.drawImage(Garage.a[1], (((v2 + 16) - Garage.a[1].getWidth()) + Garage.a_arrI[(Garage.a_arrarrI[Garage.b_I][Garage.c] % Garage.a_arrI.length)]), v3, 20);
        v1.setClip(0, 0, SysUtil.e, SysUtil.f_I);
        L1206:
        if (Garage.f_Z == 0) goto L1218;
        Planet.a(v0, 0, 0);
        L1218:
        return;
    }
    // bytecode 92 bytes, max_stack 3, max_locals 0
    public static void b() {
        if (Garage.f_I <= 0) goto L11;
        Garage.j = true;
        return;
        L11:
        Garage.a_Z = false;
        if (Settings.c() != 0) goto L61;
        Garage.a[0] = null;
        Garage.a[1] = null;
        Garage.a_Image = null;
        Garage.b_Image = null;
        Garage.c_Image = null;
        Garage.d_Image = null;
        Garage.e_Image = null;
        Garage.f_Image = null;
        Garage.g_Image = null;
        L61:
        Garage.a_cq = null;
        Garage.a_Backgr = null;
        if (Garage.a_n == null) goto L81;
        Garage.a_n.e();
        L81:
        Planet.b();
        Garage.j = false;
        java.lang.System.gc();
        return;
    }
    // bytecode 4 bytes, max_stack 1, max_locals 0
    public static int a() {
        return Garage.f_I;
    }
    // bytecode 467 bytes, max_stack 4, max_locals 2
    public static void a(float v0) {
        if (Garage.c() != 0) goto L13;
        if (Garage.d_Z != 0) goto L13;
        return;
        L13:
        if (Garage.a_Z != 0) goto L22;
        Garage.d();
        L22:
        if (Garage.f_Z == 0) goto L56;
        Planet.a();
        if (Planet.a() == 0) goto L56;
        Garage.f_Z = false;
        if (Garage.c() != 0) goto L56;
        int v1 = 0;
        Garage.d_Z = false;
        Planet.b();
        L56:
        Garage.a_F = (Garage.a_F + v0);
        Garage.b_F = (Garage.b_F + v0);
        if (fcmpl(Garage.e_F, 1.0f) >= 0) goto L107;
        Garage.e_F = (Garage.e_F + (v0 * 2.0f));
        if (fcmpg((Garage.e_F + (v0 * 2.0f)), 1.0f) < 0) goto L107;
        Garage.a_n.a_(true);
        Garage.e_F = 1.0f;
        L107:
        if (fcmpg(Garage.b_F, (Garage.a_arrarrF[Garage.b_I][Garage.c] / 2.0f)) <= 0) goto L376;
        Garage.c_F = (Garage.c_F - ((((float) Garage.b_arrarrI[Garage.b_I][Garage.c]) * Garage.b_F) / Garage.a_arrarrF[Garage.b_I][Garage.c]));
        if (fcmpl((Garage.c_F - ((((float) Garage.b_arrarrI[Garage.b_I][Garage.c]) * Garage.b_F) / Garage.a_arrarrF[Garage.b_I][Garage.c])), ((float) ((int) (((float) SysUtil.e) * 0.30000001192092896f)))) >= 0) goto L228;
        Garage.b_I = KORa.rand.nextInt(Garage.a_arrarrI.length);
        Garage.c = 0;
        Garage.c_F = ((float) ((int) (((float) SysUtil.e) * 0.30000001192092896f)));
        if (Garage.h_Z == 0) goto L221;
        if (Garage.b_I != 0) goto L221;
        Garage.b_I = 2;
        L221:
        Garage.i = false;
        goto L372;
        L228:
        if (Garage.h_Z != 0) goto L253;
        if (fcmpg(Garage.c_F, ((float) ((int) ((((float) SysUtil.e) * 0.699999988079071f) - 16.0f)))) > 0) goto L269;
        L253:
        if (fcmpg(Garage.c_F, ((float) ((int) (((float) SysUtil.e) - 46.0f)))) <= 0) goto L372;
        L269:
        Garage.b_I = KORa.rand.nextInt(Garage.a_arrarrI.length);
        if (Garage.h_Z != 0) goto L336;
        if (fcmpg(Garage.c_F, ((float) ((int) ((((float) SysUtil.e) * 0.699999988079071f) - 15.0f)))) <= 0) goto L314;
        Garage.b_I = 0;
        goto L352;
        L314:
        Garage.c_F = ((float) ((int) ((((float) SysUtil.e) * 0.699999988079071f) - 16.0f)));
        Garage.c = 0;
        goto L352;
        L336:
        Garage.c_F = ((float) ((int) (((float) SysUtil.e) - 46.0f)));
        Garage.c = 0;
        L352:
        if (Garage.h_Z == 0) goto L368;
        if (Garage.b_I != 0) goto L368;
        Garage.b_I = 2;
        L368:
        Garage.i = false;
        L372:
        Garage.b_F = 0.0f;
        L376:
        if (fcmpg(Garage.a_F, Garage.a_arrarrF[Garage.b_I][Garage.c]) <= 0) goto L466;
        Garage.a_F = 0.0f;
        Garage.b_F = 0.0f;
        Garage.c = (Garage.c + 1);
        if ((Garage.c + 1) < Garage.a_arrarrI[Garage.b_I].length) goto L466;
        Garage.b_I = KORa.rand.nextInt(Garage.a_arrarrI.length);
        Garage.c = 0;
        if (Garage.i == 0) goto L450;
        Garage.b_I = 1;
        return;
        L450:
        if (Garage.h_Z == 0) goto L466;
        if (Garage.b_I != 0) goto L466;
        Garage.b_I = 2;
        L466:
        return;
    }
    // bytecode 17 bytes, max_stack 2, max_locals 3
    public static void a(int v0, ObfAm v1, Transform v2) {
        Garage.c(v0);
        v1 = ((ObfAm) v2);
        v0 = ((int) v1);
        Garage.a_am = v1;
        Garage.a_Transf = v1;
        return;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image a() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.b_Image != null) goto L21;
        Garage.b_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/box.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.b_Image;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image b() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.e_Image != null) goto L21;
        Garage.e_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/bt.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.e_Image;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image c() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.e_Image != null) goto L21;
        Garage.d_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/pho.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.d_Image;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image d() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.c_Image != null) goto L21;
        Garage.c_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/full.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.c_Image;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image e() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.f_Image != null) goto L21;
        Garage.f_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/ea.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.f_Image;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 0
    public static Image f() {
        /* try L6-L17 catch java.io.IOException -> L20 */
        if (Garage.g_Image != null) goto L21;
        Garage.g_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/add.png"));
        goto L21;
        /* pop: ex_20; */
        L21:
        return Garage.g_Image;
    }
    // bytecode 9 bytes, max_stack 1, max_locals 1
    public static void a(int v0) {
        Garage.c(v0);
        Garage.h = 1;
        return;
    }
    // bytecode 194 bytes, max_stack 5, max_locals 2
    public static void a(String v0) {
        Garage.h = 1;
        if (Garage.a_Z != 0) goto L15;
        Garage.d();
        L15:
        Garage.h_Z = false;
        Garage.i = false;
        Garage.a_am = null;
        Garage.a_cq = null;
        Garage.a_Transf = null;
        int v1 = 1;
        Garage.e_Z = true;
        if (Garage.f_I == Garage.b_arrI.length) goto L176;
        Garage.b_arrI[((Garage.g + Garage.f_I) % Garage.b_arrI.length)] = -1000;
        Garage.a_String = v0;
        if (Garage.f_I != 0) goto L160;
        Garage.d_I = 200;
        Garage.e = 160;
        new TextBuffer((Garage.d_I - 24), v0); /* constructor */
        Garage.a_n.a(new TextBuffer((Garage.d_I - 24), v0));
        Garage.a_n.a_(false);
        Garage.e_F = 0.30000001192092896f;
        if (fcmpg(Garage.f, 0.30000001192092896f) != 0) goto L146;
        Garage.f = 0.699999988079071f;
        goto L160;
        L146:
        if (fcmpg(Garage.f, 0.699999988079071f) != 0) goto L160;
        Garage.f = 0.30000001192092896f;
        L160:
        Garage.h = 0;
        Garage.f_I = (Garage.f_I + 1);
        Garage.c_Z = true;
        L176:
        Garage.h = 1;
        Garage.h_Z = true;
        Garage.i = true;
        Garage.a_F = 1000.0f;
        return;
    }
    // bytecode 9 bytes, max_stack 1, max_locals 1
    public static void b(int v0) {
        Garage.c(v0);
        Garage.h = 2;
        return;
    }
    // bytecode 167 bytes, max_stack 6, max_locals 2
    public static void c(int v0) {
        if (Garage.a_Z != 0) goto L9;
        Garage.d();
        L9:
        Garage.h_Z = false;
        Garage.i = false;
        Garage.a_am = null;
        Garage.a_cq = null;
        Garage.a_Transf = null;
        Garage.h = 0;
        int v1 = 1;
        Garage.e_Z = true;
        if (Garage.f_I != Garage.b_arrI.length) goto L50;
        return;
        L50:
        Garage.b_arrI[((Garage.g + Garage.f_I) % Garage.b_arrI.length)] = v0;
        if (Garage.f_I != 0) goto L154;
        Garage.d_I = 200;
        Garage.e = 160;
        new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]); /* constructor */
        Garage.a_n.a(new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]));
        Garage.a_n.a_(false);
        Garage.e_F = 0.30000001192092896f;
        if (fcmpg(Garage.f, 0.30000001192092896f) != 0) goto L140;
        Garage.f = 0.699999988079071f;
        goto L154;
        L140:
        if (fcmpg(Garage.f, 0.699999988079071f) != 0) goto L154;
        Garage.f = 0.30000001192092896f;
        L154:
        Garage.f_I = (Garage.f_I + 1);
        Garage.c_Z = true;
        return;
    }
    // bytecode 29 bytes, max_stack 2, max_locals 0
    public static void e() {
        if (Garage.f_I != 0) goto L7;
        return;
        L7:
        Garage.g = ((Garage.g + 1) % Garage.b_arrI.length);
        Garage.f_I = (Garage.f_I - 1);
        return;
    }
    // bytecode 57 bytes, max_stack 6, max_locals 0
    public static void c() {
        Garage.g = (((Garage.g - 1) + Garage.b_arrI.length) % Garage.b_arrI.length);
        Garage.f_I = (Garage.f_I + 1);
        new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]); /* constructor */
        Garage.a_n.a(new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]));
        Garage.c_Z = true;
        return;
    }
    // bytecode 16 bytes, max_stack 1, max_locals 0
    public static boolean c() {
        if (Garage.c_Z != 0) goto L12;
        if (Garage.f_Z == 0) goto L14;
        L12:
        return 1;
        L14:
        return 0;
    }
    // bytecode 8 bytes, max_stack 1, max_locals 1
    public static void c(boolean v0) {
        Garage.e();
        Garage.c_Z = false;
        return;
    }
    // bytecode 218 bytes, max_stack 6, max_locals 1
    public static void d(int v0) {
        if (Garage.c() == 0) goto L14;
        if (fcmpl(Garage.e_F, 1.0f) >= 0) goto L15;
        L14:
        return;
        L15:
        if (Garage.a_n.a(v0) != 0) goto L217;
        Garage.e();
        if (Garage.h != 1) goto L48;
        if (Garage.b_arrI[Garage.g] == -1000) goto L63;
        L48:
        Garage.d_I = 200;
        Garage.e = 160;
        goto L75;
        L63:
        Garage.d_I = 200;
        Garage.e = 160;
        L75:
        if (Garage.f_I != 0) goto L94;
        Garage.c_Z = false;
        if (Garage.j == 0) goto L94;
        Garage.b();
        L94:
        if (Garage.d_Z != 0) goto L106;
        if (Garage.f_I == 0) goto L112;
        L106:
        if (Garage.f_I <= 0) goto L217;
        L112:
        if (Garage.b_arrI[Garage.g] != -1000) goto L150;
        new TextBuffer((Garage.d_I - 24), Garage.a_String); /* constructor */
        Garage.a_n.a(new TextBuffer((Garage.d_I - 24), Garage.a_String));
        goto L176;
        L150:
        new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]); /* constructor */
        Garage.a_n.a(new UiText((Garage.d_I - 24), Garage.b_arrI[Garage.g]));
        L176:
        Garage.a_n.a_(false);
        Garage.e_F = 0.30000001192092896f;
        if (fcmpg(Garage.f, 0.30000001192092896f) != 0) goto L203;
        Garage.f = 0.699999988079071f;
        return;
        L203:
        if (fcmpg(Garage.f, 0.699999988079071f) != 0) goto L217;
        Garage.f = 0.30000001192092896f;
        L217:
        return;
    }
    // bytecode 22 bytes, max_stack 2, max_locals 1
    public static void e(int v0) {
        if (Garage.c() != 0) goto L7;
        return;
        L7:
        if (Garage.a_n == null) goto L21;
        /* pop: Garage.a_n.a(v0); */
        L21:
        return;
    }
    // bytecode 100 bytes, max_stack 4, max_locals 4
    public static void a(int v0, int v1) {
        int v2 = ((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f));
        if (((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f)) >= -10) goto L29;
        v2 = -10;
        L29:
        int v3 = ((int) (((float) (SysUtil.e / 2)) - (((float) Garage.d_I) * Garage.f)));
        if (((int) (((float) (SysUtil.e / 2)) - (((float) Garage.d_I) * Garage.f))) >= 10) goto L55;
        v3 = 10;
        L55:
        if ((v3 + Garage.d_I) <= (SysUtil.e - 10)) goto L80;
        v3 = ((SysUtil.e - Garage.d_I) - 10);
        L80:
        if (Garage.a_n.b((v0 - v3), (v1 - v2)) == 0) goto L99;
        Garage.b = true;
        L99:
        return;
    }
    // bytecode 126 bytes, max_stack 4, max_locals 4
    public static void b(int v0, int v1) {
        Garage.a_n.a(v0, v1);
        if (Garage.b == 0) goto L19;
        Garage.b = false;
        return;
        L19:
        int v2 = ((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f));
        if (((int) ((Garage.d - (((float) (Garage.e + 20)) * Garage.e_F)) - 10.0f)) >= -10) goto L48;
        v2 = -10;
        L48:
        int v3 = ((int) (((float) (SysUtil.e / 2)) - (((float) Garage.d_I) * Garage.f)));
        if (((int) (((float) (SysUtil.e / 2)) - (((float) Garage.d_I) * Garage.f))) >= 10) goto L74;
        v3 = 10;
        L74:
        if ((v3 + Garage.d_I) <= (SysUtil.e - 10)) goto L99;
        v3 = ((SysUtil.e - Garage.d_I) - 10);
        L99:
        if (Garage.a_n.a((v0 - v3), (v1 - v2)) == 0) goto L115;
        return;
        L115:
        Garage.d(-201);
        Garage.e(0);
        return;
    }
}

