// Generated by tools/jdeob.py from x/r.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `r`.
// String constants: .car | /cars/ | /images/lo.png | /images/los.png | /images/w.png | /images/ws.png | /levels/ | /tex/md.jpg | /tex/md2.jpg | <clinit> | <init> | Code
// API references: java/io java/util javax/microedition
public class ObfR extends Screen {
    protected int a;
    protected int b;
    private Image c;
    protected String[] a_String;
    protected int[] a_arrI;
    protected String a_String;
    protected ObfBs a_bs;
    protected int c_I;
    protected ObfBt a_bt;
    public static byte a_B;
    protected static int d;
    protected int[] b_arrI;
    protected String[] b_String;
    private int s;
    public int e;
    protected TouchButtons a_e;
    private boolean f;
    public static int f_I;
    public static int g;
    public static int h;
    public static String b_String_2;
    public static int i;
    public static int j;
    public static int k;
    public static int l;
    public static int[] c_arrI;
    public static int m;
    public static int n;
    public static int o;
    public static boolean a_Z;
    public static String c_String;
    public static boolean b_Z;
    private Background a_Backgr;
    private float b_F;
    private Sprite[] a_arrLcq;
    private int t;
    private Transform a_Transf;
    private float c_F;
    protected Image a_Image;
    protected Image b_Image;
    protected float a_F;
    private int[] d_arrI;
    private int[] e_arrI;
    private float d_F;
    private int u;
    protected int p;
    private int v;
    protected boolean c_Z;
    protected boolean d_Z;
    private ObfCb a_cb;
    protected int q;
    public boolean e_Z;
    private static int w;
    private boolean g_Z;
    private Image d_Image;
    private Image e_Image;
    public static int r;
    static {
        ObfR.a_B = 21;
        ObfR.d = 0;
        ObfR.f_I = 0;
        ObfR.g = 0;
        ObfR.h = 0;
        ObfR.b_String_2 = null;
        ObfR.i = 0;
        ObfR.j = 0;
        ObfR.k = 0;
        ObfR.l = 0;
        ObfR.c_arrI = null;
        ObfR.m = 0;
        ObfR.n = 0;
        ObfR.o = 0;
        ObfR.a_Z = false;
        ObfR.c_String = "";
        ObfR.b_Z = false;
        ObfR.w = 0;
        ObfR.r = 0;
        return;
    }
    // bytecode 244 bytes, max_stack 5, max_locals 1
    public ObfR() {
        super();
        this.a = 0;
        this.b = 0;
        this.c = null;
        this.a_String = null;
        this.a_arrI = null;
        this.a_String = "";
        this.a_bs = null;
        this.c_I = 0;
        this.a_bt = null;
        this.b_arrI = null;
        new java.lang.String[6]#1[0] = "PLAYER";
        new java.lang.String[6]#1[1] = "JILL";
        new java.lang.String[6]#1[2] = "JOHN";
        new java.lang.String[6]#1[3] = "JIMM";
        new java.lang.String[6]#1[4] = "JAMES";
        new java.lang.String[6]#1[5] = "JUSTIN";
        this.b_String = new java.lang.String[6]#1;
        this.s = 0;
        this.e = 20;
        this.a_e = null;
        this.f = true;
        this.a_Backgr = null;
        this.b_F = 0.0f;
        this.a_arrLcq = null;
        this.t = 0;
        this.a_Transf = null;
        this.c_F = 7.0f;
        this.a_Image = null;
        this.b_Image = null;
        this.a_F = 0.0f;
        this.d_arrI = null;
        this.e_arrI = null;
        this.d_F = 0.0f;
        this.u = 64;
        this.p = 33;
        this.v = 0;
        this.c_Z = true;
        this.d_Z = false;
        this.a_cb = null;
        this.q = 92;
        this.e_Z = false;
        this.g_Z = false;
        this.d_Image = null;
        this.e_Image = null;
        ObfR.a_B = 21;
        ObfCl.f_Z = false;
        return;
    }
    // bytecode 257 bytes, max_stack 5, max_locals 2
    public ObfR(MainCanvas v1) {
        this();
        this.a = 0;
        this.b = 0;
        this.c = null;
        this.a_String = null;
        this.a_arrI = null;
        this.a_String = "";
        this.a_bs = null;
        this.c_I = 0;
        this.a_bt = null;
        this.b_arrI = null;
        new java.lang.String[6]#1[0] = "PLAYER";
        new java.lang.String[6]#1[1] = "JILL";
        new java.lang.String[6]#1[2] = "JOHN";
        new java.lang.String[6]#1[3] = "JIMM";
        new java.lang.String[6]#1[4] = "JAMES";
        new java.lang.String[6]#1[5] = "JUSTIN";
        this.b_String = new java.lang.String[6]#1;
        this.s = 0;
        this.e = 20;
        this.a_e = null;
        this.f = true;
        this.a_Backgr = null;
        this.b_F = 0.0f;
        this.a_arrLcq = null;
        this.t = 0;
        this.a_Transf = null;
        this.c_F = 7.0f;
        this.a_Image = null;
        this.b_Image = null;
        this.a_F = 0.0f;
        this.d_arrI = null;
        this.e_arrI = null;
        this.d_F = 0.0f;
        this.u = 64;
        this.p = 33;
        this.v = 0;
        this.c_Z = true;
        this.d_Z = false;
        this.a_cb = null;
        this.q = 92;
        this.e_Z = false;
        this.g_Z = false;
        this.d_Image = null;
        this.e_Image = null;
        ObfR.a_B = 21;
        ObfR.b_Z = false;
        this.a = v1;
        this.i__void();
        ObfCl.f_Z = false;
        return;
    }
    // bytecode 332 bytes, max_stack 4, max_locals 5
    public void b__void() {
        InputStream v1 = Resources.a(ObfR.c_String);
        /* pop: Resources.a(ObfR.c_String).skip(((long) ObfR.g)); */
        ObfR.k = 1;
        ObfR.j = StreamReader.a(v1);
        if (StreamReader.a(v1) <= 0) goto L38;
        jt1 = 1; /* join L39 from L34 */
        goto L39;
        L38:
        jt1 = 0; /* join L39 from L38 */
        L39:
        ObfR.a_Z = jt1;
        if (ObfR.h != -10) goto L60;
        ObfR.h = StreamReader.a(v1);
        goto L65;
        L60:
        /* pop: StreamReader.a(v1); */
        L65:
        ObfR.m = StreamReader.a(v1);
        ObfR.l = StreamReader.a(v1);
        ObfR.c_arrI = new int[StreamReader.a(v1)]#1;
        if (ObfR.l <= 3) goto L181;
        int v3 = 0;
        L94:
        if (v3 >= 4) goto L170;
        L99:
        int v2 = 1;
        ObfR.c_arrI[v3] = KORa.rand.nextInt(5);
        if (ObfR.c_arrI[v3] != ObfR.h) goto L129;
        v2 = 0;
        goto L160;
        L129:
        int v4 = 0;
        L132:
        if (v4 >= v3) goto L160;
        if (ObfR.c_arrI[v3] != ObfR.c_arrI[v4]) goto L154;
        v2 = 0;
        L154:
        v4 += 1;
        goto L132;
        L160:
        if (v2 == 0) goto L99;
        v3 += 1;
        goto L94;
        L170:
        ObfR.c_arrI[4] = ObfR.h;
        goto L327;
        L181:
        v3 = 0;
        L183:
        if (v3 >= ObfR.l) goto L327;
        L190:
        v2 = 1;
        v4 = ObfR.m;
        if (ObfR.m != 3) goto L205;
        v4 = 4;
        L205:
        v4 = ((KORa.rand.nextInt(4) + v4) - 1);
        if (((KORa.rand.nextInt(4) + v4) - 1) != 3) goto L230;
        v4 = 2;
        goto L263;
        L230:
        if (v4 != 4) goto L242;
        v4 = 3;
        goto L263;
        L242:
        if (v4 != 5) goto L254;
        v4 = 4;
        goto L263;
        L254:
        if (v4 != 2) goto L263;
        v4 = 5;
        L263:
        ObfR.c_arrI[v3] = v4;
        if (ObfR.c_arrI[v3] != ObfR.h) goto L286;
        v2 = 0;
        goto L317;
        L286:
        v4 = 0;
        L289:
        if (v4 >= v3) goto L317;
        if (ObfR.c_arrI[v3] != ObfR.c_arrI[v4]) goto L311;
        v2 = 0;
        L311:
        v4 += 1;
        goto L289;
        L317:
        if (v2 == 0) goto L190;
        v3 += 1;
        goto L183;
        L327:
        v1.close();
        return;
    }
    // bytecode 91 bytes, max_stack 5, max_locals 3
    public void c__void() {
        new ObfK(this.a.getWidth(), this.a.getHeight()); /* constructor */
        this.a_e = new ObfK(this.a.getWidth(), this.a.getHeight());
        this.a_e.a(this.a_bs.a());
        int v1 = 0;
        L41:
        ObfR v2 = this;
        if (v1 >= this.b) goto L72;
        this.a_e.a(this.a_bt.a(v1));
        v1 += 1;
        goto L41;
        L72:
        this.a_e.a(0);
        this.a_e.e(ObfR.n);
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int c__int() {
        return this.a;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int d__int() {
        return this.b;
    }
    // bytecode 18 bytes, max_stack 2, max_locals 2
    public String a__String(int v1) {
        if (v1 < this.b) goto L11;
        return "";
        L11:
        return this.a_String[v1];
    }
    // bytecode 17 bytes, max_stack 2, max_locals 2
    public int a__int(int v1) {
        if (v1 < this.b) goto L10;
        return m1;
        L10:
        return this.a_arrI[v1];
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfBs a__ObfBs() {
        return this.a_bs;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int e__int() {
        return 0;
    }
    // bytecode 29 bytes, max_stack 2, max_locals 2
    public void d__void() {
        this.g_Z = false;
        if (this.d_Z != 0) goto L16;
        this.e__void();
        L16:
        ObfR v1 = this;
        ObfR.a_B = 20;
        v1.d_F = 0.0f;
        return;
    }
    // bytecode 189 bytes, max_stack 5, max_locals 2
    public void e__void() {
        /* try L6-L10 catch java.io.IOException -> L13 */
        /* try L0-L182 catch java.lang.Exception -> L183 */
        if (ObfR.b_Z != 0) goto L18;
        this.b__void();
        goto L14;
        /* pop: ex_13; */
        L14:
        ObfR.b_Z = true;
        L18:
        this.a_String = ObfR.b_String_2;
        this.a = ObfR.k;
        this.b = (ObfR.l + 1);
        this.a_String = new java.lang.String[this.b]#1;
        if (ObfR.h >= 50) goto L73;
        this.a_String[0] = CarSpec.a[ObfR.h];
        L73:
        int v1 = 0;
        L75:
        if (v1 >= ObfR.l) goto L105;
        this.a_String[(v1 + 1)] = CarSpec.a[ObfR.c_arrI[v1]];
        v1 += 1;
        goto L75;
        L105:
        this.a_arrI = new int[this.b]#2;
        this.b_arrI = new int[this.b]#3;
        v1 = 0;
        L127:
        if (v1 >= this.b) goto L155;
        this.a_arrI[v1] = v1;
        this.b_arrI[v1] = v1;
        v1 += 1;
        goto L127;
        L155:
        this.a_arrI[0] = ObfR.w;
        this.a_arrI[ObfR.w] = 0;
        ObfR.w = 0;
        this.d_Z = true;
        return;
        v1 = ((int) ex_183);
        ex_183.printStackTrace();
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int f__int() {
        return m1;
    }
    // bytecode 36 bytes, max_stack 2, max_locals 1
    public void f__void() {
        if (this.a_bt == null) goto L14;
        this.a_bt.s();
        L14:
        this.a_bt = null;
        this.a_e = null;
        AssetManager.b__void();
        this.d_Z = false;
        java.lang.System.gc();
        return;
    }
    // bytecode 24 bytes, max_stack 2, max_locals 1
    public void g__void() {
        if (ObfR.a_B == 24) goto L16;
        if (ObfR.a_B != 25) goto L23;
        L16:
        this.a_bt.g__void();
        L23:
        return;
    }
    // bytecode 21 bytes, max_stack 2, max_locals 1
    public void h__void() {
        if (ObfR.a_B != 25) goto L20;
        ObfR.a_B = 24;
        this.a_bt.h__void();
        L20:
        return;
    }
    // bytecode 4 bytes, max_stack 1, max_locals 0
    public static int g__int() {
        return ObfR.a_B;
    }
    // bytecode 215 bytes, max_stack 4, max_locals 3
    public void a(float v1) {
        /* try L0-L212 catch java.lang.Exception -> L213 */
        this.a_e.a(v1);
        v1 = ((float) 1);
        L10:
        if (v1 >= this.b) goto L118;
        if (this.a_bt.a(v1).c() == 0) goto L112;
        int v2 = this.a_bt.a(v1).a__int();
        if (this.a_bt.a(v1).a__int() >= this.d_arrI.length) goto L112;
        if (v2 < 0) goto L112;
        if (this.d_arrI[v2] >= 0) goto L112;
        this.d_arrI[v2] = this.a_bt.a(v1).b__int();
        if (this.e_arrI[v2] < 0) goto L112;
        this.a_e.a__void((this.e_arrI[v2] - this.d_arrI[v2]));
        L112:
        v1 += 1;
        goto L10;
        L118:
        if (this.a_bt.a(0).c() == 0) goto L212;
        v1 = ((float) this.a_bt.a(0).a__int());
        if (this.a_bt.a(0).a__int() >= this.e_arrI.length) goto L212;
        if (v1 < 0) goto L212;
        if (this.e_arrI[v1] >= 0) goto L212;
        this.e_arrI[v1] = this.a_bt.a(0).b__int();
        if (this.d_arrI[v1] < 0) goto L212;
        this.a_e.a__void((this.e_arrI[v1] - this.d_arrI[v1]));
        L212:
        return;
        /* pop: ex_213; */
        return;
    }
    // bytecode 19 bytes, max_stack 3, max_locals 1
    public void i__void() {
        if (Settings.d_String.length() <= 0) goto L18;
        this.b_String[0] = Settings.d_String;
        L18:
        return;
    }
    // bytecode 405 bytes, max_stack 5, max_locals 3
    public void b(float v1) {
        /* try L205-L398 catch java.lang.Exception -> L399 */
        this.i__void();
        if (ObfR.a_B < 24) goto L78;
        if (ObfR.a_B >= 200) goto L78;
        this.a_bt.b(v1);
        this.a(v1);
        if (ObfR.a_B != 27) goto L404;
        this.a_F = (this.a_F - ((v1 * (this.a_F + 3.0f)) * 7.0f));
        if (fcmpl(this.a_F, 0.0f) >= 0) goto L404;
        this.a_F = 0.0f;
        return;
        L78:
        if (ObfR.a_B != 23) goto L141;
        float v2 = v1;
        v1 = ((float) this);
        v2 = (v2 * 3.0f);
        v1.b_F = (v1.b_F + (((v1.b_F * v2) * (v1.b_F + 0.30000001192092896f)) / 3.5f));
        if (fcmpg(v1.b_F, (v1.c_F * 2.0f)) <= 0) goto L140;
        ObfR.a_B = 24;
        L140:
        return;
        L141:
        if (ObfR.a_B != 20) goto L404;
        if (fcmpl(this.d_F, ((float) this.p)) >= 0) goto L404;
        this.d_F = (this.d_F + ((((float) this.p) * v1) * 10.0f));
        if (fcmpg(this.d_F, ((float) this.p)) < 0) goto L404;
        this.d_F = ((float) this.p);
        v1 = ((float) this);
        ObfR.a_B = 21;
        v1.o();
        if (v1.c_Z == 0) goto L234;
        v1.v = (v1.v + 1);
        MainCanvas.a();
        L234:
        v2 = v1;
        if (v1.f == 0) goto L257;
        if (Settings.e_Z != 0) goto L252;
        java.lang.System.gc();
        L252:
        v2.f = false;
        L257:
        v2 = v1;
        v1.a(v2.a.a());
        v2.a.flushGraphics();
        Settings.q(ObfR.j);
        AssetManager.a();
        v1.r();
        if (v1.c_Z == 0) goto L310;
        v1.v = (v1.v + 1);
        MainCanvas.a();
        L310:
        v1.p();
        if (v1.c_Z == 0) goto L334;
        v1.v = (v1.v + 1);
        MainCanvas.a();
        L334:
        v1.q();
        v1.c__void();
        v1.n();
        v1.a_bt.d__void();
        if (v1.c_Z == 0) goto L373;
        v1.v = (v1.v + 1);
        MainCanvas.a();
        L373:
        ObfR.a_B = 22;
        if (v1.c_Z == 0) goto L398;
        v1.v = (v1.v + 1);
        MainCanvas.a();
        L398:
        return;
        v2 = ((float) ex_399);
        ex_399.printStackTrace();
        L404:
        return;
    }
    // bytecode 331 bytes, max_stack 10, max_locals 2
    public void a_(Graphics v1) {
        /* try L14-L50 catch java.io.IOException -> L53 */
        /* try L176-L212 catch java.io.IOException -> L215 */
        if (this.a__boolean() == 0) goto L169;
        if (this.d_Image != null) goto L54;
        if (SysUtil.e_I <= 200) goto L38;
        this.d_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/w.png"));
        goto L54;
        L38:
        this.d_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/ws.png"));
        goto L54;
        /* pop: ex_53; */
        L54:
        if (Settings.m() != 0) goto L109;
        v1.drawRegion(this.d_Image, 0, 0, this.d_Image.getWidth(), this.d_Image.getHeight(), 0, ((v1.getClipWidth() - this.d_Image.getWidth()) / 2), (v1.getClipHeight() / 12), 20);
        return;
        L109:
        v1.drawRegion(this.d_Image, 0, 0, this.d_Image.getWidth(), this.d_Image.getHeight(), 5, (((11 * v1.getClipWidth()) / 12) - this.d_Image.getHeight()), ((v1.getClipHeight() - this.d_Image.getWidth()) / 2), 20);
        return;
        L169:
        if (this.e_Image != null) goto L216;
        if (SysUtil.e_I <= 200) goto L200;
        this.e_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/lo.png"));
        goto L216;
        L200:
        this.e_Image = javax.microedition.lcdui.Image.createImage(Resources.a("/images/los.png"));
        goto L216;
        /* pop: ex_215; */
        L216:
        if (Settings.m() != 0) goto L271;
        v1.drawRegion(this.e_Image, 0, 0, this.e_Image.getWidth(), this.e_Image.getHeight(), 0, ((v1.getClipWidth() - this.e_Image.getWidth()) / 2), (v1.getClipHeight() / 12), 20);
        return;
        L271:
        v1.drawRegion(this.e_Image, 0, 0, this.e_Image.getWidth(), this.e_Image.getHeight(), 5, (((11 * v1.getClipWidth()) / 12) - this.e_Image.getHeight()), ((v1.getClipHeight() - this.e_Image.getWidth()) / 2), 20);
        return;
    }
    // bytecode 127 bytes, max_stack 5, max_locals 2
    public void j() {
        if (ObfR.a_B < 24) goto L23;
        if (this.a_bt == null) goto L23;
        this.a_bt.j();
        return;
        L23:
        if (ObfR.a_B != 23) goto L126;
        this.a.a().a(this.a_Backgr);
        ObfR v1 = this;
        this.a.a().a(v1.a_Backgr);
        v1.a_Transf.setIdentity();
        v1.a_Transf.postTranslate(0.0f, 0.0f, -3.0f);
        v1.a_Transf.postRotate(0.0f, 1.0f, 0.0f, 0.0f);
        v1.a_Transf.postScale(v1.b_F, v1.b_F, 0.0f);
        v1.a_arrLcq[0].a(v1.a.a(), v1.a_Transf);
        L126:
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 1
    public void k() {
        return;
    }
    // bytecode 178 bytes, max_stack 3, max_locals 6
    public void c(Graphics v1) {
        if (this.a_bt != null) goto L8;
        return;
        L8:
        ObfR v5 = this;
        ObfCl v2 = this.a_bt.a(0);
        int v3 = 0;
        int v4 = 1;
        L25:
        v5 = this;
        if (v4 >= this.b) goto L66;
        if (fcmpg(this.a_bt.a(v4).a(), v2.a()) <= 0) goto L60;
        v3 += 1;
        L60:
        v4 += 1;
        goto L25;
        L66:
        this.a_e.i(v3);
        this.a_e.j(v2.g__int());
        this.a_e.c__void(this.b__int());
        this.a_e.d(v2.d__int());
        this.k();
        this.a_e.a(this.a_bt.a__boolean());
        this.a_e.g(((int) (v2.a().j() * 100.0f)));
        this.a_e.h(((int) ((v2.a().j() / v2.a().k()) * 100.0f)));
        this.a_e.e(v1);
        return;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 2
    public int b__int() {
        ObfR v1 = this;
        v1 = ((ObfR) this.a_bt.a(0));
        return this.a_bt.a(0).d__int();
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public TouchButtons a__TouchButtons() {
        return this.a_e;
    }
    // bytecode 897 bytes, max_stack 11, max_locals 12
    public void d(Graphics v1) {
        int v2 = 0;
        L2:
        if (v2 >= this.b) goto L896;
        if (v2 >= 4) goto L896;
        int v5 = v2;
        Graphics v4 = v1;
        ObfR v3 = this;
        int v6 = 30;
        if (SysUtil.f_I > 240) goto L40;
        v6 = 22;
        L40:
        int v7 = v3.b;
        if (v3.b <= 3) goto L54;
        v7 = 3;
        L54:
        if (Settings.m() != 0) goto L81;
        jt1 = ((v4.getClipHeight() - ((v7 * v6) << 1)) - v3.e); /* join L99 from L60 */
        goto L99;
        L81:
        jt1 = ((v4.getClipWidth() - ((v7 * v6) << 1)) - v3.e); /* join L99 from L81 */
        L99:
        v7 = (jt1 / 7);
        if ((jt1 / 7) <= 16) goto L114;
        v7 = 16;
        L114:
        if (SysUtil.f_I > 240) goto L126;
        v7 = 5;
        L126:
        int v8 = ((v6 * 2) + v7);
        if ((Settings.m() % 2) != 1) goto L186;
        if (v3.b_Image == null) goto L167;
        if (v3.b_Image.getWidth() >= (SysUtil.e_I - 20)) goto L186;
        L167:
        v3.b_Image = javax.microedition.lcdui.Image.createImage((v4.getClipWidth() - 20), (v6 * 2));
        L186:
        if (v3.a_Image == null) goto L211;
        if (v3.a_Image.getWidth() == (v4.getClipWidth() - 20)) goto L327;
        L211:
        v3.a_Image = javax.microedition.lcdui.Image.createImage((v4.getClipWidth() - 20), (v6 * 2));
        Graphics v9 = v3.a_Image.getGraphics();
        SysUtil.a(v3.a_Image.getGraphics(), 0, 0, (v4.getClipWidth() - 20), (v6 << 1), 5592405, 10066329, true);
        v9.setColor(10066329);
        v9.fillRect(((v6 * 2) - 1), v6, ((v4.getClipWidth() - 20) - (v6 * 2)), v6);
        v9.setColor(7829367);
        v9.drawRect(0, 0, ((v4.getClipWidth() - 20) - 1), ((v6 << 1) - 1));
        L327:
        if ((v5 % 2) != 0) goto L342;
        jt2 = (-v3.a_F); /* join L346 from L334 */
        goto L346;
        L342:
        jt2 = v3.a_F; /* join L346 from L342 */
        L346:
        v9 = ((Graphics) ((int) jt2));
        if (Settings.m() != 0) goto L620;
        v4.drawImage(v3.a_Image, (v9 + 10), ((v5 * v8) + v7), 20);
        SysUtil.h.a(v4, (v5 + 1), (((v9 + 10) + v6) - 6), ((((v5 * v8) + v7) + (((v6 * 2) - SysUtil.h.a()) / 2)) + 1));
        SysUtil.b.a(v4, v3.b_String[v3.b_arrI[v5]], ((((v9 + v4.getClipWidth()) - 10) - ((v6 - 7) / 2)) - SysUtil.b.a(v3.b_String[v3.b_arrI[v5]])), (((((v5 * v8) + v7) + ((v6 - 7) / 2)) - 8) + 4));
        if (v5 != 0) goto L596;
        int v10 = v3.a_bt.a(v3.b_arrI[v5]).e__int();
        SysUtil.b.a(v4, ((long) v10), ((((v9 + v4.getClipWidth()) - 10) - ((v6 - 7) / 2)) - SysUtil.b.a(((long) v10))), ((((((v5 * v8) + v7) + v6) + ((v6 - 7) / 2)) - 8) + 4));
        goto L890;
        L596:
        v3.a(v4, v5, v9, 10, v6, v8, (v7 + 4), 0);
        goto L890;
        L620:
        v10 = ((int) v3.b_Image.getGraphics());
        v3.b_Image.getGraphics().drawImage(v3.a_Image, 0, 0, 20);
        SysUtil.h.a(v10, (v5 + 1), ((v9 + v6) - 6), ((((v6 * 2) - SysUtil.h.a()) / 2) + 1));
        SysUtil.b.a(v10, v3.b_String[v3.b_arrI[v5]], ((v10.getClipWidth() - ((v6 - 7) / 2)) - SysUtil.b.a(v3.b_String[v3.b_arrI[v5]])), ((v6 - 7) / 2));
        if (v5 != 0) goto L809;
        int v11 = v3.a_bt.a(v3.b_arrI[v5]).e__int();
        SysUtil.b.a(v10, ((long) v11), (((v9 + v10.getClipWidth()) - ((v6 - 7) / 2)) - SysUtil.b.a(((long) v11))), (v6 + ((v6 - 7) / 2)));
        goto L825;
        L809:
        v3.a(v10, 0, v9, 0, v6, v8, 0, 0);
        L825:
        v4.drawRegion(v3.b_Image, 0, 0, v3.b_Image.getWidth(), v3.b_Image.getHeight(), 5, ((v4.getClipWidth() - (v7 + (v8 * v5))) - v3.b_Image.getHeight()), ((v4.getClipHeight() - v3.b_Image.getWidth()) / 2), 20);
        L890:
        v2 += 1;
        goto L2;
        L896:
        return;
    }
    // bytecode 420 bytes, max_stack 6, max_locals 7
    public void a(Graphics v1, Image v2) {
        int v3 = ((14 + v2.getHeight()) + 5);
        if (((14 + v2.getHeight()) + 5) >= 120) goto L19;
        v3 = 120;
        L19:
        int v4 = ((v1.getClipWidth() - 228) / 2);
        int v5 = ((v1.getClipHeight() - v3) / 2);
        v1.setColor(0);
        v1.fillRect((v4 + 2), (v5 + 2), 228, v3);
        v1.setColor(14540253);
        v1.fillRect(v4, v5, 228, v3);
        v1.setColor(4473924);
        v1.fillRect(v4, v5, 228, 20);
        v5 += 3;
        v3 = ((int) SysUtil.a(this.q));
        SysUtil.q.a(v1, v3, (((v4 + 228) - SysUtil.p.a(v3)) - 5), (v5 - 1));
        v3 = (v5 + 25);
        v1.drawImage(v2, ((((v4 + 228) - v2.getWidth()) - 3) - 5), v3, 20);
        v5 += 21;
        v3 = ((int) SysUtil.a(91));
        v2 = ((Image) SysUtil.p.a(v3));
        int v6 = (SysUtil.p.a__int(ObfR.d) + 1);
        v4 = (v4 + 8);
        SysUtil.p.a(v1, v3, v4, v5);
        SysUtil.p.a(v1, ObfR.d, ((v4 + v2) + 5), v5);
        SysUtil.p.a(v1, SysUtil.a(59), (((v4 + v2) + v6) + 5), v5);
        v5 = (v5 + (SysUtil.p.a() + 5));
        v3 = ((int) SysUtil.a(60));
        SysUtil.p.a(v1, v3, v4, v5);
        SysUtil.p.a(v1, ObfR.l, ((v4 + v2) + 5), v5);
        v5 = (v5 + (SysUtil.p.a() + 5));
        v3 = ((int) SysUtil.a(165));
        SysUtil.p.a(v1, v3, v4, v5);
        SysUtil.p.a(v1, SysUtil.a((76 + ObfR.j)), ((v4 + v2) + 5), v5);
        v5 = (v5 + (SysUtil.p.a() + 5));
        v3 = ((int) SysUtil.a(138));
        SysUtil.p.a(v1, v3, v4, v5);
        SysUtil.p.a(v1, SysUtil.a((133 + ObfR.m)), ((v4 + v2) + 5), v5);
        return;
    }
    // bytecode 12 bytes, max_stack 1, max_locals 2
    public void e(Graphics v1) {
        if (Settings.l() != 0) goto L11;
        /* pop: v1.getClipHeight(); */
        L11:
        return;
    }
    // bytecode 25 bytes, max_stack 2, max_locals 1
    public int h__int() {
        if (ObfR.a_B > 21) goto L11;
        return 55;
        L11:
        if (ObfR.a_B <= 24) goto L22;
        return 63;
        L22:
        return 62;
    }
    // bytecode 692 bytes, max_stack 10, max_locals 4
    public void a(Graphics v1) {
        if (ObfR.a_B < 24) goto L16;
        this.a_bt.a(v1);
        L16:
        if (ObfR.a_B != 25) goto L25;
        return;
        L25:
        if (ObfR.a_B != 24) goto L39;
        this.c(v1);
        return;
        L39:
        if (ObfR.a_B == 21) goto L55;
        if (ObfR.a_B != 22) goto L63;
        L55:
        this.e(v1);
        goto L76;
        L63:
        if (ObfR.a_B != 27) goto L76;
        this.d(v1);
        L76:
        byte[] v2 = SysUtil.a(this.h__int());
        if (Settings.m() != 0) goto L435;
        SysUtil.a(v1, 0, ((v1.getClipHeight() - SysUtil.b.a()) - this.e), v1.getClipWidth(), (SysUtil.b.a() + this.e), 5592405, 10066329, true);
        v1.setColor(10066329);
        v1.drawLine(0, ((v1.getClipHeight() - SysUtil.b.a()) - this.e), v1.getClipWidth(), ((v1.getClipHeight() - SysUtil.b.a()) - this.e));
        if (this.c_Z == 0) goto L265;
        if (ObfR.a_B == 21) goto L209;
        if (ObfR.a_B == 22) goto L209;
        if (ObfR.a_B != 23) goto L265;
        L209:
        if (this.a_cb != null) goto L229;
        new ProgressBar(null, m1); /* constructor */
        this.a_cb = new ProgressBar(null, m1);
        L229:
        this.a_cb.b__void(this.v);
        this.a_cb.a(v1, 0, ((v1.getClipHeight() - SysUtil.b.a()) - this.e));
        L265:
        if (Settings.a__boolean() == 0) goto L302;
        SysUtil.b.a(v1, v2, ((v1.getClipWidth() - SysUtil.b.a(v2)) - 5), (this.e / 2));
        goto L342;
        L302:
        SysUtil.b.a(v1, v2, ((v1.getClipWidth() - SysUtil.b.a(v2)) - 5), ((v1.getClipHeight() - SysUtil.b.a()) - (this.e / 2)));
        L342:
        if (ObfR.a_B < 26) goto L691;
        if (Settings.a__boolean() == 0) goto L403;
        v2 = SysUtil.a(48);
        SysUtil.b.a(v1, v2, ((v1.getClipWidth() - SysUtil.b.a(v2)) - 5), ((v1.getClipHeight() - SysUtil.b.a()) - (this.e / 2)));
        return;
        L403:
        SysUtil.b.a(v1, SysUtil.a(48), 5, ((v1.getClipHeight() - SysUtil.b.a()) - (this.e / 2)));
        return;
        L435:
        if (this.c != null) goto L464;
        this.c = javax.microedition.lcdui.Image.createImage(v1.getClipHeight(), (this.e + SysUtil.b.a()));
        L464:
        Graphics v3 = this.c.getGraphics();
        SysUtil.a(this.c.getGraphics(), 0, 0, v3.getClipWidth(), (SysUtil.b.a() + this.e), 5592405, 10066329, true);
        v3.setColor(10066329);
        v3.drawLine(0, (this.e + SysUtil.b.a()), v3.getClipWidth(), (this.e + SysUtil.b.a()));
        if (this.c_Z == 0) goto L607;
        if (ObfR.a_B == 21) goto L566;
        if (ObfR.a_B == 22) goto L566;
        if (ObfR.a_B != 23) goto L607;
        L566:
        if (this.a_cb != null) goto L586;
        new ProgressBar(null, m1); /* constructor */
        this.a_cb = new ProgressBar(null, m1);
        L586:
        this.a_cb.b__void(this.v);
        this.a_cb.a(v3, 0, 1);
        L607:
        SysUtil.b.a(v3, v2, ((v3.getClipWidth() - SysUtil.b.a(v2)) - 5), (this.e / 2));
        if (ObfR.a_B < 26) goto L662;
        SysUtil.b.a(v3, SysUtil.a(48), 5, (this.e / 2));
        L662:
        v1.drawRegion(this.c, 0, 0, this.c.getWidth(), this.c.getHeight(), 5, 0, 0, 20);
        L691:
        return;
    }
    // bytecode 96 bytes, max_stack 8, max_locals 9
    public void a(Graphics v1, int v2, int v3, int v4, int v5, int v6, int v7, int v8) {
        v8 = (this.a_bt.a(this.b_arrI[v2]).e__int() - this.a_bt.a(this.b_arrI[0]).e__int());
        v3 = ((((v3 + v1.getClipWidth()) - v4) - ((v5 - 7) / 2)) - SysUtil.b.b(((long) v8)));
        SysUtil.b.b(v1, ((long) v8), v3, (((((v2 * v6) + v7) + v5) + ((v5 - 7) / 2)) - 8));
        return;
    }
    // bytecode 6 bytes, max_stack 1, max_locals 0
    public static void a_() {
        ObfR.a_B = 27;
        return;
    }
    // bytecode 14 bytes, max_stack 2, max_locals 1
    public void m() {
        ObfR.a_B = 27;
        this.a_F = ((float) SysUtil.e_I);
        return;
    }
    // bytecode 67 bytes, max_stack 4, max_locals 3
    public void b__void(int v1) {
        int v2 = (this.s + 1);
        L7:
        if (v2 >= this.b) goto L46;
        if (this.b_arrI[v2] != v1) goto L40;
        this.b_arrI[v2] = this.b_arrI[this.s];
        L40:
        v2 += 1;
        goto L7;
        L46:
        this.b_arrI[this.s] = v1;
        this.s = (this.s + 1);
        return;
    }
    // bytecode 186 bytes, max_stack 2, max_locals 3
    public void a__void(int v1) {
        if (ObfR.a_B != 24) goto L48;
        if (SysUtil.a__int(v1) == -6) goto L26;
        if (SysUtil.a__int(v1) != -7) goto L39;
        L26:
        ObfR.a_B = 25;
        this.a.z();
        return;
        L39:
        this.a_bt.a__void(v1);
        return;
        L48:
        if (ObfR.a_B != 22) goto L62;
        ObfR.a_B = 24;
        return;
        L62:
        if (ObfR.a_B == 26) goto L78;
        if (ObfR.a_B != 27) goto L185;
        L78:
        if (SysUtil.a__int(v1) != -6) goto L138;
        v1 = 0;
        int v2 = 0;
        L91:
        if (v2 >= this.b) goto L119;
        if (this.b_arrI[v2] != 0) goto L113;
        v1 = v2;
        goto L119;
        L113:
        v2 += 1;
        goto L91;
        L119:
        ObfR.w = ((this.b - v1) - 1);
        this.a.t();
        return;
        L138:
        if (SysUtil.a__int(v1) == -7) goto L156;
        if (SysUtil.a__int(v1) != -5) goto L185;
        L156:
        if (ObfR.a_B != 26) goto L170;
        ObfR.a_B = 27;
        return;
        L170:
        if (ObfR.a_B != 27) goto L185;
        this.a.w();
        L185:
        return;
    }
    // bytecode 17 bytes, max_stack 2, max_locals 2
    public void c__void(int v1) {
        if (ObfR.a_B != 24) goto L16;
        this.a_bt.c__void(v1);
        L16:
        return;
    }
    // bytecode 75 bytes, max_stack 3, max_locals 2
    public void n() {
        this.d_arrI = new int[(this.a_bs.a__int() * this.a)]#1;
        this.e_arrI = new int[(this.a_bs.a__int() * this.a)]#2;
        int v1 = 0;
        L38:
        if (v1 >= (this.a_bs.a__int() * this.a)) goto L74;
        this.d_arrI[v1] = m1;
        this.e_arrI[v1] = m1;
        v1 += 1;
        goto L38;
        L74:
        return;
    }
    // bytecode 29 bytes, max_stack 2, max_locals 1
    public void o() {
        new java.lang.StringBuffer(); /* constructor */
        ObfR.a(Resources.a(new java.lang.StringBuffer().append("/levels/").append(this.a_String).toString()));
        return;
    }
    // bytecode 43 bytes, max_stack 6, max_locals 1
    public void p() {
        new java.lang.StringBuffer(); /* constructor */
        new ObfBs(AssetManager.a_cf, Resources.a(new java.lang.StringBuffer().append("/levels/").append(this.a_String).toString()), ObfR.a_Z); /* constructor */
        this.a_bs = new ObfBs(AssetManager.a_cf, Resources.a(new java.lang.StringBuffer().append("/levels/").append(this.a_String).toString()), ObfR.a_Z);
        return;
    }
    // bytecode 76 bytes, max_stack 7, max_locals 2
    public void q() {
        if (ObfR.h < 50) goto L59;
        int v1 = (ObfR.h - 49);
        new java.lang.StringBuffer(); /* constructor */
        new ObfBt(this.a, this, Resources.a(new java.lang.StringBuffer().append("/cars/").append(v1).append(".car").toString())); /* constructor */
        this.a_bt = new ObfBt(this.a, this, Resources.a(new java.lang.StringBuffer().append("/cars/").append(v1).append(".car").toString()));
        return;
        L59:
        new ObfBt(this.a, this); /* constructor */
        this.a_bt = new ObfBt(this.a, this);
        return;
    }
    // bytecode 138 bytes, max_stack 3, max_locals 7
    public static void a(InputStream v0) {
        /* try L0-L135 catch java.io.IOException -> L136 */
        int v1 = StreamReader.a(v0);
        int v2 = StreamReader.a(v0);
        ObfR.d = 0;
        int v4 = 1;
        L17:
        if (v4 >= (v2 + 1)) goto L131;
        int v5 = 1;
        L28:
        if (v5 >= (v1 + 1)) goto L125;
        int v6 = ((byte) StreamReader.a(v0));
        if ((((byte) StreamReader.a(v0)) & ObfR.b__int(0)) == 0) goto L85;
        int v3 = StreamReader.a(v0);
        if (StreamReader.a(v0) <= 0) goto L85;
        ObfR.d = (ObfR.d + 10);
        if (v3 != 15) goto L85;
        ObfR.d = (ObfR.d + 10);
        L85:
        v3 = 1;
        L87:
        if (v3 > 6) goto L119;
        if ((v6 & ObfR.b__int(v3)) == 0) goto L113;
        /* pop: StreamReader.a(v0); */
        /* pop: StreamReader.a(v0); */
        L113:
        v3 += 1;
        goto L87;
        L119:
        v5 += 1;
        goto L28;
        L125:
        v4 += 1;
        goto L17;
        L131:
        v0.close();
        return;
        /* pop: ex_136; */
        return;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 2
    public static int e(int v0) {
        int v1 = 1;
        L2:
        if (v1 >= v0) goto L14;
        v1 = (v1 << 1);
        goto L2;
        L14:
        return v1;
    }
    // bytecode 21 bytes, max_stack 2, max_locals 3
    public static int b__int(int v0) {
        int v1 = 1;
        int v2 = 0;
        L4:
        if (v2 >= v0) goto L19;
        v1 = (v1 << 1);
        v2 += 1;
        goto L4;
        L19:
        return v1;
    }
    // bytecode 12 bytes, max_stack 3, max_locals 3
    public static Image a(String v0, String v1, boolean v2) {
        v0 = ((String) Resources.a(v0));
        return ObfR.a(Resources.a(v0), v1, v2);
    }
    // bytecode 507 bytes, max_stack 9, max_locals 13
    public static Image a(InputStream v0, String v1, boolean v2) {
        /* try L0-L499 catch java.io.IOException -> L500 */
        int v3 = StreamReader.a(v0);
        int v4 = StreamReader.a(v0);
        v1 = ((String) javax.microedition.lcdui.Image.createImage(Resources.a(v1)));
        new javax.microedition.lcdui.Image[4]#1[0] = v1;
        new javax.microedition.lcdui.Image[4]#1[1] = SysUtil.a(v1, 90);
        new javax.microedition.lcdui.Image[4]#1[2] = SysUtil.a(v1, 180);
        new javax.microedition.lcdui.Image[4]#1[3] = SysUtil.a(v1, 270);
        v1 = ((String) new javax.microedition.lcdui.Image[4]#1);
        int v5 = (new javax.microedition.lcdui.Image[4]#1[0].getWidth() / 8);
        if (v2 == 0) goto L84;
        jt1 = ObfR.e(((v3 + 2) * v5)); /* join L90 from L72 */
        goto L90;
        L84:
        jt1 = ((v3 + 2) * v5); /* join L90 from L84 */
        L90:
        int v6 = jt1;
        if (v2 == 0) goto L109;
        jt2 = ObfR.e(((v4 + 2) * v5)); /* join L116 from L96 */
        goto L116;
        L109:
        jt2 = ((v4 + 2) * v5); /* join L116 from L109 */
        L116:
        int v7 = jt2;
        if (v6 <= 128) goto L131;
        v6 = 128;
        L131:
        if (v7 <= 128) goto L144;
        v7 = 128;
        L144:
        Image v8 = javax.microedition.lcdui.Image.createImage(v6, v7);
        Graphics v9 = javax.microedition.lcdui.Image.createImage(v6, v7).getGraphics();
        new java.util.Random(); /* constructor */
        java.util.Random v10 = new java.util.Random();
        if (v2 != 0) goto L239;
        v9.setColor(15395562);
        v9.drawRect(0, 0, (v6 - 1), (v7 - 1));
        v9.setColor(8947848);
        v9.drawRect(1, 1, (v6 - 2), (v7 - 2));
        SysUtil.a(v9, 1, 1, (v6 - 3), (v7 - 2), 13421772, 10066329, true);
        goto L298;
        L239:
        int v11 = 0;
        L242:
        if ((v11 * v5) >= v7) goto L298;
        int v12 = 0;
        L255:
        if ((v12 * v5) >= v6) goto L292;
        ObfR.a(v1, v9, v12, v11, 0, v10.nextInt(4), v5, 0, 0);
        v12 += 1;
        goto L255;
        L292:
        v11 += 1;
        goto L242;
        L298:
        v11 = ((v6 - ((v3 + 2) * v5)) / 2);
        v12 = ((v7 - ((v4 + 2) * v5)) / 2);
        ObfR.d = 0;
        v6 = 1;
        L332:
        if (v6 >= (v4 + 1)) goto L468;
        v7 = 1;
        L344:
        if (v7 >= (v3 + 1)) goto L462;
        v10 = ((java.util.Random) ((byte) StreamReader.a(v0)));
        if ((((byte) StreamReader.a(v0)) & ObfR.b__int(0)) == 0) goto L422;
        v2 = ((boolean) StreamReader.a(v0));
        ObfR.a(v1, v9, v7, v6, v2, StreamReader.a(v0), v5, v11, v12);
        if (v2 <= 0) goto L422;
        ObfR.d = (ObfR.d + 10);
        if (v2 != 15) goto L422;
        ObfR.d = (ObfR.d + 10);
        L422:
        v2 = ((boolean) 1);
        L424:
        if (v2 > 6) goto L456;
        if ((v10 & ObfR.b__int(v2)) == 0) goto L450;
        /* pop: StreamReader.a(v0); */
        /* pop: StreamReader.a(v0); */
        L450:
        v2 += 1;
        goto L424;
        L456:
        v7 += 1;
        goto L344;
        L462:
        v6 += 1;
        goto L332;
        L468:
        v0.close();
        v1[0] = null;
        v1[1] = null;
        v1[2] = null;
        v1[3] = null;
        if (Settings.e_Z != 0) goto L497;
        java.lang.System.gc();
        L497:
        return v8;
        v3 = ((int) ex_500);
        ex_500.printStackTrace();
        return null;
    }
    // bytecode 316 bytes, max_stack 8, max_locals 12
    public static void a(Image[] v0, Graphics v1, int v2, int v3, int v4, int v5, int v6, int v7, int v8) {
        int v9 = v1.getClipWidth();
        int v10 = v1.getClipHeight();
        v5 = ((v5 + Settings.l()) % 4);
        if (Settings.l() != 1) goto L48;
        int v11 = v3;
        v3 = v2;
        v2 = (((v9 / v6) - v11) - 1);
        goto L71;
        L48:
        if (Settings.l() != 3) goto L71;
        v11 = v3;
        v3 = (((v10 / v6) - v2) - 1);
        v2 = v11;
        L71:
        v1.setClip((v7 + (v2 * v6)), (v8 + (v3 * v6)), v6, v6);
        if (v5 != 0) goto L143;
        v1.drawImage(v0[v5], ((v7 + (v2 * v6)) - (v6 * (v4 % 8))), ((v8 + (v3 * v6)) - (v6 * (v4 / 8))), 20);
        goto L305;
        L143:
        if (v5 != 1) goto L197;
        v1.drawImage(v0[v5], ((v7 + (v2 * v6)) - (v6 * (7 - (v4 / 8)))), ((v8 + (v3 * v6)) - (v6 * (v4 % 8))), 20);
        goto L305;
        L197:
        if (v5 != 2) goto L254;
        v1.drawImage(v0[v5], ((v7 + (v2 * v6)) - (v6 * (7 - (v4 % 8)))), ((v8 + (v3 * v6)) - (v6 * (7 - (v4 / 8)))), 20);
        goto L305;
        L254:
        if (v5 != 3) goto L305;
        v1.drawImage(v0[v5], ((v7 + (v2 * v6)) - (v6 * (v4 / 8))), ((v8 + (v3 * v6)) - (v6 * (7 - (v4 % 8)))), 20);
        L305:
        v1.setClip(0, 0, v9, v10);
        return;
    }
    // bytecode 13 bytes, max_stack 2, max_locals 1
    public boolean a__boolean() {
        if (this.b_arrI[0] != 0) goto L11;
        return 1;
        L11:
        return 0;
    }
    // bytecode 97 bytes, max_stack 5, max_locals 1
    public void r() {
        /* try L0-L94 catch java.io.IOException -> L95 */
        this.a_arrLcq = new Sprite[2]#1;
        if (MainCanvas.a_Z == 0) goto L32;
        new Sprite("/tex/md2.jpg"); /* constructor */
        this.a_arrLcq[0] = new Sprite("/tex/md2.jpg");
        goto L47;
        L32:
        new Sprite("/tex/md.jpg"); /* constructor */
        this.a_arrLcq[0] = new Sprite("/tex/md.jpg");
        L47:
        new javax.microedition.m3g.Transform(); /* constructor */
        this.a_Transf = new javax.microedition.m3g.Transform();
        new javax.microedition.m3g.Background(); /* constructor */
        this.a_Backgr = new javax.microedition.m3g.Background();
        this.a_Backgr.setColor(0);
        this.c_F = (5880.0f / ((float) SysUtil.f_I));
        this.b_F = 2.75f;
        return;
        /* pop: ex_95; */
        return;
    }
    // bytecode 12 bytes, max_stack 2, max_locals 1
    public int i__int() {
        return this.a_bt.a(0).e__int();
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int a__int() {
        return 0;
    }
    // bytecode 26 bytes, max_stack 2, max_locals 2
    public int c__int(int v1) {
        if (v1 <= 0) goto L19;
        if (this.i__int() <= 0) goto L24;
        if (this.i__int() >= v1) goto L24;
        L19:
        return this.i__int();
        L24:
        return v1;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 2
    public int d(int v1) {
        return 0;
    }
    // bytecode 42 bytes, max_stack 3, max_locals 3
    public boolean a__boolean(int v1, int v2) {
        if (ObfR.a_B < 26) goto L13;
        this.g_Z = true;
        L13:
        if (ObfR.a_B == 24) goto L23;
        return 1;
        L23:
        if (this.a_bt == null) goto L40;
        return this.a_bt.a__boolean(v1, v2);
        L40:
        return 0;
    }
    // bytecode 26 bytes, max_stack 3, max_locals 3
    public void a__void(int v1, int v2) {
        if (ObfR.a_B == 24) goto L9;
        return;
        L9:
        if (this.a_bt == null) goto L25;
        this.a_bt.a__void(v1, v2);
        L25:
        return;
    }
    // bytecode 228 bytes, max_stack 3, max_locals 3
    public void b(int v1, int v2) {
        if (ObfR.a_B != 22) goto L16;
        this.a__void(-203);
        return;
        L16:
        if (ObfR.a_B < 26) goto L135;
        if (this.g_Z == 0) goto L135;
        if (Settings.m() != 0) goto L90;
        if (v1 >= 100) goto L61;
        if (v2 <= (SysUtil.f_I - 150)) goto L61;
        this.a__void(-202);
        L61:
        if (v1 <= (SysUtil.e_I - 100)) goto L134;
        if (v2 <= (SysUtil.f_I - 150)) goto L134;
        this.a__void(-203);
        return;
        L90:
        if (v2 >= 100) goto L110;
        if (v1 >= 150) goto L110;
        this.a__void(-202);
        L110:
        if (v2 <= (SysUtil.f_I - 100)) goto L134;
        if (v1 >= 150) goto L134;
        this.a__void(-203);
        L134:
        return;
        L135:
        if (ObfR.a_B == 24) goto L153;
        if (this.a__boolean(v1, v2) == 0) goto L211;
        return;
        L153:
        if (Settings.l() != 0) goto L183;
        if (v1 <= (SysUtil.e_I - 70)) goto L211;
        if (v2 >= 70) goto L211;
        this.a__void(-202);
        return;
        L183:
        if (v1 <= (SysUtil.e_I - 70)) goto L211;
        if (v2 <= (SysUtil.f_I - 70)) goto L211;
        this.a__void(-202);
        return;
        L211:
        if (this.a_bt == null) goto L227;
        this.a_bt.b(v1, v2);
        L227:
        return;
    }
}

