// Generated by tools/jdeob.py from x/ai.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ai`.
// String constants: /models/ | /tex/ | <init> | Code | append | indexOf | java/lang/Exception | java/lang/Object | java/lang/String | java/lang/StringBuffer | t.png | td2.png
public class ObfAi {
    private ObfAt a;
    private String a_String;
    private String b;
    private String c;
    private boolean a_Z;
    private boolean b_Z;
    // bytecode 48 bytes, max_stack 2, max_locals 2
    public ObfAi(String v1) {
        super();
        this.a = null;
        this.a_String = "";
        this.b = "";
        this.c = "";
        this.a_Z = false;
        this.b_Z = true;
        this.c = v1;
        this.a_Z = false;
        return;
    }
    // bytecode 112 bytes, max_stack 2, max_locals 2
    public void a(ObfCf v1) {
        /* try L0-L97 catch java.lang.Exception -> L100 */
        v1 = ((ObfCf) Resources.a(this.c));
        this.a_String = StreamReader.a(v1);
        this.b = StreamReader.a(v1);
        if (this.b.indexOf("t.png") != 0) goto L81;
        if (Settings.j != 2) goto L52;
        this.b = "ts2.png";
        goto L81;
        L52:
        if (Settings.j != 3) goto L68;
        this.b = "td2.png";
        goto L81;
        L68:
        if (Settings.j != 4) goto L81;
        this.b = "tf2.png";
        L81:
        if (StreamReader.a(v1) == 0) goto L93;
        jt1 = 1; /* join L94 from L89 */
        goto L94;
        L93:
        jt1 = 0; /* join L94 from L93 */
        L94:
        this.b_Z = jt1;
        goto L101;
        /* pop: ex_100; */
        L101:
        this.a(0);
        this.a_Z = true;
        return;
    }
    // bytecode 271 bytes, max_stack 5, max_locals 2
    public void a(boolean v1) {
        if (v1 != 0) goto L126;
        if (this.b_Z != 0) goto L69;
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.a(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString(), 1);
        goto L245;
        L69:
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.a(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString());
        goto L245;
        L126:
        if (this.b_Z != 0) goto L191;
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.b(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString(), 1);
        goto L245;
        L191:
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.b(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString());
        L245:
        this.a.b((ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f));
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return this.a_Z;
    }
    // bytecode 100 bytes, max_stack 5, max_locals 9
    public void a(ObfBq v1, ObfJ v2, float v3, float v4, float v5, float v6, float v7, float v8) {
        if (this.b_Z != 0) goto L62;
        this.a.a(v3, v4, v5);
        this.a.a(0.0f, 1.0f, 0.0f, 0.0f);
        this.a.b(0.0f, 0.0f, 1.0f, 0.0f);
        this.a.b(v8, 0.0f, 0.0f, 1.0f);
        v1.a(this.a);
        return;
        L62:
        this.a.a(v3, v4, v5);
        v3 = ((float) v2);
        v2 = ((ObfJ) ((ObfBy) this.a));
        v1.a(v2.a(), v2.a(v3));
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.a = null;
        return;
    }
}

