// Generated by tools/jdeob.py from x/bc.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bc`.
// String constants: ()Ljava/lang/String; | ()V | ()Z | (FFF)V | (FFFF)V | (Lam;)V | (Lbq;IFFF)V | (Lcf;)V | (Ljava/io/InputStream;)Ljava/lang/String; | (Ljava/lang/String;)I | (Ljava/lang/String;)Ljava/io/InputStream; | (Ljava/lang/String;)Ljava/lang/StringBuffer;
// API references: java/io
public class ObfBc {
    private ObfAt a;
    private String a_String;
    private String b;
    private String c;
    private boolean a_Z;
    // bytecode 43 bytes, max_stack 2, max_locals 2
    public ObfBc(String v1) {
        super();
        this.a = null;
        this.a_String = "";
        this.b = "";
        this.c = "";
        this.a_Z = false;
        this.c = v1;
        this.a_Z = false;
        return;
    }
    // bytecode 187 bytes, max_stack 2, max_locals 2
    public void a(ObfCf v1) {
        /* try L0-L172 catch java.lang.Exception -> L175 */
        v1 = ((ObfCf) ObfBl.a(this.c));
        this.a_String = ObfBe.a(v1);
        this.b = ObfBe.a(v1);
        if (ObfAl.j != 2) goto L73;
        if (this.b.indexOf("texpack") >= 0) goto L64;
        if (this.b.indexOf("t.png") != 0) goto L168;
        this.b = "ts2.png";
        goto L168;
        L64:
        this.b = "ts.png";
        goto L168;
        L73:
        if (ObfAl.j != 3) goto L122;
        if (this.b.indexOf("texpack") >= 0) goto L113;
        if (this.b.indexOf("t.png") != 0) goto L168;
        this.b = "td2.png";
        goto L168;
        L113:
        this.b = "td.png";
        goto L168;
        L122:
        if (ObfAl.j != 4) goto L168;
        if (this.b.indexOf("texpack") >= 0) goto L162;
        if (this.b.indexOf("t.png") != 0) goto L168;
        this.b = "tf2.png";
        goto L168;
        L162:
        this.b = "tf.png";
        L168:
        v1.close();
        goto L176;
        /* pop: ex_175; */
        L176:
        this.a(0);
        this.a_Z = true;
        return;
    }
    // bytecode 151 bytes, max_stack 5, max_locals 3
    public void a(boolean v1) {
        int v2 = ObfAl.a_Z;
        if (v1 != 0) goto L66;
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.a(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString(), 1);
        goto L121;
        L66:
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a = ObfBb.a.b(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.b).toString(), 1);
        L121:
        this.a.b((ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f));
        ObfAl.a_Z = v2;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return this.a_Z;
    }
    // bytecode 35 bytes, max_stack 5, max_locals 6
    public void a(ObfBq v1, int v2, float v3, float v4, float v5) {
        this.a.a((90.0f * ((float) v2)), 0.0f, 0.0f, 1.0f);
        this.a.a(v3, v4, 0.0f);
        v1.a(this.a);
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.a = null;
        return;
    }
}

