// Generated by tools/jdeob.py from x/b.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `b`.
// String constants: /lists/ol | /objects/ | <init> | Code | [Lai; | append | close | getClass | getResourceAsStream | java/io/IOException | java/io/InputStream | java/lang/Class
// API references: java/io
public class ObfB {
    private ObfAi[] a;
    private ObfCf a_cf;
    private int a_I;
    // bytecode 38 bytes, max_stack 2, max_locals 2
    public ObfB(ObfCf v1) {
        this();
        this.a = null;
        this.a_cf = null;
        this.a_I = 0;
        this.a = new ObfAi[50];
        this.a_cf = v1;
        this.b();
        return;
    }
    // bytecode 132 bytes, max_stack 4, max_locals 5
    public void b() {
        /* try L14-L129 catch java.io.IOException -> L130 */
        this.a[0] = null;
        int v2 = 0;
        this.a_I = 0;
        InputStream v3 = this.getClass().getResourceAsStream("/lists/ol");
        String v4 = "";
        L28:
        int v1 = v3.read();
        if (v3.read() <= 0) goto L125;
        v1 = ((char) v1);
        if (((char) v1) == 10) goto L70;
        new java.lang.StringBuffer(); /* constructor */
        v4 = new java.lang.StringBuffer().append(v4).append(v1).toString();
        goto L28;
        L70:
        new java.lang.StringBuffer(); /* constructor */
        new ObfAi(new java.lang.StringBuffer().append("/objects/").append(v4).toString()); /* constructor */
        v1 = ((int) new ObfAi(new java.lang.StringBuffer().append("/objects/").append(v4).toString()));
        this.a[v2] = v1;
        v4 = "";
        v2 += 1;
        this.a_I = (this.a_I + 1);
        goto L28;
        L125:
        v3.close();
        return;
        /* pop: ex_130; */
        return;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public ObfAi a(int v1) {
        if (this.a[v1].a() != 0) goto L25;
        this.a[v1].a(this.a_cf);
        L25:
        return this.a[v1];
    }
    // bytecode 43 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a_I) goto L32;
        this.a[v1].a();
        this.a[v1] = null;
        v1 += 1;
        goto L2;
        L32:
        this.a = null;
        this.a_cf = null;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfB() {
        super();
        return;
    }
    // bytecode 20 bytes, max_stack 2, max_locals 1
    public static int a(float v0) {
        if (fcmpg(v0, 0.0010000000474974513f) <= 0) goto L9;
        return 1;
        L9:
        if (fcmpl(v0, -0.0010000000474974513f) >= 0) goto L18;
        return m1;
        L18:
        return 0;
    }
    // bytecode 34 bytes, max_stack 1, max_locals 1
    public static int a(int v0) {
        switch (v0) {
        case 0: goto L28;
        case 2: goto L30;
        default: goto L32;
        }
        L28:
        return 1;
        L30:
        return m1;
        L32:
        return 0;
    }
    // bytecode 34 bytes, max_stack 1, max_locals 1
    public static int b(int v0) {
        switch (v0) {
        case 1: goto L28;
        case 3: goto L30;
        default: goto L32;
        }
        L28:
        return m1;
        L30:
        return 1;
        L32:
        return 0;
    }
    // bytecode 70 bytes, max_stack 6, max_locals 6
    public static double d(double v0) {
        double v2 = (v0 * v0);
        double v4 = ((((((((v2 * 16.15364129822302) + 268.42548195503974) * v2) + 1153.029351540485) * v2) + 1780.406316433197) * v2) + 896.7859740366387);
        v4 = (((((((((v2 * 16.15364129822302) + 268.42548195503974) * v2) + 1153.029351540485) * v2) + 1780.406316433197) * v2) + 896.7859740366387) / (((((((((v2 + 58.95697050844462) * v2) + 536.2653740312153) * v2) + 1666.7838148816338) * v2) + 2079.33497444541) * v2) + 896.7859740366387));
        return ((((((((((v2 * 16.15364129822302) + 268.42548195503974) * v2) + 1153.029351540485) * v2) + 1780.406316433197) * v2) + 896.7859740366387) / (((((((((v2 + 58.95697050844462) * v2) + 536.2653740312153) * v2) + 1666.7838148816338) * v2) + 2079.33497444541) * v2) + 896.7859740366387)) * v0);
    }
    // bytecode 47 bytes, max_stack 8, max_locals 2
    public static double e(double v0) {
        if (dcmpl(v0, 0.41421356237309503) >= 0) goto L13;
        return ObfB.d(v0);
        L13:
        if (dcmpg(v0, 2.414213562373095) <= 0) goto L32;
        return (1.5707963267948966 - ObfB.d((1.0 / v0)));
        L32:
        return (0.7853981633974483 + ObfB.d(((v0 - 1.0) / (v0 + 1.0))));
    }
    // bytecode 18 bytes, max_stack 4, max_locals 2
    public static double a(double v0) {
        if (dcmpg(v0, 0.0) <= 0) goto L11;
        return ObfB.e(v0);
        L11:
        return (-ObfB.e((-v0)));
    }
    // bytecode 63 bytes, max_stack 4, max_locals 4
    public static double a(double v0, double v2) {
        if (dcmpg(v2, 0.0) != 0) goto L8;
        return 0.0;
        L8:
        if (dcmpg((v0 + v2), v0) != 0) goto L30;
        if (dcmpg(v0, 0.0) < 0) goto L26;
        return 1.5707963267948966;
        L26:
        return -1.5707963267948966;
        L30:
        v0 = ObfB.a((v0 / v2));
        if (dcmpl(v2, 0.0) >= 0) goto L61;
        if (dcmpl(v0, 0.0) > 0) goto L55;
        return (v0 + 3.141592653589793);
        L55:
        return (v0 - 3.141592653589793);
        L61:
        return v0;
    }
    // bytecode 73 bytes, max_stack 6, max_locals 5
    public static double b(double v0) {
        int v4 = 0;
        if (dcmpl(v0, 0.0) >= 0) goto L15;
        v0 = (-v0);
        v4 += 1;
        L15:
        if (dcmpg(v0, 1.0) <= 0) goto L25;
        return -100000.0;
        L25:
        double v2 = java.lang.Math.sqrt((1.0 - (v0 * v0)));
        if (dcmpg(v0, 0.7) <= 0) goto L56;
        v2 = (1.5707963267948966 - ObfB.a((v2 / v0)));
        goto L63;
        L56:
        v2 = ObfB.a((v0 / v2));
        L63:
        if (v4 <= 0) goto L71;
        v2 = (-v2);
        L71:
        return v2;
    }
    // bytecode 27 bytes, max_stack 4, max_locals 2
    public static double c(double v0) {
        if (dcmpg(v0, 1.0) > 0) goto L14;
        if (dcmpl(v0, -1.0) >= 0) goto L18;
        L14:
        return -100000.0;
        L18:
        return (1.5707963267948966 - ObfB.b(v0));
    }
}

