// Generated by tools/jdeob.py from x/cl.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cl`.
// String constants: /models/ | /tex/ | /tex/shadow.png | <clinit> | <init> | Code | KORa | abs | append | close | cos | java/io/DataOutputStream
// API references: java/io java/util javax/microedition
public class ObfCl extends ObfCa {
    protected int a;
    protected int b;
    protected CameraState a_di;
    protected CarPhysics a_x;
    private float d;
    private float e;
    protected ObfAt a_at;
    private boolean h;
    protected boolean a_Z;
    private boolean i;
    private Vec3 e_bz;
    protected Vec3 a_bz;
    protected Vec3 b_bz;
    private Vec3 f;
    private Vec3 g;
    private Vec3 h_bz;
    private Rect a_bj;
    private boolean j;
    private float f_F;
    private float g_F;
    private float h_F;
    private float i_F;
    private Vec2 a_z;
    private Vec2 b_z;
    private int g_I;
    private int h_I;
    protected int c;
    private int i_I;
    private int j_I;
    protected float a_F;
    private float j_F;
    private int k;
    protected float b_F;
    protected ObfBs a_bs;
    protected boolean b_Z;
    protected int d_I;
    protected boolean c_Z;
    protected String a_String;
    protected String b_String;
    protected String c_String;
    private Vec2 c_z;
    private boolean k_Z;
    private Vec2 d_z;
    private Vec2 e_z;
    private Vec2 f_z;
    private static Vec3 i_bz;
    private static Vec3 j_bz;
    private static Vec3 k_bz;
    private static Vec3 l;
    private static Vec3 m;
    private static Vec3 n;
    private Transform a_Transf;
    protected Vec3 c_bz;
    protected Vec3 d_bz;
    private Vec3 o;
    protected Plane a_ct;
    private int l_I;
    private boolean l_Z;
    protected boolean d_Z;
    protected int e_I;
    protected int f_I;
    private boolean m_Z;
    private int m_I;
    private long a_J;
    protected float c_F;
    private boolean n_Z;
    protected boolean e_Z;
    protected static ObfCq a_cq;
    private float k_F;
    private Transform b_Transf;
    private boolean o_Z;
    public static boolean f_Z;
    public boolean g_Z;
    static {
        ObfCl.i_bz = null;
        ObfCl.j_bz = null;
        ObfCl.k_bz = null;
        ObfCl.l = null;
        ObfCl.m = null;
        ObfCl.n = null;
        ObfCl.a_cq = null;
        ObfCl.f_Z = false;
        return;
    }
    // bytecode 793 bytes, max_stack 7, max_locals 6
    public ObfCl(Textures v1, InputStream v2, int v3, ObfBs v4, int v5) {
        /* try L449-L490 catch java.lang.Exception -> L493 */
        super();
        this.a = 11141120;
        this.b = 16711680;
        this.a_di = null;
        this.a_x = null;
        this.d = 0.0f;
        this.e = 0.0f;
        this.a_at = null;
        this.h = true;
        this.a_Z = true;
        this.i = true;
        this.e_bz = null;
        this.a_bz = null;
        this.b_bz = null;
        this.f = null;
        this.g = null;
        this.h_bz = null;
        this.a_bj = null;
        this.j = true;
        this.f_F = 0.0f;
        this.g_F = 0.0f;
        this.h_F = 0.0f;
        this.i_F = 0.5f;
        this.a_z = null;
        this.b_z = null;
        this.g_I = 0;
        this.h_I = 0;
        this.c = 0;
        this.i_I = 0;
        this.j_I = 0;
        this.a_F = 0.0f;
        this.j_F = 0.0f;
        this.k = 0;
        this.b_F = 0.0f;
        this.a_bs = null;
        this.b_Z = false;
        this.d_I = m1;
        this.c_Z = false;
        this.a_String = "";
        this.b_String = "";
        this.c_String = "";
        this.c_z = null;
        this.k_Z = false;
        this.d_z = null;
        this.e_z = null;
        this.f_z = null;
        this.a_Transf = null;
        this.c_bz = null;
        this.d_bz = null;
        this.o = null;
        this.a_ct = null;
        this.l_I = 0;
        this.l_Z = false;
        this.d_Z = false;
        this.e_I = 0;
        this.f_I = 0;
        this.m_Z = false;
        this.m_I = 0;
        this.a_J = 0L;
        this.c_F = 0.0f;
        this.n_Z = true;
        this.e_Z = false;
        this.k_F = 0.0f;
        this.b_Transf = null;
        this.o_Z = false;
        this.g_Z = false;
        this.a_bs = v4;
        this.k = v3;
        this.l_I = v5;
        new CameraState(); /* constructor */
        this.a_di = new CameraState();
        this.a_di.a(0.0f, 0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        this.a_z = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.d_z = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.e_z = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.b_z = new Vec2(0.0f, 0.0f);
        this.c();
        v3 = ((int) v2);
        v2 = ((InputStream) this);
        v2.a_String = StreamReader.a(v3);
        v2.b_String = StreamReader.a(v3);
        v2.c_String = StreamReader.a(v3);
        /* pop: StreamReader.a(v3); */
        v2.a_x.a(v3);
        v3.close();
        goto L494;
        /* pop: ex_493; */
        L494:
        this.a(v1);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.c_z = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.f_z = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.e_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.f = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.g = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.h_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.j_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.i_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.k_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.m = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.l = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.b_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.a_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.c_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.d_bz = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.o = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        ObfCl.n = new Vec3(0.0f, 0.0f, 0.0f);
        new Plane(0.0f, 0.0f, 0.0f, 0.0f); /* constructor */
        this.a_ct = new Plane(0.0f, 0.0f, 0.0f, 0.0f);
        new Plane(0.0f, 0.0f, 0.0f, 0.0f); /* constructor */
        new javax.microedition.m3g.Transform(); /* constructor */
        this.b_Transf = new javax.microedition.m3g.Transform();
        new javax.microedition.m3g.Transform(); /* constructor */
        this.a_Transf = new javax.microedition.m3g.Transform();
        return;
    }
    // bytecode 12 bytes, max_stack 3, max_locals 1
    public void c() {
        new StockTune(); /* constructor */
        this.a_x = new StockTune();
        return;
    }
    // bytecode 18 bytes, max_stack 4, max_locals 1
    public void d() {
        this.m_I = (this.m_I + KORa.rand.nextInt(10));
        return;
    }
    // bytecode 24 bytes, max_stack 4, max_locals 1
    public void e() {
        if (this.m_I <= 0) goto L23;
        this.m_I = (this.m_I - KORa.rand.nextInt(2));
        L23:
        return;
    }
    // bytecode 18 bytes, max_stack 3, max_locals 2
    public void a(Textures v1) {
        if (this.d_I != Settings.d()) goto L11;
        return;
        L11:
        this.a(v1, true);
        return;
    }
    // bytecode 20 bytes, max_stack 2, max_locals 2
    public void a(ObfBq v1) {
        if (this.c_Z == 0) goto L13;
        if (Settings.d() > 0) goto L14;
        L13:
        return;
        L14:
        this.b(v1);
        return;
    }
    // bytecode 188 bytes, max_stack 5, max_locals 3
    public void b(ObfBq v1) {
        this.b_Transf.setIdentity();
        this.b_Transf.postTranslate(this.a_di.b(), this.a_di.c(), this.k_F);
        this.b_Transf.postTranslate(-0.10000000149011612f, 0.10000000149011612f, 0.8999999761581421f);
        this.b_Transf.postRotate((((-this.a_di.k()) / 3.1415927410125732f) * 180.0f), 0.0f, 0.0f, 1.0f);
        this.b_Transf.postRotate(((this.a_di.h() / 3.1415927410125732f) * 180.0f), 1.0f, 0.0f, 0.0f);
        ObfCl v2 = this;
        this.b_Transf.postRotate(((((-this.a_di.i()) / 3.1415927410125732f) * 180.0f) + this.a_di.a_F), 0.0f, 1.0f, 0.0f);
        v2 = ((ObfCl) (1.0f + ((this.k_F - this.a_di.d()) * 0.30000001192092896f)));
        if (fcmpg((1.0f + ((this.k_F - this.a_di.d()) * 0.30000001192092896f)), 2.5f) <= 0) goto L154;
        v2 = ((ObfCl) 2.5f);
        L154:
        this.b_Transf.postScale((0.25f * v2), (0.550000011920929f * v2), 0.5f);
        ObfCl.a_cq.b(v1, this.b_Transf);
        this.c_Z = false;
        return;
    }
    // bytecode 248 bytes, max_stack 7, max_locals 3
    public void a(Textures v1, boolean v2) {
        /* try L192-L211 catch java.io.IOException -> L214 */
        if (Settings.d() <= 1) goto L11;
        ObfAt.a_Z = true;
        L11:
        if (this.d_I == Settings.d()) goto L28;
        this.d_I = Settings.d();
        L28:
        if (Settings.d() <= 0) goto L119;
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a_at = AssetManager.a_de.a(new java.lang.StringBuffer().append("/models/").append(this.a_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.c_String).toString(), false, new java.lang.StringBuffer().append("/tex/").append(this.c_String).append("_l").toString());
        goto L174;
        L119:
        new java.lang.StringBuffer(); /* constructor */
        new java.lang.StringBuffer(); /* constructor */
        this.a_at = AssetManager.a_de.b(new java.lang.StringBuffer().append("/models/").append(this.b_String).toString(), new java.lang.StringBuffer().append("/tex/").append(this.c_String).toString(), false);
        L174:
        if (Settings.d() <= 0) goto L215;
        if (Settings.g() == 0) goto L215;
        if (ObfCl.a_cq != null) goto L215;
        new ObfCq(v1.a("/tex/shadow.png", true), true, true); /* constructor */
        ObfCl.a_cq = new ObfCq(v1.a("/tex/shadow.png", true), true, true);
        goto L215;
        /* pop: ex_214; */
        L215:
        this.a_at.a(this.a_di.b(), this.a_di.c(), this.a_di.d());
        this.j();
        return;
    }
    // bytecode 146 bytes, max_stack 4, max_locals 4
    public void c(ObfBq v1) {
        if (this.a_at.a == null) goto L62;
        float v2 = (ObfBt.a().c() / 360.0f);
        ObfCl v3 = this;
        v3 = ((ObfCl) (-this.a_di.h()));
        this.a_Transf.setIdentity();
        this.a_Transf.postTranslate(v2, v3, 0.0f);
        this.a_at.a.setTransform(this.a_Transf);
        L62:
        v2 = ((float) this);
        this.a_at.a(v2.a_di.b(), v2.a_di.c(), v2.a_di.d());
        v2.j();
        if (ObfCl.a_cq == null) goto L118;
        this.c_Z = true;
        if (Settings.e() != 0) goto L118;
        this.a(v1);
        L118:
        v1.a(this.a_at);
        if (this.o_Z != 0) goto L140;
        this.a_at.c();
        L140:
        this.o_Z = false;
        return;
    }
    // bytecode 84 bytes, max_stack 3, max_locals 3
    public void f(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        this.i = false;
        if (fcmpl(this.a_di.e(), 0.0f) >= 0) goto L35;
        this.a_di.a();
        return;
        L35:
        this.a_di.c((this.a().h() * v1));
        if (fcmpg(this.a_di.e(), this.a().l()) <= 0) goto L83;
        this.a_di.b(this.a().l());
        L83:
        return;
    }
    // bytecode 108 bytes, max_stack 3, max_locals 3
    public void g(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        this.i = false;
        if (this.a_di.b() != 0) goto L58;
        if (fcmpg(this.a_di.j(), 0.10000000149011612f) <= 0) goto L58;
        this.a_di.a();
        this.a_at.b();
        this.o_Z = true;
        return;
        L58:
        this.a_di.c(((-this.a().h()) * v1));
        if (fcmpl(this.a_di.e(), this.a().m()) >= 0) goto L107;
        this.a_di.b(this.a().m());
        L107:
        return;
    }
    // bytecode 200 bytes, max_stack 4, max_locals 3
    public void n(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        if (fcmpl(this.a_di.j(), 0.009999999776482582f) >= 0) goto L32;
        this.a_di.d(0.0f);
        return;
        L32:
        v1 = (this.a().j() * v1);
        v2 = this;
        v2 = ((ObfCl) java.lang.Math.abs(this.a_di.l()));
        if (this.g_Z != 0) goto L118;
        if (fcmpl(v2, 1.0f) >= 0) goto L118;
        if (this.a_x.a() == 0) goto L118;
        if (Settings.m != 1) goto L91;
        if (ObfCl.f_Z == 0) goto L118;
        L91:
        if (Settings.r() != 0) goto L118;
        if (Settings.m != 2) goto L108;
        /* pop: ObfCl.f_Z; */
        L108:
        v1 = (v1 * (1.399999976158142f - (0.4000000059604645f * v2)));
        L118:
        this.g_Z = false;
        this.a_di.e(v1);
        if (fcmpg(this.a_di.j(), 0.0f) <= 0) goto L171;
        v1 = (this.a().n() / this.a_di.j());
        if (fcmpg((this.a().n() / this.a_di.j()), this.a().o()) <= 0) goto L179;
        L171:
        v1 = this.a().o();
        L179:
        if (fcmpg(this.a_di.l(), v1) <= 0) goto L199;
        this.a_di.d(v1);
        L199:
        return;
    }
    // bytecode 77 bytes, max_stack 3, max_locals 3
    public void j(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        this.a_Z = false;
        if (fcmpl(this.a_di.j(), 0.009999999776482582f) >= 0) goto L37;
        this.a_di.d(0.0f);
        return;
        L37:
        if (this.a_di.b() == 0) goto L63;
        jt1 = (this.a().o() * v1); /* join L73 from L51 */
        goto L73;
        L63:
        jt1 = ((-this.a().o()) * v1); /* join L73 from L63 */
        L73:
        this.a_di.d(jt1);
        return;
    }
    // bytecode 203 bytes, max_stack 4, max_locals 3
    public void o(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        if (fcmpl(this.a_di.j(), 0.009999999776482582f) >= 0) goto L32;
        this.a_di.d(0.0f);
        return;
        L32:
        v1 = ((-this.a().j()) * v1);
        v2 = this;
        v2 = ((ObfCl) java.lang.Math.abs(this.a_di.l()));
        if (this.g_Z != 0) goto L119;
        if (fcmpl(v2, 1.0f) >= 0) goto L119;
        if (this.a_x.a() == 0) goto L119;
        if (Settings.m != 1) goto L92;
        if (ObfCl.f_Z == 0) goto L119;
        L92:
        if (Settings.r() != 0) goto L119;
        if (Settings.m != 2) goto L109;
        /* pop: ObfCl.f_Z; */
        L109:
        v1 = (v1 * (1.399999976158142f - (0.4000000059604645f * v2)));
        L119:
        this.g_Z = false;
        this.a_di.e(v1);
        if (fcmpg(this.a_di.j(), 0.0f) <= 0) goto L172;
        v1 = (this.a().n() / this.a_di.j());
        if (fcmpg((this.a().n() / this.a_di.j()), this.a().o()) <= 0) goto L180;
        L172:
        v1 = this.a().o();
        L180:
        if (fcmpl(this.a_di.l(), (-v1)) >= 0) goto L202;
        this.a_di.d((-v1));
        L202:
        return;
    }
    // bytecode 37 bytes, max_stack 2, max_locals 3
    public void h(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        this.a_Z = false;
        if (this.a_di.b() != 0) goto L31;
        this.n(v1);
        return;
        L31:
        this.o(v1);
        return;
    }
    // bytecode 37 bytes, max_stack 2, max_locals 3
    public void i(float v1) {
        ObfCl v2 = this;
        if (this.l_Z == 0) goto L10;
        return;
        L10:
        this.a_Z = false;
        if (this.a_di.b() != 0) goto L31;
        this.o(v1);
        return;
        L31:
        this.n(v1);
        return;
    }
    // bytecode 167 bytes, max_stack 5, max_locals 5
    public void k(float v1) {
        float v3 = v1;
        ObfCl v2 = this;
        if (this.i != 0) goto L24;
        ObfCl v4 = v2;
        if (v2.a_di.a() != 0) goto L136;
        L24:
        v4 = v2;
        if (fcmpg(v2.a_di.b().d(), 10.0f) <= 0) goto L136;
        v4 = v2;
        if (v2.a_di.a() == 0) goto L98;
        v4 = v2;
        v4 = v2;
        v2.a_di.b().f((1.0f - (((v3 * (v2.a_di.b().d() - 10.0f)) / 13.0f) / 1.7000000476837158f)));
        goto L136;
        L98:
        v4 = v2;
        v4 = v2;
        v2.a_di.b().f((1.0f - (((v3 * (v2.a_di.b().d() - 10.0f)) / 13.0f) / 2.0f)));
        L136:
        this.a(v1);
        this.b(v1);
        v3 = v1;
        v2 = this;
        this.a_di.l((v3 * v2.a().w()));
        return;
    }
    // bytecode 100 bytes, max_stack 3, max_locals 2
    public void a(float v1) {
        if (this.i != 0) goto L13;
        this.i = true;
        return;
        L13:
        if (fcmpg(this.a_di.e(), 0.0f) <= 0) goto L63;
        this.a_di.c(((-this.a().p()) * v1));
        if (fcmpl(this.a_di.e(), 0.0f) >= 0) goto L99;
        this.a_di.b(0.0f);
        return;
        L63:
        this.a_di.c((this.a().p() * v1));
        if (fcmpg(this.a_di.e(), 0.0f) <= 0) goto L99;
        this.a_di.b(0.0f);
        L99:
        return;
    }
    // bytecode 169 bytes, max_stack 3, max_locals 2
    public void b(float v1) {
        if (this.a_Z != 0) goto L13;
        this.a_Z = true;
        return;
        L13:
        if (fcmpg(this.a_di.l(), 0.0f) <= 0) goto L98;
        if (Settings.m != 2) goto L60;
        if (ObfCl.f_Z != 0) goto L60;
        this.a_di.e((((-this.a().q()) * v1) * 2.0f));
        goto L77;
        L60:
        this.a_di.e(((-this.a().q()) * v1));
        L77:
        if (fcmpl(this.a_di.l(), 0.0f) >= 0) goto L168;
        this.a_di.d(0.0f);
        return;
        L98:
        if (Settings.m != 2) goto L132;
        if (ObfCl.f_Z != 0) goto L132;
        this.a_di.e(((this.a().q() * v1) * 2.0f));
        goto L148;
        L132:
        this.a_di.e((this.a().q() * v1));
        L148:
        if (fcmpg(this.a_di.l(), 0.0f) <= 0) goto L168;
        this.a_di.d(0.0f);
        L168:
        return;
    }
    // bytecode 2689 bytes, max_stack 7, max_locals 5
    public void c(float v1) {
        this.b_Z = false;
        this.g_F = ((float) java.lang.Math.sin(((double) this.a_di.k())));
        this.h_F = ((float) java.lang.Math.cos(((double) this.a_di.k())));
        float v4 = this.h_F;
        float v3 = this.g_F;
        ObfCl v2 = this;
        this.a_z.b(v3, v4);
        v2.a_z.a();
        this.f.b(((this.h_F * this.a_di.b().b()) + (this.g_F * this.a_di.b().a())), (((-this.g_F) * this.a_di.b().b()) + (this.h_F * this.a_di.b().a())), this.a_di.b().c());
        if (fcmpl(this.f.a(), 0.0f) >= 0) goto L167;
        jt1 = 1; /* join L168 from L163 */
        goto L168;
        L167:
        jt1 = 0; /* join L168 from L167 */
        L168:
        this.a_di.a(jt1);
        if (fcmpl(java.lang.Math.abs(this.f.a()), 0.0010000000474974513f) >= 0) goto L195;
        this.f.c(0.0f);
        L195:
        if (fcmpl(java.lang.Math.abs(this.f.b()), 0.0010000000474974513f) >= 0) goto L219;
        this.f.d(0.0f);
        L219:
        if (fcmpl(java.lang.Math.abs(this.f.c()), 0.0010000000474974513f) >= 0) goto L243;
        this.f.e(0.0f);
        L243:
        v2 = ((ObfCl) ((this.a().b() * 0.5f) * this.a_di.m()));
        if (fcmpl(this.f.a(), 0.0f) >= 0) goto L315;
        v2 = ((ObfCl) ((float) MeshCache.a(((double) v2), ((double) (-this.f.a())))));
        v3 = ((float) MeshCache.a(((double) this.f.b()), ((double) (-this.f.a()))));
        goto L370;
        L315:
        if (fcmpg(this.f.a(), 0.0f) <= 0) goto L366;
        v2 = ((ObfCl) ((float) MeshCache.a(((double) v2), ((double) this.f.a()))));
        v3 = ((float) MeshCache.a(((double) this.f.b()), ((double) this.f.a())));
        goto L370;
        L366:
        v2 = ((ObfCl) 0.0f);
        v3 = 0.0f;
        L370:
        if (fcmpl(java.lang.Math.abs(v2), 0.009999999776482582f) >= 0) goto L382;
        v2 = ((ObfCl) 0.0f);
        L382:
        if (fcmpl(java.lang.Math.abs(v3), 0.009999999776482582f) >= 0) goto L394;
        v3 = 0.0f;
        L394:
        v4 = ((v3 + v2) - this.a_di.l());
        v2 = ((ObfCl) (v3 - v2));
        v3 = ((float) this);
        this.a_di.a(v2);
        if (this.a_di.a() != 0) goto L436;
        v4 = 0.0f;
        v2 = ((ObfCl) 0.0f);
        L436:
        this.d_z.b(0.0f, (this.a().g() * java.lang.Math.max((-this.a().v()), java.lang.Math.min(this.a().v(), (this.a().u() * v4)))));
        if (fcmpg(this.a_di.f(), 0.0f) <= 0) goto L549;
        this.e_z.b(0.0f, ((this.a().g() * this.i_F) * java.lang.Math.max((-this.a().v()), java.lang.Math.min(this.a().v(), (this.a().t() * v2)))));
        goto L595;
        L549:
        this.e_z.b(0.0f, (this.a().g() * java.lang.Math.max((-this.a().v()), java.lang.Math.min(this.a().v(), (this.a().t() * v2)))));
        L595:
        if (fcmpg(java.lang.Math.abs(this.d_z.b()), 0.0f) <= 0) goto L656;
        if (fcmpg(java.lang.Math.abs(this.d), 0.0f) <= 0) goto L656;
        if (fcmpl(this.a_di.j(), 0.4000000059604645f) >= 0) goto L656;
        this.d_z.b(((this.d_z.b() + this.d) / 2.0f));
        L656:
        if (fcmpg(java.lang.Math.abs(this.e_z.b()), 0.0f) <= 0) goto L717;
        if (fcmpg(java.lang.Math.abs(this.e), 0.0f) <= 0) goto L717;
        if (fcmpl(this.a_di.j(), 0.4000000059604645f) >= 0) goto L717;
        this.e_z.b(((this.e_z.b() + this.e) / 2.0f));
        L717:
        this.e = this.e_z.b();
        this.d = this.d_z.b();
        this.a_bj = null;
        if (this.a_di.a() == 0) goto L941;
        this.a_bj = this.a_bs.a(this.a_di.b(), this.a_di.c());
        v2 = ((ObfCl) (((this.a_bj.a() * this.g_F) + (this.a_bj.b() * this.h_F)) / this.a_bj.c()));
        ObfCl.i_bz.b((100.0f * (this.a_di.e() - ((this.a().i() * this.a_di.f()) * ((float) MeshCache.a(this.f.a()))))), 0.0f, 0.0f);
        ObfCl.j_bz.b(((float) (-MeshCache.a(v2))), 0.0f, 0.0f);
        ObfCl.j_bz.e(java.lang.Math.abs((ObfCl.j_bz.a() * v2)));
        ObfCl.i_bz.e(java.lang.Math.abs((ObfCl.i_bz.a() * v2)));
        v2 = ((ObfCl) (v2 * v2));
        ObfCl.j_bz.f((((19.600000381469727f * this.a().e()) * v2) / ((float) java.lang.Math.sqrt(((double) (v2 + 1.0f))))));
        goto L1085;
        L941:
        ObfCl.i_bz.b(0.0f, 0.0f, 0.0f);
        if (Settings.m != 2) goto L1067;
        if (ObfCl.f_Z != 0) goto L1067;
        v3 = ((float) this);
        v3 = ((float) this);
        v3 = ((float) this);
        v2 = ((ObfCl) (this.a_di.d() - this.a_bs.a((this.a_di.b() - (0.30000001192092896f * this.g_F)), (this.a_di.c() - (0.30000001192092896f * this.g_F)))));
        if (fcmpl((this.a_di.d() - this.a_bs.a((this.a_di.b() - (0.30000001192092896f * this.g_F)), (this.a_di.c() - (0.30000001192092896f * this.g_F)))), -5.0f) >= 0) goto L1046;
        ObfCl.j_bz.b(0.0f, 0.0f, ((9.800000190734863f * this.a().e()) / 2.4000000953674316f));
        goto L1085;
        L1046:
        ObfCl.j_bz.b(0.0f, 0.0f, (9.800000190734863f * this.a().e()));
        goto L1085;
        L1067:
        ObfCl.j_bz.b(0.0f, 0.0f, (9.800000190734863f * this.a().e()));
        L1085:
        ObfCl.k_bz.b(((-(this.a().s() * this.f.a())) + ((this.a().r() * this.f.a()) * java.lang.Math.abs(this.f.a()))), ((-(this.a().s() * this.f.b())) + ((this.a().r() * this.f.b()) * java.lang.Math.abs(this.f.b()))), (-(this.a().s() * this.f.c())));
        this.f_z.b(((((float) java.lang.Math.sin(((double) this.a_di.l()))) * this.d_z.a()) + this.e_z.a()), ((((float) java.lang.Math.cos(((double) this.a_di.l()))) * this.d_z.b()) + this.e_z.b()));
        ObfCl.l.b((((ObfCl.i_bz.a() + this.f_z.a()) + ObfCl.k_bz.a()) + ObfCl.j_bz.a()), (((ObfCl.i_bz.b() + this.f_z.b()) + ObfCl.k_bz.b()) + ObfCl.j_bz.b()), ((ObfCl.i_bz.c() + ObfCl.j_bz.c()) + ObfCl.k_bz.c()));
        if (fcmpl(this.a_di.j(), 0.20000000298023224f) >= 0) goto L1400;
        if (fcmpl(java.lang.Math.abs(ObfCl.l.a()), java.lang.Math.abs(ObfCl.l.b())) >= 0) goto L1400;
        if (fcmpl(this.a_di.n(), 0.0f) > 0) goto L1400;
        this.f.d(0.0f);
        ObfCl.l.d(0.0f);
        L1400:
        v2 = ((ObfCl) ((this.a().c() * this.d_z.b()) - (this.a().d() * this.e_z.b())));
        ObfCl.m.b((ObfCl.l.a() / this.a().e()), (ObfCl.l.b() / this.a().e()), (ObfCl.l.c() / this.a().e()));
        this.f_F = (v2 / this.a().f());
        this.g.b(this.f.a(), this.f.b(), this.f.c());
        this.h_bz.b(this.a_di.b(), this.a_di.c(), this.a_di.d());
        L1549:
        if (this.j != 0) goto L1921;
        if (fcmpg(v1, 0.009999999776482582f) <= 0) goto L1921;
        v1 = (v1 - 0.009999999776482582f);
        this.b_bz.b((0.009999999776482582f * ObfCl.m.a()), (0.009999999776482582f * ObfCl.m.b()), (0.009999999776482582f * ObfCl.m.c()));
        this.b_bz.a(this.g.a(), this.g.b(), this.g.c());
        this.b_bz.b(((this.h_F * this.b_bz.b()) + (this.g_F * this.b_bz.a())), (((-this.g_F) * this.b_bz.b()) + (this.h_F * this.b_bz.a())), this.b_bz.c());
        if (fcmpg(this.b_bz.e(), this.a().k()) <= 0) goto L1764;
        this.b_bz.a();
        this.b_bz.c((this.b_bz.a() * this.a().k()));
        this.b_bz.d((this.b_bz.b() * this.a().k()));
        L1764:
        this.g.b(((this.h_F * this.b_bz.b()) + (this.g_F * this.b_bz.a())), (((-this.g_F) * this.b_bz.b()) + (this.h_F * this.b_bz.a())), this.b_bz.c());
        this.a_bz.b((this.h_bz.a() + (0.009999999776482582f * this.b_bz.a())), (this.h_bz.b() + (0.009999999776482582f * this.b_bz.b())), (this.h_bz.c() + (0.009999999776482582f * this.b_bz.c())));
        this.h_bz.b(this.a_bz.a(), this.a_bz.b(), this.a_bz.c());
        goto L1549;
        L1921:
        this.b_bz.b((v1 * ObfCl.m.a()), (v1 * ObfCl.m.b()), (v1 * ObfCl.m.c()));
        this.b_bz.a(this.g.a(), this.g.b(), this.g.c());
        this.g();
        this.b_bz.b(((this.h_F * this.b_bz.b()) + (this.g_F * this.b_bz.a())), (((-this.g_F) * this.b_bz.b()) + (this.h_F * this.b_bz.a())), this.b_bz.c());
        if (fcmpg(this.b_bz.e(), this.a().k()) <= 0) goto L2118;
        this.b_bz.a();
        this.b_bz.c((this.b_bz.a() * this.a().k()));
        this.b_bz.d((this.b_bz.b() * this.a().k()));
        L2118:
        this.a_bz.b((this.h_bz.a() + (v1 * this.b_bz.a())), (this.h_bz.b() + (v1 * this.b_bz.b())), (this.h_bz.c() + (v1 * this.b_bz.c())));
        v1 = this.a_bs.a((this.a_bz.a() - (0.30000001192092896f * this.g_F)), (this.a_bz.b() - (0.30000001192092896f * this.g_F)));
        v1 = (this.a_bs.a((this.a_bz.a() - (0.30000001192092896f * this.g_F)), (this.a_bz.b() - (0.30000001192092896f * this.g_F))) * ObfAr.c);
        this.j = true;
        this.k_F = v1;
        v2 = ((ObfCl) (v1 - this.a_bz.c()));
        if (fcmpg((v1 - this.a_bz.c()), 0.009999999776482582f) <= 0) goto L2255;
        this.j = false;
        goto L2468;
        L2255:
        if (fcmpl(java.lang.Math.abs(v2), 2.5f) > 0) goto L2468;
        this.a_bz.e(v1);
        if (fcmpg((this.a_bz.a() - this.a_di.a().a()), 0.0f) == 0) goto L2351;
        this.b_bz.e(((this.b_bz.a() * (this.a_bz.c() - this.a_di.a().c())) / (this.a_bz.a() - this.a_di.a().a())));
        goto L2437;
        L2351:
        if (fcmpg((this.a_bz.b() - this.a_di.a().b()), 0.0f) == 0) goto L2429;
        this.b_bz.e(((this.b_bz.b() * (this.a_bz.c() - this.a_di.a().c())) / (this.a_bz.b() - this.a_di.a().b())));
        goto L2437;
        L2429:
        this.b_bz.e(0.0f);
        L2437:
        if (this.a_di.a() != 0) goto L2468;
        if (fcmpl(this.b_bz.c(), -0.30000001192092896f) >= 0) goto L2468;
        this.b_bz.e(0.0f);
        L2468:
        v1 = this.a_bs.a((this.a_bz.a() + (0.6000000238418579f * this.g_F)), (this.a_bz.b() + (0.6000000238418579f * this.h_F)));
        v2 = ((ObfCl) this.a_bs.a((this.a_bz.a() - (0.6000000238418579f * this.g_F)), (this.a_bz.b() - (0.6000000238418579f * this.h_F))));
        v3 = this.a_bs.a((this.a_bz.a() - (0.30000001192092896f * this.h_F)), (this.a_bz.b() + (0.30000001192092896f * this.g_F)));
        v4 = this.a_bs.a((this.a_bz.a() + (0.30000001192092896f * this.h_F)), (this.a_bz.b() - (0.30000001192092896f * this.g_F)));
        this.k_Z = false;
        if (this.j == 0) goto L2688;
        this.c_bz.b(1.2000000476837158f, 0.0f, (ObfAr.c * (v1 - v2)));
        this.d_bz.b(0.0f, 0.6000000238418579f, (ObfAr.c * (v4 - v3)));
        this.k_Z = true;
        this.e_bz.b(this.d_bz, this.c_bz);
        L2688:
        return;
    }
    // bytecode 109 bytes, max_stack 5, max_locals 1
    public void f() {
        this.g_F = ((float) java.lang.Math.sin(((double) this.a_di.k())));
        this.h_F = ((float) java.lang.Math.cos(((double) this.a_di.k())));
        this.b_bz.a(4.0f, 0.0f, 0.0f);
        this.a_di.b(((this.h_F * this.b_bz.b()) + (this.g_F * this.b_bz.a())), (((-this.g_F) * this.b_bz.b()) + (this.h_F * this.b_bz.a())), this.b_bz.c());
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 1
    public void g() {
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void h() {
        this.e_Z = true;
        return;
    }
    // bytecode 636 bytes, max_stack 5, max_locals 7
    public int a(float v1) {
        int v2 = 0;
        this.a_ct.a(this.a_di.a(), this.a_bz);
        this.o.b((-this.a_di.a().c()), (-this.a_bz.c()), 0.0f);
        ObfAu.a.a(this.a_di.a(), this.a_bz);
        ObfAu.a_bz.b((-this.a_di.a().c()), (-this.a_bz.c()), 0.0f);
        this.k();
        if (this.a_bs.a() == 0) goto L634;
        v1 = ((float) this);
        if (fcmpl(this.a_di.j(), 1.0f) >= 0) goto L141;
        if (Settings.m != 2) goto L141;
        if (ObfCl.f_Z != 0) goto L141;
        jt1 = 0.800000011920929f; /* join L143 from L136 */
        goto L143;
        L141:
        jt1 = 0.5f; /* join L143 from L141 */
        L143:
        v1 = 0.30000001192092896f;
        float v4 = jt1;
        Plane v3 = ObfAu.b;
        v2 = ((int) v1);
        v1 = ((float) this);
        float v5 = Vec2.a(this.b_bz, v3.a());
        float v6 = v1.b_bz.d();
        v6 = (0.20000000298023224f + ((v1.a().k() - v6) / v1.a().k()));
        if (fcmpg((0.20000000298023224f + ((v1.a().k() - v6) / v1.a().k())), 1.0f) <= 0) goto L205;
        v6 = 1.0f;
        L205:
        v1.c_z.b((v1.b_bz.a() - ((v5 * 1.0f) * v3.a())), (v1.b_bz.b() - ((v5 * 1.0f) * v3.b())));
        v1.c_z.a();
        v5 = ((v1.c_z.a() * v3.a()) + (v1.c_z.b() * v3.b()));
        v5 = (1.0f - java.lang.Math.abs(v5));
        v5 = ((1.0f - java.lang.Math.abs(v5)) + v6);
        v5 = (((1.0f - java.lang.Math.abs(v5)) + v6) / 2.0f);
        v1.c_z.a((((v3.a() * v5) * 4.0f) * v2), (((v3.b() * v5) * 4.0f) * v2));
        v2 = ((int) (v4 * v1.b_bz.d()));
        if (fcmpl((v4 * v1.b_bz.d()), 2.0f) >= 0) goto L350;
        v2 = ((int) 2.0f);
        L350:
        v1.c_z.a();
        v1.c_z.c(v2);
        v2 = ((int) v1.b_bz.c());
        if (v1.j == 0) goto L444;
        if (v1.a_bj == null) goto L444;
        if (fcmpg(v1.a_bj.c(), 0.0f) == 0) goto L444;
        v1.i();
        v2 = ((int) ((-((v1.a_bj.a() * v1.c_z.a()) + (v1.a_bj.b() * v1.c_z.b()))) / v1.a_bj.c()));
        L444:
        v1.a_di.b(v1.c_z.a(), v1.c_z.b(), v2);
        v1.c_z.b(((v1.h_F * v1.c_z.b()) + (v1.g_F * v1.c_z.a())), (((-v1.g_F) * v1.c_z.b()) + (v1.h_F * v1.c_z.a())));
        v1.a_di.b(v1.c_z.a(), v1.c_z.b());
        v2 = ((int) ((0.30000001192092896f * v1.a_di.o()) * v1.a_di.n()));
        if (fcmpl(((0.30000001192092896f * v1.a_di.o()) * v1.a_di.n()), 1.5f) >= 0) goto L580;
        if (fcmpg(v2, 0.0f) <= 0) goto L580;
        v2 = ((int) 1.5f);
        L580:
        if (fcmpg(v2, -1.5f) <= 0) goto L596;
        if (fcmpl(v2, 0.0f) >= 0) goto L596;
        v2 = ((int) -1.5f);
        L596:
        if (fcmpg(v1.f.a(), 0.0f) < 0) goto L619;
        v1.a_di.i(v2);
        goto L628;
        L619:
        v1.a_di.i((-v2));
        L628:
        v1.a();
        v2 = 1;
        L634:
        return v2;
    }
    // bytecode 26 bytes, max_stack 4, max_locals 1
    public void i() {
        this.a_bj = this.a_bs.a(this.a_di.b(), this.a_di.c());
        return;
    }
    // bytecode 385 bytes, max_stack 5, max_locals 7
    public void a(Plane v1, Vec3 v2, float v3, float v4, Vec3 v5) {
        ObfCl.n.a(v2, this.b_bz);
        float v6 = (-v1.a(ObfCl.n));
        this.c_z.a(v1.a());
        this.c_z.c((v6 * 2.0f));
        this.c_z.a(ObfCl.n.a(), ObfCl.n.b());
        this.c_z.a(this.c_z, v2);
        this.c_z.a();
        this.c_z.c((this.b_bz.d() * v3));
        this.c_z.c((v5.a() * (0.75f - v3)), (v5.b() * (1.0f - v3)));
        v1 = ((Plane) this.b_bz.c());
        if (this.j == 0) goto L202;
        if (this.a_bj == null) goto L202;
        if (fcmpg(this.a_bj.c(), 0.0f) == 0) goto L202;
        this.i();
        v1 = ((Plane) ((-((this.a_bj.a() * this.c_z.a()) + (this.a_bj.b() * this.c_z.b()))) / this.a_bj.c()));
        L202:
        this.a_di.b(this.c_z.a(), this.c_z.b(), v1);
        this.c_z.b(((this.h_F * this.c_z.b()) + (this.g_F * this.c_z.a())), (((-this.g_F) * this.c_z.b()) + (this.h_F * this.c_z.a())));
        this.a_di.b(this.c_z.a(), this.c_z.b());
        v1 = ((Plane) ((v4 * this.a_di.o()) * this.a_di.n()));
        if (fcmpl(((v4 * this.a_di.o()) * this.a_di.n()), 1.5f) >= 0) goto L338;
        if (fcmpg(v1, 0.0f) <= 0) goto L338;
        v1 = ((Plane) 1.5f);
        L338:
        if (fcmpg(v1, -1.5f) <= 0) goto L354;
        if (fcmpl(v1, 0.0f) >= 0) goto L354;
        v1 = ((Plane) -1.5f);
        L354:
        if (fcmpg(this.f.a(), 0.0f) < 0) goto L375;
        this.a_di.i(v1);
        return;
        L375:
        this.a_di.i((-v1));
        return;
    }
    // bytecode 383 bytes, max_stack 7, max_locals 5
    public boolean a(ObfCl v1, boolean v2) {
        ObfCl v4 = this;
        if (this.b_Z != 0) goto L21;
        v4 = this;
        Vec3 v3 = this.a_bz;
        goto L32;
        L21:
        v4 = this;
        v3 = this.a_di.a();
        L32:
        v4 = v1;
        if (v1.b_Z != 0) goto L54;
        v4 = v1;
        v4 = ((ObfCl) v1.a_bz);
        goto L66;
        L54:
        v4 = v1;
        v4 = ((ObfCl) v1.a_di.a());
        L66:
        v3 = ((Vec3) Vec2.b(v3, v4));
        if (fcmpl(Vec2.b(v3, v4), 0.8999999761581421f) >= 0) goto L381;
        v1.d();
        this.a();
        v1.a();
        if (v2 != 0) goto L98;
        return 1;
        L98:
        v4 = this;
        v4 = v1;
        v2 = ((boolean) Vec3.a(this.a_di.a(), v1.a_di.a()));
        v4 = this;
        v4 = this;
        this.c_bz.a(this.a_bz, this.a_di.a(), 0.0f);
        v4 = v1;
        v4 = v1;
        this.d_bz.a(v1.a_bz, v1.a_di.a(), 0.0f);
        this.a_ct.a(this.d_bz, this.c_bz);
        if (fcmpl((v2 - v3), 0.10000000149011612f) >= 0) goto L275;
        v4 = this;
        if (fcmpl(this.a_di.j(), 0.10000000149011612f) >= 0) goto L275;
        v4 = v1;
        if (fcmpl(v1.a_di.j(), 0.10000000149011612f) >= 0) goto L275;
        v4 = v1;
        this.a(this.a_ct, this.c_bz, 1.0f, 0.5f, v1.b_bz);
        v4 = this;
        v1.a(this.a_ct, this.d_bz, 1.0f, 0.5f, this.b_bz);
        goto L321;
        L275:
        v4 = v1;
        this.a(this.a_ct, this.c_bz, 0.10000000149011612f, 0.5f, v1.b_bz);
        v4 = this;
        v1.a(this.a_ct, this.d_bz, 0.10000000149011612f, 0.5f, this.b_bz);
        L321:
        v4 = this;
        v4 = v1;
        if (fcmpg(this.j_F, v1.j_F) <= 0) goto L379;
        v4 = this;
        v4 = v1;
        if (dcmpl(((double) (this.a_di.d() - v1.a_di.d())), 0.3) >= 0) goto L379;
        v1 = ((ObfCl) 0.25f);
        v1.c_F = 0.25f;
        L379:
        return 1;
        L381:
        return 0;
    }
    // bytecode 121 bytes, max_stack 3, max_locals 5
    public void l(float v1) {
        ObfCl v2 = this;
        if (this.b_Z == 0) goto L10;
        return;
        L10:
        v2 = ((ObfCl) MeshCache.a(this.a_di.m()));
        float v3 = (this.a_di.m() + (this.f_F * v1));
        int v4 = MeshCache.a((this.a_di.m() + (this.f_F * v1)));
        if (fcmpl(this.a_di.j(), this.a().a()) >= 0) goto L77;
        if (v2 == 0) goto L77;
        if (v4 == 0) goto L77;
        if (v2 == v4) goto L77;
        v3 = 0.0f;
        L77:
        v2 = ((ObfCl) ((float) java.lang.Math.sin(((double) (this.a_di.k() + (v1 * v3))))));
        v1 = ((float) java.lang.Math.cos(((double) (this.a_di.k() + (v1 * v3)))));
        this.b_z.b(v2, v1);
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean b() {
        return this.b_Z;
    }
    // bytecode 40 bytes, max_stack 5, max_locals 2
    public void a() {
        this.b_Z = true;
        ObfCl v1 = this;
        v1 = this;
        v1 = this;
        this.a_bz.b(this.a_di.b(), this.a_di.c(), this.a_di.d());
        return;
    }
    // bytecode 18 bytes, max_stack 2, max_locals 1
    public int a() {
        return ((this.g_I * this.a_bs.a()) + this.f_I);
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int b() {
        return this.e_I;
    }
    // bytecode 323 bytes, max_stack 5, max_locals 4
    public void d(float v1) {
        this.b_F = 0.0f;
        this.a_di.b(this.b_bz.a(), this.b_bz.b(), this.b_bz.c());
        this.d_Z = false;
        int v2 = this.a_bs.a(this.a_di.b(), this.a_di.c(), this.a_bz.a(), this.a_bz.b());
        if (this.a_bs.a(this.a_di.b(), this.a_di.c(), this.a_bz.a(), this.a_bz.b()) < 0) goto L96;
        this.e_I = this.c;
        this.f_I = v2;
        this.d_Z = true;
        L96:
        this.a_di.a(this.a_bz.a(), this.a_bz.b(), this.a_bz.c(), this.j);
        v2 = MeshCache.a(this.a_di.m());
        this.a_di.j((this.f_F * v1));
        int v3 = MeshCache.a(this.a_di.m());
        if (fcmpl(this.a_di.j(), this.a().a()) >= 0) goto L202;
        if (v2 == 0) goto L202;
        if (v3 == 0) goto L202;
        if (v2 == v3) goto L202;
        this.a_di.i(0.0f);
        L202:
        if (this.k_Z == 0) goto L253;
        this.h = true;
        this.a_di.c(MeshCache.b(((double) this.e_bz.b())));
        this.a_di.a(MeshCache.b(((double) this.e_bz.a())));
        goto L278;
        L253:
        if (this.h == 0) goto L268;
        this.h = false;
        goto L278;
        L268:
        this.a_di.a(0.30000001192092896);
        L278:
        this.a_di.f(v1);
        this.a_di.k((v1 * (this.a_di.m() + this.a_x.x())));
        this.a_di.b();
        this.b_F = 0.0f;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public CameraState a() {
        return this.a_di;
    }
    // bytecode 315 bytes, max_stack 4, max_locals 8
    public void a(float v1, float v2, float v3, ObfR v4) {
        float v5 = 0.0f;
        float v6 = 0.0f;
        if (ObfR.l <= 0) goto L177;
        if (this.l_I != 0) goto L42;
        v5 = (0.0f + (0.30000001192092896f * ObfAr.c));
        v6 = (0.0f + (-0.10000000149011612f * ObfAr.c));
        goto L195;
        L42:
        if (this.l_I != 1) goto L73;
        v5 = (0.0f + (0.30000001192092896f * ObfAr.c));
        v6 = (0.0f + (0.10000000149011612f * ObfAr.c));
        goto L195;
        L73:
        if (this.l_I != 2) goto L94;
        v6 = (0.0f + (-0.10000000149011612f * ObfAr.c));
        goto L195;
        L94:
        if (this.l_I != 3) goto L115;
        v6 = (0.0f + (0.10000000149011612f * ObfAr.c));
        goto L195;
        L115:
        if (this.l_I != 4) goto L146;
        v5 = (0.0f - (0.30000001192092896f * ObfAr.c));
        v6 = (0.0f + (-0.10000000149011612f * ObfAr.c));
        goto L195;
        L146:
        if (this.l_I != 5) goto L195;
        v5 = (0.0f - (0.30000001192092896f * ObfAr.c));
        v6 = (0.0f + (0.10000000149011612f * ObfAr.c));
        goto L195;
        L177:
        if (v4.e_Z != 0) goto L195;
        v5 = (0.0f + (0.30000001192092896f * ObfAr.c));
        L195:
        v4 = ((ObfR) this.a_bs.a(this.a_bs.b(), this.a_bs.c()));
        v4 = ((ObfR) (2 - this.a_bs.a(this.a_bs.b(), this.a_bs.c()).a));
        float v7 = SysUtil.a(((float) (2 - v4)), v5, v6);
        v6 = SysUtil.b(((float) (2 - v4)), v5, v6);
        v5 = v7;
        this.a_di.a((v1 + v6), (v2 + v5), 0.0f);
        this.a_di.h(v3);
        this.a_at.a(this.a_di.b(), this.a_di.c(), this.a_di.d());
        this.j();
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public CarPhysics a() {
        return this.a_x;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void e(float v1) {
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec3 a() {
        return this.a_bz;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec3 b() {
        return this.b_bz;
    }
    // bytecode 53 bytes, max_stack 4, max_locals 2
    public void m(float v1) {
        this.b_F = (this.b_F + v1);
        if (fcmpg(this.b_F, 0.10000000149011612f) <= 0) goto L52;
        v1 = ((float) this);
        this.a_di.i(0.0f);
        v1 = ((float) this);
        this.a_di.b(0.0f, 0.0f, 0.0f);
        v1 = ((float) this);
        this.a_di.b(0.0f);
        L52:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec2 a() {
        return this.a_z;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean c() {
        return this.d_Z;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 1
    public int c() {
        if (this.m_Z == 0) goto L14;
        return (this.g_I - 1);
        L14:
        return m1;
    }
    // bytecode 215 bytes, max_stack 3, max_locals 3
    public void a(int v1, ObfR v2) {
        if (v2.e_Z != 0) goto L12;
        this.n_Z = false;
        L12:
        if (this.l_Z != 0) goto L46;
        if (this.n_Z != 0) goto L46;
        this.c = (this.c + v1);
        this.j_I = (this.j_I + v1);
        L46:
        this.m_Z = false;
        v1 = ((int) this);
        v1 = ((int) this.a_bs.a(this.a_di, this.k));
        if (fcmpl(this.a_bs.a(this.a_di, this.k), 0.0f) >= 0) goto L76;
        return;
        L76:
        v2 = ((ObfR) (v1 - this.a_F));
        if (fcmpg((v1 - this.a_F), 0.800000011920929f) <= 0) goto L103;
        this.g_I = (this.g_I - 1);
        goto L183;
        L103:
        if (fcmpl(v2, -0.8999999761581421f) < 0) goto L116;
        if (fcmpg(v1, 1.0f) <= 0) goto L183;
        L116:
        if (this.g_I != this.h_I) goto L173;
        if (this.i_I == 0) goto L145;
        if (this.i_I <= this.j_I) goto L153;
        L145:
        this.i_I = this.j_I;
        L153:
        this.j_I = 0;
        this.h_I = (this.h_I + 1);
        this.m_Z = true;
        L173:
        this.g_I = (this.g_I + 1);
        L183:
        this.a_F = v1;
        this.j_F = (((float) this.g_I) + this.a_F);
        if (this.g_I < 0) goto L214;
        this.n_Z = false;
        L214:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int d() {
        return this.j_I;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int e() {
        return this.c;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int f() {
        return this.i_I;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public float a() {
        return this.j_F;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int g() {
        return this.h_I;
    }
    // bytecode 82 bytes, max_stack 5, max_locals 2
    public void j() {
        this.a_at.a((((-this.a_di.k()) / 3.1415927410125732f) * 180.0f), 0.0f, 0.0f, 1.0f);
        this.a_at.b(((this.a_di.h() / 3.1415927410125732f) * 180.0f), 1.0f, 0.0f, 0.0f);
        ObfCl v1 = this;
        this.a_at.b(((((-this.a_di.i()) / 3.1415927410125732f) * 180.0f) + this.a_di.a_F), 0.0f, 1.0f, 0.0f);
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void k() {
        ObfAu.a_Z = true;
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 1
    public void b() {
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return 0;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int h() {
        return this.a;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int i() {
        return this.b;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean d() {
        return this.l_Z;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void l() {
        this.l_Z = true;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int j() {
        return this.g_I;
    }
    // bytecode 212 bytes, max_stack 5, max_locals 3
    public void a(DataOutputStream v1) {
        v1.writeLong(this.a_J);
        this.a_J = (this.a_J + 1L);
        ObfCl v2 = this;
        v1.writeFloat(this.a_di.a().a());
        v2 = this;
        v1.writeFloat(this.a_di.a().b());
        v2 = this;
        v1.writeFloat(this.a_di.a().c());
        v2 = this;
        v1.writeFloat(this.a_di.b().a());
        v2 = this;
        v1.writeFloat(this.a_di.b().b());
        v2 = this;
        v1.writeFloat(this.a_di.b().c());
        v2 = this;
        v1.writeFloat(this.a_di.k());
        v2 = this;
        v1.writeFloat(this.a_di.h());
        v2 = this;
        v1.writeFloat(this.a_di.i());
        v2 = this;
        v1.writeFloat(this.a_di.e());
        v2 = this;
        v1.writeFloat(this.a_di.l());
        v2 = this;
        v1.writeFloat(this.a_di.a().a());
        v2 = this;
        v1.writeFloat(this.a_di.a().b());
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void a(DataInputStream v1) {
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        this.c = v1;
        return;
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public void b(int v1) {
        this.a().a(v1);
        return;
    }
}

