// Generated by tools/jdeob.py from x/ar.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ar`.
// String constants: /models/ | /tex/ | <clinit> | <init> | Code | [Lz; | append | close | compareTo | indexOf | java/io/IOException | java/io/InputStream
// API references: java/io
public class ObfAr {
    public static float a;
    public static float b;
    public static float c;
    private ObfAm a_am;
    private Vec2[] a_arrLz;
    private int[] a_arrI;
    private int[] b_arrI;
    private float[] a_arrF;
    private boolean[] a_arrZ;
    private boolean[] b_arrZ;
    private String a_String;
    private boolean b_Z;
    private int a_I;
    private ObfA a_a;
    private static Plane a_ct;
    private static float d;
    private static float e;
    private static float f;
    private static float g;
    public static boolean a_Z;
    private String b_String;
    private String c_String;
    static {
        new byte[24]#1[0] = m1;
        new byte[24]#1[1] = 0;
        new byte[24]#1[2] = m1;
        new byte[24]#1[3] = 1;
        new byte[24]#1[4] = 0;
        new byte[24]#1[5] = m1;
        new byte[24]#1[6] = 0;
        new byte[24]#1[7] = 0;
        new byte[24]#1[8] = 0;
        new byte[24]#1[9] = 1;
        new byte[24]#1[10] = 0;
        new byte[24]#1[11] = 1;
        new byte[24]#1[12] = m1;
        new byte[24]#1[13] = 0;
        new byte[24]#1[14] = 1;
        new byte[24]#1[15] = m1;
        new byte[24]#1[16] = 0;
        new byte[24]#1[17] = 1;
        new byte[24]#1[18] = m1;
        new byte[24]#1[19] = 0;
        new byte[24]#1[20] = m1;
        new byte[24]#1[21] = 0;
        new byte[24]#1[22] = 0;
        new byte[24]#1[23] = 0;
        ObfAr.a = 7.0f;
        ObfAr.b = (1.0f * ObfAr.a);
        ObfAr.c = (2.0f * ObfAr.b);
        new Plane(); /* constructor */
        ObfAr.a_ct = new Plane();
        ObfAr.d = 0.0f;
        ObfAr.e = 0.0f;
        ObfAr.f = 0.0f;
        ObfAr.g = 0.0f;
        ObfAr.a_Z = false;
        return;
    }
    // bytecode 163 bytes, max_stack 4, max_locals 1
    public ObfAr() {
        super();
        new byte[16]#1[0] = 0;
        new byte[16]#1[1] = 0;
        new byte[16]#1[2] = 2;
        new byte[16]#1[3] = 0;
        new byte[16]#1[4] = 1;
        new byte[16]#1[5] = 1;
        new byte[16]#1[6] = 2;
        new byte[16]#1[7] = 2;
        new byte[16]#1[8] = 0;
        new byte[16]#1[9] = 2;
        new byte[16]#1[10] = 0;
        new byte[16]#1[11] = 2;
        new byte[16]#1[12] = 0;
        new byte[16]#1[13] = 0;
        new byte[16]#1[14] = 1;
        new byte[16]#1[15] = 1;
        this.a_am = null;
        this.a_arrLz = null;
        this.a_arrI = null;
        this.b_arrI = null;
        this.a_arrF = null;
        this.a_arrZ = null;
        this.b_arrZ = null;
        this.a_String = null;
        this.b_Z = false;
        this.a_I = 0;
        this.a_a = null;
        this.b_String = "";
        this.c_String = "";
        this.a_arrZ = new boolean[4]#2;
        this.b_arrZ = new boolean[4]#3;
        return;
    }
    // bytecode 10 bytes, max_stack 2, max_locals 2
    public ObfAr(String v1) {
        this();
        this.a_String = v1;
        return;
    }
    // bytecode 244 bytes, max_stack 6, max_locals 4
    public void a(boolean v1) {
        String v2 = this.b_String;
        if (this.b_String.compareTo("vl") != 0) goto L23;
        if (Settings.f() != 0) goto L23;
        v2 = "vl1";
        L23:
        int v3 = Settings.a_Z;
        Settings.a_Z = true;
        if (v1 != 0) goto L123;
        new java.lang.StringBuffer(); /* constructor */
        if (Settings.a_Z == 0) goto L62;
        jt1 = "p/"; /* join L64 from L57 */
        goto L64;
        L62:
        jt1 = "np/"; /* join L64 from L62 */
        L64:
        new java.lang.StringBuffer(); /* constructor */
        if (Settings.d == 0) goto L97;
        jt2 = "h/"; /* join L99 from L92 */
        goto L99;
        L97:
        jt2 = ""; /* join L99 from L97 */
        L99:
        this.a_am = ObfBb.a.a(new java.lang.StringBuffer().append("/models/").append(jt1).append(v2).toString(), new java.lang.StringBuffer().append("/tex/").append(jt2).append(this.c_String).toString(), false, true);
        goto L208;
        L123:
        new java.lang.StringBuffer(); /* constructor */
        if (Settings.a_Z == 0) goto L150;
        jt3 = "p/"; /* join L152 from L145 */
        goto L152;
        L150:
        jt3 = "np/"; /* join L152 from L150 */
        L152:
        new java.lang.StringBuffer(); /* constructor */
        if (Settings.d == 0) goto L185;
        jt4 = "h/"; /* join L187 from L180 */
        goto L187;
        L185:
        jt4 = ""; /* join L187 from L185 */
        L187:
        this.a_am = ObfBb.a.b(new java.lang.StringBuffer().append("/models/").append(jt3).append(v2).toString(), new java.lang.StringBuffer().append("/tex/").append(jt4).append(this.c_String).toString(), false, true);
        L208:
        this.a_am.b((ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f));
        Settings.a_Z = v3;
        ObfAr.a_Z = Settings.d;
        return;
    }
    // bytecode 500 bytes, max_stack 5, max_locals 4
    public void a(Textures v1) {
        /* try L481-L485 catch java.io.IOException -> L488 */
        ObfAr.a = 7.0f;
        if (Settings.m != 2) goto L23;
        if (ObfCl.f != 0) goto L23;
        ObfAr.a = 9.0f;
        L23:
        ObfAr.b = (1.0f * ObfAr.a);
        ObfAr.c = (2.0f * ObfAr.b);
        v1 = ((Textures) Resources.a(this.a_String));
        this.b_String = StreamReader.a(v1);
        this.c_String = StreamReader.a(v1);
        if (this.c_String.indexOf("texpack.png") < 0) goto L120;
        if (Settings.j != 2) goto L91;
        this.c_String = "ts.png";
        goto L120;
        L91:
        if (Settings.j != 3) goto L107;
        this.c_String = "td.png";
        goto L120;
        L107:
        if (Settings.j != 4) goto L120;
        this.c_String = "tf.png";
        L120:
        /* pop: StreamReader.a(v1); */
        int v3 = StreamReader.a(v1);
        ObfAr v2 = this;
        if (v3 <= 0) goto L144;
        v2.a_arrLz = new Vec2[v3]#1;
        L144:
        v3 = 0;
        L146:
        if (v3 >= this.a_arrLz.length) goto L200;
        new Vec2(((ObfAr.c * ((float) StreamReader.a(v1))) / 100.0f), ((ObfAr.c * ((float) StreamReader.a(v1))) / 100.0f)); /* constructor */
        v2 = ((ObfAr) new Vec2(((ObfAr.c * ((float) StreamReader.a(v1))) / 100.0f), ((ObfAr.c * ((float) StreamReader.a(v1))) / 100.0f)));
        this.a_arrLz[v3] = v2;
        v3 += 1;
        goto L146;
        L200:
        v3 = StreamReader.a(v1);
        v2 = this;
        if (v3 <= 0) goto L218;
        v2.a_arrI = new int[v3]#3;
        L218:
        v3 = 0;
        L220:
        if (v3 >= this.a_arrI.length) goto L245;
        this.a_arrI[v3] = StreamReader.a(v1);
        v3 += 1;
        goto L220;
        L245:
        v3 = StreamReader.a(v1);
        v2 = this;
        if (v3 <= 0) goto L263;
        v2.b_arrI = new int[v3]#4;
        L263:
        this.a_arrF = new float[this.b_arrI.length]#5;
        v2 = ((ObfAr) 0);
        L276:
        if (v2 >= this.b_arrI.length) goto L348;
        v3 = StreamReader.a(v1);
        if (StreamReader.a(v1) >= 100) goto L314;
        this.b_arrI[v2] = v3;
        this.a_arrF[v2] = 1000.0f;
        goto L342;
        L314:
        this.b_arrI[v2] = StreamReader.a(v1);
        this.a_arrF[v2] = ((ObfAr.c * ((float) (v3 - 100))) / 100.0f);
        L342:
        v2 += 1;
        goto L276;
        L348:
        v2 = ((ObfAr) 0);
        L350:
        if (v2 >= 4) goto L398;
        if (StreamReader.a(v1) == 0) goto L371;
        jt1 = 1; /* join L372 from L367 */
        goto L372;
        L371:
        jt1 = 0; /* join L372 from L371 */
        L372:
        this.a_arrZ[v2] = jt1;
        if (this.a_arrZ[v2] == 0) goto L392;
        this.a_I = (this.a_I + 1);
        L392:
        v2 += 1;
        goto L350;
        L398:
        if (StreamReader.a(v1) == 0) goto L439;
        v2 = ((ObfAr) 0);
        L407:
        if (v2 >= 4) goto L436;
        if (StreamReader.a(v1) == 0) goto L428;
        jt2 = 1; /* join L429 from L424 */
        goto L429;
        L428:
        jt2 = 0; /* join L429 from L428 */
        L429:
        this.b_arrZ[v2] = jt2;
        v2 += 1;
        goto L407;
        L436:
        goto L464;
        L439:
        v2 = ((ObfAr) 0);
        L441:
        if (v2 >= 4) goto L464;
        this.b_arrZ[v2] = this.a_arrZ[v2];
        v2 += 1;
        goto L441;
        L464:
        /* pop: StreamReader.a(v1); */
        new ObfA(v1); /* constructor */
        this.a_a = new ObfA(v1);
        v1.close();
        goto L489;
        /* pop: ex_488; */
        L489:
        this.a(false);
        this.b_Z = true;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return this.b_Z;
    }
    // bytecode 35 bytes, max_stack 5, max_locals 6
    public void a(ObfBq v1, int v2, float v3, float v4, float v5) {
        this.a_am.a((90.0f * ((float) v2)), 0.0f, 0.0f, 1.0f);
        this.a_am.a(v3, v4, 0.0f);
        v1.a(this.a_am);
        return;
    }
    // bytecode 326 bytes, max_stack 6, max_locals 5
    public boolean a(int v1, float v2, float v3) {
        if (this.a_arrI != null) goto L9;
        return 0;
        L9:
        int v4 = 0;
        L12:
        if (v4 >= (this.a_arrI.length / 2)) goto L324;
        ObfAr.d = this.a_arrLz[this.a_arrI[(v4 << 1)]].a();
        ObfAr.f = this.a_arrLz[this.a_arrI[(v4 << 1)]].b();
        ObfAr.e = this.a_arrLz[this.a_arrI[((v4 << 1) + 1)]].a();
        ObfAr.g = this.a_arrLz[this.a_arrI[((v4 << 1) + 1)]].b();
        if (v1 != 0) goto L157;
        ObfAr.a_ct.a(((ObfAr.c - ObfAr.d) + v2), ((ObfAr.c - ObfAr.f) + v3), ((ObfAr.c - ObfAr.e) + v2), ((ObfAr.c - ObfAr.g) + v3));
        goto L267;
        L157:
        if (v1 != 1) goto L199;
        ObfAr.a_ct.a((ObfAr.f + v2), ((ObfAr.c - ObfAr.d) + v3), (ObfAr.g + v2), ((ObfAr.c - ObfAr.e) + v3));
        goto L267;
        L199:
        if (v1 != 2) goto L233;
        ObfAr.a_ct.a((ObfAr.d + v2), (ObfAr.f + v3), (ObfAr.e + v2), (ObfAr.g + v3));
        goto L267;
        L233:
        ObfAr.a_ct.a(((ObfAr.c - ObfAr.f) + v2), (ObfAr.d + v3), ((ObfAr.c - ObfAr.g) + v2), (ObfAr.e + v3));
        L267:
        ObfAu.a.e(this.a_arrF[v4]);
        ObfAu.b = ObfAr.a_ct;
        if (ObfAu.a_Z == 0) goto L298;
        if (Plane.b() != 0) goto L310;
        L298:
        if (ObfAu.a_Z != 0) goto L318;
        if (Plane.a() == 0) goto L318;
        L310:
        ObfAu.b = ObfAr.a_ct;
        return 1;
        L318:
        v4 += 1;
        goto L12;
        L324:
        return 0;
    }
    // bytecode 18 bytes, max_stack 2, max_locals 2
    public boolean a(int v1) {
        if (v1 < 0) goto L9;
        if (v1 < 4) goto L11;
        L9:
        return 0;
        L11:
        return this.a_arrZ[v1];
    }
    // bytecode 18 bytes, max_stack 2, max_locals 2
    public boolean b(int v1) {
        if (v1 < 0) goto L9;
        if (v1 < 4) goto L11;
        L9:
        return 0;
        L11:
        return this.b_arrZ[v1];
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.b_Z = true;
        return;
    }
    // bytecode 19 bytes, max_stack 3, max_locals 3
    public float a(float v1, float v2) {
        if (this.a_a != null) goto L9;
        return 0.0f;
        L9:
        return this.a_a.a(v1, v2);
    }
    // bytecode 29 bytes, max_stack 5, max_locals 3
    public Rect a(float v1, float v2) {
        if (this.a_a != null) goto L19;
        return SysUtil.a.a(0.0f, 0.0f, -1.0f, 0.0f);
        L19:
        return this.a_a.a(v1, v2);
    }
    // bytecode 36 bytes, max_stack 2, max_locals 1
    public void b() {
        this.a_am = null;
        this.a_arrLz = null;
        this.a_arrI = null;
        this.b_arrI = null;
        this.a_arrF = null;
        this.a_arrZ = null;
        this.b_arrZ = null;
        return;
    }
    // bytecode 65 bytes, max_stack 5, max_locals 1
    public void c() {
        ObfAr.a = 7.0f;
        if (Settings.m != 2) goto L23;
        if (ObfCl.f != 0) goto L23;
        ObfAr.a = 9.0f;
        L23:
        ObfAr.b = (1.0f * ObfAr.a);
        ObfAr.c = (2.0f * ObfAr.b);
        this.a_am.b((ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f), (ObfAr.a + 0.009999999776482582f));
        return;
    }
}

