// Generated by tools/jdeob.py from x/o.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `o`.
// String constants: <init> | Code | java/io/DataInputStream | java/io/IOException | readFloat | readLong | StackMap
// API references: java/io
public class GhostCar extends ObfCl {
    private Vec3 e;
    private float d;
    private float e_F;
    private float f;
    private boolean h;
    private boolean i;
    private long a;
    private Vec3 f_bz;
    private float g;
    private float h_F;
    private float i_F;
    // bytecode 104 bytes, max_stack 6, max_locals 6
    public GhostCar(ObfCf v1, InputStream v2, int v3, ObfBs v4, int v5) {
        super(v1, v2, v3, v4, v5);
        this.e = null;
        this.d = 0.0f;
        this.e_F = 0.0f;
        this.f = 0.0f;
        this.h = false;
        this.i = false;
        this.a = 0L;
        this.f_bz = null;
        this.g = 0.0f;
        this.h_F = 0.0f;
        this.i_F = 0.0f;
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.e = new Vec3(0.0f, 0.0f, 0.0f);
        new Vec3(0.0f, 0.0f, 0.0f); /* constructor */
        this.f_bz = new Vec3(0.0f, 0.0f, 0.0f);
        return;
    }
    // bytecode 241 bytes, max_stack 5, max_locals 5
    public void a(DataInputStream v1) {
        float v2 = (this.g + 0.25f);
        long v3 = v1.readLong();
        if (lcmp(v1.readLong(), this.a) > 0) goto L23;
        return;
        L23:
        this.a = v3;
        this.h_F = (v2 - this.g);
        this.i_F = 0.0f;
        this.f_bz.b(((v1.readFloat() - this.a().b()) / this.h_F), ((v1.readFloat() - this.a().c()) / this.h_F), ((v1.readFloat() - this.a().d()) / this.h_F));
        this.g = v2;
        this.e.b(v1.readFloat(), v1.readFloat(), v1.readFloat());
        this.d = ((v1.readFloat() - this.a().k()) / this.h_F);
        this.e_F = ((v1.readFloat() - this.a().h()) / this.h_F);
        this.f = ((v1.readFloat() - this.a().i()) / this.h_F);
        this.a().b(v1.readFloat());
        this.a().d(v1.readFloat());
        this.a().a(v1.readFloat(), v1.readFloat());
        this.h = true;
        this.i = true;
        this.g = 0.0f;
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void a(float v1) {
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void b(float v1) {
        return;
    }
    // bytecode 113 bytes, max_stack 5, max_locals 2
    public void c(float v1) {
        if (this.h != 0) goto L18;
        this.c(v1);
        this.i = false;
        return;
        L18:
        this.b = false;
        this.a.a((this.f_bz.a() * v1), (this.f_bz.b() * v1), (this.f_bz.c() * v1));
        this.i_F = (this.i_F + v1);
        this.b.b(this.e.a(), this.e.b(), this.e.c());
        if (fcmpg(this.i_F, this.h_F) <= 0) goto L112;
        this.h = false;
        L112:
        return;
    }
    // bytecode 208 bytes, max_stack 5, max_locals 3
    public void d(float v1) {
        if (this.i != 0) goto L13;
        this.d(v1);
        return;
        L13:
        this.b = 0.0f;
        this.a.b(this.b.a(), this.b.b(), this.b.c());
        this.d = false;
        int v2 = this.a.a(this.a.b(), this.a.c(), this.a.a(), this.a.b());
        if (this.a.a(this.a.b(), this.a.c(), this.a.a(), this.a.b()) < 0) goto L109;
        this.e = this.c;
        this.f = v2;
        this.d = true;
        L109:
        this.a.a(this.a.a(), this.a.b(), this.a.c(), 1);
        this.a.g((this.f * v1));
        this.a.b(((double) (this.e_F * v1)));
        this.a.k((this.d * v1));
        this.a.b();
        this.b = 0.0f;
        if (fcmpg(this.i_F, this.h_F) <= 0) goto L207;
        this.i = false;
        L207:
        return;
    }
    // bytecode 15 bytes, max_stack 2, max_locals 1
    public void a() {
        this.a();
        this.h = false;
        this.i = false;
        return;
    }
}

