// Generated by tools/jdeob.py from x/dl.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `dl`.
// String constants: <init> | Code | drawImage | getClipHeight | getHeight | getWidth | javax/microedition/lcdui/Graphics | javax/microedition/lcdui/Image | StackMap
// API references: javax/microedition
public class ImageItem extends MenuItem {
    private Image a;
    private int b;
    private byte b_B;
    // bytecode 27 bytes, max_stack 6, max_locals 6
    public ImageItem(Widget v1, int v2, int v3, int v4, Font v5) {
        super(v1, 0, 0, v4, v5);
        this.a = null;
        this.b = 0;
        this.b_B = 0;
        return;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 4
    public void a(Image v1, int v2, byte v3) {
        this.a = v1;
        this.b = 5;
        this.b_B = v3;
        return;
    }
    // bytecode 57 bytes, max_stack 4, max_locals 1
    public int b() {
        if (this.a != null) goto L19;
        return this.a(this.a.b());
        L19:
        return ((this.a((this.a.b() - (this.b + this.a.getWidth()))) + this.b) + this.a.getWidth());
    }
    // bytecode 405 bytes, max_stack 7, max_locals 5
    public void a(Graphics v1, int v2, int v3, int v4) {
        this.h();
        if (this.b_B != 0) goto L195;
        this.a(v1, ((v2 + this.a.getWidth()) + this.b), v3, (v4 - (this.a.getWidth() + this.b)));
        if (Settings.l() != 0) goto L92;
        v1.drawImage(this.a, (v2 + this.e()), (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1), 20);
        return;
        L92:
        if (Settings.l() != 1) goto L143;
        v1.drawImage(this.a, (SysUtil.e_I - (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1)), (v2 + this.e()), 24);
        return;
        L143:
        if (Settings.l() != 3) goto L404;
        v1.drawImage(this.a, (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1), (v1.getClipHeight() - (v2 + this.e())), 36);
        return;
        L195:
        this.a(v1, v2, v3, (v4 - (this.a.getWidth() + this.b)));
        if (Settings.l() != 0) goto L276;
        v1.drawImage(this.a, (((v2 + this.e()) + this.b()) - this.a.getWidth()), (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1), 20);
        return;
        L276:
        if (Settings.l() != 1) goto L340;
        v1.drawImage(this.a, (SysUtil.e_I - (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1)), (((v2 + this.e()) + this.b()) - this.a.getWidth()), 24);
        return;
        L340:
        if (Settings.l() != 3) goto L404;
        v1.drawImage(this.a, (((v3 + this.f()) + ((this.a() - this.a.getHeight()) / 2)) - 1), (v1.getClipHeight() - (((v2 + this.e()) + this.b()) - this.a.getWidth())), 36);
        L404:
        return;
    }
    // bytecode 25 bytes, max_stack 3, max_locals 3
    public boolean a(int v1, int v2) {
        if (v2 < this.f()) goto L23;
        if (v2 >= (this.f() + this.a())) goto L23;
        return 1;
        L23:
        return 0;
    }
}

