// Generated by tools/jdeob.py from x/ag.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ag`.
// String constants: /images/i_s.png | <clinit> | <init> | Code | [Lbw; | createImage | java/io/IOException | javax/microedition/lcdui/Image | StackMap | javax/microedition/lcdui/Graphics
// API references: javax/microedition
public class ImageGrid extends Widget {
    private GridCell[] a;
    private static ImageGrid a_ag;
    public static ImageCell a_ci;
    public static ImageCell b;
    public static ImageCell c;
    public static ImageCell d;
    static {
        ImageGrid.a_ag = null;
        ImageGrid.a_ci = null;
        ImageGrid.b = null;
        ImageGrid.c = null;
        ImageGrid.d = null;
        return;
    }
    // bytecode 39 bytes, max_stack 6, max_locals 5
    public ImageGrid(int v1, int v2, int v3, int v4) {
        super(null, 0, 0, v3, 28);
        new GridCell[5]#1[0] = null;
        new GridCell[5]#1[1] = null;
        new GridCell[5]#1[2] = null;
        new GridCell[5]#1[3] = null;
        new GridCell[5]#1[4] = null;
        this.a = new GridCell[5]#1;
        return;
    }
    // bytecode 18 bytes, max_stack 3, max_locals 3
    public void a(GridCell v1, int v2) {
        if (v1 == null) goto L10;
        v1.a(0, v2);
        L10:
        this.a[0] = v1;
        return;
    }
    // bytecode 7 bytes, max_stack 2, max_locals 1
    public GridCell a() {
        return this.a[0];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 1
    public GridCell b() {
        return this.a[2];
    }
    // bytecode 19 bytes, max_stack 3, max_locals 3
    public void b(GridCell v1, int v2) {
        if (v1 == null) goto L11;
        v1.a(2, -7);
        L11:
        this.a[2] = v1;
        return;
    }
    // bytecode 141 bytes, max_stack 5, max_locals 5
    public void a(Graphics v1, int v2, int v3) {
        if (this.a[0] == null) goto L19;
        this.a[0].a(0);
        L19:
        if (this.a[1] == null) goto L38;
        this.a[1].a(1);
        L38:
        if (this.a[2] == null) goto L57;
        this.a[2].a(2);
        L57:
        if (this.a[3] == null) goto L76;
        this.a[3].a(3);
        L76:
        if (this.a[4] == null) goto L95;
        this.a[4].a(4);
        L95:
        int v4 = 0;
        L98:
        if (v4 >= 5) goto L140;
        if (this.a[v4] == null) goto L130;
        this.a[v4].a(v1, v2, (v3 - 12));
        L130:
        v4 = ((byte) (v4 + 1));
        goto L98;
        L140:
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 2
    public boolean a(int v1) {
        return 0;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int c() {
        return m1;
    }
    // bytecode 28 bytes, max_stack 4, max_locals 3
    public static void b(Graphics v0, int v1, int v2) {
        if (ImageGrid.a_ag != null) goto L9;
        ImageGrid.a();
        L9:
        ImageGrid.a_ag.e(SysUtil.e_I);
        ImageGrid.a_ag.a(v0, 0, v2);
        return;
    }
    // bytecode 139 bytes, max_stack 6, max_locals 1
    public static void a() {
        /* try L17-L112 catch java.io.IOException -> L115 */
        new ImageGrid(0, 0, SysUtil.e_I, 28); /* constructor */
        ImageGrid.a_ag = new ImageGrid(0, 0, SysUtil.e_I, 28);
        if (SysUtil.e_I > 400) goto L31;
        SysUtil.a_String_2 = "/images/i_s.png";
        L31:
        Image v0 = javax.microedition.lcdui.Image.createImage(Resources.a(SysUtil.a_String_2));
        new ImageCell(ImageGrid.a_ag, v0, 0); /* constructor */
        ImageGrid.a_ci = new ImageCell(ImageGrid.a_ag, v0, 0);
        new ImageCell(ImageGrid.a_ag, v0, 1); /* constructor */
        ImageGrid.b = new ImageCell(ImageGrid.a_ag, v0, 1);
        new ImageCell(ImageGrid.a_ag, v0, 2); /* constructor */
        new ImageCell(ImageGrid.a_ag, v0, 3); /* constructor */
        ImageGrid.c = new ImageCell(ImageGrid.a_ag, v0, 3);
        new ImageCell(ImageGrid.a_ag, v0, 4); /* constructor */
        ImageGrid.d = new ImageCell(ImageGrid.a_ag, v0, 4);
        goto L116;
        /* pop: ex_115; */
        L116:
        ImageGrid.a_ag.a(ImageGrid.a_ci, -6);
        ImageGrid.a_ag.b(ImageGrid.b, -7);
        return;
    }
    // bytecode 13 bytes, max_stack 1, max_locals 0
    public static ImageGrid a() {
        if (ImageGrid.a_ag != null) goto L9;
        ImageGrid.a();
        L9:
        return ImageGrid.a_ag;
    }
}

