// Generated by tools/jdeob.py from x/cv.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cv`.
// String constants: /campaign/campaign | /campaign/deluxe | <clinit> | <init> | Code | KORa | Key | [[Ljava/lang/String; | abs | append | close | compareTo
// API references: java/io java/util javax/microedition
public class MainCanvas extends javax.microedition.lcdui.game.GameCanvas implements java.lang.Runnable {
    private boolean b;
    private ObfBq a;
    private ObfAn a_an;
    private ObfR a_r;
    private ObfY a_y;
    private ObfY b_y;
    private Thread a_Thread;
    private boolean c;
    private Graphics a_Graphi;
    private ObfU a_u;
    private boolean d;
    private int b_I;
    private boolean e;
    public static volatile int a_I;
    private boolean f;
    private boolean g;
    private boolean h;
    private boolean i;
    private boolean j;
    private String a_String;
    private String b_String;
    private String c_String;
    private Image a_Image;
    private ObfBr a_br;
    public static boolean a_Z;
    private boolean k;
    private Image b_Image;
    private boolean l;
    private int c_I;
    private int d_I;
    static int vservDisplaybleSet;
    static Hashtable configHashTable;
    static {
        MainCanvas.a_I = 0;
        MainCanvas.a_Z = false;
        return;
    }
    // bytecode 146 bytes, max_stack 2, max_locals 1
    public MainCanvas() {
        super(0);
        this.b = false;
        this.a = null;
        this.a_an = null;
        this.a_r = null;
        this.a_y = null;
        this.b_y = null;
        this.a_Thread = null;
        this.c = false;
        this.a_Graphi = null;
        this.a_u = null;
        this.d = false;
        this.b_I = 0;
        this.e = false;
        this.f = false;
        this.g = false;
        this.h = false;
        this.i = false;
        this.j = false;
        this.a_String = null;
        this.b_String = null;
        this.c_String = null;
        this.a_Image = null;
        this.a_br = null;
        this.k = false;
        this.b_Image = null;
        this.l = false;
        this.c_I = 0;
        this.d_I = 0;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfBq a() {
        return this.a;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Graphics a() {
        return this.a_Graphi;
    }
    // bytecode 901 bytes, max_stack 10, max_locals 2
    public void H() {
        /* try L368-L556 catch java.lang.Exception -> L566 */
        /* try L368-L556 catch finally -> L600 */
        /* try L566-L590 catch finally -> L600 */
        /* try L859-L891 catch java.lang.Exception -> L894 */
        if (MainCanvas.a_I <= 0) goto L152;
        this.a_Graphi.setColor(7829367);
        this.a_Graphi.fillRect(((this.a_Graphi.getClipWidth() / 2) - 50), ((this.a_Graphi.getClipHeight() / 2) - 7), 100, 16);
        this.a_Graphi.setColor(5592405);
        this.a_Graphi.drawRect(((this.a_Graphi.getClipWidth() / 2) - 50), ((this.a_Graphi.getClipHeight() / 2) - 7), 100, 16);
        if (MainCanvas.a_I != 0) goto L101;
        return;
        L101:
        byte[] v1 = SysUtil.a((182 + MainCanvas.a_I));
        SysUtil.a.a(this.a_Graphi, v1, ((this.a_Graphi.getClipWidth() - SysUtil.a.a(v1)) / 2), ((this.a_Graphi.getClipHeight() / 2) - 5));
        return;
        L152:
        if (this.l == 0) goto L160;
        return;
        L160:
        this.l = true;
        this.a_Graphi.setClip(0, 0, this.getWidth(), this.getHeight());
        if ((Settings.m() % 2) != 1) goto L258;
        if (this.b_y == this.a_r) goto L258;
        if (this.a_Image == null) goto L226;
        if (this.a_Image.getWidth() == this.a_Graphi.getClipHeight()) goto L247;
        L226:
        this.a_Image = javax.microedition.lcdui.Image.createImage(this.a_Graphi.getClipHeight(), this.a_Graphi.getClipWidth());
        L247:
        this.a_Graphi = this.a_Image.getGraphics();
        L258:
        if (this.getHeight() != SysUtil.f) goto L278;
        if (this.getWidth() == SysUtil.e) goto L304;
        L278:
        SysUtil.f = this.getHeight();
        SysUtil.e = this.getWidth();
        this.a(this.getWidth(), this.getHeight());
        L304:
        if (this.b_y == null) goto L347;
        if (ObfCo.c() == 0) goto L323;
        if (ObfCo.b() != 0) goto L347;
        L323:
        if (this.h != 0) goto L347;
        if (MainCanvas.a_I != 0) goto L347;
        this.b_y.b(this.a_Graphi);
        L347:
        if (ObfR.a != 25) goto L368;
        if (this.k != 0) goto L368;
        if (Settings.m() != 0) goto L610;
        L368:
        if (ObfR.a != 25) goto L434;
        if (this.k == 0) goto L434;
        if (Settings.m() == 0) goto L434;
        if (this.b_Image != null) goto L417;
        this.b_Image = javax.microedition.lcdui.Image.createImage(this.a_Graphi.getClipWidth(), this.a_Graphi.getClipHeight());
        L417:
        this.a.a(this.b_Image.getGraphics());
        goto L445;
        L434:
        this.a.a(this.a_Graphi);
        L445:
        if (ObfR.a != 25) goto L475;
        if (Settings.m() == 0) goto L475;
        if (MainCanvas.a_I != 0) goto L475;
        this.a_r.j();
        goto L556;
        L475:
        if (this.b_y == null) goto L509;
        if (this.b_y != this.a_r) goto L509;
        if (MainCanvas.a_I != 0) goto L509;
        this.b_y.j();
        goto L556;
        L509:
        if (this.b_y == null) goto L541;
        if (MainCanvas.a_I != 0) goto L541;
        if (ObfCo.c() == 0) goto L534;
        if (ObfCo.b() != 0) goto L541;
        L534:
        this.b_y.j();
        L541:
        if (ObfCo.c() == 0) goto L556;
        if (MainCanvas.a_I != 0) goto L556;
        ObfCo.a();
        L556:
        this.a.a();
        goto L610;
        v1 = ((byte[]) ex_566);
        v1 = ((byte[]) ex_566);
        java.lang.System.out.println(v1.getMessage());
        java.lang.System.out.println(v1);
        v1.printStackTrace();
        this.a.a();
        goto L610;
        v1 = ((byte[]) ex_600);
        this.a.a();
        throw v1;
        L610:
        if (ObfR.a != 25) goto L657;
        if (Settings.m() == 0) goto L657;
        this.a_Graphi.drawRegion(this.b_Image, 0, 0, this.b_Image.getWidth(), this.b_Image.getHeight(), 6, 0, 0, 20);
        L657:
        if (this.b_y == null) goto L702;
        if (this.b_y != this.a_r) goto L702;
        if (this.h != 0) goto L702;
        if (MainCanvas.a_I != 0) goto L702;
        this.b_y.a(this.a_Graphi);
        goto L783;
        L702:
        if (ObfCo.c() != 0) goto L721;
        if (ObfCo.a() == 0) goto L721;
        ObfCo.a(this.a_Graphi);
        L721:
        if (this.b_y == null) goto L764;
        if (ObfCo.c() == 0) goto L740;
        if (ObfCo.b() != 0) goto L764;
        L740:
        if (this.h != 0) goto L764;
        if (MainCanvas.a_I != 0) goto L764;
        this.b_y.a(this.a_Graphi);
        L764:
        if (ObfCo.c() == 0) goto L783;
        if (MainCanvas.a_I != 0) goto L783;
        ObfCo.a(this.a_Graphi);
        L783:
        if (this.h == 0) goto L839;
        if (this.i != 0) goto L839;
        if (MainCanvas.a_I != 0) goto L839;
        ObfAg.a().a(ObfAg.a, -6);
        ObfAg.a().b(ObfAg.b, -7);
        ObfAg.b(this.a_Graphi, 0, (SysUtil.f - 28));
        L839:
        if ((Settings.m() % 2) != 1) goto L895;
        if (this.b_y == this.a_r) goto L895;
        this.a_Graphi.drawRegion(this.a_Image, 0, 0, this.a_Image.getWidth(), this.a_Image.getHeight(), 5, 0, 0, 20);
        goto L895;
        /* pop: ex_894; */
        L895:
        this.l = false;
        return;
    }
    // bytecode 13 bytes, max_stack 1, max_locals 0
    public static void a() {
        KORa.m_pCanvas.H();
        KORa.m_pCanvas.flushGraphics();
        return;
    }
    // bytecode 211 bytes, max_stack 2, max_locals 3
    public void run() {
        /* try L9-L187 catch java.lang.Exception -> L190 */
        L0:
        MainCanvas v1 = this;
        if (this.b == 0) goto L198;
        this.a_an.a();
        v1 = this;
        if (this.i == 0) goto L64;
        if (ObfCo.c() != 0) goto L64;
        ObfCo.b(1);
        if (v1.j != 0) goto L50;
        ObfCo.a(67);
        goto L55;
        L50:
        ObfCo.c(69);
        L55:
        ObfCo.c(0);
        v1.i = false;
        L64:
        ObfAn v2 = v1.a_an;
        v2 = ((ObfAn) (((float) v1.a_an.a_I) / 1000.0f));
        if (v1.b_y == null) goto L145;
        if (ObfCo.c() != 0) goto L145;
        if (v1.h != 0) goto L145;
        if (v1.b_y != v1.a_r) goto L130;
        if (ObfR.g() != 24) goto L130;
        if (fcmpg(v2, 1.0f) <= 0) goto L130;
        v1.F();
        goto L160;
        L130:
        v1.b_y.b(v2);
        v1.b_y.l();
        L145:
        ObfCo.a(v2);
        if (v1.g == 0) goto L160;
        v1.k();
        L160:
        if (this.c != 0) goto L175;
        this.H();
        this.flushGraphics();
        L175:
        this.c = false;
        java.lang.Thread.sleep(1L);
        java.lang.Thread.yield();
        goto L0;
        v1 = ((MainCanvas) ex_190);
        ex_190.printStackTrace();
        goto L0;
        L198:
        v1 = this;
        v1 = this;
        this.b = false;
        KORa.die();
        return;
    }
    // bytecode 44 bytes, max_stack 3, max_locals 3
    public void sizeChangedMainApp(int v1, int v2) {
        if ((Settings.m() % 2) != 1) goto L32;
        if (this.b_y == this.a_r) goto L32;
        SysUtil.a(v2, v1);
        this.a(v2, v1);
        return;
        L32:
        SysUtil.a(v1, v2);
        this.a(v1, v2);
        return;
    }
    // bytecode 12 bytes, max_stack 4, max_locals 3
    public void a(int v1, int v2) {
        this.a.a(v1, v2, 90.0f);
        return;
    }
    // bytecode 202 bytes, max_stack 5, max_locals 3
    public void b() {
        /* try L94-L174 catch java.lang.Exception -> L177 */
        /* try L0-L9 catch java.lang.Exception -> L12 */
        /* pop: KORa.self.getAppProperty("Key"); */
        goto L13;
        /* pop: ex_12; */
        L13:
        this.b = true;
        SysUtil.a(this);
        new ObfBq(); /* constructor */
        this.a = new ObfBq();
        SysUtil.g = ((java.lang.Integer) javax.microedition.m3g.Graphics3D.getProperties().get("numTextureUnits")).intValue();
        this.setFullScreenMode(1);
        this.a_Graphi = this.getGraphics();
        new ObfAn(); /* constructor */
        this.a_an = new ObfAn();
        this.sizeChanged(this.a_Graphi.getClipWidth(), this.a_Graphi.getClipHeight());
        MainCanvas v1 = this;
        MainCanvas v2 = v1;
        new ObfBd(v2); /* constructor */
        v1.a_y = new ObfBd(v2);
        v2.b_y = v2.a_y;
        v2.a(SysUtil.e, SysUtil.f);
        new ObfU(v2, "/campaign/campaign"); /* constructor */
        v2.a_u = new ObfU(v2, "/campaign/campaign");
        MainCanvas.a_Z = false;
        if (Settings.h() != 0) goto L174;
        ObfCo.c(0);
        ObfCo.c(1);
        ObfCo.b(1);
        ((ObfBd) v1.a_y).p();
        L174:
        goto L182;
        v1 = ((MainCanvas) ex_177);
        ex_177.printStackTrace();
        L182:
        new java.lang.Thread(this); /* constructor */
        this.a_Thread = new java.lang.Thread(this);
        this.a_Thread.start();
        return;
    }
    // bytecode 252 bytes, max_stack 3, max_locals 5
    public void c() {
        int v1 = m1;
        if (java.lang.System.getProperty("wireless.messaging.sms.smsc").startsWith("+420") == 0) goto L20;
        v1 = 0;
        goto L53;
        L20:
        if (java.lang.System.getProperty("wireless.messaging.sms.smsc").startsWith("+421") == 0) goto L38;
        v1 = 1;
        goto L53;
        L38:
        if (java.lang.System.getProperty("wireless.messaging.sms.smsc").startsWith("+48") == 0) goto L53;
        v1 = 2;
        L53:
        if (v1 < 0) goto L224;
        this.b_y = this.a_y;
        this.b_String = SysUtil.a[v1][1];
        this.a_String = SysUtil.a[v1][2];
        int v2 = KORa.rand.nextInt();
        int v3 = KORa.rand.nextInt();
        int v4 = KORa.rand.nextInt();
        if (v2 >= 0) goto L116;
        v2 = (-v2);
        L116:
        if (v3 >= 0) goto L123;
        v3 = (-v3);
        L123:
        if (v4 >= 0) goto L133;
        v4 = (-v4);
        L133:
        new java.lang.StringBuffer(); /* constructor */
        this.c_String = new java.lang.StringBuffer().append(v2).append("").append(v3).append("").append(v4).toString();
        new java.lang.StringBuffer(); /* constructor */
        this.a_String = new java.lang.StringBuffer().append(this.a_String).append(" ").append(this.c_String).toString();
        ObfCo.a(SysUtil.a[v1][0]);
        this.h = true;
        this.i = true;
        return;
        L224:
        this.b_y = this.a_y;
        ObfCo.b(1);
        ObfCo.a(66);
        ((ObfBd) this.a_y).o();
        return;
    }
    // bytecode 15 bytes, max_stack 1, max_locals 1
    public void d() {
        ObfCo.b(0);
        ((ObfBd) this.a_y).q();
        return;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 1
    public void e() {
        this.h = true;
        this.i = true;
        this.j = true;
        return;
    }
    // bytecode 169 bytes, max_stack 3, max_locals 4
    public void a(String v1) {
        /* try L17-L95 catch java.lang.Exception -> L158 */
        /* try L96-L157 catch java.lang.Exception -> L158 */
        new java.io.ByteArrayOutputStream(); /* constructor */
        java.io.ByteArrayOutputStream v2 = new java.io.ByteArrayOutputStream();
        new java.io.DataOutputStream(v2); /* constructor */
        java.io.DataOutputStream v3 = new java.io.DataOutputStream(v2);
        v3.writeByte(111);
        v3.writeUTF(v1);
        v3.writeUTF(java.lang.System.getProperty("wireless.messaging.sms.smsc"));
        v1 = ((String) ObfDj.a(Settings.c_String, 1, TouchButtons.a(v2.toByteArray())));
        v3.close();
        v2.close();
        new java.io.ByteArrayInputStream(v1); /* constructor */
        v1 = ((String) new java.io.ByteArrayInputStream(v1));
        new java.io.DataInputStream(v1); /* constructor */
        v1 = ((String) new java.io.DataInputStream(v1));
        if (Settings.a(new java.io.DataInputStream(v1)).compareTo("OK") == 0) goto L96;
        ObfCo.c(15);
        return;
        L96:
        v2 = ((java.io.ByteArrayOutputStream) Settings.b(v1));
        this.b_String = Settings.a(v1);
        this.a_String = Settings.a(v1);
        this.c_String = Settings.a(v1);
        ObfCo.a(v2);
        if (this.b_String.length() <= 1) goto L153;
        this.h = true;
        this.i = true;
        goto L168;
        L153:
        this.d();
        return;
        /* pop: ex_158; */
        ObfCo.c(15);
        this.d();
        L168:
        return;
    }
    // bytecode 20 bytes, max_stack 1, max_locals 1
    public void f() {
        if (this.a_u == null) goto L19;
        this.a_u.o();
        ObfCo.c(26);
        L19:
        return;
    }
    // bytecode 194 bytes, max_stack 2, max_locals 2
    public void keyPressed(int v1) {
        if (this.f == 0) goto L8;
        return;
        L8:
        if (ObfCo.c() != 0) goto L167;
        if (this.h == 0) goto L167;
        if (ObfBh.a(v1) != -11) goto L40;
        this.h = false;
        this.d();
        return;
        L40:
        if (SysUtil.a(v1) == -5) goto L67;
        if (SysUtil.a(v1) == -6) goto L67;
        if (SysUtil.b(v1) != 8) goto L166;
        L67:
        ObfCo.b(0);
        if (this.j != 0) goto L130;
        if (SysUtil.a(this.b_String, this.a_String) == 0) goto L109;
        Settings.c(this.c_String);
        ObfCo.c(68);
        this.e();
        return;
        L109:
        ObfCo.c(72);
        this.h = false;
        ((ObfBd) this.a_y).q();
        return;
        L130:
        this.h = false;
        this.d();
        if (Settings.j() == 0) goto L166;
        this.E();
        this.a_u.i();
        ((ObfBd) this.a_y).v();
        L166:
        return;
        L167:
        if (ObfCo.c() == 0) goto L178;
        ObfCo.d(v1);
        return;
        L178:
        if (this.b_y == null) goto L193;
        this.b_y.a(v1);
        L193:
        return;
    }
    // bytecode 27 bytes, max_stack 2, max_locals 2
    public void keyReleased(int v1) {
        if (ObfCo.c() == 0) goto L11;
        ObfCo.e(v1);
        return;
        L11:
        if (this.b_y == null) goto L26;
        this.b_y.c(v1);
        L26:
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void g() {
        this.b = false;
        return;
    }
    // bytecode 35 bytes, max_stack 2, max_locals 1
    public void h() {
        this.a_y.g();
        this.c = true;
        this.a_u.h();
        this.b_y = this.a_u;
        this.a_an.a();
        return;
    }
    // bytecode 60 bytes, max_stack 5, max_locals 1
    public void i() {
        this.a_y.g();
        this.c = true;
        this.a_u.b();
        new ObfBr(this, "/campaign/deluxe"); /* constructor */
        this.a_br = new ObfBr(this, "/campaign/deluxe");
        this.a_br.h();
        this.b_y = this.a_br;
        this.a_an.a();
        MainCanvas.a_Z = true;
        return;
    }
    // bytecode 42 bytes, max_stack 2, max_locals 1
    public void j() {
        this.a_br.b();
        this.a_br.s();
        this.a_br = null;
        MainCanvas.a_Z = false;
        java.lang.System.gc();
        this.a_u.a();
        this.b_y = this.a_y;
        return;
    }
    // bytecode 405 bytes, max_stack 4, max_locals 2
    public void k() {
        /* try L124-L130 catch java.lang.Exception -> L133 */
        /* try L0-L91 catch java.lang.Exception -> L399 */
        /* try L92-L105 catch java.lang.Exception -> L399 */
        /* try L106-L398 catch java.lang.Exception -> L399 */
        if (this.d != 0) goto L114;
        if (this.b_y != this.a_u) goto L92;
        if (Settings.b() != 0) goto L92;
        ObfCo.c(33);
        ObfCo.c(63);
        ObfCo.c(41);
        if (Settings.k() >= 3) goto L51;
        jt1 = 34; /* join L53 from L46 */
        goto L53;
        L51:
        jt1 = 35; /* join L53 from L51 */
        L53:
        ObfCo.c(jt1);
        ObfCo.c(36);
        ObfCo.c(37);
        if (Settings.k() >= 2) goto L78;
        ObfCo.c(46);
        L78:
        ObfCo.c(38);
        this.g = true;
        Settings.a();
        return;
        L92:
        if (this.g == 0) goto L111;
        if (ObfCo.a() <= 0) goto L106;
        return;
        L106:
        this.g = false;
        L111:
        MainCanvas.a();
        L114:
        this.b_I = 0;
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L134;
        /* pop: ex_133; */
        L134:
        this.a_y.g();
        this.c = true;
        if (this.d != 0) goto L210;
        ObfCo.b();
        this.a_u.b();
        if (this.a_br == null) goto L177;
        this.a_br.b();
        L177:
        this.a_y.s();
        this.a_y = null;
        if (Settings.e != 0) goto L198;
        java.lang.System.gc();
        L198:
        new ObfBh(this); /* constructor */
        this.a_y = new ObfBh(this);
        L210:
        if (ObfR.f != 0) goto L231;
        new ObfCu(this); /* constructor */
        this.a_r = new ObfCu(this);
        goto L361;
        L231:
        if (ObfR.f != 1) goto L253;
        new ObfR(this); /* constructor */
        this.a_r = new ObfR(this);
        goto L361;
        L253:
        if (ObfR.f != 2) goto L275;
        new CareerMap(this); /* constructor */
        this.a_r = new CareerMap(this);
        goto L361;
        L275:
        if (ObfR.f != 3) goto L297;
        new ObfCd(this); /* constructor */
        this.a_r = new ObfCd(this);
        goto L361;
        L297:
        if (ObfR.f != 4) goto L319;
        new ObfAc(this); /* constructor */
        this.a_r = new ObfAc(this);
        goto L361;
        L319:
        if (ObfR.f != 5) goto L341;
        new ObfBv(this); /* constructor */
        this.a_r = new ObfBv(this);
        goto L361;
        L341:
        if (ObfR.f != 6) goto L361;
        new CarSelect(this); /* constructor */
        this.a_r = new CarSelect(this);
        L361:
        this.a_r.d();
        this.c = false;
        this.a_an.a();
        this.b_y = this.a_r;
        this.a(SysUtil.e, SysUtil.f);
        return;
        java.lang.Exception v1 = ex_399;
        ex_399.printStackTrace();
        return;
    }
    // bytecode 8 bytes, max_stack 1, max_locals 0
    public static void l() {
        ObfCo.c();
        ObfCo.b(1);
        return;
    }
    // bytecode 25 bytes, max_stack 1, max_locals 1
    public void m() {
        ((ObfBd) this.a_y).u();
        ObfCo.c(4);
        ((ObfBd) this.a_y).r();
        return;
    }
    // bytecode 16 bytes, max_stack 1, max_locals 1
    public void n() {
        ObfCo.c(45);
        ((ObfBd) this.a_y).t();
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void o() {
        this.q();
        return;
    }
    // bytecode 16 bytes, max_stack 1, max_locals 1
    public void p() {
        ObfCo.c(45);
        ((ObfBd) this.a_y).t();
        return;
    }
    // bytecode 27 bytes, max_stack 1, max_locals 1
    public void q() {
        ObfCo.c(10);
        ObfCo.b(0);
        if (Settings.h() != 0) goto L26;
        Settings.e(1);
        Settings.b();
        this.E();
        L26:
        return;
    }
    // bytecode 10 bytes, max_stack 1, max_locals 1
    public void r() {
        ObfCo.c(9);
        this.q();
        return;
    }
    // bytecode 30 bytes, max_stack 2, max_locals 1
    public void s() {
        this.a_y.l();
        this.a_y.g();
        this.b_y = this.a_r;
        this.b_y.h();
        return;
    }
    // bytecode 116 bytes, max_stack 2, max_locals 2
    public void t() {
        /* try L0-L109 catch java.lang.Exception -> L110 */
        this.f = true;
        if (this.b_I != 1) goto L26;
        ((CareerScreen) this.a_r).a();
        goto L104;
        L26:
        if (this.b_I == 0) goto L49;
        if (this.b_I == 2) goto L49;
        if (this.b_I != 3) goto L104;
        L49:
        this.d = true;
        this.w();
        if (this.b_I != 0) goto L72;
        this.k();
        goto L99;
        L72:
        if (this.b_I != 2) goto L87;
        this.B();
        goto L99;
        L87:
        if (this.b_I != 3) goto L99;
        this.C();
        L99:
        this.d = false;
        L104:
        this.f = false;
        return;
        java.lang.Exception v1 = ex_110;
        ex_110.printStackTrace();
        return;
    }
    // bytecode 76 bytes, max_stack 2, max_locals 1
    public void u() {
        /* try L15-L21 catch java.lang.Exception -> L24 */
        this.f = true;
        this.d = true;
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L25;
        /* pop: ex_24; */
        L25:
        ((ObfBh) this.a_y).a(null);
        ((CareerScreen) this.a_r).t();
        if (Settings.e != 0) goto L55;
        java.lang.System.gc();
        L55:
        this.a_an.a();
        this.b_y = this.a_r;
        this.f = false;
        return;
    }
    // bytecode 15 bytes, max_stack 2, max_locals 1
    public void v() {
        this.e = true;
        this.w();
        this.e = false;
        return;
    }
    // bytecode 686 bytes, max_stack 5, max_locals 2
    public void w() {
        /* try L28-L34 catch java.lang.Exception -> L37 */
        ObfR.a = 21;
        this.f = true;
        if (this.b_I != 1) goto L23;
        this.x();
        return;
        L23:
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L38;
        /* pop: ex_37; */
        L38:
        ((ObfBh) this.a_y).a(null);
        int v1 = 0;
        if (this.d != 0) goto L126;
        if (this.e != 0) goto L126;
        if (this.b_I != 0) goto L108;
        if (MainCanvas.a_Z == 0) goto L93;
        v1 = this.a_br.a(this.a_r);
        goto L126;
        L93:
        v1 = this.a_u.a(this.a_r);
        goto L126;
        L108:
        if (this.b_I != 3) goto L126;
        ObfW.a.a(this.a_r);
        L126:
        this.a_r.f();
        if (this.d != 0) goto L680;
        this.a_y.s();
        this.a_y = null;
        java.lang.System.gc();
        if (MainCanvas.a_Z == 0) goto L178;
        if (this.b_I != 0) goto L178;
        this.a_br.a();
        goto L185;
        L178:
        this.a_u.a();
        L185:
        new ObfBd(this); /* constructor */
        this.a_y = new ObfBd(this);
        if (this.b_I != 0) goto L654;
        if (MainCanvas.a_Z != 0) goto L220;
        ((ObfBd) this.a_y).k();
        L220:
        if (v1 == 0) goto L626;
        if (v1 <= 0) goto L235;
        ObfCo.c(v1);
        goto L623;
        L235:
        if (v1 != m1) goto L319;
        new javax.microedition.m3g.Transform(); /* constructor */
        v1 = ((int) new javax.microedition.m3g.Transform());
        new javax.microedition.m3g.Transform().setIdentity();
        v1.postTranslate(0.0f, -0.550000011920929f, -2.0f);
        v1.postRotate(180.0f, 0.0f, 1.0f, 0.0f);
        v1.postRotate(90.0f, 1.0f, 0.0f, 0.0f);
        v1.postRotate(300.0f, 0.0f, 0.0f, 1.0f);
        ObfCo.a(47, ObfBd.a.a(0, 0.0f), v1);
        ObfCo.a(48, ObfBd.a.a(0, 0.0f), v1);
        goto L623;
        L319:
        if (v1 != -2) goto L412;
        new javax.microedition.m3g.Transform(); /* constructor */
        v1 = ((int) new javax.microedition.m3g.Transform());
        new javax.microedition.m3g.Transform().setIdentity();
        v1.postTranslate(0.0f, -0.550000011920929f, -1.7999999523162842f);
        v1.postRotate(180.0f, 0.0f, 1.0f, 0.0f);
        v1.postRotate(90.0f, 1.0f, 0.0f, 0.0f);
        v1.postRotate(235.0f, 0.0f, 0.0f, 1.0f);
        v1.postScale(0.800000011920929f, 1.0f, 1.0f);
        ObfCo.a(39, ObfBd.a.a(2, 0.0f), v1);
        ObfCo.a(42, ObfBd.a.a(2, 0.0f), v1);
        goto L623;
        L412:
        if (v1 != -3) goto L483;
        new javax.microedition.m3g.Transform(); /* constructor */
        v1 = ((int) new javax.microedition.m3g.Transform());
        new javax.microedition.m3g.Transform().setIdentity();
        v1.postTranslate(0.0f, -0.550000011920929f, -1.899999976158142f);
        v1.postRotate(180.0f, 0.0f, 1.0f, 0.0f);
        v1.postRotate(90.0f, 1.0f, 0.0f, 0.0f);
        v1.postRotate(125.0f, 0.0f, 0.0f, 1.0f);
        ObfCo.a(43, ObfBd.a.a(3, 0.0f), v1);
        goto L623;
        L483:
        if (v1 != -4) goto L554;
        new javax.microedition.m3g.Transform(); /* constructor */
        v1 = ((int) new javax.microedition.m3g.Transform());
        new javax.microedition.m3g.Transform().setIdentity();
        v1.postTranslate(0.0f, -0.550000011920929f, -1.899999976158142f);
        v1.postRotate(180.0f, 0.0f, 1.0f, 0.0f);
        v1.postRotate(90.0f, 1.0f, 0.0f, 0.0f);
        v1.postRotate(125.0f, 0.0f, 0.0f, 1.0f);
        ObfCo.a(73, ObfBd.a.a(5, 0.0f), v1);
        goto L623;
        L554:
        if (v1 != -5) goto L623;
        new javax.microedition.m3g.Transform(); /* constructor */
        v1 = ((int) new javax.microedition.m3g.Transform());
        new javax.microedition.m3g.Transform().setIdentity();
        v1.postTranslate(0.0f, -0.550000011920929f, -1.899999976158142f);
        v1.postRotate(180.0f, 0.0f, 1.0f, 0.0f);
        v1.postRotate(90.0f, 1.0f, 0.0f, 0.0f);
        v1.postRotate(125.0f, 0.0f, 0.0f, 1.0f);
        ObfCo.a(74, ObfBd.a.a(6, 0.0f), v1);
        L623:
        MainCanvas.a();
        L626:
        if (MainCanvas.a_Z == 0) goto L643;
        this.b_y = this.a_br;
        goto L680;
        L643:
        this.b_y = this.a_u;
        goto L680;
        L654:
        if (this.b_I != 3) goto L672;
        ((ObfBd) this.a_y).i();
        L672:
        this.b_y = this.a_y;
        L680:
        this.f = false;
        return;
    }
    // bytecode 86 bytes, max_stack 4, max_locals 1
    public void x() {
        /* try L10-L16 catch java.lang.Exception -> L19 */
        this.f = true;
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L20;
        /* pop: ex_19; */
        L20:
        ((ObfBh) this.a_y).a(null);
        this.a_r.f();
        this.a_y.s();
        this.a_y = null;
        java.lang.System.gc();
        new ObfBd(this); /* constructor */
        this.a_y = new ObfBd(this);
        this.a_u.a();
        this.b_y = this.a_y;
        this.f = false;
        return;
    }
    // bytecode 40 bytes, max_stack 2, max_locals 1
    public void y() {
        ((ObfBh) this.a_y).a(null);
        ((ObfBd) this.a_y).b();
        this.b_y = this.a_y;
        this.a_r.f();
        java.lang.System.gc();
        return;
    }
    // bytecode 62 bytes, max_stack 2, max_locals 1
    public void z() {
        this.b_y.g();
        this.k = true;
        if (Settings.m() != 0) goto L35;
        ((ObfBh) this.a_y).a(this.a_r);
        goto L46;
        L35:
        ((ObfBh) this.a_y).a(null);
        L46:
        this.b_y = this.a_y;
        this.b_y.h();
        return;
    }
    // bytecode 30 bytes, max_stack 2, max_locals 1
    public void A() {
        this.b_y.l();
        this.b_y.g();
        this.b_y = this.a_y;
        this.b_y.h();
        return;
    }
    // bytecode 16 bytes, max_stack 1, max_locals 1
    public ObfU a() {
        if (MainCanvas.a_Z == 0) goto L11;
        return this.a_br;
        L11:
        return this.a_u;
    }
    // bytecode 136 bytes, max_stack 4, max_locals 1
    public void B() {
        /* try L10-L16 catch java.lang.Exception -> L19 */
        this.b_I = 2;
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L20;
        /* pop: ex_19; */
        L20:
        this.a_y.g();
        this.c = true;
        if (this.d != 0) goto L79;
        this.a_u.b();
        this.a_y.s();
        this.a_y = null;
        if (Settings.e != 0) goto L67;
        java.lang.System.gc();
        L67:
        new ObfBh(this); /* constructor */
        this.a_y = new ObfBh(this);
        L79:
        new ObfH(this); /* constructor */
        this.a_r = new ObfH(this);
        if (this.d == 0) goto L108;
        ((ObfH) this.a_r).a();
        L108:
        this.a_r.d();
        this.c = false;
        this.a_an.a();
        this.b_y = this.a_r;
        return;
    }
    // bytecode 51 bytes, max_stack 5, max_locals 2
    public void a(boolean v1) {
        this.b_I = 1;
        this.b_y = null;
        new CareerScreen(this, v1); /* constructor */
        this.a_r = new CareerScreen(this, v1);
        this.a_r.d();
        this.c = false;
        this.a_an.a();
        this.b_y = this.a_r;
        return;
    }
    // bytecode 159 bytes, max_stack 5, max_locals 1
    public void C() {
        /* try L10-L16 catch java.lang.Exception -> L19 */
        this.b_I = 3;
        this.b_y = null;
        java.lang.Thread.sleep(100L);
        goto L20;
        /* pop: ex_19; */
        L20:
        if (this.d != 0) goto L67;
        this.a_u.b();
        this.a_y.s();
        this.a_y = null;
        if (Settings.e != 0) goto L55;
        java.lang.System.gc();
        L55:
        new ObfBh(this); /* constructor */
        this.a_y = new ObfBh(this);
        L67:
        if (ObfW.f != 0) goto L89;
        new ObfW(this, 0); /* constructor */
        this.a_r = new ObfW(this, 0);
        goto L131;
        L89:
        if (ObfW.f != 1) goto L112;
        new ObfW(this, 1); /* constructor */
        this.a_r = new ObfW(this, 1);
        goto L131;
        L112:
        if (ObfW.f != 2) goto L131;
        new ObfV(this); /* constructor */
        this.a_r = new ObfV(this);
        L131:
        this.a_r.d();
        this.c = false;
        this.a_an.a();
        this.b_y = this.a_r;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfY a() {
        return this.a_y;
    }
    // bytecode 75 bytes, max_stack 4, max_locals 1
    public void D() {
        /* try L0-L6 catch java.lang.Exception -> L9 */
        java.lang.Thread.sleep(100L);
        goto L10;
        L10:
        if (this.d != 0) goto L69;
        this.a_y.g();
        this.c = true;
        this.a_u.b();
        this.a_y.s();
        this.a_y = null;
        if (Settings.e != 0) goto L57;
        java.lang.System.gc();
        L57:
        new ObfBh(this); /* constructor */
        this.a_y = new ObfBh(this);
        L69:
        this.d = false;
        return;
    }
    // bytecode 29 bytes, max_stack 1, max_locals 2
    public void b(String v1) {
        if (Settings.a(v1) == 0) goto L28;
        this.E();
        this.a_u.i();
        ((ObfBd) this.a_y).v();
        L28:
        return;
    }
    // bytecode 47 bytes, max_stack 4, max_locals 1
    public void E() {
        this.b_y = null;
        this.a_y.s();
        this.a_y = null;
        if (Settings.e != 0) goto L26;
        java.lang.System.gc();
        L26:
        new ObfBd(this); /* constructor */
        this.a_y = new ObfBd(this);
        this.b_y = this.a_y;
        return;
    }
    // bytecode 107 bytes, max_stack 3, max_locals 4
    public void pointerDragged(int v1, int v2) {
        if (java.lang.Math.abs((v1 - this.c_I)) >= 20) goto L29;
        if (java.lang.Math.abs((v2 - this.d_I)) >= 20) goto L29;
        return;
        L29:
        if ((Settings.m() % 2) != 1) goto L63;
        if (this.b_y == this.a_r) goto L63;
        int v3 = v1;
        v1 = v2;
        v2 = (this.a_Graphi.getClipWidth() - v3);
        L63:
        if (this.h == 0) goto L78;
        if (this.i != 0) goto L78;
        return;
        L78:
        if (ObfCo.c() == 0) goto L90;
        ObfCo.a(v1, v2);
        return;
        L90:
        if (this.b_y == null) goto L106;
        this.b_y.a(v1, v2);
        L106:
        return;
    }
    // bytecode 86 bytes, max_stack 3, max_locals 4
    public void pointerPressed(int v1, int v2) {
        this.c_I = v1;
        this.d_I = v2;
        if ((Settings.m() % 2) != 1) goto L44;
        if (this.b_y == this.a_r) goto L44;
        int v3 = v1;
        v1 = v2;
        v2 = (this.a_Graphi.getClipWidth() - v3);
        L44:
        if (this.h == 0) goto L59;
        if (this.i != 0) goto L59;
        return;
        L59:
        Settings.d();
        if (ObfCo.c() != 0) goto L85;
        if (this.b_y == null) goto L85;
        /* pop: this.b_y.a(v1, v2); */
        L85:
        return;
    }
    // bytecode 128 bytes, max_stack 3, max_locals 4
    public void pointerReleased(int v1, int v2) {
        if ((Settings.m() % 2) != 1) goto L34;
        if (this.b_y == this.a_r) goto L34;
        int v3 = v1;
        v1 = v2;
        v2 = (this.a_Graphi.getClipWidth() - v3);
        L34:
        if (this.h == 0) goto L99;
        if (this.i != 0) goto L99;
        if (v1 >= 50) goto L71;
        if (v2 <= (SysUtil.f - 50)) goto L71;
        this.keyPressed(-202);
        L71:
        if (v1 <= (SysUtil.e - 50)) goto L98;
        if (v2 <= (SysUtil.f - 50)) goto L98;
        this.keyPressed(-203);
        L98:
        return;
        L99:
        if (ObfCo.c() == 0) goto L111;
        ObfCo.b(v1, v2);
        return;
        L111:
        if (this.b_y == null) goto L127;
        this.b_y.b(v1, v2);
        L127:
        return;
    }
    // bytecode 24 bytes, max_stack 2, max_locals 1
    public void F() {
        if (this.b_y != this.a_r) goto L23;
        if (ObfR.g() != 24) goto L23;
        this.z();
        L23:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void hideNotify() {
        this.F();
        return;
    }
    // bytecode 146 bytes, max_stack 4, max_locals 0
    public static void G() {
        /* try L0-L143 catch java.lang.Exception -> L144 */
        if (KORa.self.platformRequest("http://koragame.com/pay") != 1) goto L143;
        new java.util.Hashtable(); /* constructor */
        MainCanvas.configHashTable = new java.util.Hashtable();
        /* pop: MainCanvas.configHashTable.put("staticAdOnlyOnFailure", "false"); */
        /* pop: MainCanvas.configHashTable.put("zoneId", "12791"); */
        /* pop: MainCanvas.configHashTable.put("viewMandatory", "true"); */
        /* pop: MainCanvas.configHashTable.put("staticAdResource", "Your_Resource_Name.Extention"); */
        /* pop: MainCanvas.configHashTable.put("supportedScreens", "352x288|300x250|216x162|168x126|120x90"); */
        /* pop: MainCanvas.configHashTable.put("staticAdPosition", "0"); */
        /* pop: MainCanvas.configHashTable.put("staticAdTemplate", "staticAd_end.txt"); */
        /* pop: MainCanvas.configHashTable.put("showAds", "true"); */
        new VservManager(KORa.self, MainCanvas.configHashTable); /* constructor */
        new VservManager(KORa.self, MainCanvas.configHashTable).showAtEnd();
        return;
        L143:
        return;
        /* pop: ex_144; */
        return;
    }
    // bytecode 24 bytes, max_stack 3, max_locals 3
    public void sizeChanged(int v1, int v2) {
        MainCanvas.vservDisplaybleSet = (MainCanvas.vservDisplaybleSet + 1);
        if (MainCanvas.vservDisplaybleSet != 2) goto L16;
        return;
        L16:
        this.sizeChangedMainApp(v1, v2);
        return;
    }
}

