// Generated by tools/jdeob.py from x/ac.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ac`.
// String constants: <init> | Code | KORa | close | java/io/IOException | java/io/InputStream | java/util/Random | nextInt | rand | skip | StackMap
// API references: java/io java/util
public class ObfAc extends MenuScreen {
    // bytecode 12 bytes, max_stack 2, max_locals 1
    public ObfAc() {
        super();
        this.q = 196;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public ObfAc(MainCanvas v1) {
        super(v1);
        return;
    }
    // bytecode 147 bytes, max_stack 4, max_locals 5
    public void b() {
        InputStream v1 = Resources.a(ObfAc.c);
        /* pop: Resources.a(ObfAc.c).skip(((long) ObfAc.g)); */
        ObfAc.k = StreamReader.a(v1);
        ObfAc.j = StreamReader.a(v1);
        if (StreamReader.a(v1) <= 0) goto L41;
        jt1 = 1; /* join L42 from L37 */
        goto L42;
        L41:
        jt1 = 0; /* join L42 from L41 */
        L42:
        ObfAc.a = jt1;
        ObfAc.m = StreamReader.a(v1);
        ObfAc.l = 1;
        ObfAc.c = new int[1];
        int v3 = 0;
        L64:
        if (v3 >= ObfAc.l) goto L142;
        L71:
        int v2 = 1;
        ObfAc.c[v3] = KORa.rand.nextInt(4);
        if (ObfAc.c[v3] != ObfAc.h) goto L101;
        v2 = 0;
        goto L132;
        L101:
        int v4 = 0;
        L104:
        if (v4 >= v3) goto L132;
        if (ObfAc.c[v3] != ObfAc.c[v4]) goto L126;
        v2 = 0;
        L126:
        v4 += 1;
        goto L104;
        L132:
        if (v2 == 0) goto L71;
        v3 += 1;
        goto L64;
        L142:
        v1.close();
        return;
    }
}

