// Generated by tools/jdeob.py from x/ap.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ap`.
// String constants: /lists/hd_list | /tiles/ | <init> | Code | [Lbp; | append | close | getClass | getResourceAsStream | java/io/IOException | java/io/InputStream | java/lang/Class
// API references: java/io
public class ObfAp {
    private ObfBp[] a;
    private int a_I;
    // bytecode 28 bytes, max_stack 2, max_locals 1
    public ObfAp() {
        super();
        this.a = null;
        this.a_I = 0;
        this.a = new ObfBp[50];
        this.b();
        return;
    }
    // bytecode 132 bytes, max_stack 4, max_locals 5
    public void b() {
        /* try L14-L129 catch java.io.IOException -> L130 */
        this.a[0] = null;
        int v2 = 0;
        this.a_I = 0;
        InputStream v3 = this.getClass().getResourceAsStream("/lists/hd_list");
        String v4 = "";
        L28:
        int v1 = v3.read();
        if (v3.read() <= 0) goto L125;
        v1 = ((char) v1);
        if (((char) v1) == 10) goto L70;
        new java.lang.StringBuffer(); /* constructor */
        v4 = new java.lang.StringBuffer().append(v4).append(v1).toString();
        goto L28;
        L70:
        new java.lang.StringBuffer(); /* constructor */
        new ObfBp(new java.lang.StringBuffer().append("/tiles/").append(v4).toString()); /* constructor */
        v1 = ((int) new ObfBp(new java.lang.StringBuffer().append("/tiles/").append(v4).toString()));
        this.a[v2] = v1;
        v4 = "";
        v2 += 1;
        this.a_I = (this.a_I + 1);
        goto L28;
        L125:
        v3.close();
        return;
        /* pop: ex_130; */
        return;
    }
    // bytecode 50 bytes, max_stack 3, max_locals 2
    public ObfBp a(int v1) {
        if (v1 == 0) goto L11;
        if (Settings.f() > 1) goto L13;
        L11:
        return null;
        L13:
        if (this.a[(v1 - 1)].a() != 0) goto L41;
        this.a[(v1 - 1)].a(ObfBb.a);
        L41:
        return this.a[(v1 - 1)];
    }
    // bytecode 38 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a_I) goto L32;
        this.a[v1].a();
        this.a[v1] = null;
        v1 += 1;
        goto L2;
        L32:
        this.a = null;
        return;
    }
}

