// Generated by tools/jdeob.py from x/af.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `af`.
// String constants: ()B | ()I | ()V | ()Z | (B)V | (I)Ljava/lang/String; | (I)V | (Lbn;II)V | (Lbn;III)V | (Ljava/lang/String;)I | (Ljava/lang/String;)V | (Ljavax/microedition/lcdui/Graphics;II)V
// API references: javax/microedition
public class ObfAf extends ObfDb {
    private String[] a;
    // bytecode 27 bytes, max_stack 4, max_locals 5
    public ObfAf(ObfBn v1, int v2, int v3, int v4) {
        super(v1, v2, v4);
        this.a = null;
        this.a = new java.lang.String[v2];
        this.g(0);
        return;
    }
    // bytecode 21 bytes, max_stack 3, max_locals 2
    public void a(String v1) {
        this.a[this.a] = v1;
        this.a = (this.a + 1);
        return;
    }
    // bytecode 107 bytes, max_stack 8, max_locals 4
    public void b(Graphics v1, int v2, int v3) {
        ObfAq.b.a();
        if (this.c() == 0) goto L49;
        v1.setColor(10066329);
        ObfAq.a(v1, 0, ((v3 + this.f()) - 1), v1.getClipWidth(), (ObfAq.b.a() + 1), 11184810, 8947848, 1);
        L49:
        ObfAq.b.a(v1, this.a[this.b], ((v2 + this.e()) + ((this.b() - ObfAq.b.a(this.a[this.b])) / 2)), (v3 + this.f()));
        ObfAq.b.b();
        return;
    }
    // bytecode 35 bytes, max_stack 3, max_locals 1
    public int a() {
        if (this.a != null) goto L17;
        return (ObfAq.b.a(1) + 3);
        L17:
        return ((this.a.a() + ObfAq.b.a(1)) + 3);
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void a(byte v1) {
        this.a = v1;
        return;
    }
    // bytecode 16 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        if (this.a == null) goto L15;
        this.a.a(v1);
        L15:
        return;
    }
    // bytecode 19 bytes, max_stack 3, max_locals 1
    public int b() {
        return (ObfAq.b.a(this.a[this.b]) + 10);
    }
    // bytecode 29 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a) goto L23;
        this.a[v1] = null;
        v1 += 1;
        goto L2;
        L23:
        this.a = 0;
        return;
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public String a(int v1) {
        return this.a[v1];
    }
}

