// Generated by tools/jdeob.py from x/bf.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bf`.
// String constants: ()I | ()Ljava/lang/Class; | ()Ljava/lang/String; | ()V | ()Z | (C)Ljava/lang/StringBuffer; | (I)Lar; | (I)Ljava/lang/StringBuffer; | (Lar;)V | (Lcf;)V | (Ljava/lang/String;)Ljava/io/InputStream; | (Ljava/lang/String;)Ljava/lang/StringBuffer;
// API references: java/io
public class ObfBf {
    private ObfAr[] a;
    private ObfCf a_cf;
    private int a_I;
    // bytecode 39 bytes, max_stack 2, max_locals 2
    public ObfBf(ObfCf v1) {
        super();
        this.a = null;
        this.a_cf = null;
        this.a_I = 0;
        this.a = new ObfAr[200];
        this.a_cf = v1;
        this.b();
        return;
    }
    // bytecode 21 bytes, max_stack 3, max_locals 2
    public void a(ObfAr v1) {
        this.a[this.a_I] = v1;
        this.a_I = (this.a_I + 1);
        return;
    }
    // bytecode 124 bytes, max_stack 6, max_locals 4
    public void b() {
        /* try L17-L121 catch java.io.IOException -> L122 */
        new ObfAr(); /* constructor */
        ObfAr v1 = new ObfAr();
        new ObfAr().a();
        this.a(v1);
        InputStream v2 = this.getClass().getResourceAsStream("/lists/tile_list");
        new java.lang.StringBuffer(); /* constructor */
        java.lang.StringBuffer v3 = new java.lang.StringBuffer();
        L35:
        v1 = ((ObfAr) v2.read());
        if (v2.read() <= 0) goto L117;
        v1 = ((ObfAr) ((char) v1));
        if (((char) v1) == 10) goto L62;
        /* pop: v3.append(v1); */
        goto L35;
        L62:
        new java.lang.StringBuffer(); /* constructor */
        new ObfAr(new java.lang.StringBuffer().append("/tiles/").append(v3.deleteCharAt((v3.length() - 1)).toString()).toString()); /* constructor */
        v1 = new ObfAr(new java.lang.StringBuffer().append("/tiles/").append(v3.deleteCharAt((v3.length() - 1)).toString()).toString());
        this.a(v1);
        new java.lang.StringBuffer(); /* constructor */
        v3 = new java.lang.StringBuffer();
        goto L35;
        L117:
        v2.close();
        return;
        /* pop: ex_122; */
        return;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public ObfAr a(int v1) {
        if (this.a[v1].a() != 0) goto L25;
        this.a[v1].a(this.a_cf);
        L25:
        return this.a[v1];
    }
    // bytecode 38 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a_I) goto L32;
        this.a[v1].b();
        this.a[v1] = null;
        v1 += 1;
        goto L2;
        L32:
        this.a = null;
        return;
    }
}

