// Generated by tools/jdeob.py from x/bk.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bk`.
// String constants: ()B | ()I | ()Z | (B)V | (I)I | (I)V | (I)Z | (II)Z | (Lbn;III)V | (Lbn;IIII)V | (Lbn;IIILp;)V | (Ljava/io/InputStream;)Ljavax/microedition/lcdui/Image;
// API references: javax/microedition
public class ObfBk extends ObfBn {
    private ObfAx a;
    private Image[] a_Image;
    private ObfDl[] a_arrLdl;
    private int a_I;
    private int b;
    private int h;
    private boolean b_Z;
    // bytecode 173 bytes, max_stack 8, max_locals 5
    public ObfBk(ObfBn v1, int v2, int v3, int v4) {
        /* try L112-L156 catch java.io.IOException -> L157 */
        super(v1, 0, 0, 0, 0);
        this.a = null;
        new javax.microedition.lcdui.Image[2][0] = null;
        new javax.microedition.lcdui.Image[2][1] = null;
        this.a_Image = new javax.microedition.lcdui.Image[2];
        this.a_arrLdl = null;
        this.a_I = 0;
        this.b = 0;
        this.h = 0;
        this.b_Z = false;
        this.b(1);
        this.a(0);
        new ObfAx(this, 0, 0, v4, ObfAq.b); /* constructor */
        this.a = new ObfAx(this, 0, 0, v4, ObfAq.b);
        this.a_arrLdl = new ObfDl[3];
        this.e(this.a.b());
        v2 = 1;
        v1 = ((ObfBn) this);
        this.b = v2;
        this.a_Image[0] = javax.microedition.lcdui.Image.createImage(ObfBl.a(ObfAq.a[0]));
        this.a_Image[1] = javax.microedition.lcdui.Image.createImage(ObfBl.a(ObfAq.a[1]));
        /* pop: this.a_Image[0].getWidth(); */
        return;
        /* pop: ex_157; */
        this.a_Image[0] = null;
        this.a_Image[1] = null;
        return;
    }
    // bytecode 139 bytes, max_stack 3, max_locals 3
    public boolean a(int v1) {
        if (this.c() != 0) goto L9;
        return 0;
        L9:
        if (ObfAq.a(v1) == -5) goto L44;
        if (ObfAq.a(v1) == -6) goto L44;
        if (ObfAq.b(v1) == 5) goto L44;
        if (ObfAq.b(v1) != 8) goto L58;
        L44:
        int v2 = this.h;
        v1 = ((int) this);
        this.b = v2;
        return 1;
        L58:
        if (ObfAq.b(v1) != 1) goto L95;
        if ((this.h - 1) >= 0) goto L83;
        this.a(0);
        goto L93;
        L83:
        this.h = (this.h - 1);
        L93:
        return 1;
        L95:
        if (ObfAq.b(v1) != 6) goto L137;
        if ((this.h + 1) < this.a_I) goto L125;
        this.a(0);
        goto L135;
        L125:
        this.h = (this.h + 1);
        L135:
        return 1;
        L137:
        return 0;
    }
    // bytecode 176 bytes, max_stack 5, max_locals 7
    public void a(Graphics v1, int v2, int v3) {
        this.a.a(v1, (v2 + this.e()), (v3 + this.f()), this.a.b());
        int v5 = this.a.a();
        int v6 = 0;
        L39:
        if (v6 >= this.a_I) goto L175;
        if (this.c() == 0) goto L75;
        if (v6 != this.h) goto L75;
        this.a_arrLdl[v6].a = true;
        L75:
        if (v6 != this.b) goto L88;
        jt1 = 1; /* join L89 from L84 */
        goto L89;
        L88:
        jt1 = 0; /* join L89 from L88 */
        L89:
        int v4 = jt1;
        this.a_arrLdl[v6].a(this.a_Image[v4], 5, 2);
        this.a_arrLdl[v6].a(v1, (v2 + this.e()), ((v3 + this.f()) + v5), this.a.b());
        v5 = (v5 + this.a_arrLdl[v6].a());
        this.a_arrLdl[v6].a = false;
        v6 += 1;
        goto L39;
        L175:
        return;
    }
    // bytecode 50 bytes, max_stack 9, max_locals 2
    public void b(int v1) {
        new ObfDl(this, 0, 0, v1, ObfAq.b); /* constructor */
        this.a_arrLdl[this.a_I] = new ObfDl(this, 0, 0, v1, ObfAq.b);
        this.a_arrLdl[this.a_I].a(this.a());
        this.a_I = (this.a_I + 1);
        return;
    }
    // bytecode 35 bytes, max_stack 2, max_locals 2
    public void a(byte v1) {
        this.a = v1;
        v1 = ((byte) 0);
        L7:
        if (v1 >= this.a_I) goto L34;
        this.a_arrLdl[v1].a(this.a());
        v1 += 1;
        goto L7;
        L34:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int d() {
        return this.b;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void c(int v1) {
        this.b = v1;
        return;
    }
    // bytecode 17 bytes, max_stack 2, max_locals 2
    public int b() {
        int v1 = this.a.a(this.a.b());
        return this.a.a(this.a.b());
    }
    // bytecode 46 bytes, max_stack 3, max_locals 3
    public void a(boolean v1, byte v2) {
        this.a(1);
        if (this.b_Z == 0) goto L18;
        this.b_Z = false;
        return;
        L18:
        if (v2 != 5) goto L29;
        this.h = 0;
        return;
        L29:
        if (v2 != 6) goto L45;
        this.h = (this.a_I - 1);
        L45:
        return;
    }
    // bytecode 35 bytes, max_stack 2, max_locals 3
    public void a(int v1) {
        this.a.a(v1);
        int v2 = 0;
        L10:
        if (v2 >= this.a_I) goto L34;
        this.a_arrLdl[v2].a(v1);
        v2 += 1;
        goto L10;
        L34:
        return;
    }
    // bytecode 38 bytes, max_stack 3, max_locals 3
    public int a() {
        int v1 = this.a.a();
        int v2 = 0;
        L10:
        if (v2 >= this.a_I) goto L36;
        v1 = (v1 + this.a_arrLdl[v2].a());
        v2 += 1;
        goto L10;
        L36:
        return v1;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int c() {
        return 1;
    }
    // bytecode 88 bytes, max_stack 4, max_locals 5
    public boolean a(int v1, int v2) {
        int v3 = this.a.a();
        int v4 = 0;
        L11:
        if (v4 >= this.a_I) goto L86;
        if (this.a_arrLdl[v4].a(v1, ((v2 - v3) - this.f())) == 0) goto L67;
        this.h = v4;
        v2 = this.h;
        v1 = ((int) this);
        this.b = v2;
        this.b_Z = true;
        return 1;
        L67:
        v3 = (v3 + this.a_arrLdl[v4].a());
        v4 += 1;
        goto L11;
        L86:
        return 0;
    }
}

