// Generated by tools/jdeob.py from x/br.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `br`.
// String constants: /images/a.png | /images/map2.jpg | /images/qm2.png | /images/st.png | <init> | Code | KORa_deluxe | createImage | java/io/IOException | javax/microedition/lcdui/Image | StackMap
// API references: javax/microedition
public class ObfBr extends TrackSelect {
    // bytecode 46 bytes, max_stack 2, max_locals 3
    public ObfBr(MainCanvas v1, String v2) {
        super(v1);
        this.b = "KORa_deluxe";
        this.a = new int[10];
        this.d = 0;
        this.b = new int[5];
        this.e = 0;
        this.a = v2;
        this.c();
        return;
    }
    // bytecode 14 bytes, max_stack 2, max_locals 1
    public void n() {
        Settings.h = true;
        Settings.b();
        this.b(7);
        return;
    }
    // bytecode 20 bytes, max_stack 3, max_locals 1
    public void k() {
        this.c = ((int) (((float) (100 * this.c)) / ((float) this.a)));
        return;
    }
    // bytecode 21 bytes, max_stack 2, max_locals 2
    public boolean a(int v1) {
        if (v1 < 7) goto L19;
        if (this.b < 13) goto L17;
        return 1;
        L17:
        return 0;
        L19:
        return 1;
    }
    // bytecode 46 bytes, max_stack 2, max_locals 2
    public byte[] a(int v1) {
        if (v1 != 2) goto L12;
        return SysUtil.a(162);
        L12:
        if (v1 != 5) goto L24;
        return SysUtil.a(163);
        L24:
        if (v1 != 6) goto L37;
        return SysUtil.a(161);
        L37:
        return SysUtil.a((v1 + 202));
    }
    // bytecode 83 bytes, max_stack 2, max_locals 1
    public void a() {
        /* try L0-L80 catch java.io.IOException -> L81 */
        if (Settings.c() == 0) goto L13;
        if (this.a != null) goto L75;
        L13:
        this.a = javax.microedition.lcdui.Image.createImage(Resources.a("/images/map2.jpg"));
        this.b = javax.microedition.lcdui.Image.createImage(Resources.a("/images/st.png"));
        this.c = javax.microedition.lcdui.Image.createImage(Resources.a("/images/qm2.png"));
        this.a = SysUtil.p;
        this.b = SysUtil.r;
        this.d = javax.microedition.lcdui.Image.createImage(Resources.a("/images/a.png"));
        L75:
        this.a = true;
        return;
        /* pop: ex_81; */
        return;
    }
    // bytecode 8 bytes, max_stack 1, max_locals 1
    public void m() {
        this.a.j();
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return 1;
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public String a(int v1) {
        return ObfBd.a.a(7);
    }
}

