// Generated by tools/jdeob.py from x/cs.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cs`.
// String constants: ()F | ()V | <init> | Code
public class ObfCs extends ObfX {
    // bytecode 34 bytes, max_stack 3, max_locals 1
    public ObfCs() {
        super();
        this.b = 1.0f;
        this.c = 1.0f;
        this.a = (this.b + this.c);
        this.e = 1500.0f;
        return;
    }
    // bytecode 20 bytes, max_stack 3, max_locals 1
    public float t() {
        return (((this.r * ObfAl.b) * ((float) (this.b + 3))) / 7.0f);
    }
    // bytecode 9 bytes, max_stack 2, max_locals 1
    public float u() {
        return (this.s * ObfAl.a);
    }
}

