// Generated by tools/jdeob.py from x/cj.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cj`.
// String constants: <init> | Code | flush | java/io/ByteArrayOutputStream | java/io/IOException | java/lang/Object | toByteArray | write | StackMap
// API references: java/io
public class ObfCj {
     ByteArrayOutputStream a;
    private byte[] a_arrB;
     byte a_B;
    // bytecode 35 bytes, max_stack 3, max_locals 1
    public ObfCj() {
        super();
        new java.io.ByteArrayOutputStream(); /* constructor */
        this.a = new java.io.ByteArrayOutputStream();
        this.a_arrB = new byte[1]#2;
        this.a_arrB[0] = 0;
        this.a_B = 0;
        return;
    }
    // bytecode 70 bytes, max_stack 4, max_locals 2
    public void a(byte v1) {
        this.a_arrB[0] = ((byte) (this.a_arrB[0] << 1));
        this.a_arrB[0] = ((byte) (this.a_arrB[0] + v1));
        this.a_B = ((byte) (this.a_B + 1));
        if (this.a_B != 8) goto L69;
        this.a.write(this.a_arrB);
        this.a_arrB[0] = 0;
        this.a_B = 0;
        L69:
        return;
    }
    // bytecode 18 bytes, max_stack 1, max_locals 1
    public byte[] a() {
        /* try L0-L14 catch java.io.IOException -> L15 */
        this.a.flush();
        return this.a.toByteArray();
        /* pop: ex_15; */
        return null;
    }
}

