// Generated by tools/jdeob.py from x/ca.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ca`.
// String constants: ()V | (F)V | <init> | Code | java/lang/Object
public class ObfCa {
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfCa() {
        super();
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void f(float v1) {
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void g(float v1) {
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void h(float v1) {
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void i(float v1) {
        return;
    }
}

