// Generated by tools/jdeob.py from x/cz.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cz`.
// String constants: ()I | (I)V | (I)Z | (Lbn;IIII)V | (Ljavax/microedition/lcdui/Graphics;II)V | <init> | Code
public class ObfCz extends ObfBn {
    // bytecode 10 bytes, max_stack 6, max_locals 2
    public ObfCz(int v1) {
        super(null, 0, 0, 0, 3);
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 2
    public boolean a(int v1) {
        return 0;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 4
    public void a(Graphics v1, int v2, int v3) {
        return;
    }
    // bytecode 2 bytes, max_stack 1, max_locals 1
    public int c() {
        return m1;
    }
}

