// Generated by tools/jdeob.py from x/de.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `de`.
// String constants: <init> | Code | [Lat; | [Ljava/lang/String; | compareTo | getAppearance | java/lang/Object | java/lang/String | javax/microedition/m3g/Appearance | javax/microedition/m3g/Mesh | setTexture | StackMap
// API references: javax/microedition
public class ObfDe {
    private ObfAt[] a;
    private String[] a_String;
    private ObfCf a_cf;
    private int a_I;
    // bytecode 53 bytes, max_stack 2, max_locals 2
    public ObfDe(ObfCf v1) {
        super();
        this.a = null;
        this.a_String = null;
        this.a_cf = null;
        this.a_I = 0;
        this.a = new ObfAt[100];
        this.a_String = new java.lang.String[100];
        this.a_cf = v1;
        this.a_I = 0;
        return;
    }
    // bytecode 33 bytes, max_stack 3, max_locals 3
    public int a(String v1) {
        int v2 = 0;
        L2:
        if (v2 >= this.a_I) goto L31;
        if (v1.compareTo(this.a_String[v2]) != 0) goto L25;
        return v2;
        L25:
        v2 += 1;
        goto L2;
        L31:
        return m1;
    }
    // bytecode 9 bytes, max_stack 5, max_locals 4
    public ObfAt a(String v1, String v2, boolean v3) {
        return this.a(v1, v2, v3, 0);
    }
    // bytecode 49 bytes, max_stack 5, max_locals 4
    public ObfAt a(String v1, String v2) {
        int v3 = this.a(v1);
        if (this.a(v1) >= 0) goto L17;
        return this.c(v1, v2);
        L17:
        this.a[v3].a().getAppearance(0).setTexture(0, ObfBb.a_cf.a(v2, 1));
        return this.a[v3];
    }
    // bytecode 55 bytes, max_stack 5, max_locals 6
    public ObfAt a(String v1, String v2, boolean v3, boolean v4) {
        int v5 = this.a(v1);
        if (this.a(v1) >= 0) goto L21;
        return this.c(v1, v2, v3, v4);
        L21:
        this.a[v5].a().getAppearance(0).setTexture(0, ObfBb.a_cf.a(v2, v3));
        return this.a[v5];
    }
    // bytecode 47 bytes, max_stack 9, max_locals 4
    public ObfAt b(String v1, String v2) {
        int v3 = this.a(v1);
        if (this.a(v1) >= 0) goto L17;
        return this.c(v1, v2);
        L17:
        new ObfBy(this.a_cf, v1, v2, Settings.d, 1); /* constructor */
        this.a[v3] = new ObfBy(this.a_cf, v1, v2, Settings.d, 1);
        return this.a[v3];
    }
    // bytecode 9 bytes, max_stack 5, max_locals 4
    public ObfAt b(String v1, String v2, boolean v3) {
        return this.b(v1, v2, v3, 0);
    }
    // bytecode 55 bytes, max_stack 10, max_locals 6
    public ObfAt b(String v1, String v2, boolean v3, boolean v4) {
        int v5 = this.a(v1);
        if (this.a(v1) >= 0) goto L21;
        return this.c(v1, v2, v3, v4);
        L21:
        new ObfAt(this.a_cf, v1, v2, Settings.d, v3, v4); /* constructor */
        this.a[v5] = new ObfAt(this.a_cf, v1, v2, Settings.d, v3, v4);
        return this.a[v5];
    }
    // bytecode 120 bytes, max_stack 11, max_locals 6
    public ObfAt a(String v1, String v2, boolean v3, String v4) {
        v3 = ((boolean) this.a(v1));
        if (this.a(v1) >= 0) goto L87;
        String v5 = v4;
        v1 = ((String) 0);
        v4 = ((String) 0);
        v3 = ((boolean) v2);
        v2 = v1;
        v1 = ((String) this);
        new ObfAt(v1.a_cf, v2, v3, Settings.d, v4, 0, v5); /* constructor */
        this.a[v1.a_I] = new ObfAt(v1.a_cf, v2, v3, Settings.d, v4, 0, v5);
        v1.a_String[v1.a_I] = v2;
        v1.a_I = (v1.a_I + 1);
        return v1.a[(v1.a_I - 1)];
        L87:
        new ObfAt(this.a_cf, v1, v2, Settings.d, 0, 0, v4); /* constructor */
        this.a[v3] = new ObfAt(this.a_cf, v1, v2, Settings.d, 0, 0, v4);
        return this.a[v3];
    }
    // bytecode 60 bytes, max_stack 10, max_locals 5
    public ObfAt c(String v1, String v2, boolean v3, boolean v4) {
        new ObfAt(this.a_cf, v1, v2, Settings.d, v3, v4); /* constructor */
        this.a[this.a_I] = new ObfAt(this.a_cf, v1, v2, Settings.d, v3, v4);
        this.a_String[this.a_I] = v1;
        this.a_I = (this.a_I + 1);
        return this.a[(this.a_I - 1)];
    }
    // bytecode 58 bytes, max_stack 9, max_locals 3
    public ObfAt c(String v1, String v2) {
        new ObfBy(this.a_cf, v1, v2, Settings.d, 1); /* constructor */
        this.a[this.a_I] = new ObfBy(this.a_cf, v1, v2, Settings.d, 1);
        this.a_String[this.a_I] = v1;
        this.a_I = (this.a_I + 1);
        return this.a[(this.a_I - 1)];
    }
    // bytecode 48 bytes, max_stack 3, max_locals 2
    public void a() {
        int v1 = 0;
        L2:
        if (v1 >= this.a_I) goto L32;
        this.a[v1].a();
        this.a[v1] = null;
        v1 += 1;
        goto L2;
        L32:
        this.a = null;
        this.a_cf = null;
        this.a_String = null;
        return;
    }
}

