// Generated by tools/jdeob.py from x/dj.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `dj`.
// String constants: &p= | <init> | ?a=b | ?a=s&s= | Code | Error | POST | [Ljava/lang/String; | append | close | compareTo | indexOf
// API references: java/io javax/microedition
public class ObfDj {
    private String a;
    private String b;
    private String c;
    private int[] a_arrI;
    private String[] a_String;
    // bytecode 91 bytes, max_stack 3, max_locals 1
    public ObfDj() {
        super();
        new java.lang.StringBuffer(); /* constructor */
        this.a = new java.lang.StringBuffer().append(Settings.b).append("?a=b").toString();
        new java.lang.StringBuffer(); /* constructor */
        this.b = new java.lang.StringBuffer().append(this.a).append("&p=").toString();
        new java.lang.StringBuffer(); /* constructor */
        this.c = new java.lang.StringBuffer().append(Settings.b).append("?a=s&s=").toString();
        this.a_arrI = null;
        this.a_String = null;
        return;
    }
    // bytecode 11 bytes, max_stack 2, max_locals 2
    public String[] a() {
        String[] v1 = this.a(this.a);
        return this.a(this.a);
    }
    // bytecode 33 bytes, max_stack 4, max_locals 2
    public String[] a(int v1) {
        new java.lang.StringBuffer(); /* constructor */
        v1 = ((int) this.a(new java.lang.StringBuffer().append(this.b).append(this.a_arrI[v1]).toString()));
        return this.a(new java.lang.StringBuffer().append(this.b).append(this.a_arrI[v1]).toString());
    }
    // bytecode 111 bytes, max_stack 3, max_locals 4
    public String[] a(String v1) {
        /* try L17-L48 catch java.io.IOException -> L105 */
        /* try L49-L102 catch java.io.IOException -> L105 */
        int v2 = 1;
        v1 = ((String) ObfDj.a(v1, v2, null));
        if (ObfDj.a(v1, v2, null) != null) goto L17;
        return null;
        L17:
        new java.io.ByteArrayInputStream(v1); /* constructor */
        v1 = ((String) new java.io.ByteArrayInputStream(v1));
        new java.io.DataInputStream(v1); /* constructor */
        v1 = ((String) new java.io.DataInputStream(v1));
        if (Settings.a(new java.io.DataInputStream(v1)).compareTo("OK") == 0) goto L49;
        return null;
        L49:
        v2 = v1.readByte();
        this.a_arrI = new int[v2];
        this.a_String = new java.lang.String[v2];
        int v3 = 0;
        L71:
        if (v3 >= v2) goto L102;
        this.a_arrI[v3] = v1.readByte();
        this.a_String[v3] = Settings.a(v1);
        v3 += 1;
        goto L71;
        L102:
        goto L106;
        /* pop: ex_105; */
        L106:
        return this.a_String;
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public String a(int v1) {
        return this.a_String[v1];
    }
    // bytecode 176 bytes, max_stack 5, max_locals 6
    public static byte[] a(String v0, boolean v1, byte[] v2) {
        /* try L0-L134 catch java.lang.Exception -> L165 */
        /* try L135-L141 catch java.lang.Exception -> L165 */
        /* try L142-L161 catch java.lang.Exception -> L165 */
        MainCanvas.a = 1;
        MainCanvas.a();
        v0 = ((String) ((javax.microedition.io.HttpConnection) javax.microedition.io.Connector.open(v0)));
        ((javax.microedition.io.HttpConnection) javax.microedition.io.Connector.open(v0)).setRequestMethod("POST");
        MainCanvas.a = 2;
        MainCanvas.a();
        if (v2 == null) goto L50;
        OutputStream v3 = v0.openOutputStream();
        v0.openOutputStream().write(v2);
        v3.close();
        L50:
        MainCanvas.a = 3;
        MainCanvas.a();
        v2 = ((byte[]) v0.openInputStream());
        int v4 = 0;
        byte v5 = new byte[4096];
        L74:
        v3 = ((OutputStream) v2.read(v5, v4, 128));
        if (v2.read(v5, v4, 128) <= 0) goto L96;
        v4 = (v4 + v3);
        L96:
        if (v3 > 0) goto L74;
        MainCanvas.a = 0;
        if (v4 <= 0) goto L138;
        new java.lang.String(v5, 0, v4); /* constructor */
        v3 = ((OutputStream) new java.lang.String(v5, 0, v4));
        if (new java.lang.String(v5, 0, v4).indexOf("Error") < 0) goto L135;
        return new byte[0];
        L135:
        goto L142;
        L138:
        return new byte[0];
        L142:
        v2.close();
        v0.close();
        if (v1 == 0) goto L162;
        return TouchButtons.b(v5);
        L162:
        return v5;
        v3 = ((OutputStream) ex_165);
        MainCanvas.a = 0;
        v3.printStackTrace();
        return null;
    }
    // bytecode 282 bytes, max_stack 3, max_locals 3
    public boolean a(int v1) {
        /* try L42-L73 catch java.io.IOException -> L279 */
        /* try L74-L278 catch java.io.IOException -> L279 */
        new java.lang.StringBuffer(); /* constructor */
        int v2 = 1;
        v1 = ((int) new java.lang.StringBuffer().append(this.c).append(this.a_arrI[v1]).toString());
        v1 = ((int) ObfDj.a(new java.lang.StringBuffer().append(this.c).append(this.a_arrI[v1]).toString(), v2, null));
        if (ObfDj.a(new java.lang.StringBuffer().append(this.c).append(this.a_arrI[v1]).toString(), v2, null) != null) goto L42;
        return 0;
        L42:
        new java.io.ByteArrayInputStream(v1); /* constructor */
        v1 = ((int) new java.io.ByteArrayInputStream(v1));
        new java.io.DataInputStream(v1); /* constructor */
        v1 = ((int) new java.io.DataInputStream(v1));
        if (Settings.a(new java.io.DataInputStream(v1)).compareTo("OK") == 0) goto L74;
        return 0;
        L74:
        Settings.d(v1.readByte());
        Settings.e(v1.readByte());
        Settings.f(v1.readByte());
        Settings.h((2 - v1.readByte()));
        Settings.g(v1.readByte());
        if (v1.readByte() == 0) goto L124;
        jt1 = 1; /* join L125 from L120 */
        goto L125;
        L124:
        jt1 = 0; /* join L125 from L124 */
        L125:
        Settings.b(jt1);
        if (v1.readByte() == 0) goto L139;
        jt2 = 1; /* join L140 from L135 */
        goto L140;
        L139:
        jt2 = 0; /* join L140 from L139 */
        L140:
        Settings.c(jt2);
        if (v1.readByte() == 0) goto L154;
        jt3 = 1; /* join L155 from L150 */
        goto L155;
        L154:
        jt3 = 0; /* join L155 from L154 */
        L155:
        Settings.d(jt3);
        if (v1.readByte() == 0) goto L169;
        jt4 = 1; /* join L170 from L165 */
        goto L170;
        L169:
        jt4 = 0; /* join L170 from L169 */
        L170:
        Settings.e = jt4;
        Settings.i(v1.readByte());
        Settings.j(v1.readByte());
        Settings.b(v1.readByte());
        v2 = v1.readByte();
        if (Settings.c() != 1) goto L210;
        Settings.k(v2);
        L210:
        if (v1.readByte() == 0) goto L221;
        jt5 = 1; /* join L222 from L217 */
        goto L222;
        L221:
        jt5 = 0; /* join L222 from L221 */
        L222:
        Settings.a(jt5);
        if (v1.readByte() == 0) goto L236;
        jt6 = 1; /* join L237 from L232 */
        goto L237;
        L236:
        jt6 = 0; /* join L237 from L236 */
        L237:
        Settings.f = jt6;
        Settings.r(v1.readByte());
        Settings.l(v1.readByte());
        if (v1.readByte() == 0) goto L265;
        jt7 = 1; /* join L266 from L261 */
        goto L266;
        L265:
        jt7 = 0; /* join L266 from L265 */
        L266:
        Settings.g = jt7;
        Settings.b();
        ObfCo.c(32);
        return 1;
        /* pop: ex_279; */
        return 0;
    }
}

