// Generated by tools/jdeob.py from x/db.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `db`.
// String constants: ()B | ()I | ()V | ()Z | (B)V | (C)I | (I)I | (I)Lax; | (I)V | (I)Z | (II)Z | (Lbn;II)V
// API references: javax/microedition
public class ObfDb extends ObfBn {
    protected ObfAx a;
    private ObfAx[] a_arrLax;
    protected int a_I;
    protected int b;
    private boolean b_Z;
    // bytecode 99 bytes, max_stack 6, max_locals 4
    public ObfDb(ObfBn v1, int v2, int v3) {
        super(v1, 0, 0, 0, 0);
        this.a = null;
        this.a_arrLax = null;
        this.a_I = 0;
        this.b = 0;
        this.b_Z = false;
        this.b(1);
        this.a(0);
        this.b(v3);
        this.a_arrLax = new ObfAx[v2];
        if (this.a == null) goto L78;
        this.e(this.a.b());
        goto L89;
        L78:
        this.e(this.a.b());
        L89:
        v2 = 1;
        v1 = ((ObfBn) this);
        this.b = v2;
        return;
    }
    // bytecode 23 bytes, max_stack 8, max_locals 2
    public void b(int v1) {
        if (v1 < 0) goto L22;
        new ObfAx(this, 0, 0, v1, ObfAq.b); /* constructor */
        this.a = new ObfAx(this, 0, 0, v1, ObfAq.b);
        L22:
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void c(boolean v1) {
        this.b_Z = true;
        return;
    }
    // bytecode 139 bytes, max_stack 3, max_locals 2
    public boolean a(int v1) {
        if (this.c() != 0) goto L9;
        return 0;
        L9:
        if (this.b_Z != 0) goto L24;
        jt1 = 2; /* join L25 from L20 */
        goto L25;
        L24:
        jt1 = 5; /* join L25 from L24 */
        L25:
        if (ObfAq.b(v1) != jt1) goto L58;
        if (this.b >= (this.a_I - 1)) goto L58;
        this.b = ((this.b + 1) % this.a_I);
        return 1;
        L58:
        if (this.b_Z != 0) goto L73;
        jt2 = 5; /* join L74 from L69 */
        goto L74;
        L73:
        jt2 = 2; /* join L74 from L73 */
        L74:
        if (ObfAq.b(v1) != jt2) goto L106;
        if (this.b <= 0) goto L106;
        this.b = (((this.b - 1) + this.a_I) % this.a_I);
        return 1;
        L106:
        if (ObfAq.b(v1) != 1) goto L121;
        this.a(0);
        return 1;
        L121:
        if (ObfAq.b(v1) != 6) goto L137;
        this.a(0);
        return 1;
        L137:
        return 0;
    }
    // bytecode 65 bytes, max_stack 5, max_locals 4
    public void b(Graphics v1, int v2, int v3) {
        if (this.c() == 0) goto L20;
        this.a_arrLax[this.b].a = true;
        L20:
        this.a_arrLax[this.b].h();
        this.a_arrLax[this.b].a(v1, (v2 + this.e()), (v3 + this.f()), this.a.b());
        return;
    }
    // bytecode 473 bytes, max_stack 8, max_locals 5
    public void a(Graphics v1, int v2, int v3) {
        if (this.a == null) goto L49;
        this.a.a(v1, ((v2 + this.e()) + ((this.b() - this.a.b()) / 2)), (v3 + this.f()), this.a.b());
        L49:
        int v4 = 0;
        if (this.a == null) goto L68;
        v4 = this.a.a();
        L68:
        this.b(v1, v2, (v3 + v4));
        if (this.c() == 0) goto L447;
        ObfAq.b.a();
        if (ObfAl.l() != 0) goto L234;
        if (this.b_Z != 0) goto L117;
        if (this.b < (this.a_I - 1)) goto L131;
        L117:
        if (this.b_Z == 0) goto L166;
        if (this.b <= 0) goto L166;
        L131:
        ObfAq.b.a(v1, "<", (((v2 + this.e()) - ObfAq.b.a(60)) - 2), ((v3 + this.f()) + v4));
        L166:
        if (this.b_Z == 0) goto L186;
        if (this.b < (this.a_I - 1)) goto L200;
        L186:
        if (this.b_Z != 0) goto L441;
        if (this.b <= 0) goto L441;
        L200:
        ObfAq.b.a(v1, ">", (((v2 + this.e()) + this.b()) + 2), ((v3 + this.f()) + v4));
        goto L441;
        L234:
        if (ObfAl.l() != 1) goto L338;
        if (this.b >= (this.a_I - 1)) goto L293;
        ObfAq.b.a(v1, "<", (ObfAq.e - ((v3 + this.f()) + v4)), (((v2 + this.e()) - ObfAq.b.a(60)) - 2));
        L293:
        if (this.b <= 0) goto L441;
        ObfAq.b.a(v1, ">", (ObfAq.e - ((v3 + this.f()) + v4)), (((v2 + this.e()) + this.b()) + 2));
        goto L441;
        L338:
        if (ObfAl.l() != 3) goto L441;
        if (this.b >= (this.a_I - 1)) goto L398;
        ObfAq.b.a(v1, "<", ((v3 + this.f()) + v4), (v1.getClipHeight() - (((v2 + this.e()) - ObfAq.b.a(60)) - 2)));
        L398:
        if (this.b <= 0) goto L441;
        ObfAq.b.a(v1, ">", ((v3 + this.f()) + v4), (v1.getClipHeight() - (((v2 + this.e()) + this.b()) + 2)));
        L441:
        ObfAq.b.b();
        L447:
        if (this.a_arrLax[this.b] == null) goto L472;
        this.a_arrLax[this.b].a = false;
        L472:
        return;
    }
    // bytecode 50 bytes, max_stack 9, max_locals 2
    public void c(int v1) {
        new ObfAx(this, 0, 0, v1, ObfAq.b); /* constructor */
        this.a_arrLax[this.a_I] = new ObfAx(this, 0, 0, v1, ObfAq.b);
        this.a_arrLax[this.a_I].a(this.a());
        this.a_I = (this.a_I + 1);
        return;
    }
    // bytecode 35 bytes, max_stack 2, max_locals 2
    public void a(byte v1) {
        this.a = v1;
        v1 = ((byte) 0);
        L7:
        if (v1 >= this.a_I) goto L34;
        this.a_arrLax[v1].a(this.a());
        v1 += 1;
        goto L7;
        L34:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int d() {
        return this.b;
    }
    // bytecode 7 bytes, max_stack 2, max_locals 2
    public ObfAx a(int v1) {
        return this.a_arrLax[v1];
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void g(int v1) {
        this.b = v1;
        return;
    }
    // bytecode 35 bytes, max_stack 2, max_locals 2
    public int b() {
        if (this.a == null) goto L25;
        int v1 = this.a.a(this.a.b());
        goto L33;
        L25:
        v1 = this.a.b();
        L33:
        return v1;
    }
    // bytecode 42 bytes, max_stack 2, max_locals 3
    public void a(int v1) {
        if (this.a == null) goto L15;
        this.a.a(v1);
        L15:
        int v2 = 0;
        L17:
        if (v2 >= this.a_I) goto L41;
        this.a_arrLax[v2].a(v1);
        v2 += 1;
        goto L17;
        L41:
        return;
    }
    // bytecode 79 bytes, max_stack 3, max_locals 1
    public int a() {
        if (this.a != null) goto L34;
        if (this.a_arrLax[this.b] == null) goto L34;
        return (this.a_arrLax[this.b].a() + 3);
        L34:
        if (this.a_arrLax[this.b] != null) goto L56;
        return (this.a.a() + 3);
        L56:
        return ((this.a.a() + this.a_arrLax[this.b].a()) + 3);
    }
    // bytecode 48 bytes, max_stack 3, max_locals 1
    public int c() {
        if (this.b >= (this.a_I - 1)) goto L22;
        if (this.b <= 0) goto L22;
        return 2;
        L22:
        if (this.b >= (this.a_I - 1)) goto L37;
        return 3;
        L37:
        if (this.b <= 0) goto L46;
        return 4;
        L46:
        return m1;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public int g() {
        return this.a_I;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.a_I = 0;
        return;
    }
    // bytecode 212 bytes, max_stack 3, max_locals 4
    public boolean a(int v1, int v2) {
        if (this.c() != 0) goto L14;
        return this.a(v1, v2);
        L14:
        if (this.b_Z != 0) goto L34;
        if (this.b < (this.a_I - 1)) goto L48;
        L34:
        if (this.b_Z == 0) goto L114;
        if (this.b <= 0) goto L114;
        L48:
        int v3 = (((this.e() - ObfAq.b.a(60)) - 2) - 20);
        if (v2 < this.f()) goto L114;
        if (v2 >= (this.f() + this.a())) goto L114;
        if (v1 <= v3) goto L114;
        if (v1 >= (v3 + 50)) goto L114;
        KORa.buzz();
        /* pop: this.a(ObfAq.a()); */
        return 1;
        L114:
        if (this.b_Z == 0) goto L134;
        if (this.b < (this.a_I - 1)) goto L148;
        L134:
        if (this.b_Z != 0) goto L210;
        if (this.b <= 0) goto L210;
        L148:
        v3 = (((this.e() + this.b()) + 2) - 20);
        if (v2 < this.f()) goto L210;
        if (v2 >= (this.f() + this.a())) goto L210;
        if (v1 <= v3) goto L210;
        if (v1 >= (v3 + 50)) goto L210;
        KORa.buzz();
        /* pop: this.a(ObfAq.b()); */
        return 1;
        L210:
        return 0;
    }
}

