// Generated by tools/jdeob.py from x/e.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `e`.
// String constants: ()F | ()I | ()Ldi; | ()Ljava/lang/String; | ()Ljavax/microedition/lcdui/Graphics; | ()Ljavax/microedition/lcdui/Image; | ()V | ()Z | ()[B | (B)V | (F)F | (F)V
// API references: java/io javax/microedition
public class ObfE {
    protected int a;
    protected int b;
    protected int c;
    protected int d;
    private int l;
    private boolean a_Z;
    private int m;
    private Image a_Image;
    private Image b_Image;
    private Image c_Image;
    private Image d_Image;
    private Image e;
    protected int e_I;
    protected int f;
    private int n;
    private int o;
    protected int g;
    protected int h;
    protected int i;
    protected int j;
    private int p;
    private int q;
    private int r;
    private Image f_Image;
    private ObfCl[] a_arrLcl;
    private int[] a_arrI;
    private int s;
    private int t;
    private int u;
    private byte a_B;
    private int v;
    private int w;
    private float a_F;
    private Image g_Image;
    protected int k;
    private int x;
    private int y;
    private float b_F;
    private int z;
    private String a_String;
    private float c_F;
    private int A;
    private int B;
    private Image h_Image;
    private Image i_Image;
    private Image j_Image;
    private Image k_Image;
    private Image l_Image;
    private int C;
    // bytecode 491 bytes, max_stack 7, max_locals 3
    public ObfE(int v1, int v2) {
        /* try L391-L482 catch java.lang.Exception -> L485 */
        super();
        this.a = 0;
        this.b = 0;
        this.c = 0;
        this.d = 0;
        this.l = 0;
        this.a_Z = false;
        this.m = 2;
        this.a_Image = null;
        this.b_Image = null;
        this.c_Image = null;
        this.d_Image = null;
        this.e = null;
        this.e_I = 0;
        this.f = 0;
        this.n = 0;
        this.o = 0;
        this.g = 0;
        this.h = 0;
        this.i = 0;
        this.j = 0;
        this.p = 0;
        this.q = 0;
        this.r = 0;
        new int[2][0] = 0;
        new int[2][1] = 17;
        new Obf[I[8][0] = new int[2];
        new int[2][0] = 4;
        new int[2][1] = 9;
        new Obf[I[8][1] = new int[2];
        new int[2][0] = 11;
        new int[2][1] = 3;
        new Obf[I[8][2] = new int[2];
        new int[2][0] = 20;
        new int[2][1] = 0;
        new Obf[I[8][3] = new int[2];
        new int[2][0] = 32;
        new int[2][1] = 0;
        new Obf[I[8][4] = new int[2];
        new int[2][0] = 41;
        new int[2][1] = 3;
        new Obf[I[8][5] = new int[2];
        new int[2][0] = 48;
        new int[2][1] = 9;
        new Obf[I[8][6] = new int[2];
        new int[2][0] = 52;
        new int[2][1] = 17;
        new Obf[I[8][7] = new int[2];
        this.f_Image = null;
        this.a_arrLcl = null;
        this.a_arrI = null;
        this.s = 0;
        this.t = 0;
        this.u = 0;
        this.a_B = 5;
        this.v = 0;
        this.w = 0;
        this.a_F = -100.0f;
        this.g_Image = null;
        this.k = 0;
        this.x = 0;
        this.y = 0;
        this.b_F = 0.0f;
        this.z = 0;
        this.a_String = "";
        this.c_F = 0.0f;
        this.A = 0;
        this.B = 0;
        this.h_Image = null;
        this.i_Image = null;
        this.j_Image = null;
        this.k_Image = null;
        this.l_Image = null;
        this.C = m1;
        this.a = v1;
        this.b = v2;
        v1 = ((int) this);
        v1.a_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/ww.png"));
        v1.b_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/f.png"));
        v1.c_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/v.png"));
        v1.d_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/s.png"));
        v1.e = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/l.png"));
        if (ObfAl.d() == 0) goto L482;
        /* pop: v1.c(); */
        /* pop: v1.d(); */
        /* pop: v1.b(); */
        /* pop: v1.a(); */
        /* pop: v1.e(); */
        L482:
        goto L486;
        /* pop: ex_485; */
        L486:
        v1.a();
        return;
    }
    // bytecode 11 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        this.y = v1;
        this.b_F = 2.0f;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void b(int v1) {
        this.z = v1;
        return;
    }
    // bytecode 669 bytes, max_stack 4, max_locals 1
    public void a() {
        /* try L320-L666 catch java.lang.Exception -> L667 */
        this.a = ObfAq.e_I;
        this.b = ObfAq.f;
        this.e_I = 0;
        this.f = 30;
        this.n = (this.a - 60);
        this.o = (this.b - 35);
        this.g = (this.a - 43);
        if (ObfAl.d() == 0) goto L83;
        this.g = (this.g - 28);
        this.h = 5;
        goto L88;
        L83:
        this.h = 3;
        L88:
        this.i = 1;
        this.j = 3;
        this.p = 5;
        this.q = (this.b - 45);
        if (ObfAl.l() != 1) goto L234;
        this.e_I = (this.a - 30);
        this.f = 0;
        this.o = (this.b - 60);
        this.n = 35;
        this.h = (this.b - 43);
        if (ObfAl.d() == 0) goto L195;
        this.h = (this.h - 28);
        this.g = (this.a - 5);
        goto L205;
        L195:
        this.g = (this.a - 3);
        L205:
        this.j = 1;
        this.i = (this.a - 3);
        this.q = 5;
        this.p = 45;
        goto L320;
        L234:
        if (ObfAl.l() != 3) goto L320;
        this.e_I = 30;
        this.f = this.b;
        this.o = 60;
        this.n = (this.a - 35);
        this.h = 43;
        this.g = 3;
        this.j = (this.b - 1);
        this.i = 3;
        this.q = (this.b - 10);
        this.p = (this.a - 45);
        L320:
        this.a_Image = ObfAq.a(this.a_Image, (((ObfAl.n() - this.w) + 360) % 360));
        this.b_Image = ObfAq.a(this.b_Image, (((ObfAl.n() - this.w) + 360) % 360));
        this.c_Image = ObfAq.a(this.c_Image, (((ObfAl.n() - this.w) + 360) % 360));
        this.d_Image = ObfAq.a(this.d_Image, (((ObfAl.n() - this.w) + 360) % 360));
        this.e = ObfAq.a(this.e, (((ObfAl.n() - this.w) + 360) % 360));
        if (this.f_Image == null) goto L489;
        this.f_Image = ObfAq.a(this.f_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L489:
        if (this.g_Image == null) goto L523;
        this.g_Image = ObfAq.a(this.g_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L523:
        if (this.h_Image == null) goto L557;
        this.h_Image = ObfAq.a(this.h_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L557:
        if (this.i_Image == null) goto L591;
        this.i_Image = ObfAq.a(this.i_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L591:
        if (this.k_Image == null) goto L625;
        this.k_Image = ObfAq.a(this.k_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L625:
        if (this.l_Image == null) goto L659;
        this.l_Image = ObfAq.a(this.l_Image, (((ObfAl.n() - this.w) + 360) % 360));
        L659:
        this.w = ObfAl.n();
        return;
        /* pop: ex_667; */
        return;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public Image a() {
        /* try L7-L19 catch java.lang.Exception -> L22 */
        if (this.l_Image != null) goto L27;
        this.l_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/pause.png"));
        goto L27;
        java.lang.Exception v1 = ex_22;
        ex_22.printStackTrace();
        L27:
        return this.l_Image;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public Image b() {
        /* try L7-L19 catch java.lang.Exception -> L22 */
        if (this.k_Image != null) goto L27;
        this.k_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/bp.png"));
        goto L27;
        java.lang.Exception v1 = ex_22;
        ex_22.printStackTrace();
        L27:
        return this.k_Image;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public Image c() {
        /* try L7-L19 catch java.lang.Exception -> L22 */
        if (this.h_Image != null) goto L27;
        this.h_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/left.png"));
        goto L27;
        java.lang.Exception v1 = ex_22;
        ex_22.printStackTrace();
        L27:
        return this.h_Image;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public Image d() {
        /* try L7-L19 catch java.lang.Exception -> L22 */
        if (this.i_Image != null) goto L27;
        this.i_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/right.png"));
        goto L27;
        java.lang.Exception v1 = ex_22;
        ex_22.printStackTrace();
        L27:
        return this.i_Image;
    }
    // bytecode 87 bytes, max_stack 3, max_locals 2
    public void a(ObfCl v1) {
        if (this.s != 0) goto L24;
        this.a_arrLcl = new ObfCl[6];
        this.a_arrI = new int[12];
        L24:
        this.a_arrLcl[this.s] = v1;
        this.a_arrI[(2 * this.s)] = v1.h();
        this.a_arrI[((2 * this.s) + 1)] = v1.i();
        this.s = (this.s + 1);
        this.z = (this.z + 1);
        return;
    }
    // bytecode 22 bytes, max_stack 3, max_locals 2
    public void a(Image v1) {
        /* try L5-L19 catch java.lang.Exception -> L20 */
        this.f_Image = v1;
        this.f_Image = ObfAq.a(this.f_Image, ObfAl.n());
        return;
        /* pop: ex_20; */
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void c(int v1) {
        this.c = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void d(int v1) {
        this.x = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void e(int v1) {
        this.d = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void f(int v1) {
        this.C = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void a(boolean v1) {
        this.a_Z = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void g(int v1) {
        this.l = v1;
        return;
    }
    // bytecode 21 bytes, max_stack 2, max_locals 2
    public void h(int v1) {
        this.r = v1;
        if (this.r <= 8) goto L20;
        this.r = 8;
        L20:
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void i(int v1) {
        this.t = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void a(byte v1) {
        this.a_B = v1;
        return;
    }
    // bytecode 197 bytes, max_stack 7, max_locals 2
    public void a(Graphics v1) {
        if (ObfAl.l() != 0) goto L65;
        ObfAq.d.a(v1, ((long) this.c), (this.e_I + 7), (this.f + 5));
        if (ObfAl.e_I != 2) goto L196;
        ObfAq.e.a(v1, ((long) this.d), (this.e_I + 7), (this.f + 15));
        return;
        L65:
        if (ObfAl.l() != 1) goto L131;
        ObfAq.d.a(v1, ((long) this.c), (this.e_I - 5), (this.f + 7));
        if (ObfAl.e_I != 2) goto L196;
        ObfAq.e.a(v1, ((long) this.d), (this.e_I - 15), (this.f + 7));
        return;
        L131:
        if (ObfAl.l() != 3) goto L196;
        ObfAq.d.a(v1, ((long) this.c), (this.e_I + 5), (this.f - 7));
        if (ObfAl.e_I != 2) goto L196;
        ObfAq.e.a(v1, ((long) this.d), (this.e_I + 15), (this.f - 7));
        L196:
        return;
    }
    // bytecode 471 bytes, max_stack 7, max_locals 2
    public void b(Graphics v1) {
        if (ObfAl.l() != 0) goto L162;
        ObfAq.h.a(v1, (this.t + 1), (((this.g + 7) + 10) - ObfAq.h.a((this.t + 1))), (this.h + 4));
        ObfAq.f.a(v1, this.z, (this.g + 23), (this.h + 5));
        v1.setClip((this.g + 20), (this.h + 5), 5, 7);
        v1.drawImage(this.e, (this.g + 20), (this.h + 5), 20);
        v1.setClip((this.g + 16), (this.h + 13), 20, 7);
        v1.drawImage(this.e, (this.g - 8), (this.h + 13), 20);
        return;
        L162:
        if (ObfAl.l() != 1) goto L315;
        ObfAq.l.a(v1, (this.t + 1), (this.g - 5), (this.h + 7));
        ObfAq.f.a(v1, this.z, (this.g - 5), (this.h + 23));
        v1.setClip(((this.g - 5) - 7), (this.h + 20), 7, 5);
        v1.drawImage(this.e, (this.g - 5), (this.h + 20), 24);
        v1.setClip(((this.g - 13) - 7), (this.h + 16), 7, 20);
        v1.drawImage(this.e, (this.g - 13), (this.h - 8), 24);
        return;
        L315:
        if (ObfAl.l() != 3) goto L470;
        ObfAq.l.a(v1, (this.t + 1), (this.g + 5), (this.h - 7));
        ObfAq.f.a(v1, this.z, (this.g + 5), (this.h - 23));
        v1.setClip((this.g + 5), (((this.h - 20) - 5) + 2), 7, 5);
        v1.drawImage(this.e, (this.g + 5), ((this.h - 20) + 2), 36);
        v1.setClip((this.g + 13), ((this.h - 16) - 20), 7, 20);
        v1.drawImage(this.e, (this.g + 13), (this.h + 8), 36);
        L470:
        return;
    }
    // bytecode 189 bytes, max_stack 9, max_locals 2
    public void c(Graphics v1) {
        if (fcmpg(this.b_F, 0.0f) <= 0) goto L188;
        if (ObfAl.l() != 0) goto L67;
        if (this.y <= 9) goto L30;
        jt1 = ObfAq.k; /* join L33 from L24 */
        goto L33;
        L30:
        jt1 = ObfAq.j; /* join L33 from L30 */
        L33:
        jt1.b(v1, ((long) this.y), ((this.a - ObfAq.h.b(((long) this.y))) / 2), (v1.getClipHeight() / 4));
        return;
        L67:
        if (ObfAl.l() != 1) goto L128;
        if (this.y <= 9) goto L89;
        jt2 = ObfAq.k; /* join L92 from L83 */
        goto L92;
        L89:
        jt2 = ObfAq.j; /* join L92 from L89 */
        L92:
        jt2.b(v1, ((long) this.y), ((3 * v1.getClipWidth()) / 4), ((v1.getClipHeight() - ObfAq.h.b(((long) this.y))) / 2));
        return;
        L128:
        if (ObfAl.l() != 3) goto L188;
        if (this.y <= 9) goto L150;
        jt3 = ObfAq.k; /* join L153 from L144 */
        goto L153;
        L150:
        jt3 = ObfAq.j; /* join L153 from L150 */
        L153:
        jt3.b(v1, ((long) this.y), ((1 * v1.getClipWidth()) / 4), ((v1.getClipHeight() + ObfAq.h.b(((long) this.y))) / 2));
        L188:
        return;
    }
    // bytecode 30 bytes, max_stack 3, max_locals 2
    public void a(float v1) {
        if (fcmpg(this.b_F, 0.0f) <= 0) goto L19;
        this.b_F = (this.b_F - v1);
        L19:
        this.c_F = (this.c_F - v1);
        return;
    }
    // bytecode 621 bytes, max_stack 7, max_locals 3
    public void d(Graphics v1) {
        int v2 = (((this.x * this.m) / 1000) % 60);
        if (ObfAl.l() != 0) goto L224;
        if (this.a_Z == 0) goto L68;
        if (this.a_Image == null) goto L68;
        if ((v2 % 2) != 0) goto L68;
        v1.drawImage(this.a_Image, ((this.a - this.a_Image.getWidth()) / 2), 5, 20);
        L68:
        ObfAq.h.a(v1, (this.u + 1), (((this.i + 7) + 10) - ObfAq.h.a((this.u + 1))), (this.j + 4));
        ObfAq.f.a(v1, this.v, (this.i + 23), (this.j + 5));
        v1.setClip((this.i + 20), (this.j + 5), 5, 7);
        v1.drawImage(this.e, (this.i + 20), (this.j + 5), 20);
        v1.setClip((this.i + 16), (this.j + 13), 19, 7);
        v1.drawImage(this.e, (this.i + 11), (this.j + 13), 20);
        return;
        L224:
        if (ObfAl.l() != 1) goto L427;
        if (this.a_Z == 0) goto L281;
        if (this.a_Image == null) goto L281;
        if ((v2 % 2) != 0) goto L281;
        v1.drawImage(this.a_Image, (this.a - 5), ((this.b - this.a_Image.getHeight()) / 2), 24);
        L281:
        ObfAq.l.a(v1, (this.u + 1), (this.i - 5), (this.j + 7));
        ObfAq.f.a(v1, this.v, (this.i - 5), (this.j + 23));
        v1.setClip(((this.i - 5) - 7), (this.j + 20), 7, 5);
        v1.drawImage(this.e, (this.i - 5), (this.j + 20), 24);
        v1.setClip(((this.i - 13) - 7), (this.j + 16), 7, 19);
        v1.drawImage(this.e, (this.i - 13), (this.j + 11), 24);
        return;
        L427:
        if (this.a_Z == 0) goto L472;
        if (this.a_Image == null) goto L472;
        if ((v2 % 2) != 0) goto L472;
        v1.drawImage(this.a_Image, 5, ((this.b + this.a_Image.getHeight()) / 2), 36);
        L472:
        ObfAq.l.a(v1, (this.u + 1), (this.i + 5), (this.j - 7));
        ObfAq.f.a(v1, this.v, (this.i + 5), (this.j - 23));
        v1.setClip((this.i + 5), (((this.j - 20) - 5) + 1), 7, 5);
        v1.drawImage(this.e, (this.i + 5), ((this.j - 20) + 1), 36);
        v1.setClip((this.i + 13), ((this.j - 16) - 19), 7, 19);
        v1.drawImage(this.e, (this.i + 13), (this.j - 11), 36);
        return;
    }
    // bytecode 3403 bytes, max_stack 8, max_locals 13
    public void e(Graphics v1) {
        if (this.w != ObfAl.n()) goto L20;
        if (ObfAq.e_I == this.a) goto L24;
        L20:
        this.a();
        L24:
        if (this.a_B >= 4) goto L138;
        String v2 = java.lang.String.valueOf((3 - this.a_B));
        if (ObfAl.l() != 0) goto L75;
        ObfAq.c.a(v1, v2, ((ObfAq.e_I - ObfAq.c.a(v2)) / 2), (ObfAq.f / 3));
        return;
        L75:
        if (ObfAl.l() != 1) goto L111;
        ObfAq.c.a(v1, v2, ((2 * ObfAq.e_I) / 3), ((ObfAq.f - ObfAq.c.a(v2)) / 2));
        return;
        L111:
        ObfAq.c.a(v1, v2, (ObfAq.e_I / 3), ((ObfAq.f + ObfAq.c.a(v2)) / 2));
        return;
        L138:
        if (ObfAl.e_I != 0) goto L145;
        return;
        L145:
        v2 = ((String) v1.getClipX());
        int v3 = v1.getClipY();
        int v4 = v1.getClipWidth();
        int v5 = v1.getClipHeight();
        if (fcmpg(this.a_F, -100.0f) <= 0) goto L753;
        Graphics v7 = v1;
        ObfE v6 = this;
        if (this.g_Image != null) goto L297;
        ObfE v10 = v6;
        v6.g_Image = javax.microedition.lcdui.Image.createImage(80, 6);
        Graphics v8 = v10.g_Image.getGraphics();
        ObfAq.a(v10.g_Image.getGraphics(), 0, 0, 20, 6, 13631488, 15790080, 0);
        ObfAq.a(v8, 20, 0, 20, 6, 15790080, 6472704, 0);
        ObfAq.a(v8, 40, 0, 20, 6, 6472704, 15790080, 0);
        ObfAq.a(v8, 60, 0, 20, 6, 15790080, 13631488, 0);
        v10.g_Image = ObfAq.a(v10.g_Image, ObfAl.n());
        L297:
        if (ObfAl.l() != 0) goto L309;
        jt1 = ObfAq.e_I; /* join L312 from L303 */
        goto L312;
        L309:
        jt1 = ObfAq.f; /* join L312 from L309 */
        L312:
        v8 = ((Graphics) ((jt1 - 80) / 2));
        v7.setColor(0);
        if (ObfAl.l() != 0) goto L348;
        v7.drawRect((v8 - 1), 5, 81, 7);
        goto L409;
        L348:
        if (ObfAl.l() != 1) goto L381;
        v7.drawRect((((ObfAq.e_I - 5) - 6) - 2), (v8 - 1), 7, 81);
        goto L409;
        L381:
        if (ObfAl.l() != 3) goto L409;
        v7.drawRect(5, (ObfAq.f - ((v8 + 80) + 1)), 7, 81);
        L409:
        if (fcmpl(java.lang.Math.abs(v6.a_F), 0.0010000000474974513f) < 0) goto L753;
        if (fcmpl(v6.a_F, 0.0f) >= 0) goto L556;
        if (ObfAl.l() != 0) goto L466;
        v7.setClip((v8 + 40), 6, ((int) (40.0f * (-v6.a_F))), 6);
        goto L658;
        L466:
        if (ObfAl.l() != 1) goto L507;
        v7.setClip(((ObfAq.e_I - 6) - 6), (v8 + 40), 6, ((int) (40.0f * (-v6.a_F))));
        goto L658;
        L507:
        if (ObfAl.l() != 3) goto L658;
        v7.setClip(6, (ObfAq.f - ((v8 + 40) + ((int) (40.0f * (-v6.a_F))))), 6, ((int) (40.0f * (-v6.a_F))));
        goto L658;
        L556:
        int v9 = ((int) (40.0f * v6.a_F));
        if (ObfAl.l() != 0) goto L595;
        v7.setClip(((v8 + 40) - v9), 6, v9, 6);
        goto L658;
        L595:
        if (ObfAl.l() != 1) goto L631;
        v7.setClip(((ObfAq.e_I - 6) - 6), ((v8 + 40) - v9), 6, v9);
        goto L658;
        L631:
        if (ObfAl.l() != 3) goto L658;
        v7.setClip(6, (ObfAq.f - (v8 + 40)), 6, v9);
        L658:
        if (ObfAl.l() != 0) goto L683;
        v7.drawImage(v6.g_Image, v8, 6, 20);
        goto L740;
        L683:
        if (ObfAl.l() != 1) goto L713;
        v7.drawImage(v6.g_Image, (ObfAq.e_I - 6), v8, 24);
        goto L740;
        L713:
        if (ObfAl.l() != 3) goto L740;
        v7.drawImage(v6.g_Image, 6, (ObfAq.f - v8), 36);
        L740:
        v7.setClip(0, 0, ObfAq.e_I, ObfAq.f);
        L753:
        if (ObfAl.d() == 0) goto L1472;
        if (ObfAl.l() != 0) goto L1140;
        if (this.C != 0) goto L824;
        if (ObfAl.r() != 0) goto L824;
        v1.drawImage(this.e(), (8 - ((this.e().getWidth() - this.c().getWidth()) / 2)), ((ObfAq.f - this.e().getHeight()) / 2), 20);
        goto L1016;
        L824:
        if (this.C != 1) goto L888;
        if (ObfAl.r() != 0) goto L888;
        v1.drawImage(this.e(), (ObfAq.e_I - (8 - ((this.e().getWidth() - this.c().getWidth()) / 2))), ((ObfAq.f - this.e().getHeight()) / 2), 24);
        goto L1016;
        L888:
        if (this.C != 2) goto L946;
        v1.drawImage(this.e(), ((ObfAq.e_I - this.e().getWidth()) / 2), ((ObfAq.f - 40) - ((this.e().getHeight() - this.b().getHeight()) / 2)), 20);
        goto L1016;
        L946:
        if (this.C != 3) goto L1016;
        v1.drawImage(this.e(), (((ObfAq.e_I - this.a().getWidth()) - 6) - ((this.e().getWidth() - this.a().getWidth()) / 2)), (6 - ((this.e().getHeight() - this.a().getHeight()) / 2)), 20);
        L1016:
        if (ObfAl.r() != 0) goto L1047;
        v1.drawImage(this.c(), 8, ((ObfAq.f - this.c().getHeight()) / 2), 20);
        L1047:
        if (ObfAl.r() != 0) goto L1082;
        v1.drawImage(this.d(), (ObfAq.e_I - 8), ((ObfAq.f - this.d().getHeight()) / 2), 24);
        L1082:
        v1.drawImage(this.b(), ((ObfAq.e_I - this.b().getWidth()) / 2), (ObfAq.f - 40), 20);
        v1.drawImage(this.a(), ((ObfAq.e_I - this.a().getWidth()) - 6), 6, 20);
        goto L1472;
        L1140:
        if (this.C != 0) goto L1193;
        v1.drawImage(this.e(), ((ObfAq.e_I - this.e().getHeight()) / 2), (8 - ((this.e().getWidth() - this.c().getWidth()) / 2)), 20);
        goto L1371;
        L1193:
        if (this.C != 1) goto L1251;
        v1.drawImage(this.e(), ((ObfAq.e_I - this.e().getHeight()) / 2), (ObfAq.f - (8 - ((this.e().getWidth() - this.c().getWidth()) / 2))), 36);
        goto L1371;
        L1251:
        if (this.C != 2) goto L1305;
        v1.drawImage(this.e(), (40 + ((this.e().getWidth() - this.b().getWidth()) / 2)), ((ObfAq.f - this.e().getHeight()) / 2), 24);
        goto L1371;
        L1305:
        if (this.C != 3) goto L1371;
        v1.drawImage(this.e(), ((ObfAq.e_I - 6) + ((this.e().getWidth() - this.a().getWidth()) / 2)), ((ObfAq.f - 6) + ((this.e().getHeight() - this.a().getHeight()) / 2)), 40);
        L1371:
        v1.drawImage(this.c(), ((ObfAq.e_I - this.c().getHeight()) / 2), 8, 20);
        v1.drawImage(this.d(), ((ObfAq.e_I - this.d().getHeight()) / 2), (ObfAq.f - 8), 36);
        v1.drawImage(this.b(), 40, ((ObfAq.f - this.b().getHeight()) / 2), 24);
        v1.drawImage(this.a(), (ObfAq.e_I - 6), (ObfAq.f - 6), 40);
        L1472:
        this.a(v1);
        this.f(v1);
        this.b(v1);
        v1.setClip(v2, v3, v4, v5);
        this.d(v1);
        v1.setClip(v2, v3, v4, v5);
        v7 = v1;
        v6 = this;
        if (ObfAl.e_I != 2) goto L2088;
        v8 = ((Graphics) v7.getClipX());
        v9 = v7.getClipY();
        v10 = ((ObfE) v7.getClipWidth());
        v2 = ((String) v7.getClipHeight());
        if (ObfAl.l() != 0) goto L1675;
        v7.setClip(v6.n, v6.o, (v6.c_Image.getWidth() / 9), v6.c_Image.getHeight());
        v7.drawImage(v6.c_Image, (v6.n - ((v6.r * v6.c_Image.getWidth()) / 9)), v6.o, 20);
        v7.setClip(v8, v9, v10, v2);
        v7.drawImage(v6.d_Image, (v6.n + 12), (v6.o + 9), 20);
        goto L1934;
        L1675:
        if (ObfAl.l() != 1) goto L1808;
        v7.setClip((v6.n - v6.c_Image.getWidth()), v6.o, v6.c_Image.getWidth(), (v6.c_Image.getHeight() / 9));
        v7.drawImage(v6.c_Image, v6.n, (v6.o - ((v6.r * v6.c_Image.getHeight()) / 9)), 24);
        v7.setClip(v8, v9, v10, v2);
        v7.drawImage(v6.d_Image, (v6.n - 9), (v6.o + 12), 24);
        goto L1934;
        L1808:
        v7.setClip(v6.n, (v6.o - (v6.c_Image.getHeight() / 9)), v6.c_Image.getWidth(), (v6.c_Image.getHeight() / 9));
        v7.drawImage(v6.c_Image, v6.n, (v6.o + ((v6.r * v6.c_Image.getHeight()) / 9)), 36);
        v7.setClip(v8, v9, v10, v2);
        v7.drawImage(v6.d_Image, (v6.n + 9), (v6.o - 12), 36);
        L1934:
        if (ObfAl.l() != 0) goto L1988;
        ObfAq.g.a(v7, v6.l, (((40 + v6.n) - ObfAq.g.a(v6.l)) - 1), ((v6.o + 12) - 1));
        goto L2088;
        L1988:
        if (ObfAl.l() != 1) goto L2043;
        ObfAq.g.a(v7, v6.l, ((-12 + v6.n) - 1), (((v6.o + 40) - ObfAq.g.a(v6.l)) - 1));
        goto L2088;
        L2043:
        ObfAq.g.a(v7, v6.l, ((12 + v6.n) - 1), (((v6.o - 40) + ObfAq.g.a(v6.l)) - 1));
        L2088:
        v7 = v1;
        v6 = this;
        if (this.f_Image == null) goto L3181;
        if (ObfAl.e_I != 2) goto L3181;
        v8 = ((Graphics) v6.f_Image.getWidth());
        v9 = v6.f_Image.getHeight();
        if (ObfAl.l() == 0) goto L2148;
        v8 = ((Graphics) v9);
        v9 = v6.f_Image.getWidth();
        L2148:
        v10 = ((ObfE) (-(((int) (3.0f * ((v6.a_arrLcl[0].a().b() / ObfAr.c_F) + 0.5f))) - (v8 / 2))));
        v2 = ((String) (-(((int) (3.0f * ((v6.a_arrLcl[0].a().c() / ObfAr.c_F) + 0.5f))) - (v9 / 2))));
        if (v8 > 32) goto L2224;
        v10 = ((ObfE) 0);
        goto L2261;
        L2224:
        v3 = ((v8 / 2) - java.lang.Math.abs(v10));
        if (((v8 / 2) - java.lang.Math.abs(v10)) >= 16) goto L2261;
        if (v10 >= 0) goto L2250;
        jt2 = m1; /* join L2251 from L2246 */
        goto L2251;
        L2250:
        jt2 = 1; /* join L2251 from L2250 */
        L2251:
        v10 = ((ObfE) (jt2 * ((v8 / 2) - 16)));
        L2261:
        if (v9 >= 32) goto L2273;
        v2 = ((String) 0);
        goto L2307;
        L2273:
        v3 = ((v9 / 2) - java.lang.Math.abs(v2));
        if (((v9 / 2) - java.lang.Math.abs(v2)) >= 16) goto L2307;
        if (v2 >= 0) goto L2297;
        jt3 = m1; /* join L2298 from L2293 */
        goto L2298;
        L2297:
        jt3 = 1; /* join L2298 from L2297 */
        L2298:
        v2 = ((String) (jt3 * ((v9 / 2) - 16)));
        L2307:
        v10 = ((ObfE) (v10 - ((v8 / 2) - 16)));
        v2 = ((String) (v2 - ((v9 / 2) - 16)));
        if (ObfAl.l() != 0) goto L2416;
        v7.setColor(5131854);
        v7.fillRect((v6.p - 1), (v6.q - 1), 34, 34);
        v7.setColor(0);
        v7.drawRect((v6.p - 2), (v6.q - 2), 35, 35);
        v7.setClip(v6.p, v6.q, 32, 32);
        goto L2626;
        L2416:
        if (ObfAl.l() != 1) goto L2526;
        v7.setColor(5131854);
        v7.fillRect((((v6.p - 1) - 32) + 1), (v6.q - 1), 34, 34);
        v7.setColor(0);
        v7.drawRect((((v6.p - 2) - 32) + 1), (v6.q - 2), 35, 35);
        v7.setClip((v6.p - 32), v6.q, 32, 32);
        v3 = v10;
        v10 = ((ObfE) (-v2));
        v2 = ((String) v3);
        goto L2626;
        L2526:
        v7.setColor(5131854);
        v7.fillRect((v6.p - 1), (((v6.q - 1) - 32) + 2), 34, 34);
        v7.setColor(0);
        v7.drawRect((v6.p - 2), (((v6.q - 2) - 32) + 2), 35, 35);
        v7.setClip(v6.p, (v6.q - 32), 32, 32);
        v3 = v10;
        v10 = ((ObfE) v2);
        v2 = ((String) (-v3));
        L2626:
        if (ObfAl.l() != 1) goto L2659;
        jt4 = v6.f_Image.getWidth(); /* join L2660 from L2648 */
        goto L2660;
        L2659:
        jt4 = 0; /* join L2660 from L2659 */
        L2660:
        if (ObfAl.l() != 3) goto L2686;
        jt5 = v6.f_Image.getHeight(); /* join L2687 from L2675 */
        goto L2687;
        L2686:
        jt5 = 0; /* join L2687 from L2686 */
        L2687:
        v7.drawImage(v6.f_Image, ((v6.p + v10) - jt4), ((v6.q + v2) - jt5), 20);
        v9 = (v6.s - 1);
        L2702:
        if (v9 < 0) goto L3168;
        v3 = ((int) ((v6.a_arrLcl[v9].a().b() / ObfAr.c_F) + 0.5f));
        v4 = ((int) ((v6.a_arrLcl[v9].a().c() / ObfAr.c_F) + 0.5f));
        v8 = ((Graphics) ((int) v3));
        v5 = ((int) v4);
        v3 = ((int) (v3 - ((float) v8)));
        v4 = ((int) (v4 - ((float) v5)));
        v8 += 1;
        int v11 = v6.p;
        int v12 = v6.q;
        if (ObfAl.l() != 1) goto L2805;
        v12 += -2;
        v11 += 1;
        L2805:
        if (ObfAl.l() != 3) goto L2818;
        v11 += 1;
        v12 += 4;
        L2818:
        v7.setColor(v6.a_arrI[(v9 * 2)]);
        if (ObfAl.l() != 0) goto L2887;
        v7.drawRect((((((v11 + (v8 * 3)) + ((int) (v3 * 3.0f))) - 1) + v10) - 3), ((((v12 + (v5 * 3)) + ((int) (v4 * 3.0f))) - 1) + v2), 2, 2);
        goto L2995;
        L2887:
        if (ObfAl.l() != 1) goto L2946;
        v7.drawRect(((((v11 - (((v5 * 3) + ((int) (v4 * 3.0f))) - 1)) - 3) + v10) - 1), (((v12 + (((v8 * 3) + ((int) (v3 * 3.0f))) - 1)) + v2) - 1), 2, 2);
        goto L2995;
        L2946:
        v7.drawRect((((((v11 + (v5 * 3)) + ((int) (v4 * 3.0f))) - 1) + v10) - 1), ((((v12 - (((v8 * 3) + ((int) (v3 * 3.0f))) - 1)) - 3) + v2) - 1), 2, 2);
        L2995:
        v7.setColor(v6.a_arrI[((v9 * 2) + 1)]);
        if (ObfAl.l() != 0) goto L3062;
        v7.fillRect(((((v11 + (v8 * 3)) + ((int) (v3 * 3.0f))) + v10) - 3), (((v12 + (v5 * 3)) + ((int) (v4 * 3.0f))) + v2), 1, 1);
        goto L3162;
        L3062:
        if (ObfAl.l() != 1) goto L3117;
        v7.fillRect(((((v11 - ((v5 * 3) + ((int) (v4 * 3.0f)))) - 1) + v10) - 1), (((v12 + ((v8 * 3) + ((int) (v3 * 3.0f)))) + v2) - 1), 1, 1);
        goto L3162;
        L3117:
        v7.fillRect(((((v11 + (v5 * 3)) + ((int) (v4 * 3.0f))) + v10) - 1), ((((v12 - ((v8 * 3) + ((int) (v3 * 3.0f)))) - 1) + v2) - 1), 1, 1);
        L3162:
        v9 += -1;
        goto L2702;
        L3168:
        v7.setClip(0, 0, ObfAq.e_I, ObfAq.f);
        L3181:
        this.c(v1);
        if (fcmpg(this.c_F, 0.0f) <= 0) goto L3402;
        if (ObfAl.l() != 0) goto L3257;
        ObfAq.b.a(v1, this.a_String, ((v1.getClipWidth() - this.B) / 2), 11);
        ObfAq.b.a(v1, ObfAq.a(198), (((v1.getClipWidth() - this.B) / 2) + this.A), 11);
        return;
        L3257:
        if (ObfAl.l() != 1) goto L3330;
        ObfAq.a.a(v1, this.a_String, (v1.getClipWidth() - 11), ((v1.getClipHeight() - this.B) / 2));
        ObfAq.a.a(v1, ObfAq.a(198), (v1.getClipWidth() - 11), (((v1.getClipHeight() - this.B) / 2) + this.A));
        return;
        L3330:
        if (ObfAl.l() != 3) goto L3402;
        ObfAq.a.a(v1, this.a_String, 11, (v1.getClipHeight() - ((v1.getClipHeight() - this.B) / 2)));
        ObfAq.a.a(v1, ObfAq.a(198), 11, (v1.getClipHeight() - (((v1.getClipHeight() - this.B) / 2) + this.A)));
        L3402:
        return;
    }
    // bytecode 32 bytes, max_stack 2, max_locals 2
    public Image e() {
        /* try L7-L19 catch java.lang.Exception -> L22 */
        if (this.j_Image != null) goto L27;
        this.j_Image = javax.microedition.lcdui.Image.createImage(ObfBl.a("/images/touched.png"));
        goto L27;
        java.lang.Exception v1 = ex_22;
        ex_22.printStackTrace();
        L27:
        return this.j_Image;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void j(int v1) {
        this.u = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void k(int v1) {
        this.v = v1;
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 2
    public void l(int v1) {
        this.k = v1;
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void f(Graphics v1) {
        return;
    }
    // bytecode 64 bytes, max_stack 4, max_locals 2
    public void a(String v1) {
        new java.lang.StringBuffer(); /* constructor */
        this.a_String = new java.lang.StringBuffer().append(v1).append(" ").toString();
        this.A = ObfAq.b.a(this.a_String);
        this.B = (this.A + ObfAq.b.a(ObfAq.a(198)));
        this.c_F = 2.0f;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public ObfE() {
        super();
        return;
    }
    // bytecode 399 bytes, max_stack 4, max_locals 12
    public static byte[] a(byte[] v0) {
        /* try L56-L388 catch java.io.IOException -> L391 */
        new ObfCj(); /* constructor */
        ObfCj v1 = new ObfCj();
        int v5 = 0;
        int v6 = 8388607;
        int v8 = 0;
        int v9 = 0;
        int v10 = new int[257];
        int v11 = 0;
        L31:
        if (v11 >= 257) goto L51;
        v10[v11] = 1;
        v11 += 1;
        goto L31;
        L51:
        int v4 = 257;
        v11 = 0;
        L59:
        if (v11 >= (v0.length + 1)) goto L321;
        if (v11 != v0.length) goto L86;
        int v2 = (v4 - 1);
        int v3 = v4;
        goto L127;
        L86:
        v9 = (v0[v11] & 255);
        v2 = 0;
        v3 = 0;
        L100:
        if (v3 >= v9) goto L119;
        v2 = (v2 + v10[v3]);
        v3 += 1;
        goto L100;
        L119:
        v3 = (v2 + v10[v9]);
        L127:
        int v7 = (((v6 - v5) + 1) / v4);
        v6 = ((v5 + (v7 * v3)) - 1);
        v5 = (v5 + (v7 * v2));
        L159:
        if (v6 < 4194304) goto L173;
        if (v5 < 4194304) goto L263;
        L173:
        if (v6 >= 4194304) goto L215;
        v1.a(0);
        v5 = (v5 << 1);
        v6 = ((v6 << 1) + 1);
        L199:
        if (v8 <= 0) goto L159;
        v1.a(1);
        v8 += -1;
        goto L199;
        L215:
        if (v5 < 4194304) goto L159;
        v1.a(1);
        v5 = ((v5 - 4194304) << 1);
        v6 = (((v6 - 4194304) << 1) + 1);
        L247:
        if (v8 <= 0) goto L159;
        v1.a(0);
        v8 += -1;
        goto L247;
        L263:
        if (2097152 > v5) goto L303;
        if (v6 >= 6291456) goto L303;
        v8 += 1;
        v5 = ((v5 - 2097152) << 1);
        v6 = (((v6 - 2097152) << 1) + 1);
        goto L263;
        L303:
        v10[v9] = (v10[v9] + 1);
        v4 += 1;
        v11 += 1;
        goto L59;
        L321:
        if (v5 >= 2097152) goto L359;
        v1.a(0);
        v11 = 0;
        L336:
        if (v11 >= (v8 + 1)) goto L356;
        v1.a(1);
        v11 += 1;
        goto L336;
        L356:
        goto L364;
        L359:
        v1.a(1);
        L364:
        v0 = ((byte[]) v1);
        L366:
        if (v0.a_B == 0) goto L381;
        v0.a(0);
        goto L366;
        L381:
        v0.a.flush();
        goto L394;
        /* pop: ex_391; */
        return null;
        L394:
        return v1.a();
    }
    // bytecode 365 bytes, max_stack 4, max_locals 10
    public static byte[] b(byte[] v0) {
        if (v0 == null) goto L9;
        if (v0.length != 0) goto L13;
        L9:
        return new byte[0];
        L13:
        new java.io.ByteArrayOutputStream(); /* constructor */
        java.io.ByteArrayOutputStream v1 = new java.io.ByteArrayOutputStream();
        int v2 = new int[257];
        int v3 = 0;
        L29:
        if (v3 >= 257) goto L46;
        v2[v3] = 1;
        v3 += 1;
        goto L29;
        L46:
        v3 = 257;
        int v6 = 0;
        int v4 = 8388607;
        int v8 = 0;
        new ObfDa(v0); /* constructor */
        ObfDa v9 = new ObfDa(v0);
        v0 = ((byte[]) 0);
        L72:
        if (v0 >= 23) goto L99;
        v8 = (v8 * 2);
        v8 = ((v8 * 2) + v9.a());
        v0 += 1;
        goto L72;
        L99:
        int v7 = (((v4 - v6) + 1) / v3);
        v4 = ((v8 - v6) / v7);
        int v5 = 0;
        v0 = ((byte[]) 0);
        L125:
        if (v0 >= 256) goto L157;
        if ((v5 + v2[v0]) > v4) goto L157;
        v5 = (v5 + v2[v0]);
        v0 += 1;
        goto L125;
        L157:
        if (v0 == 256) goto L360;
        v1.write(v0);
        v4 = (v5 + v2[v0]);
        v4 = ((v6 + (v7 * v4)) - 1);
        v6 = (v6 + (v7 * v5));
        L199:
        if (v4 < 4194304) goto L213;
        if (v6 < 4194304) goto L292;
        L213:
        if (v4 >= 4194304) goto L243;
        v6 = (v6 << 1);
        v4 = ((v4 << 1) + 1);
        v8 = (v8 * 2);
        goto L279;
        L243:
        if (v6 < 4194304) goto L279;
        v6 = (2 * (v6 - 4194304));
        v4 = ((2 * (v4 - 4194304)) + 1);
        v8 = (2 * (v8 - 4194304));
        L279:
        v8 = (v8 + v9.a());
        goto L199;
        L292:
        if (2097152 > v6) goto L347;
        if (v4 >= 6291456) goto L347;
        v6 = (2 * (v6 - 2097152));
        v4 = ((2 * (v4 - 2097152)) + 1);
        v8 = (2 * (v8 - 2097152));
        v8 = ((2 * (v8 - 2097152)) + v9.a());
        goto L292;
        L347:
        v2[v0] = (v2[v0] + 1);
        v3 += 1;
        goto L99;
        L360:
        return v1.toByteArray();
    }
}

