// Generated by tools/jdeob.py from x/h.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `h`.
// String constants: <init> | Code | KORa | fillRect | java/io/IOException | java/util/Random | javax/microedition/lcdui/Graphics | nextInt | rand | setColor | StackMap
// API references: java/util javax/microedition
public class ObfH extends MenuScreen {
    private boolean f;
    // bytecode 15 bytes, max_stack 2, max_locals 2
    public ObfH(MainCanvas v1) {
        super(v1);
        this.f = false;
        ObfR.b_Z = false;
        return;
    }
    // bytecode 86 bytes, max_stack 4, max_locals 4
    public void b() {
        ObfR.c_arrI = new int[ObfR.l]#1;
        int v2 = 0;
        L10:
        if (v2 >= ObfR.l) goto L85;
        L17:
        int v1 = 1;
        ObfR.c_arrI[v2] = KORa.rand.nextInt(4);
        if (ObfR.c_arrI[v2] != ObfR.h) goto L47;
        v1 = 0;
        goto L75;
        L47:
        int v3 = 0;
        L49:
        if (v3 >= v2) goto L75;
        if (ObfR.c_arrI[v2] != ObfR.c_arrI[v3]) goto L69;
        v1 = 0;
        L69:
        v3 += 1;
        goto L49;
        L75:
        if (v1 == 0) goto L17;
        v2 += 1;
        goto L10;
        L85:
        return;
    }
    // bytecode 42 bytes, max_stack 5, max_locals 2
    public void a(Graphics v1) {
        if (this.f != 0) goto L36;
        if (ObfR.a_B > 21) goto L36;
        v1.setColor(0);
        v1.fillRect(0, (SysUtil.f_I - 25), SysUtil.e_I, 25);
        L36:
        this.a(v1);
        return;
    }
    // bytecode 20 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        if (ObfR.a_B != 22) goto L14;
        ObfR.a_B = 24;
        return;
        L14:
        this.a(v1);
        return;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void a() {
        this.f = true;
        return;
    }
}

