// Generated by tools/jdeob.py from x/i.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `i`.
// String constants: ()F | ()Lbj; | ()V | (FF)V | (FF)Z | (FFF)V | (FFFF)Lbj; | (FFFF)V | (FFFFFFFFF)V | (Lbz;Lbz;)F | (Lbz;Lbz;)V | (Lbz;Lz;)F
public class ObfI {
    private float a;
    private float b;
    private float c;
    private float d;
    private float e;
    private float f;
    private ObfBz a_bz;
    private ObfBz b_bz;
    private ObfBj a_bj;
    private static ObfZ a_z;
    static {
        new ObfZ(0.0f, 0.0f); /* constructor */
        ObfI.a_z = new ObfZ(0.0f, 0.0f);
        return;
    }
    // bytecode 247 bytes, max_stack 9, max_locals 10
    public ObfI(float v1, float v2, float v3, float v4, float v5, float v6, float v7, float v8, float v9) {
        super();
        this.a = 0.0f;
        this.b = 0.0f;
        this.c = 0.0f;
        this.d = 0.0f;
        this.a_bz = null;
        this.b_bz = null;
        this.a_bj = null;
        new ObfBz((v7 - v1), (v8 - v2), (v9 - v3)); /* constructor */
        this.a_bz = new ObfBz((v7 - v1), (v8 - v2), (v9 - v3));
        new ObfBz((v4 - v1), (v5 - v2), (v6 - v3)); /* constructor */
        this.b_bz = new ObfBz((v4 - v1), (v5 - v2), (v6 - v3));
        this.a = ObfZ.a(this.a_bz, this.a_bz);
        this.b = ObfZ.a(this.a_bz, this.b_bz);
        this.c = ObfZ.a(this.b_bz, this.b_bz);
        this.d = (1.0f / ((this.a * this.c) - (this.b * this.b)));
        this.e = v1;
        this.f = v2;
        new ObfBz(0.0f, 0.0f, 0.0f); /* constructor */
        v4 = ((float) new ObfBz(0.0f, 0.0f, 0.0f));
        new ObfBz(0.0f, 0.0f, 0.0f).b(this.a_bz, this.b_bz);
        new ObfBj(v4.a(), v4.b(), v4.c(), (-(((v4.a() * v1) + (v4.b() * v2)) + (v4.c() * v3)))); /* constructor */
        this.a_bj = new ObfBj(v4.a(), v4.b(), v4.c(), (-(((v4.a() * v1) + (v4.b() * v2)) + (v4.c() * v3))));
        this.a_bj.a();
        return;
    }
    // bytecode 102 bytes, max_stack 4, max_locals 4
    public boolean a(float v1, float v2) {
        ObfI.a_z.b((v1 - this.e), (v2 - this.f));
        v1 = ObfZ.a(this.a_bz, ObfI.a_z);
        v2 = ObfZ.a(this.b_bz, ObfI.a_z);
        float v3 = (((this.c * v1) - (this.b * v2)) * this.d);
        v1 = (((this.a * v2) - (this.b * v1)) * this.d);
        if (fcmpg(v3, 0.0f) < 0) goto L100;
        if (fcmpg(v1, 0.0f) < 0) goto L100;
        if (fcmpl((v3 + v1), 1.0f) > 0) goto L100;
        return 1;
        L100:
        return 0;
    }
    // bytecode 35 bytes, max_stack 5, max_locals 1
    public ObfBj a() {
        return ObfAq.a_bj.a(this.a_bj.a(), this.a_bj.b(), this.a_bj.c(), this.a_bj.d());
    }
}

