// Generated by tools/jdeob.py from x/w.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `w`.
// String constants: <clinit> | <init> | ?a=m | Code | append | createImage | drawImage | drawRect | fillRect | getClipHeight | getClipWidth | getGraphics
// API references: java/io javax/microedition
public class ObfW extends MenuScreen {
    public static MainMenu a;
    private int s;
    private byte[] a_arrB;
    static {
        ObfW.a = null;
        return;
    }
    // bytecode 52 bytes, max_stack 2, max_locals 3
    public ObfW(MainCanvas v1, int v2) {
        super(v1);
        new java.lang.StringBuffer(); /* constructor */
        /* pop: new java.lang.StringBuffer().append(Settings.b_String).append("?a=m").toString(); */
        this.s = 0;
        this.a_arrB = null;
        ObfCl.f_Z = true;
        this.s = v2;
        this.c = true;
        return;
    }
    // bytecode 46 bytes, max_stack 2, max_locals 1
    public void b() {
        ObfR.k = ObfW.a.f();
        ObfR.j = ObfW.a.g();
        this.a_arrB = ObfW.a.a();
        ObfR.j = ObfW.a.g();
        ObfR.m = 1;
        ObfR.l = 0;
        return;
    }
    // bytecode 28 bytes, max_stack 8, max_locals 1
    public void q() {
        new java.io.ByteArrayInputStream(this.a_arrB); /* constructor */
        new ObfBt(this.a, this, new java.io.ByteArrayInputStream(this.a_arrB)); /* constructor */
        this.a = new ObfBt(this.a, this, new java.io.ByteArrayInputStream(this.a_arrB));
        return;
    }
    // bytecode 119 bytes, max_stack 5, max_locals 2
    public void c() {
        new TouchButtons(this.a.getWidth(), this.a.getHeight()); /* constructor */
        this.a = new TouchButtons(this.a.getWidth(), this.a.getHeight());
        this.a.e(0);
        this.a.a(this.a.a());
        int v1 = 0;
        L49:
        if (v1 >= this.d()) goto L78;
        this.a.a(this.a.a(v1));
        v1 += 1;
        goto L49;
        L78:
        this.a.j(0);
        this.a.k(this.c());
        this.a.a(0);
        this.a.e(ObfW.a.i());
        return;
    }
    // bytecode 10 bytes, max_stack 1, max_locals 1
    public void o() {
        ObfW.a(ObfW.a.a());
        return;
    }
    // bytecode 21 bytes, max_stack 5, max_locals 1
    public void p() {
        new ObfBs(ObfBb.a_cf, ObfW.a.a()); /* constructor */
        this.a = new ObfBs(ObfBb.a_cf, ObfW.a.a());
        return;
    }
    // bytecode 19 bytes, max_stack 2, max_locals 2
    public int c(int v1) {
        if (this.s != 0) goto L13;
        return this.c(v1);
        L13:
        return this.d(v1);
    }
    // bytecode 235 bytes, max_stack 9, max_locals 6
    public void d(Graphics v1) {
        int v2 = ((15 * v1.getClipHeight()) / 196);
        if (((15 * v1.getClipHeight()) / 196) <= 20) goto L21;
        v2 = 20;
        L21:
        if (Settings.l() != 0) goto L45;
        jt1 = ((v1.getClipHeight() - ((v2 * 4) << 1)) - this.e); /* join L55 from L27 */
        goto L55;
        L45:
        jt1 = (v1.getClipWidth() - ((v2 * 4) << 1)); /* join L55 from L45 */
        L55:
        int v3 = (jt1 / 7);
        if ((jt1 / 7) <= 30) goto L68;
        v3 = 30;
        L68:
        int v4 = ((v2 * 2) + v3);
        if (this.a != null) goto L181;
        this.a = javax.microedition.lcdui.Image.createImage((v1.getClipWidth() - 20), (v2 * 2));
        Graphics v5 = this.a.getGraphics();
        SysUtil.a(this.a.getGraphics(), 0, 0, (v1.getClipWidth() - 20), (v2 << 1), 5592405, 10066329, true);
        v5.setColor(10066329);
        v5.fillRect(0, v2, ((v1.getClipWidth() - 20) - 1), v2);
        v5.setColor(7829367);
        v5.drawRect(0, 0, ((v1.getClipWidth() - 20) - 1), ((v2 << 1) - 1));
        L181:
        if (Settings.l() != 0) goto L234;
        v1.setColor(7829367);
        this.b(v1, 0, 171, ObfW.a.i(), 10, v3, v2, v4);
        this.b(v1, 1, 172, this.c(0), 10, v3, v2, v4);
        L234:
        return;
    }
    // bytecode 156 bytes, max_stack 8, max_locals 10
    public void b(Graphics v1, int v2, int v3, int v4, int v5, int v6, int v7, int v8) {
        v5 = (v6 + (v8 * v2));
        if ((v2 % 2) != 0) goto L23;
        jt1 = (-this.a); /* join L27 from L15 */
        goto L27;
        L23:
        jt1 = this.a; /* join L27 from L23 */
        L27:
        int v9 = ((int) jt1);
        v1.drawImage(this.a, (v9 + 10), v5, 20);
        v5 = (((v2 * v8) + v6) + ((v7 - 7) / 2));
        v3 = ((int) SysUtil.a(v3));
        SysUtil.a_p.a(v1, v3, ((((v1.getClipWidth() - 10) - 6) - SysUtil.a_p.a(v3)) + v9), v5);
        v5 = ((((v2 * v8) + v6) + v7) + ((v7 - 7) / 2));
        SysUtil.a_p.a(v1, ((long) v4), ((((v1.getClipWidth() - 10) - 6) - SysUtil.a_p.a(((long) v4))) + v9), v5);
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 2
    public void e(Graphics v1) {
        return;
    }
    // bytecode 20 bytes, max_stack 2, max_locals 2
    public void a(int v1) {
        if (ObfR.a_B != 22) goto L14;
        ObfR.a_B = 24;
        return;
        L14:
        this.a(v1);
        return;
    }
    // bytecode 14 bytes, max_stack 2, max_locals 1
    public void k() {
        this.a.e(ObfW.a.i());
        return;
    }
    // bytecode 29 bytes, max_stack 2, max_locals 2
    public int b() {
        ObfCl v1 = this.a.a(this.e());
        if (this.s != 0) goto L24;
        return v1.e();
        L24:
        return v1.d();
    }
}

