// Generated by tools/jdeob.py from x/cw.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cw`.
// String constants: <clinit> | <init> | Code | KORa | abs | drawRGB | java/lang/Math | java/lang/Object | java/lang/System | java/util/Random | javax/microedition/lcdui/Graphics | nextInt
// API references: java/util javax/microedition
public class Planet {
    private static int[] a;
    private static int a_I;
    private static int b;
    private static int c;
    private static int d;
    private static boolean a_Z;
    private static int e;
    private static byte a_B;
    private static boolean b_Z;
    private static int f;
    static {
        Planet.d = 0;
        Planet.a_B = m1;
        Planet.b_Z = false;
        Planet.f = 20;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Planet() {
        super();
        return;
    }
    // bytecode 42 bytes, max_stack 2, max_locals 0
    public static void c() {
        Planet.c = 20;
        Planet.a_I = Planet.f;
        Planet.b = Planet.f;
        Planet.a = new int[(Planet.a_I * Planet.b)];
        Planet.a_B = 1;
        Planet.a(1);
        Planet.b_Z = true;
        return;
    }
    // bytecode 320 bytes, max_stack 4, max_locals 3
    public static void a() {
        if (Planet.b_Z != 0) goto L9;
        Planet.c();
        L9:
        if (Planet.a_Z == 0) goto L16;
        return;
        L16:
        switch (Planet.a_B) {
        case 0: goto L48;
        case 1: goto L116;
        case 2: goto L180;
        case 3: goto L253;
        default: goto L300;
        }
        L48:
        int v1 = 0;
        int v2 = 0;
        L52:
        if (v2 >= Planet.e) goto L113;
        v1 += 1;
        if (v1 != (Planet.e * 5)) goto L72;
        return;
        L72:
        int v0 = java.lang.Math.abs((KORa.rand.nextInt() % Planet.a.length));
        if (Planet.a[v0] == 0) goto L104;
        Planet.a[v0] = 0;
        goto L107;
        L104:
        v2 += -1;
        L107:
        v2 += 1;
        goto L52;
        L113:
        goto L300;
        L116:
        v2 = 0;
        L118:
        if (v2 >= Planet.a.length) goto L177;
        v0 = (Planet.a[v2] >>> 24);
        v1 = (Planet.a[v2] & 16777215);
        v0 = (v0 - Planet.e);
        if ((v0 - Planet.e) >= 0) goto L156;
        v0 = 0;
        L156:
        v0 = (v0 << 24);
        v1 = (v1 + v0);
        Planet.a[v2] = v1;
        v2 += 1;
        goto L118;
        L177:
        goto L300;
        L180:
        v2 = 0;
        L182:
        if (v2 >= Planet.a.length) goto L250;
        v0 = (Planet.a[v2] >>> 24);
        if ((Planet.a[v2] >>> 24) == 0) goto L244;
        v1 = (Planet.a[v2] & 16777215);
        v0 = (v0 + Planet.e);
        if ((v0 + Planet.e) <= 255) goto L229;
        v0 = 255;
        L229:
        v0 = (v0 << 24);
        v1 = (v1 + v0);
        Planet.a[v2] = v1;
        L244:
        v2 += 1;
        goto L182;
        L250:
        goto L300;
        L253:
        v2 = ((Planet.d * Planet.a_I) * Planet.e);
        v0 = ((Planet.d * Planet.a_I) * Planet.e);
        L267:
        if (v0 >= (v2 + (Planet.a_I * Planet.e))) goto L300;
        if (v0 >= Planet.a.length) goto L300;
        Planet.a[v0] = 0;
        v0 += 1;
        goto L267;
        L300:
        Planet.d = (Planet.d + 1);
        if ((Planet.d + 1) != Planet.c) goto L319;
        Planet.a_Z = true;
        L319:
        return;
    }
    // bytecode 80 bytes, max_stack 9, max_locals 3
    public static void a(Graphics v0, int v1, int v2) {
        if (Planet.b_Z != 0) goto L9;
        Planet.c();
        L9:
        v1 = 0;
        L11:
        if (v1 > (SysUtil.f / Planet.f)) goto L79;
        v2 = 0;
        L24:
        if (v2 > (SysUtil.e / Planet.f)) goto L73;
        v0.drawRGB(Planet.a, 0, Planet.a_I, (0 + (v2 * Planet.f)), (0 + (v1 * Planet.f)), Planet.a_I, Planet.b, true);
        v2 += 1;
        goto L24;
        L73:
        v1 += 1;
        goto L11;
        L79:
        return;
    }
    // bytecode 4 bytes, max_stack 1, max_locals 0
    public static boolean a() {
        return Planet.a_Z;
    }
    // bytecode 263 bytes, max_stack 3, max_locals 3
    public static void a(byte v0) {
        if (Planet.b_Z != 0) goto L9;
        Planet.c();
        L9:
        Planet.a_Z = false;
        Planet.d = 0;
        Planet.a_B = v0;
        v0 = ((byte) 0);
        L23:
        if (v0 >= Planet.a.length) goto L44;
        Planet.a[v0] = -16777216;
        v0 += 1;
        goto L23;
        L44:
        switch (Planet.a_B) {
        case 0: goto L80;
        case 1: goto L92;
        case 2: goto L105;
        case 3: goto L175;
        case 4: goto L205;
        default: goto L262;
        }
        L80:
        Planet.e = (Planet.a.length / Planet.c);
        return;
        L92:
        Planet.e = ((255 / Planet.c) + 1);
        return;
        L105:
        v0 = ((byte) 0);
        L107:
        if (v0 >= Planet.a.length) goto L154;
        int v1 = (Planet.a[v0] >>> 24);
        if ((Planet.a[v0] >>> 24) == 0) goto L148;
        int v2 = (Planet.a[v0] & 16777215);
        v2 = ((Planet.a[v0] & 16777215) + 16777216);
        Planet.a[v0] = v2;
        L148:
        v0 += 1;
        goto L107;
        L154:
        Planet.e = ((255 / Planet.c) + 1);
        Planet.c = (Planet.c + 5);
        return;
        L175:
        Planet.e = (Planet.b / Planet.c);
        if (((Planet.b / Planet.c) * Planet.c) >= Planet.b) goto L262;
        Planet.e = (Planet.e + 1);
        return;
        L205:
        v0 = ((byte) 0);
        L207:
        if (v0 >= Planet.a.length) goto L262;
        v1 = (Planet.a[v0] >>> 24);
        if ((Planet.a[v0] >>> 24) == 0) goto L256;
        v2 = (Planet.a[v0] & 16777215);
        v1 = Planet.c;
        v1 = (Planet.c << 24);
        v2 = (v2 + v1);
        Planet.a[v0] = v2;
        L256:
        v0 += 1;
        goto L207;
        L262:
        return;
    }
    // bytecode 18 bytes, max_stack 1, max_locals 0
    public static void b() {
        Planet.a = null;
        if (Settings.e != 0) goto L13;
        java.lang.System.gc();
        L13:
        Planet.b_Z = false;
        return;
    }
}

