// Generated by tools/jdeob.py from x/ct.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `ct`.
// String constants: <clinit> | <init> | Code | abs | java/lang/Math | java/lang/Object | StackMap
public class Plane {
    private Vec2 a;
    private float a_F;
    private Vec2 b;
    private Vec2 c;
    private static Vec2 d;
    private static Vec2 e;
    static {
        new Vec2(0.0f, 0.0f); /* constructor */
        Plane.d = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        Plane.e = new Vec2(0.0f, 0.0f);
        return;
    }
    // bytecode 64 bytes, max_stack 5, max_locals 1
    public Plane() {
        super();
        this.a = null;
        this.a_F = 0.0f;
        this.b = null;
        this.c = null;
        new Vec2(0.0f, 0.0f); /* constructor */
        this.a = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.b = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.c = new Vec2(0.0f, 0.0f);
        return;
    }
    // bytecode 21 bytes, max_stack 5, max_locals 3
    public void a(Vec3 v1, Vec3 v2) {
        this.a(v1.a__float(), v1.b__float(), v2.a__float(), v2.b__float());
        return;
    }
    // bytecode 13 bytes, max_stack 5, max_locals 5
    public Plane(float v1, float v2, float v3, float v4) {
        this();
        this.a(0.0f, 0.0f, 0.0f, 0.0f);
        return;
    }
    // bytecode 59 bytes, max_stack 5, max_locals 4
    public void a(Vec3 v1, float v2, float v3) {
        this.b.b(v1.a__float(), v1.b__float());
        this.a.b(v2, v3);
        v2 = ((float) this);
        v2 = ((float) this);
        this.a_F = (-((v1.a__float() * this.a.a__float()) + (v1.b__float() * this.a.b__float())));
        return;
    }
    // bytecode 71 bytes, max_stack 5, max_locals 6
    public void a(float v1, float v2, float v3, float v4) {
        this.a.b((v4 - v2), (v1 - v3));
        this.a.a();
        Plane v5 = this;
        v5 = this;
        this.a_F = (-((v1 * this.a.a__float()) + (v2 * this.a.b__float())));
        this.b.b(v1, v2);
        this.c.b(v3, v4);
        return;
    }
    // bytecode 8 bytes, max_stack 1, max_locals 1
    public float a__float() {
        return this.a.a__float();
    }
    // bytecode 8 bytes, max_stack 1, max_locals 1
    public float b__float() {
        return this.a.b__float();
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec2 a__Vec2() {
        return this.a;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec2 b__Vec2() {
        return this.b;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public Vec2 c() {
        return this.c;
    }
    // bytecode 76 bytes, max_stack 3, max_locals 1
    public static boolean a__boolean() {
        Plane v0 = ObfAu.b;
        v0 = ObfAu.a;
        v0 = ObfAu.b;
        v0 = ((Plane) (Vec2.a(ObfAu.b.a, ObfAu.a.b) + ObfAu.b.a_F));
        if (fcmpg((Vec2.a(ObfAu.b.a, ObfAu.a.b) + ObfAu.b.a_F), 0.6000000238418579f) <= 0) goto L74;
        v0 = ObfAu.a;
        if (fcmpl(ObfAu.b.a(ObfAu.a.c), 0.6000000238418579f) >= 0) goto L74;
        if (fcmpl(ObfAu.a_bz.b__float(), ObfAu.a_bz.c()) >= 0) goto L74;
        return 1;
        L74:
        return 0;
    }
    // bytecode 528 bytes, max_stack 5, max_locals 6
    public static boolean b__boolean() {
        Plane v5 = ObfAu.b;
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        float v0 = (Vec2.a(ObfAu.b.a, ObfAu.a.b) + ObfAu.b.a_F);
        if (fcmpg((Vec2.a(ObfAu.b.a, ObfAu.a.b) + ObfAu.b.a_F), 0.30000001192092896f) <= 0) goto L78;
        v5 = ObfAu.a;
        if (fcmpl(ObfAu.b.a(ObfAu.a.c), 0.30000001192092896f) >= 0) goto L78;
        if (fcmpl(ObfAu.a_bz.b__float(), ObfAu.a_bz.c()) >= 0) goto L78;
        return 1;
        L78:
        v0 = ((float) SceneryList.a(v0));
        v5 = ObfAu.b;
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        int v1 = SceneryList.a((Vec2.a(ObfAu.b.a, ObfAu.a.c) + ObfAu.b.a_F));
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        v5 = ObfAu.a;
        int v2 = SceneryList.a((Vec2.a(ObfAu.a.a, ObfAu.b.b) + ObfAu.a.a_F));
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        v5 = ObfAu.a;
        int v3 = SceneryList.a((Vec2.a(ObfAu.a.a, ObfAu.b.c) + ObfAu.a.a_F));
        if (v2 == v3) goto L206;
        if (v0 == v1) goto L206;
        if (fcmpg(((float) v1), 0.0010000000474974513f) <= 0) goto L208;
        L206:
        return 0;
        L208:
        v5 = ObfAu.a;
        v5 = ObfAu.a;
        v0 = (ObfAu.a.c.a__float() - ObfAu.a.b.a__float());
        v5 = ObfAu.a;
        v5 = ObfAu.a;
        v1 = ((int) (ObfAu.a.c.b__float() - ObfAu.a.b.b__float()));
        v5 = ObfAu.b;
        v5 = ObfAu.b;
        v2 = ((int) (ObfAu.b.c.a__float() - ObfAu.b.b.a__float()));
        v5 = ObfAu.b;
        v5 = ObfAu.b;
        v3 = ((int) (ObfAu.b.c.b__float() - ObfAu.b.b.b__float()));
        float v4 = ((v2 * v1) - (v3 * v0));
        if (fcmpg(((v2 * v1) - (v3 * v0)), 0.0f) != 0) goto L345;
        if (fcmpl(ObfAu.a_bz.b__float(), ObfAu.a_bz.c()) >= 0) goto L345;
        return 1;
        L345:
        v5 = ObfAu.b;
        v5 = ObfAu.a;
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        v0 = (((v0 * (ObfAu.b.b.b__float() - ObfAu.a.b.b__float())) + (v1 * (ObfAu.a.b.a__float() - ObfAu.b.b.a__float()))) / v4);
        v5 = ObfAu.a;
        v5 = ObfAu.b;
        v5 = ObfAu.b;
        v5 = ObfAu.a;
        v1 = ((int) (((v2 * (ObfAu.a.b.b__float() - ObfAu.b.b.b__float())) + (v3 * (ObfAu.b.b.a__float() - ObfAu.a.b.a__float()))) / (-v4)));
        if (fcmpg(v0, -0.0010000000474974513f) < 0) goto L526;
        if (fcmpl(v0, 1.0010000467300415f) > 0) goto L526;
        if (fcmpg(v1, -0.0010000000474974513f) < 0) goto L526;
        if (fcmpl(v1, 1.0010000467300415f) > 0) goto L526;
        if (fcmpl((ObfAu.a_bz.a__float() + (v1 * (ObfAu.a_bz.b__float() - ObfAu.a_bz.a__float()))), ObfAu.a_bz.c()) >= 0) goto L526;
        return 1;
        L526:
        return 0;
    }
    // bytecode 132 bytes, max_stack 5, max_locals 3
    public float a(Vec2 v1) {
        Plane v2 = this;
        v2 = this;
        Plane.d.a(this.c, this.b);
        v2 = this;
        Plane.e.a(v1, this.b);
        v2 = ((Plane) (Vec2.a(Plane.e, Plane.d) / Vec2.a(Plane.d, Plane.d)));
        if (fcmpl((Vec2.a(Plane.e, Plane.d) / Vec2.a(Plane.d, Plane.d)), 0.0f) >= 0) goto L64;
        return Plane.e.c();
        L64:
        if (fcmpg(v2, 1.0f) <= 0) goto L111;
        v2 = this;
        v2 = this;
        Plane.e.b((v1.a__float() - this.c.a__float()), (v1.b__float() - this.c.b__float()));
        return Plane.e.c();
        L111:
        v2 = this;
        v2 = this;
        return java.lang.Math.abs((Vec2.a(this.a, v1) + this.a_F));
    }
    // bytecode 18 bytes, max_stack 3, max_locals 3
    public float a(Vec3 v1) {
        Plane v2 = this;
        v2 = this;
        return (Vec2.a(this.a, v1) + this.a_F);
    }
}

