// Generated by tools/jdeob.py from x/cx.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `cx`.
// String constants: /models/ | /tex/ | /tex/shadow.png | <init> | Code | abs | append | java/io/IOException | java/lang/Math | java/lang/StringBuffer | toString | StackMap
public class PlayerCar extends ObfCl {
    private Vec2 a;
    private float d;
    private float e;
    private Vec2 b;
    private Vec2 c;
    private RaceLine a_ck;
    private boolean h;
    private float f;
    private float g;
    // bytecode 147 bytes, max_stack 6, max_locals 6
    public PlayerCar(Textures v1, InputStream v2, int v3, ObfBs v4, int v5) {
        super(v1, v2, v3, v4, v5);
        this.a = null;
        this.d = 0.0f;
        this.e = 0.0f;
        this.b = null;
        this.c = null;
        this.a_ck = null;
        this.h = false;
        this.f = 0.0f;
        this.g = 0.0f;
        this.a = 10526880;
        this.b = 13684944;
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        this.a = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        new Vec2(0.0f, 0.0f); /* constructor */
        this.b = new Vec2(0.0f, 0.0f);
        new Vec2(0.0f, 0.0f); /* constructor */
        this.c = new Vec2(0.0f, 0.0f);
        new RaceLine(this.a); /* constructor */
        this.a_ck = new RaceLine(this.a);
        return;
    }
    // bytecode 12 bytes, max_stack 3, max_locals 1
    public void c() {
        new PlayerTune(); /* constructor */
        this.a = new PlayerTune();
        return;
    }
    // bytecode 18 bytes, max_stack 3, max_locals 2
    public void a(Textures v1) {
        if (this.d != Settings.e()) goto L11;
        return;
        L11:
        this.a(v1, true);
        return;
    }
    // bytecode 171 bytes, max_stack 5, max_locals 3
    public void a(Textures v1, boolean v2) {
        /* try L115-L134 catch java.io.IOException -> L137 */
        if (Settings.e() <= 1) goto L11;
        ObfAt.a_Z = true;
        L11:
        if (this.d == Settings.e()) goto L28;
        this.d = Settings.e();
        L28:
        new java.lang.StringBuffer(); /* constructor */
        if (this.d <= 0) goto L58;
        jt1 = this.a; /* join L62 from L51 */
        goto L62;
        L58:
        jt1 = this.b; /* join L62 from L58 */
        L62:
        new java.lang.StringBuffer(); /* constructor */
        this.a = AssetManager.a_de.b(new java.lang.StringBuffer().append("/models/").append(jt1).toString(), new java.lang.StringBuffer().append("/tex/").append(this.c).toString(), false);
        if (Settings.e() <= 0) goto L138;
        if (Settings.g() == 0) goto L138;
        if (ObfCl.a_cq != null) goto L138;
        new ObfCq(v1.a("/tex/shadow.png", true), true, true); /* constructor */
        ObfCl.a_cq = new ObfCq(v1.a("/tex/shadow.png", true), true, true);
        goto L138;
        /* pop: ex_137; */
        L138:
        this.a.a(this.a.b(), this.a.c(), this.a.d());
        this.j();
        return;
    }
    // bytecode 263 bytes, max_stack 6, max_locals 5
    public boolean a(ObfCl v1, boolean v2) {
        if (this.b() != 0) goto L15;
        Vec3 v3 = this.a();
        goto L23;
        L15:
        v3 = this.a().a();
        L23:
        if (v1.b() != 0) goto L39;
        Vec3 v4 = v1.a();
        goto L48;
        L39:
        v4 = v1.a().a();
        L48:
        v3 = ((Vec3) Vec2.b(v3, v4));
        if (fcmpl(Vec2.b(v3, v4), 0.800000011920929f) >= 0) goto L261;
        this.d();
        v1.d();
        this.a();
        v1.a();
        if (v2 != 0) goto L84;
        return 1;
        L84:
        v2 = ((boolean) Vec3.a(this.a().a(), v1.a().a()));
        v4 = ((Vec3) ((0.800000011920929f - v3) / (v2 - v3)));
        this.c.a(this.a(), this.a().a(), v4);
        this.d.a(v1.a(), v1.a().a(), v4);
        this.a.a(this.d, this.c);
        if (fcmpl((v2 - v3), 0.009999999776482582f) >= 0) goto L219;
        this.a(this.a, this.c, 0.5f, 0.4000000059604645f, v1.b());
        v1.a(this.a, this.d, 0.5f, 0.4000000059604645f, this.b());
        goto L259;
        L219:
        this.a(this.a, this.c, 0.20000000298023224f, 0.4000000059604645f, v1.b());
        v1.a(this.a, this.d, 0.20000000298023224f, 0.4000000059604645f, this.b());
        L259:
        return 1;
        L261:
        return 0;
    }
    // bytecode 6 bytes, max_stack 2, max_locals 1
    public void b() {
        this.h = true;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public boolean a() {
        return this.h;
    }
    // bytecode 415 bytes, max_stack 4, max_locals 5
    public void e(float v1) {
        if (this.d() == 0) goto L8;
        return;
        L8:
        if (fcmpg(this.c, 0.0f) <= 0) goto L28;
        this.c = (this.c - v1);
        return;
        L28:
        this.g = true;
        this.e();
        if (fcmpg(this.e, 0.0f) <= 0) goto L62;
        this.g(v1);
        this.e = (this.e - v1);
        return;
        L62:
        this.a = this.a_ck.a(this.a, this.a.a());
        Vec2 v2 = this.a();
        this.a.a(this.a().a(), v2.a(), v2.b());
        v2 = ((Vec2) this.a.a(this.a));
        this.b.a(this.a, this.a().a());
        this.c.b((-this.a().b().b()), this.a().b().a());
        this.c.a();
        int v3 = SceneryList.a((Vec2.a(this.c, this.a) - Vec2.a(this.a().a(), this.c)));
        float v4 = Vec2.b(this.b, this.a().b());
        v4 = (((float) v3) * ((float) SceneryList.c(((double) v4))));
        this.a().d(0.0f);
        /* pop: this.b.c(); */
        v4 = ((1.5f * v4) * java.lang.Math.abs(v4));
        if (fcmpg(((1.5f * v4) * java.lang.Math.abs(v4)), 1.5f) <= 0) goto L274;
        v4 = 1.5f;
        L274:
        if (fcmpl(v4, -1.5f) >= 0) goto L286;
        v4 = -1.5f;
        L286:
        if (fcmpl(v4, -0.0f) >= 0) goto L304;
        this.h((-v4));
        goto L317;
        L304:
        if (fcmpg(v4, 0.0f) <= 0) goto L317;
        this.i(v4);
        L317:
        this.a = false;
        v3 = ((int) 0.0f);
        if (fcmpg(v2, 0.0f) <= 0) goto L345;
        if (fcmpl(v2, 1.0f) >= 0) goto L338;
        v2 = ((Vec2) 1.0f);
        L338:
        v3 = ((int) ((v4 + 0.0f) / v2));
        L345:
        if (fcmpg((7.0f * v3), this.a().j()) <= 0) goto L379;
        if (fcmpg(this.a().j(), 1.2000000476837158f) <= 0) goto L379;
        this.g(v1);
        return;
        L379:
        if (fcmpl(v3, 0.10000000149011612f) >= 0) goto L396;
        if (fcmpl(java.lang.Math.abs(v4), 1.0f) < 0) goto L409;
        L396:
        if (fcmpl(this.a().j(), 0.4000000059604645f) >= 0) goto L414;
        L409:
        this.f(v1);
        L414:
        return;
    }
    // bytecode 57 bytes, max_stack 4, max_locals 2
    public void m(float v1) {
        this.b = (this.b + v1);
        if (fcmpg(this.b, 1.0f) <= 0) goto L56;
        this.b = 0.0f;
        this.e = 1.5f;
        this.a().i(0.0f);
        this.a().b(0.0f, 0.0f, 0.0f);
        this.a().b(0.0f);
        L56:
        return;
    }
    // bytecode 1 bytes, max_stack 0, max_locals 1
    public void i() {
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void k() {
        ObfAu.a_Z = true;
        return;
    }
    // bytecode 20 bytes, max_stack 2, max_locals 2
    public void a(ObfBq v1) {
        if (this.c == 0) goto L13;
        if (Settings.e() > 0) goto L14;
        L13:
        return;
        L14:
        this.b(v1);
        return;
    }
    // bytecode 69 bytes, max_stack 4, max_locals 1
    public void g() {
        this.g();
        if (Settings.m == 1) goto L68;
        if (this.a.a() >= 2) goto L68;
        this.b.b(this.b.a(), ((this.b.b() + this.f) / 2.0f), this.b.c());
        this.f = this.b.b();
        L68:
        return;
    }
    // bytecode 100 bytes, max_stack 5, max_locals 2
    public void j() {
        float v1 = ((this.a.k() + this.g) / 2.0f);
        this.g = this.a.k();
        this.a.a((((-v1) / 3.1415927410125732f) * 180.0f), 0.0f, 0.0f, 1.0f);
        this.a.b(((this.a.h() / 3.1415927410125732f) * 180.0f), 1.0f, 0.0f, 0.0f);
        this.a.b(((((-this.a.i()) / 3.1415927410125732f) * 180.0f) + this.a().a), 0.0f, 1.0f, 0.0f);
        return;
    }
}

