// Generated by tools/jdeob.py from x/aw.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `aw`.
// String constants: <init> | Code | java/io/IOException | java/lang/Math | min | StackMap
public class PlayerTune extends CarPhysics {
    // bytecode 155 bytes, max_stack 3, max_locals 1
    public PlayerTune() {
        super();
        this.b = 1.0f;
        this.c = 1.0f;
        this.a = (this.b + this.c);
        this.d = 1500.0f;
        this.e = 1500.0f;
        this.f = ((this.d * 9.800000190734863f) * 0.5f);
        this.g = 150.0f;
        this.h = 0.5f;
        this.i = 0.6283185482025146f;
        this.k = 80.0f;
        this.j = 20.0f;
        this.l = -30.0f;
        this.m = 0.7853981852531433f;
        this.n = 1.5707963705062866f;
        this.o = 60.0f;
        this.p = 30.0f;
        this.q = 2.0f;
        this.r = -20.0f;
        this.s = -20.0f;
        this.t = 1.2999999523162842f;
        this.r = -6.0f;
        this.s = -3.0f;
        this.t = 1.2999999523162842f;
        return;
    }
    // bytecode 136 bytes, max_stack 2, max_locals 2
    public void a(InputStream v1) {
        this.u = ((float) StreamReader.a(v1));
        this.v = ((float) StreamReader.a(v1));
        this.a = StreamReader.a(v1);
        this.b = StreamReader.a(v1);
        this.g = 150.0f;
        this.h = 0.5f;
        this.i = 0.6283185482025146f;
        this.k = 80.0f;
        this.j = 20.0f;
        this.l = -30.0f;
        this.m = 0.7853981852531433f;
        this.n = 1.5707963705062866f;
        this.o = 60.0f;
        this.p = 30.0f;
        this.q = 2.0f;
        this.r = -20.0f;
        this.s = -20.0f;
        this.t = 1.2999999523162842f;
        this.r = -6.0f;
        this.s = -3.0f;
        this.t = 1.2999999523162842f;
        return;
    }
    // bytecode 106 bytes, max_stack 3, max_locals 3
    public float l() {
        float v1 = 0.20000000298023224f;
        float v2 = ((float) this.c);
        if (Settings.c() != 1) goto L26;
        if (this.c != 0) goto L26;
        v1 = 0.3499999940395355f;
        L26:
        if (Settings.c() != 0) goto L48;
        if (this.c <= 0) goto L48;
        v2 = (0.6499999761581421f * ((float) this.c));
        L48:
        if (Settings.m != 2) goto L83;
        return (((((14.0f - java.lang.Math.min(v2, 4.0f)) * ((v2 * 2.0f) + 5.0f)) / 7.0f) * this.k) / 20.0f);
        L83:
        return ((((0.75f + (((float) Settings.c()) * v1)) * (v2 + 6.0f)) / 7.0f) * this.k);
    }
    // bytecode 110 bytes, max_stack 3, max_locals 2
    public float h() {
        float v1 = 0.20000000298023224f;
        if (Settings.c() != 1) goto L20;
        if (this.c != 0) goto L20;
        v1 = 0.3499999940395355f;
        L20:
        if (Settings.m != 2) goto L48;
        return (((((2.0f * ((float) this.c)) + 5.0f) / 7.0f) * this.g) / 2.0f);
        L48:
        if (Settings.m != 1) goto L82;
        return ((((0.75f + (((float) Settings.c()) * v1)) * ((float) (this.c + 6))) / 7.0f) * this.g);
        L82:
        return ((((0.75f + (((float) Settings.c()) * v1)) * ((float) ((2 * this.c) + 5))) / 7.0f) * this.g);
    }
    // bytecode 49 bytes, max_stack 3, max_locals 2
    public float i() {
        float v1 = 0.20000000298023224f;
        if (Settings.c() != 1) goto L20;
        if (this.c != 0) goto L20;
        v1 = 0.3499999940395355f;
        L20:
        return ((((0.75f + (((float) Settings.c()) * v1)) * ((2.0f * ((float) this.c)) + 5.0f)) / 7.0f) * this.h);
    }
    // bytecode 49 bytes, max_stack 3, max_locals 2
    public float k() {
        float v1 = 0.20000000298023224f;
        if (Settings.c() != 1) goto L20;
        if (this.c != 0) goto L20;
        v1 = 0.3499999940395355f;
        L20:
        return ((((0.75f + (((float) Settings.c()) * v1)) * ((2.0f * ((float) this.c)) + 5.0f)) / 7.0f) * this.j);
    }
    // bytecode 16 bytes, max_stack 4, max_locals 1
    public float v() {
        return (this.t * (1.0f + (((float) this.b) / 10.0f)));
    }
    // bytecode 7 bytes, max_stack 2, max_locals 1
    public float t() {
        return (this.r * 2.0f);
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public float u() {
        return this.s;
    }
}

