// Generated by tools/jdeob.py from x/dd.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `dd`.
// String constants: <init> | Code | append | getTime | java/io/DataInputStream | java/io/DataOutputStream | java/io/IOException | java/lang/Object | java/lang/StringBuffer | java/util/Date | readByte | readInt
// API references: java/io java/util
public class ScoreRecord {
    private int a;
    private int b;
    private long a_J;
    private int c;
    private String a_String;
    private boolean a_Z;
    private boolean b_Z;
    // bytecode 40 bytes, max_stack 3, max_locals 1
    public ScoreRecord() {
        super();
        this.a = m1;
        this.b = m1;
        this.a_J = 0L;
        this.c = 0;
        this.a_String = null;
        this.a_Z = true;
        this.b_Z = false;
        return;
    }
    // bytecode 93 bytes, max_stack 5, max_locals 5
    public void a(DataInputStream v1) {
        this.a = v1.readInt();
        this.b = v1.readInt();
        int v2 = v1.readInt();
        new java.util.Date(); /* constructor */
        long v3 = (new java.util.Date().getTime() / 1000L);
        this.a_J = (v3 + ((long) v2));
        this.c = v1.readInt();
        this.a_String = Settings.a(v1);
        if (v1.readByte() == 0) goto L72;
        jt1 = 1; /* join L73 from L68 */
        goto L73;
        L72:
        jt1 = 0; /* join L73 from L72 */
        L73:
        this.a_Z = jt1;
        if (v1.readByte() == 0) goto L88;
        jt2 = 1; /* join L89 from L84 */
        goto L89;
        L88:
        jt2 = 0; /* join L89 from L88 */
        L89:
        this.b_Z = jt2;
        return;
    }
    // bytecode 57 bytes, max_stack 3, max_locals 2
    public void a(DataOutputStream v1) {
        v1.writeInt(this.a);
        v1.writeInt(this.b);
        v1.writeLong(this.a_J);
        v1.writeInt(this.c);
        v1.writeUTF(this.a_String);
        v1.writeBoolean(this.a_Z);
        v1.writeBoolean(this.b_Z);
        return;
    }
    // bytecode 30 bytes, max_stack 2, max_locals 1
    public String toString() {
        new java.lang.StringBuffer(); /* constructor */
        return new java.lang.StringBuffer().append(this.a).append(" ").append(this.a_String).toString();
    }
}

