// Generated by tools/jdeob.py from x/bx.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bx`.
// String constants: <clinit> | <init> | Code | VolumeControl | [Ljava/io/InputStream; | abs | addPlayerListener | amr | audio/amr | audio/midi | audio/x-wav | compareTo
// API references: java/io java/util javax/microedition
public class SoundBank extends AudioPlayer {
    protected String a;
    protected static int a_I;
    protected boolean a_Z;
    private static Class a_Class;
    static {
        SoundBank.a_I = m1;
        return;
    }
    // bytecode 15 bytes, max_stack 2, max_locals 1
    public SoundBank() {
        super();
        this.a = null;
        this.a_Z = false;
        return;
    }
    // bytecode 189 bytes, max_stack 4, max_locals 4
    public Player a__Player(String v1) {
        /* try L16-L171 catch java.lang.Exception -> L174 */
        javax.microedition.media.Player v2 = ((javax.microedition.media.Player) this.a.get(v1));
        if (((javax.microedition.media.Player) this.a.get(v1)) != null) goto L187;
        String v3 = v1;
        if (SoundBank.a_Class != null) goto L44;
        SoundBank.a_Class = SoundBank.a__Class("cy");
        jt1 = SoundBank.a__Class("cy"); /* join L47 from L32 */
        goto L47;
        L44:
        jt1 = SoundBank.a_Class; /* join L47 from L44 */
        L47:
        this.a[this.b] = jt1.getResourceAsStream(v3);
        if (v3.endsWith("amr") == 0) goto L79;
        v2 = ((javax.microedition.media.Player) javax.microedition.media.Manager.createPlayer(this.a[this.b], "audio/amr"));
        goto L130;
        L79:
        if (v3.endsWith("mid") == 0) goto L106;
        v2 = ((javax.microedition.media.Player) javax.microedition.media.Manager.createPlayer(this.a[this.b], "audio/midi"));
        goto L130;
        L106:
        if (v3.endsWith("wav") == 0) goto L130;
        v2 = ((javax.microedition.media.Player) javax.microedition.media.Manager.createPlayer(this.a[this.b], "audio/x-wav"));
        L130:
        v2.addPlayerListener(this);
        /* pop: this.a.put(v1, v2); */
        this.b = (this.b + 1);
        v2.setLoopCount(1);
        /* pop: v2.getDuration(); */
        goto L187;
        v3 = ((String) ex_174);
        java.lang.System.out.println(v3.toString());
        v2 = ((javax.microedition.media.Player) null);
        L187:
        return v2;
    }
    // bytecode 156 bytes, max_stack 4, max_locals 5
    public boolean a(String v1, int v2) {
        /* try L65-L71 catch javax.microedition.media.MediaException -> L74 */
        /* try L91-L145 catch java.lang.Exception -> L148 */
        long v3 = java.lang.Math.abs((java.lang.System.currentTimeMillis() - this.a));
        if (lcmp(java.lang.Math.abs((java.lang.System.currentTimeMillis() - this.a)), 500L) < 0) goto L46;
        if (lcmp(v3, 1500L) >= 0) goto L35;
        if (SoundBank.b() == 4) goto L46;
        L35:
        if (v1.compareTo(this.b) != 0) goto L48;
        L46:
        return 0;
        L48:
        v3 = ((long) AudioPlayer.a_Player);
        if (AudioPlayer.a_Player == null) goto L77;
        this.a = v1;
        SoundBank.a_I = v2;
        v3.stop();
        goto L75;
        /* pop: ex_74; */
        L75:
        return 0;
        L77:
        AudioPlayer.a_Player = this.a__Player(v1);
        if (this.a__Player(v1) != null) goto L91;
        return 0;
        L91:
        AudioPlayer.a_Player.realize();
        AudioPlayer.a_Player.prefetch();
        /* pop: AudioPlayer.a_Player.setMediaTime(0L); */
        this.e();
        this.a = java.lang.System.currentTimeMillis();
        AudioPlayer.a_Player.start();
        AudioPlayer.d = v2;
        this.a_Z = false;
        goto L149;
        /* pop: ex_148; */
        L149:
        this.b = v1;
        return 1;
    }
    // bytecode 43 bytes, max_stack 2, max_locals 1
    public void a() {
        /* try L11-L19 catch javax.microedition.media.MediaException -> L22 */
        this.a_Z = true;
        if (AudioPlayer.a_Player == null) goto L23;
        AudioPlayer.a_Player.stop();
        goto L23;
        /* pop: ex_22; */
        L23:
        this.b = "";
        AudioPlayer.a_Player = null;
        AudioPlayer.d = m1;
        this.c = m1;
        return;
    }
    // bytecode 130 bytes, max_stack 3, max_locals 4
    public void playerUpdate(Player v1, String v2, Object v3) {
        /* try L8-L127 catch java.lang.Exception -> L128 */
        if (this.a_Z == 0) goto L8;
        return;
        L8:
        if (v2.equals("stopped") == 0) goto L42;
        AudioPlayer.a_Player = null;
        this.b = "";
        /* pop: this.a(this.a, SoundBank.a_I); */
        goto L129;
        L42:
        if (v2.equals("endOfMedia") == 0) goto L67;
        AudioPlayer.a_Player = null;
        this.b = "";
        EngineSounds.c();
        goto L129;
        L67:
        if (v2.equals("stopped") != 0) goto L127;
        if (v2.equals("stoppedAtTime") != 0) goto L127;
        if (v2.equals("error") != 0) goto L127;
        if (v2.equals("deviceUnavailable") == 0) goto L112;
        v1.stop();
        goto L129;
        L112:
        if (v2.equals("deviceAvailable") == 0) goto L127;
        v1.start();
        L127:
        return;
        /* pop: ex_128; */
        L129:
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void b() {
        this.e();
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public void c() {
        this.d();
        return;
    }
    // bytecode 47 bytes, max_stack 2, max_locals 2
    public void d() {
        if (AudioPlayer.a_Player == null) goto L46;
        if (AudioPlayer.a_Player.getState() != 400) goto L46;
        javax.microedition.media.control.VolumeControl v1 = ((javax.microedition.media.control.VolumeControl) AudioPlayer.a_Player.getControl("VolumeControl"));
        if (((javax.microedition.media.control.VolumeControl) AudioPlayer.a_Player.getControl("VolumeControl")) == null) goto L46;
        /* pop: v1.setLevel(0); */
        L46:
        return;
    }
    // bytecode 18 bytes, max_stack 3, max_locals 1
    public static Class a__Class(String v0) {
        /* try L0-L4 catch java.lang.ClassNotFoundException -> L5 */
        return java.lang.Class.forName(v0);
        v0 = ((String) ex_5);
        new java.lang.NoClassDefFoundError(v0.getMessage()); /* constructor */
        throw new java.lang.NoClassDefFoundError(v0.getMessage());
    }
}

