// Generated by tools/jdeob.py from x/aq.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `aq`.
// String constants: .tab | /fonts/black | /fonts/font | /fonts/font.tab | /fonts/in | /fonts/in.tab | /fonts/it | /fonts/it.tab | /fonts/la | /fonts/lg | /fonts/ln | /fonts/lr
// API references: java/io javax/microedition javax/wireless
public class SysUtil {
    public static Rect a;
    public static Font a_p;
    public static Font b;
    public static Font c;
    public static Font d;
    public static Font e;
    public static Font f;
    public static Font g;
    public static int a_I;
    public static Font h;
    public static Font i;
    public static Font j;
    public static Font k;
    public static Font l;
    public static Font m;
    public static Font n;
    public static Font o;
    public static Font p;
    public static Font q;
    public static Font r;
    private static Font u;
    public static Font s;
    private static String b_String;
    private static String c_String;
    private static String d_String;
    private static String e_String;
    private static String f_String;
    private static String g_String;
    private static String h_String;
    private static String i_String;
    private static String j_String;
    private static String k_String;
    private static String l_String;
    private static String m_String;
    private static String n_String;
    private static String o_String;
    private static String p_String;
    private static String q_String;
    private static String r_String;
    public static Font t;
    public static int b_I;
    public static int c_I;
    public static int d_I;
    private static GlyphTable a_f;
    private static int h_I;
    public static final String[] a_String;
    public static String a_String_2;
    private static Canvas a_Canvas;
    private static String[] b_String;
    public static int e_I;
    public static int f_I;
    public static int g_I;
    private static byte[][] a_arrarrB;
    public static String[][] a_String;
    static {
        new Rect(0.0f, 0.0f, 0.0f, 0.0f); /* constructor */
        SysUtil.a = new Rect(0.0f, 0.0f, 0.0f, 0.0f);
        SysUtil.a_p = null;
        SysUtil.b = null;
        SysUtil.c = null;
        SysUtil.d = null;
        SysUtil.e = null;
        SysUtil.f = null;
        SysUtil.g = null;
        SysUtil.a_I = 244;
        SysUtil.h = null;
        SysUtil.i = null;
        SysUtil.j = null;
        SysUtil.k = null;
        SysUtil.l = null;
        SysUtil.m = null;
        SysUtil.n = null;
        SysUtil.o = null;
        SysUtil.p = null;
        SysUtil.q = null;
        SysUtil.r = null;
        SysUtil.u = null;
        SysUtil.s = null;
        SysUtil.b_String = "/fonts/lg";
        SysUtil.c_String = "/fonts/lr";
        SysUtil.d_String = "/fonts/font.tab";
        SysUtil.e_String = "/fonts/font";
        SysUtil.f_String = "/fonts/s.tab";
        SysUtil.g_String = "/fonts/s";
        SysUtil.h_String = "/fonts/in.tab";
        SysUtil.i_String = "/fonts/it.tab";
        SysUtil.j_String = "/fonts/n0";
        SysUtil.k_String = "/fonts/n2";
        SysUtil.l_String = "/fonts/ln";
        SysUtil.m_String = "/fonts/in";
        SysUtil.n_String = "/fonts/it";
        SysUtil.o_String = "/fonts/sn";
        SysUtil.p_String = "/fonts/n3";
        SysUtil.q_String = "/fonts/la";
        SysUtil.r_String = "/fonts/black";
        SysUtil.t = null;
        SysUtil.b_I = 230;
        SysUtil.c_I = 255;
        SysUtil.d_I = 3;
        SysUtil.a_f = null;
        SysUtil.h_I = 0;
        new java.lang.String[2]#2[0] = "/images/be.png";
        new java.lang.String[2]#2[1] = "/images/bf.png";
        SysUtil.a_String = new java.lang.String[2]#2;
        SysUtil.a_String_2 = "/images/i.png";
        SysUtil.a_Canvas = null;
        new java.lang.String[1]#3[0] = "/ui/ui.txt";
        SysUtil.b_String = new java.lang.String[1]#3;
        SysUtil.e_I = 0;
        SysUtil.f_I = 0;
        SysUtil.g_I = 1;
        new byte[1]#5[0] = 0;
        new Obf[B[12]#4[0] = new byte[1]#5;
        new byte[1]#6[0] = 0;
        new Obf[B[12]#4[1] = new byte[1]#6;
        new byte[1]#7[0] = 0;
        new Obf[B[12]#4[2] = new byte[1]#7;
        new byte[1]#8[0] = 0;
        new Obf[B[12]#4[3] = new byte[1]#8;
        new byte[1]#9[0] = 0;
        new Obf[B[12]#4[4] = new byte[1]#9;
        new byte[1]#10[0] = 0;
        new Obf[B[12]#4[5] = new byte[1]#10;
        new byte[1]#11[0] = 0;
        new Obf[B[12]#4[6] = new byte[1]#11;
        new byte[1]#12[0] = 0;
        new Obf[B[12]#4[7] = new byte[1]#12;
        new byte[1]#13[0] = 0;
        new Obf[B[12]#4[8] = new byte[1]#13;
        new byte[1]#14[0] = 0;
        new Obf[B[12]#4[9] = new byte[1]#14;
        new byte[1]#15[0] = 0;
        new Obf[B[12]#4[10] = new byte[1]#15;
        new byte[1]#16[0] = 0;
        new Obf[B[12]#4[11] = new byte[1]#16;
        SysUtil.a_arrarrB = new Obf[B[12]#4;
        new java.lang.String[3]#18[0] = "Pokud chces ziskat plnou verzi hry, posli SMS ve tvaru HRAJ KORA na telefonni cislo 9079950. Sluzbu technicky zajistuje Axima spol. s r.o., cena SMS je 50,- Kc vc. DPH, infolinka prsms@axima-brno.cz.";
        new java.lang.String[3]#18[1] = "9079909";
        new java.lang.String[3]#18[2] = "HRAJ 92629";
        new ObfString;[3]#17[0] = new java.lang.String[3]#18;
        new java.lang.String[3]#19[0] = "Ak chces plnu verziu, odosli sms v tvare EPAY KORA na tel. cislo 7604, cena sms je ¼1.593 (48 SKK) s DPH. Sluzbu zabezpecuju sms-platby.eu. Reklamacie uplatni na e-mailovej adrese KORA@KORAGAME.COM.";
        new java.lang.String[3]#19[1] = "7604";
        new java.lang.String[3]#19[2] = "EPAY KORA";
        new ObfString;[3]#17[1] = new java.lang.String[3]#19;
        new java.lang.String[3]#20[0] = "Jesli chcialbys pelna wersje gry, wyslij SMS o tresci EPAY KORA na numer telefonu 7955. Koszt SMSa wynosi 9 zl (10,98 zl z VAT). Dostawca uslugi SMS jest firma sms-platby.eu. Reklamacje: kora@koragame.com, poniedzialek-piatek, od 9:00-17:00.";
        new java.lang.String[3]#20[1] = "7955";
        new java.lang.String[3]#20[2] = "EPAY KORA";
        new ObfString;[3]#17[2] = new java.lang.String[3]#20;
        SysUtil.a_String = new ObfString;[3]#17;
        return;
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public SysUtil() {
        super();
        return;
    }
    // bytecode 1105 bytes, max_stack 6, max_locals 2
    public static void a(Canvas v0) {
        /* try L857-L912 catch java.lang.IllegalArgumentException -> L915 */
        /* try L916-L971 catch java.lang.IllegalArgumentException -> L974 */
        /* try L975-L1031 catch java.lang.IllegalArgumentException -> L1034 */
        /* try L0-L1098 catch java.io.IOException -> L1099 */
        SysUtil.a_Canvas = v0;
        new FontCodec(SysUtil.d_String); /* constructor */
        FontCodec v1 = new FontCodec(SysUtil.d_String);
        new Font(SysUtil.e_String, v1, -2, 15); /* constructor */
        SysUtil.a_p = new Font(SysUtil.e_String, v1, -2, 15);
        new Font(SysUtil.e_String, v1, -2, 15).d();
        new Font(SysUtil.r_String, v1, -2); /* constructor */
        SysUtil.t = new Font(SysUtil.r_String, v1, -2);
        if (SysUtil.e_I > 400) goto L71;
        SysUtil.b = SysUtil.a_p;
        goto L139;
        L71:
        new java.lang.StringBuffer(); /* constructor */
        new Font(new java.lang.StringBuffer().append(SysUtil.e_String).append("2").toString(), v1, -2, 25); /* constructor */
        SysUtil.b = new Font(new java.lang.StringBuffer().append(SysUtil.e_String).append("2").toString(), v1, -2, 25);
        new java.lang.StringBuffer(); /* constructor */
        new Font(new java.lang.StringBuffer().append(SysUtil.e_String).append("3").toString(), v1, -2, 25); /* constructor */
        L139:
        new Font("/fonts/sm", v1, 1, 15); /* constructor */
        SysUtil.n = new Font("/fonts/sm", v1, 1, 15);
        new Font("/fonts/sml", v1, 1, 15); /* constructor */
        SysUtil.o = new Font("/fonts/sml", v1, 1, 15);
        new Font("/fonts/sm2", v1, -2, 15); /* constructor */
        SysUtil.p = new Font("/fonts/sm2", v1, -2, 15);
        new Font("/fonts/sml2", v1, -2, 15); /* constructor */
        SysUtil.q = new Font("/fonts/sml2", v1, -2, 15);
        new Font("/fonts/smg", v1, -2, 15); /* constructor */
        SysUtil.r = new Font("/fonts/smg", v1, -2, 15);
        new Font(SysUtil.q_String, v1, m1); /* constructor */
        SysUtil.m = new Font(SysUtil.q_String, v1, m1);
        new BitmapFont(SysUtil.j_String, 7, 7, 7); /* constructor */
        SysUtil.d = new BitmapFont(SysUtil.j_String, 7, 7, 7);
        new BitmapFont(((BitmapFont) SysUtil.d)); /* constructor */
        SysUtil.e = new BitmapFont(((BitmapFont) SysUtil.d));
        new BitmapFont(((BitmapFont) SysUtil.d)).a(-24416, true);
        new BitmapFont(SysUtil.p_String, 14, 13, 9); /* constructor */
        new BitmapFont(SysUtil.k_String, 6, 11, 8); /* constructor */
        SysUtil.g = new BitmapFont(SysUtil.k_String, 6, 11, 8);
        new FontCodec(SysUtil.h_String); /* constructor */
        v1 = new FontCodec(SysUtil.h_String);
        new Font(SysUtil.m_String, v1, 0); /* constructor */
        SysUtil.h = new Font(SysUtil.m_String, v1, 0);
        new Font(SysUtil.m_String, v1, 0).a(2);
        new Font(SysUtil.h); /* constructor */
        SysUtil.k = new Font(SysUtil.h);
        new Font(SysUtil.h); /* constructor */
        SysUtil.j = new Font(SysUtil.h);
        SysUtil.k.a(-65536, true);
        SysUtil.j.a(-16711936, true);
        new ObfAh(SysUtil.l_String, 12, 11, 8); /* constructor */
        SysUtil.l = new ObfAh(SysUtil.l_String, 12, 11, 8);
        new FontCodec(SysUtil.f_String); /* constructor */
        v1 = new FontCodec(SysUtil.f_String);
        new Font(SysUtil.g_String, v1, 0); /* constructor */
        SysUtil.c = new Font(SysUtil.g_String, v1, 0);
        new FontCodec(SysUtil.i_String); /* constructor */
        v1 = new FontCodec(SysUtil.i_String);
        new Font(SysUtil.n_String, v1, 0); /* constructor */
        SysUtil.i = new Font(SysUtil.n_String, v1, 0);
        new Font(SysUtil.o_String, v1, 0); /* constructor */
        SysUtil.f = new Font(SysUtil.o_String, v1, 0);
        new java.lang.StringBuffer(); /* constructor */
        new FontCodec(new java.lang.StringBuffer().append(SysUtil.b_String).append(".tab").toString()); /* constructor */
        v1 = new FontCodec(new java.lang.StringBuffer().append(SysUtil.b_String).append(".tab").toString());
        if (v0.getWidth() <= 200) goto L529;
        new Font(SysUtil.b_String, v1, -12); /* constructor */
        goto L559;
        L529:
        new java.lang.StringBuffer(); /* constructor */
        new Font(new java.lang.StringBuffer().append(SysUtil.b_String).append("s").toString(), v1, -6); /* constructor */
        L559:
        new java.lang.StringBuffer(); /* constructor */
        new FontCodec(new java.lang.StringBuffer().append(SysUtil.c_String).append(".tab").toString()); /* constructor */
        v1 = new FontCodec(new java.lang.StringBuffer().append(SysUtil.c_String).append(".tab").toString());
        if (v0.getWidth() <= 200) goto L651;
        new Font(SysUtil.c_String, v1, -12); /* constructor */
        SysUtil.u = new Font(SysUtil.c_String, v1, -12);
        new java.lang.StringBuffer(); /* constructor */
        new Font(new java.lang.StringBuffer().append(SysUtil.c_String).append("s").toString(), v1, -6); /* constructor */
        SysUtil.s = new Font(new java.lang.StringBuffer().append(SysUtil.c_String).append("s").toString(), v1, -6);
        goto L689;
        L651:
        new java.lang.StringBuffer(); /* constructor */
        new Font(new java.lang.StringBuffer().append(SysUtil.c_String).append("s").toString(), v1, -6); /* constructor */
        SysUtil.u = new Font(new java.lang.StringBuffer().append(SysUtil.c_String).append("s").toString(), v1, -6);
        SysUtil.s = new Font(new java.lang.StringBuffer().append(SysUtil.c_String).append("s").toString(), v1, -6);
        L689:
        SysUtil.a_arrarrB[0] = SysUtil.a_p.a("0");
        SysUtil.a_arrarrB[1] = SysUtil.a_p.a("1");
        SysUtil.a_arrarrB[2] = SysUtil.a_p.a("2");
        SysUtil.a_arrarrB[3] = SysUtil.a_p.a("3");
        SysUtil.a_arrarrB[4] = SysUtil.a_p.a("4");
        SysUtil.a_arrarrB[5] = SysUtil.a_p.a("5");
        SysUtil.a_arrarrB[6] = SysUtil.a_p.a("6");
        SysUtil.a_arrarrB[7] = SysUtil.a_p.a("7");
        SysUtil.a_arrarrB[8] = SysUtil.a_p.a("8");
        SysUtil.a_arrarrB[9] = SysUtil.a_p.a("9");
        SysUtil.a_arrarrB[10] = SysUtil.a_p.a("#");
        SysUtil.a_arrarrB[11] = SysUtil.a_p.a("*");
        SysUtil.h_I = m1;
        if (v0.getGameAction(-5) != 8) goto L912;
        if (v0.getGameAction(m1) != 1) goto L912;
        if (v0.getGameAction(-2) != 6) goto L912;
        if (v0.getGameAction(-3) != 2) goto L912;
        if (v0.getGameAction(-4) != 5) goto L912;
        SysUtil.h_I = 0;
        L912:
        goto L916;
        /* pop: ex_915; */
        L916:
        if (v0.getGameAction(-20) != 8) goto L971;
        if (v0.getGameAction(m1) != 1) goto L971;
        if (v0.getGameAction(-6) != 6) goto L971;
        if (v0.getGameAction(-2) != 2) goto L971;
        if (v0.getGameAction(-5) != 5) goto L971;
        SysUtil.h_I = 2;
        L971:
        goto L975;
        /* pop: ex_974; */
        L975:
        if (v0.getGameAction(-26) != 8) goto L1031;
        if (v0.getGameAction(-59) != 1) goto L1031;
        if (v0.getGameAction(-60) != 6) goto L1031;
        if (v0.getGameAction(-61) != 2) goto L1031;
        if (v0.getGameAction(-62) != 5) goto L1031;
        SysUtil.h_I = 1;
        L1031:
        goto L1035;
        /* pop: ex_1034; */
        L1035:
        v0 = ((Canvas) Settings.a());
        Settings.a(Settings.a());
        if (SysUtil.a_f != null) goto L1079;
        /* pop: SysUtil.a_Canvas.getWidth(); */
        new GlyphTable(SysUtil.b_String[Settings.a()], SysUtil.a_p); /* constructor */
        SysUtil.a_f = new GlyphTable(SysUtil.b_String[Settings.a()], SysUtil.a_p);
        goto L1095;
        L1079:
        SysUtil.a_f.a(SysUtil.b_String[Settings.a()], SysUtil.a_p);
        L1095:
        Settings.c();
        return;
        v1 = ((FontCodec) ex_1099);
        ex_1099.printStackTrace();
        return;
    }
    // bytecode 110 bytes, max_stack 3, max_locals 3
    public static boolean a(String v0, String v1) {
        /* try L51-L92 catch java.lang.Exception -> L93 */
        /* try L98-L104 catch java.lang.Exception -> L107 */
        new java.lang.StringBuffer(); /* constructor */
        java.lang.System.out.println(new java.lang.StringBuffer().append(v0).append(": ").append(v1).toString());
        new java.lang.StringBuffer(); /* constructor */
        v0 = new java.lang.StringBuffer().append("sms://").append(v0).toString();
        Object v2 = null;
        v2 = ((Object) ((javax.wireless.messaging.MessageConnection) javax.microedition.io.Connector.open(v0)));
        v0 = ((String) ((javax.wireless.messaging.TextMessage) ((javax.wireless.messaging.MessageConnection) javax.microedition.io.Connector.open(v0)).newMessage("text")));
        ((javax.wireless.messaging.TextMessage) ((javax.wireless.messaging.MessageConnection) javax.microedition.io.Connector.open(v0)).newMessage("text")).setPayloadText(v1);
        v2.send(v0);
        v2.close();
        return 1;
        /* pop: ex_93; */
        if (v2 == null) goto L108;
        v2.close();
        goto L108;
        /* pop: ex_107; */
        L108:
        return 0;
    }
    // bytecode 65 bytes, max_stack 3, max_locals 2
    public static int a(byte[] v0, int v1) {
        v1 = ((v0[0] + 256) % 256);
        v1 = (((v0[1] + 256) % 256) + (v1 << 8));
        v1 = (((v0[2] + 256) % 256) + (v1 << 8));
        v1 = (((v0[3] + 256) % 256) + (v1 << 8));
        return (((v0[3] + 256) % 256) + (v1 << 8));
    }
    // bytecode 363 bytes, max_stack 2, max_locals 1
    public static String a(int v0) {
        if (v0 != -3000) goto L10;
        return "0";
        L10:
        if (v0 != -3001) goto L20;
        return "1";
        L20:
        if (v0 != -3002) goto L30;
        return "2";
        L30:
        if (v0 != -3003) goto L40;
        return "3";
        L40:
        if (v0 != -3004) goto L50;
        return "4";
        L50:
        if (v0 != -3005) goto L60;
        return "5";
        L60:
        if (v0 != -3006) goto L70;
        return "6";
        L70:
        if (v0 != -3007) goto L80;
        return "7";
        L80:
        if (v0 != -3008) goto L90;
        return "8";
        L90:
        if (v0 != -3009) goto L100;
        return "9";
        L100:
        if (v0 != -3010) goto L110;
        return "#";
        L110:
        if (v0 != -3011) goto L120;
        return "*";
        L120:
        if (v0 != 35) goto L138;
        return SysUtil.a_p.a(SysUtil.a(35));
        L138:
        if (v0 != 36) goto L156;
        return SysUtil.a_p.a(SysUtil.a(36));
        L156:
        if (v0 != 37) goto L174;
        return SysUtil.a_p.a(SysUtil.a(37));
        L174:
        if (v0 != 38) goto L258;
        v0 = ((int) SysUtil.a_p.a(SysUtil.a(38)));
        if (Settings.k() != 2) goto L256;
        if (Settings.m() != 1) goto L229;
        new java.lang.StringBuffer(); /* constructor */
        v0 = ((int) new java.lang.StringBuffer().append(v0).append("/A").toString());
        goto L256;
        L229:
        if (Settings.m() != 3) goto L256;
        new java.lang.StringBuffer(); /* constructor */
        v0 = ((int) new java.lang.StringBuffer().append(v0).append("/B").toString());
        L256:
        return v0;
        L258:
        if (v0 != 39) goto L342;
        v0 = ((int) SysUtil.a_p.a(SysUtil.a(39)));
        if (Settings.k() != 2) goto L340;
        if (Settings.m() != 1) goto L313;
        new java.lang.StringBuffer(); /* constructor */
        v0 = ((int) new java.lang.StringBuffer().append(v0).append("/B").toString());
        goto L340;
        L313:
        if (Settings.m() != 3) goto L340;
        new java.lang.StringBuffer(); /* constructor */
        v0 = ((int) new java.lang.StringBuffer().append(v0).append("/A").toString());
        L340:
        return v0;
        L342:
        if (v0 != 0) goto L349;
        return "";
        L349:
        return ((javax.microedition.lcdui.game.GameCanvas) SysUtil.a_Canvas).getKeyName(v0).toUpperCase();
    }
    // bytecode 205 bytes, max_stack 3, max_locals 1
    public static byte[] a(int v0) {
        if (v0 != -3000) goto L13;
        return SysUtil.a_arrarrB[0];
        L13:
        if (v0 != -3001) goto L26;
        return SysUtil.a_arrarrB[1];
        L26:
        if (v0 != -3002) goto L39;
        return SysUtil.a_arrarrB[2];
        L39:
        if (v0 != -3003) goto L52;
        return SysUtil.a_arrarrB[3];
        L52:
        if (v0 != -3004) goto L65;
        return SysUtil.a_arrarrB[4];
        L65:
        if (v0 != -3005) goto L78;
        return SysUtil.a_arrarrB[5];
        L78:
        if (v0 != -3006) goto L92;
        return SysUtil.a_arrarrB[6];
        L92:
        if (v0 != -3007) goto L106;
        return SysUtil.a_arrarrB[7];
        L106:
        if (v0 != -3008) goto L120;
        return SysUtil.a_arrarrB[8];
        L120:
        if (v0 != -3009) goto L134;
        return SysUtil.a_arrarrB[9];
        L134:
        if (v0 != -3010) goto L148;
        return SysUtil.a_arrarrB[10];
        L148:
        if (v0 != -3011) goto L162;
        return SysUtil.a_arrarrB[11];
        L162:
        if (v0 != 10000) goto L197;
        new java.lang.StringBuffer(); /* constructor */
        return SysUtil.a_p.a(new java.lang.StringBuffer().append("ACTIVATION KEY: ").append(Settings.a()).toString());
        L197:
        return SysUtil.a_f.a(v0);
    }
    // bytecode 470 bytes, max_stack 2, max_locals 1
    public static int a(int v0) {
        if (v0 != -201) goto L10;
        return -5;
        L10:
        if (v0 != -202) goto L20;
        return -6;
        L20:
        if (v0 != -203) goto L30;
        return -7;
        L30:
        switch (v0) {
        case 8: goto L64;
        case 10: goto L67;
        case 13: goto L67;
        default: goto L70;
        }
        L64:
        return -8;
        L67:
        return -4;
        L70:
        if (SysUtil.h_I != 0) goto L237;
        switch (v0) {
        case -204: goto L228;
        case -203: goto L225;
        case -202: goto L222;
        case -16: goto L228;
        case -15: goto L216;
        case -14: goto L219;
        case -11: goto L231;
        case -8: goto L228;
        case -7: goto L225;
        case -6: goto L222;
        case -5: goto L219;
        case -4: goto L216;
        case -3: goto L213;
        case -2: goto L210;
        case -1: goto L208;
        default: goto L234;
        }
        L208:
        return m1;
        L210:
        return -2;
        L213:
        return -3;
        L216:
        return -4;
        L219:
        return -5;
        L222:
        return -6;
        L225:
        return -7;
        L228:
        return -8;
        L231:
        return -11;
        L234:
        goto L467;
        L237:
        if (SysUtil.h_I != 1) goto L335;
        switch (v0) {
        case -62: goto L320;
        case -61: goto L317;
        case -60: goto L314;
        case -59: goto L312;
        case -26: goto L323;
        case -4: goto L329;
        case -1: goto L326;
        default: goto L332;
        }
        L312:
        return m1;
        L314:
        return -2;
        L317:
        return -3;
        L320:
        return -4;
        L323:
        return -5;
        L326:
        return -6;
        L329:
        return -7;
        L332:
        goto L467;
        L335:
        if (SysUtil.h_I != 2) goto L447;
        switch (v0) {
        case -22: goto L441;
        case -21: goto L438;
        case -20: goto L435;
        case -6: goto L426;
        case -5: goto L432;
        case -2: goto L429;
        case -1: goto L424;
        case 21: goto L438;
        case 22: goto L441;
        default: goto L444;
        }
        L424:
        return m1;
        L426:
        return -2;
        L429:
        return -3;
        L432:
        return -4;
        L435:
        return -5;
        L438:
        return -6;
        L441:
        return -7;
        L444:
        goto L467;
        L447:
        if (v0 != -255) goto L457;
        return -5;
        L457:
        if (v0 != -254) goto L467;
        return -7;
        L467:
        return 2147483647;
    }
    // bytecode 119 bytes, max_stack 2, max_locals 1
    public static int d(int v0) {
        if (Settings.m() != 1) goto L60;
        switch (v0) {
        case 1: goto L48;
        case 2: goto L54;
        case 3: goto L57;
        case 4: goto L57;
        case 5: goto L52;
        case 6: goto L50;
        default: goto L57;
        }
        L48:
        return 2;
        L50:
        return 5;
        L52:
        return 1;
        L54:
        return 6;
        L57:
        goto L117;
        L60:
        if (Settings.m() != 3) goto L117;
        switch (v0) {
        case 1: goto L108;
        case 2: goto L115;
        case 3: goto L117;
        case 4: goto L117;
        case 5: goto L112;
        case 6: goto L110;
        default: goto L117;
        }
        L108:
        return 5;
        L110:
        return 2;
        L112:
        return 6;
        L115:
        return 1;
        L117:
        return v0;
    }
    // bytecode 109 bytes, max_stack 2, max_locals 1
    public static boolean a(int v0) {
        switch (v0) {
        case -15: goto L70;
        case -14: goto L70;
        case 10: goto L68;
        case 13: goto L68;
        case 1000: goto L68;
        case 1001: goto L68;
        case 1002: goto L68;
        default: goto L78;
        }
        L68:
        return 1;
        L70:
        if (SysUtil.h_I != 0) goto L78;
        return 1;
        L78:
        v0 = ((char) v0);
        if (((char) v0) < 48) goto L93;
        if (v0 <= 57) goto L105;
        L93:
        if (v0 == 42) goto L105;
        if (v0 != 35) goto L107;
        L105:
        return 1;
        L107:
        return 0;
    }
    // bytecode 161 bytes, max_stack 2, max_locals 1
    public static int b(int v0) {
        /* try L143-L156 catch java.lang.Exception -> L157 */
        switch (v0) {
        case -15: goto L122;
        case -14: goto L111;
        case 10: goto L89;
        case 13: goto L89;
        case 1000: goto L84;
        case 1001: goto L89;
        case 1002: goto L106;
        case 1003: goto L100;
        case 1004: goto L95;
        default: goto L134;
        }
        L84:
        return SysUtil.d(2);
        L89:
        return SysUtil.d(8);
        L95:
        return SysUtil.d(1);
        L100:
        return SysUtil.d(6);
        L106:
        return SysUtil.d(5);
        L111:
        if (SysUtil.h_I != 0) goto L122;
        return SysUtil.d(5);
        L122:
        if (SysUtil.h_I != 0) goto L134;
        return SysUtil.d(8);
        L134:
        if (v0 >= -127) goto L143;
        return -127;
        L143:
        return SysUtil.d(((javax.microedition.lcdui.game.GameCanvas) SysUtil.a_Canvas).getGameAction(v0));
        /* pop: ex_157; */
        return 127;
    }
    // bytecode 9 bytes, max_stack 1, max_locals 2
    public static void a(int v0, int v1) {
        SysUtil.e_I = v0;
        SysUtil.f_I = v1;
        return;
    }
    // bytecode 164 bytes, max_stack 2, max_locals 1
    public static int c(int v0) {
        if (v0 != 48) goto L10;
        return -3000;
        L10:
        if (v0 != 49) goto L20;
        return -3001;
        L20:
        if (v0 != 50) goto L30;
        return -3002;
        L30:
        if (v0 != 51) goto L40;
        return -3003;
        L40:
        if (v0 != 52) goto L50;
        return -3004;
        L50:
        if (v0 != 53) goto L60;
        return -3005;
        L60:
        if (v0 != 54) goto L70;
        return -3006;
        L70:
        if (v0 != 55) goto L80;
        return -3007;
        L80:
        if (v0 != 56) goto L90;
        return -3008;
        L90:
        if (v0 != 57) goto L100;
        return -3009;
        L100:
        if (v0 != 35) goto L110;
        return -3010;
        L110:
        if (v0 != 42) goto L120;
        return -3011;
        L120:
        if (v0 != 2147483647) goto L129;
        return 35;
        L129:
        if (v0 != 1) goto L137;
        return 36;
        L137:
        if (v0 != 6) goto L146;
        return 37;
        L146:
        if (v0 != 2) goto L154;
        return 38;
        L154:
        if (v0 != 5) goto L162;
        return 39;
        L162:
        return v0;
    }
    // bytecode 207 bytes, max_stack 8, max_locals 9
    public static Image a(Image v0, int v1) {
        if (v1 != 0) goto L6;
        return v0;
        L6:
        if (v1 == 180) goto L28;
        if (v1 == 90) goto L28;
        if (v1 == 270) goto L28;
        return v0;
        L28:
        int v2 = v0.getWidth();
        int v3 = v0.getHeight();
        int v4 = new int[v2]#1;
        int v5 = new int[(v2 * v3)]#2;
        int v7 = 0;
        L53:
        if (v7 >= v3) goto L159;
        v0.getRGB(v4, 0, v2, 0, v7, v2, 1);
        int v8 = 0;
        L75:
        if (v8 >= v2) goto L153;
        if (v1 != 90) goto L101;
        jt1 = (((v3 - v7) - 1) + (v8 * v3)); /* join L135 from L87 */
        goto L135;
        L101:
        if (v1 != 270) goto L122;
        jt2 = jt1; /* join L135 from L108 */
        goto L135;
        jt1 = (v7 + (v3 * ((v2 - v8) - 1))); /* join L135 from L108 */
        L122:
        jt2 = (((v2 * v3) - ((v7 * v2) + v8)) - 1); /* join L135 from L122 */
        L135:
        int v6 = jt2;
        v5[v6] = v4[v8];
        v8 += 1;
        goto L75;
        L153:
        v7 += 1;
        goto L53;
        L159:
        if (v1 == 90) goto L172;
        if (v1 != 270) goto L185;
        L172:
        v7 = ((int) javax.microedition.lcdui.Image.createRGBImage(v5, v3, v2, true));
        goto L195;
        L185:
        v7 = ((int) javax.microedition.lcdui.Image.createRGBImage(v5, v2, v3, true));
        L195:
        if (Settings.e != 0) goto L204;
        java.lang.System.gc();
        L204:
        return v7;
    }
    // bytecode 130 bytes, max_stack 8, max_locals 7
    public static Image a(Image v0) {
        int v1 = v0.getWidth();
        int v2 = v0.getHeight();
        int v3 = new int[v1]#1;
        int v4 = new int[(v1 * v2)]#2;
        int v5 = 0;
        L24:
        if (v5 >= v2) goto L108;
        v0.getRGB(v3, 0, v1, 0, v5, v1, 1);
        int v6 = 0;
        L45:
        if (v6 >= v1) goto L102;
        if (v3[v6] == -16777216) goto L81;
        v4[((((v5 * v1) + v1) - v6) - 1)] = v3[v6];
        goto L96;
        L81:
        v4[((((v5 * v1) + v1) - v6) - 1)] = 0;
        L96:
        v6 += 1;
        goto L45;
        L102:
        v5 += 1;
        goto L24;
        L108:
        v5 = ((int) javax.microedition.lcdui.Image.createRGBImage(v4, v1, v2, true));
        if (Settings.e != 0) goto L127;
        java.lang.System.gc();
        L127:
        return v5;
    }
    // bytecode 200 bytes, max_stack 7, max_locals 14
    public static void a(Graphics v0, int v1, int v2, int v3, int v4, int v5, int v6, boolean v7) {
        int v8 = (v5 % 256);
        int v9 = ((v5 / 256) % 256);
        v5 = (((v5 / 256) / 256) % 256);
        int v10 = (v6 % 256);
        int v11 = ((v6 / 256) % 256);
        v6 = (((v6 / 256) / 256) % 256);
        int v12 = 0;
        L75:
        if (v7 == 0) goto L87;
        jt1 = v4; /* join L88 from L82 */
        goto L88;
        L87:
        jt1 = v3; /* join L88 from L87 */
        L88:
        if (v12 >= jt1) goto L199;
        if (v7 != 0) goto L103;
        jt2 = v3; /* join L105 from L99 */
        goto L105;
        L103:
        jt2 = v4; /* join L105 from L103 */
        L105:
        float v13 = (((float) v12) / ((float) jt2));
        v0.setColor((v5 + ((int) (v13 * ((float) (v6 - v5))))), (v9 + ((int) (v13 * ((float) (v11 - v9))))), (v8 + ((int) (v13 * ((float) (v10 - v8))))));
        if (v7 == 0) goto L176;
        v0.drawLine(v1, (v2 + v12), (v1 + v3), (v2 + v12));
        goto L193;
        L176:
        v0.drawLine((v1 + v12), v2, (v1 + v12), (v2 + v4));
        L193:
        v12 += 1;
        goto L75;
        L199:
        return;
    }
    // bytecode 43 bytes, max_stack 2, max_locals 3
    public static float a(float v0, float v1, float v2) {
        v0 = ((v0 + 4.0f) % 4.0f);
        if (fcmpg(((v0 + 4.0f) % 4.0f), 1.0f) != 0) goto L19;
        v1 = v2;
        goto L41;
        L19:
        if (fcmpg(v0, 2.0f) != 0) goto L31;
        v1 = (-v1);
        goto L41;
        L31:
        if (fcmpg(v0, 3.0f) != 0) goto L41;
        v1 = (-v2);
        L41:
        return v1;
    }
    // bytecode 39 bytes, max_stack 2, max_locals 3
    public static float b(float v0, float v1, float v2) {
        if (fcmpg(v0, 1.0f) != 0) goto L14;
        v0 = v1;
        v2 = (-v1);
        goto L37;
        L14:
        if (fcmpg(v0, 2.0f) != 0) goto L26;
        v2 = (-v2);
        goto L37;
        L26:
        if (fcmpg(v0, 3.0f) != 0) goto L37;
        v0 = v1;
        v2 = v1;
        L37:
        return v2;
    }
    // bytecode 26 bytes, max_stack 2, max_locals 0
    public static int a() {
        if (Settings.m() != 1) goto L11;
        return 1004;
        L11:
        if (Settings.m() != 3) goto L22;
        return 1003;
        L22:
        return 1000;
    }
    // bytecode 26 bytes, max_stack 2, max_locals 0
    public static int b() {
        if (Settings.m() != 1) goto L11;
        return 1003;
        L11:
        if (Settings.m() != 3) goto L22;
        return 1004;
        L22:
        return 1002;
    }
    // bytecode 26 bytes, max_stack 2, max_locals 0
    public static int c() {
        if (Settings.m() != 1) goto L11;
        return 1002;
        L11:
        if (Settings.m() != 3) goto L22;
        return 1000;
        L22:
        return 1004;
    }
    // bytecode 13 bytes, max_stack 3, max_locals 2
    public static void a(int v0, String v1) {
        SysUtil.a_f.a((v0 + SysUtil.a_I), v1);
        return;
    }
    // bytecode 26 bytes, max_stack 2, max_locals 0
    public static int d() {
        if (Settings.m() != 1) goto L11;
        return 1000;
        L11:
        if (Settings.m() != 3) goto L22;
        return 1002;
        L22:
        return 1003;
    }
}

