// Generated by tools/jdeob.py from x/z.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `z`.
// String constants: <init> | Code | append | java/lang/Math | java/lang/Object | java/lang/StringBuffer | sqrt | toString | StackMap
public class Vec2 {
    private float[] a;
    // bytecode 26 bytes, max_stack 5, max_locals 1
    public Vec2() {
        super();
        new float[2]#1[0] = 0.0f;
        new float[2]#1[1] = 0.0f;
        this.a = new float[2]#1;
        this.b(0.0f, 0.0f);
        return;
    }
    // bytecode 26 bytes, max_stack 5, max_locals 3
    public Vec2(float v1, float v2) {
        this();
        new float[2]#1[0] = 0.0f;
        new float[2]#1[1] = 0.0f;
        this.a = new float[2]#1;
        this.b(v1, v2);
        return;
    }
    // bytecode 21 bytes, max_stack 4, max_locals 3
    public void a(float v1, float v2) {
        this.a[0] = (this.a[0] + v1);
        this.a[1] = (this.a[1] + v2);
        return;
    }
    // bytecode 23 bytes, max_stack 3, max_locals 4
    public void b(float v1, float v2) {
        float v3 = v1;
        v1 = ((float) this);
        this.a[0] = v3;
        v3 = v2;
        v1 = ((float) this);
        this.a[1] = v3;
        return;
    }
    // bytecode 37 bytes, max_stack 3, max_locals 4
    public void a(Vec2 v1) {
        Vec2 v2 = v1;
        float v3 = v1.a[0];
        v2 = this;
        this.a[0] = v3;
        v2 = v1;
        v3 = v1.a[1];
        v2 = this;
        this.a[1] = v3;
        return;
    }
    // bytecode 7 bytes, max_stack 2, max_locals 1
    public float a__float() {
        return this.a[0];
    }
    // bytecode 7 bytes, max_stack 2, max_locals 1
    public float b() {
        return this.a[1];
    }
    // bytecode 8 bytes, max_stack 3, max_locals 2
    public void a(float v1) {
        this.a[0] = v1;
        return;
    }
    // bytecode 8 bytes, max_stack 3, max_locals 2
    public void b(float v1) {
        this.a[1] = v1;
        return;
    }
    // bytecode 33 bytes, max_stack 4, max_locals 1
    public float c() {
        return ((float) java.lang.Math.sqrt(((double) ((this.a[0] * this.a[0]) + (this.a[1] * this.a[1])))));
    }
    // bytecode 33 bytes, max_stack 4, max_locals 2
    public void a__void() {
        float v1 = this.c();
        if (fcmpg(this.c(), 0.0f) != 0) goto L12;
        return;
        L12:
        this.a[0] = (this.a[0] / v1);
        this.a[1] = (this.a[1] / v1);
        return;
    }
    // bytecode 21 bytes, max_stack 4, max_locals 3
    public void c(float v1, float v2) {
        this.a[0] = (this.a[0] + v1);
        this.a[1] = (this.a[1] + v2);
        return;
    }
    // bytecode 39 bytes, max_stack 5, max_locals 4
    public void a__void(Vec2 v1, Vec2 v2) {
        Vec2 v3 = v1;
        v3 = v2;
        v3 = v1;
        v3 = v2;
        this.b((v1.a[0] - v2.a[0]), (v1.a[1] - v2.a[1]));
        return;
    }
    // bytecode 31 bytes, max_stack 4, max_locals 4
    public void a__void(Vec2 v1, Vec3 v2) {
        Vec2 v3 = v1;
        v3 = v1;
        this.b((v1.a[0] - v2.a__float()), (v1.a[1] - v2.b()));
        return;
    }
    // bytecode 21 bytes, max_stack 4, max_locals 2
    public void c(float v1) {
        this.a[0] = (this.a[0] * v1);
        this.a[1] = (this.a[1] * v1);
        return;
    }
    // bytecode 36 bytes, max_stack 4, max_locals 3
    public static float a__float(Vec2 v0, Vec2 v1) {
        Vec2 v2 = v0;
        v2 = v1;
        v2 = v0;
        v2 = v1;
        return ((v0.a[0] * v1.a[0]) + (v0.a[1] * v1.a[1]));
    }
    // bytecode 20 bytes, max_stack 3, max_locals 2
    public static float a(Vec3 v0, Vec3 v1) {
        return ((v0.a__float() * v1.a__float()) + (v0.b() * v1.b()));
    }
    // bytecode 28 bytes, max_stack 4, max_locals 3
    public static float a(Vec3 v0, Vec2 v1) {
        Vec2 v2 = v1;
        v2 = v1;
        return ((v0.a__float() * v1.a[0]) + (v0.b() * v1.a[1]));
    }
    // bytecode 28 bytes, max_stack 3, max_locals 3
    public static float a__float(Vec2 v0, Vec3 v1) {
        Vec2 v2 = v0;
        v2 = v0;
        return ((v0.a[0] * v1.a__float()) + (v0.a[1] * v1.b()));
    }
    // bytecode 48 bytes, max_stack 3, max_locals 2
    public String toString() {
        new java.lang.StringBuffer(); /* constructor */
        Vec2 v1 = this;
        v1 = this;
        return new java.lang.StringBuffer().append("(").append(this.a[0]).append(", ").append(this.a[1]).append(")").toString();
    }
    // bytecode 16 bytes, max_stack 3, max_locals 2
    public static float b(Vec2 v0, Vec3 v1) {
        return (Vec2.a__float(v0, v1) / (v0.c() * v1.d()));
    }
    // bytecode 33 bytes, max_stack 3, max_locals 3
    public static float b(Vec3 v0, Vec3 v1) {
        float v2 = (v0.a__float() - v1.a__float());
        v0 = ((Vec3) (v0.b() - v1.b()));
        return ((float) java.lang.Math.sqrt(((double) ((v2 * v2) + (v0 * v0)))));
    }
}

