// Generated by tools/jdeob.py from x/bz.class.  Do not hand
// edit: fix the emitter and re-run.  Original name `bz`.
// String constants: <init> | Code | cos | java/lang/Math | java/lang/Object | sin | sqrt | toRadians | StackMap
public class Vec3 {
    private float[] a;
    // bytecode 24 bytes, max_stack 5, max_locals 1
    public Vec3() {
        super();
        new float[3][0] = 0.0f;
        new float[3][1] = 0.0f;
        new float[3][2] = 0.0f;
        this.a = new float[3];
        return;
    }
    // bytecode 31 bytes, max_stack 5, max_locals 4
    public Vec3(float v1, float v2, float v3) {
        this();
        new float[3][0] = 0.0f;
        new float[3][1] = 0.0f;
        new float[3][2] = 0.0f;
        this.a = new float[3];
        this.b(v1, v2, v3);
        return;
    }
    // bytecode 31 bytes, max_stack 4, max_locals 4
    public void a(float v1, float v2, float v3) {
        this.a[0] = (this.a[0] + v1);
        this.a[1] = (this.a[1] + v2);
        this.a[2] = (this.a[2] + v3);
        return;
    }
    // bytecode 22 bytes, max_stack 3, max_locals 4
    public void b(float v1, float v2, float v3) {
        this.a[0] = v1;
        this.a[1] = v2;
        this.a[2] = v3;
        return;
    }
    // bytecode 62 bytes, max_stack 5, max_locals 5
    public void a(float v1) {
        double v2 = java.lang.Math.toRadians(((double) v1));
        v1 = ((float) java.lang.Math.sin(java.lang.Math.toRadians(((double) v1))));
        v2 = ((double) ((float) java.lang.Math.cos(v2)));
        float v3 = this.a[1];
        float v4 = this.a[2];
        this.a[1] = ((v3 * v2) - (v4 * v1));
        this.a[2] = ((v3 * v1) + (v4 * v2));
        return;
    }
    // bytecode 62 bytes, max_stack 5, max_locals 5
    public void b(float v1) {
        double v2 = java.lang.Math.toRadians(((double) v1));
        v1 = ((float) java.lang.Math.sin(java.lang.Math.toRadians(((double) v1))));
        v2 = ((double) ((float) java.lang.Math.cos(v2)));
        float v3 = this.a[0];
        float v4 = this.a[1];
        this.a[0] = ((v3 * v2) - (v4 * v1));
        this.a[1] = ((v3 * v1) + (v4 * v2));
        return;
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public float a() {
        Vec3 v1 = this;
        return this.a[0];
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public float b() {
        Vec3 v1 = this;
        return this.a[1];
    }
    // bytecode 9 bytes, max_stack 2, max_locals 2
    public float c() {
        Vec3 v1 = this;
        return this.a[2];
    }
    // bytecode 5 bytes, max_stack 1, max_locals 1
    public float[] a() {
        return this.a;
    }
    // bytecode 47 bytes, max_stack 4, max_locals 1
    public float d() {
        return ((float) java.lang.Math.sqrt(((double) (((this.a[0] * this.a[0]) + (this.a[1] * this.a[1])) + (this.a[2] * this.a[2])))));
    }
    // bytecode 32 bytes, max_stack 5, max_locals 3
    public void a(Vec3 v1, Vec3 v2) {
        this.b((v1.a() - v2.a()), (v1.b() - v2.b()), (v1.c() - v2.c()));
        return;
    }
    // bytecode 8 bytes, max_stack 3, max_locals 2
    public void c(float v1) {
        this.a[0] = v1;
        return;
    }
    // bytecode 8 bytes, max_stack 3, max_locals 2
    public void d(float v1) {
        this.a[1] = v1;
        return;
    }
    // bytecode 8 bytes, max_stack 3, max_locals 2
    public void e(float v1) {
        this.a[2] = v1;
        return;
    }
    // bytecode 24 bytes, max_stack 4, max_locals 3
    public void f(float v1) {
        int v2 = 0;
        L2:
        if (v2 >= 3) goto L23;
        this.a[v2] = (this.a[v2] * v1);
        v2 += 1;
        goto L2;
        L23:
        return;
    }
    // bytecode 26 bytes, max_stack 4, max_locals 2
    public void a() {
        float v1 = this.e();
        this.a[0] = (this.a[0] / v1);
        this.a[1] = (this.a[1] / v1);
        return;
    }
    // bytecode 33 bytes, max_stack 4, max_locals 1
    public float e() {
        return ((float) java.lang.Math.sqrt(((double) ((this.a[0] * this.a[0]) + (this.a[1] * this.a[1])))));
    }
    // bytecode 62 bytes, max_stack 6, max_locals 3
    public void b(Vec3 v1, Vec3 v2) {
        this.b(((v1.b() * v2.c()) - (v1.c() * v2.b())), ((v1.c() * v2.a()) - (v1.a() * v2.c())), ((v1.a() * v2.b()) - (v1.b() * v2.a())));
        return;
    }
    // bytecode 47 bytes, max_stack 3, max_locals 4
    public static float a(Vec3 v0, Vec3 v1) {
        float v2 = (v0.a() - v1.a());
        float v3 = (v0.b() - v1.b());
        v0 = ((Vec3) (v0.c() - v1.c()));
        return ((float) java.lang.Math.sqrt(((double) (((v2 * v2) + (v3 * v3)) + (v0 * v0)))));
    }
    // bytecode 55 bytes, max_stack 4, max_locals 4
    public void a(Vec3 v1, Vec3 v2, float v3) {
        this.a(v2, v1);
        this.f(v3);
        v2 = v1;
        v1 = this;
        this.a[0] = (this.a[0] + v2.a());
        v1.a[1] = (v1.a[1] + v2.b());
        v1.a[2] = (v1.a[2] + v2.c());
        return;
    }
}

